### ISSUE TITLE
`onunload` not triggering despite being defined in a controller?

### ISSUE THREAD

**Issue by Morklympious** [MithrilJS/mithril.js#1098]
Posting so this doesn't get lost in the cobwebs of gitter. 

**Version**: 0.2.0, (also checked on jsfiddle w/ 0.2.5)
**Browser**: Chrome 50.0.2661.102
### Description:

@jpablom came into gitter with an issue of `onunload` not actually firing when a component was being replaced by another component. 
### Steps to Reproduce:

[Link to JSfiddle of behavior](https://jsfiddle.net/4Lgnds5n/), Note that the `console.log` statements aren't being run despite components being unmounted.

Strangely enough, [Adding `onunload` or `onunload: onunload` to the view](https://jsfiddle.net/4Lgnds5n/1/) makes those statements run. 

``` js
const visible = m.prop(false);

const Actions = {
  toggle: () => {
    visible(!visible());
  }
};

const app = {
  controller: () => {
    return {
      visible
    };
  },
  view: () => {
    return [
      m('h1', 'Hey'),
      visible() ? second : first
    ];
  }
};

const first = {
  controller: () => {
    return {
      onunload: () => {
        console.log('unload first');
      }
    };
  },
  view: () => m('button', {
    onclick: Actions.toggle,
  }, 'show second')
};

const second = {
  controller: () => {
    return {
      onunload: () => {
        console.log('unload second');
      }
    };
  },
  view: () => m('button', {
    onclick: Actions.toggle,
  }, 'show first')
};

m.mount(document.body, app);
```
### Expected:

Without additional code, the `onunload` handler from the `controller` should run when the component is removed or replaced by another component.
### Actual:

The `console.log` statements didn't run, and for some reason need a reference or an explicit `onunload` property in the view `attrs` in order to fire these things. Seems weird or inconsistent with what I expect as a developer. 

If this is a duplicate, feel free to axe it, but I feel this was different enough to the current `onunload` issues to warrant another issue.

**Comment by isiahmeadows** [comment]
@Morklympious I fixed your code's indentation, BTW. It was a bit wonky because of the tabs.

**Comment by Morklympious** [comment]
@isiahmeadows I've really got to figure out my life when it comes to indentation and the mithril community. hahaha.

**Comment by isiahmeadows** [comment]
You're okay. :smile:

**Comment by leiyangyou** [comment]
looks like mithril has considered these two components the same component (assigning a different key to the component will help)

**Comment by isiahmeadows** [comment]
I think it's Mithril not seeing the components as different enough, instead focusing on the underlying element.

**Comment by FREEZX** [comment]
+1 having the same issue

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
