### ISSUE TITLE
configContext.onunload may not be called on route change

### ISSUE THREAD

**Issue by leiyangyou** [MithrilJS/mithril.js#1200]
configContext.onunload are sometimes not called when a route changes, I tracked it down to the following line:

``` diff
function maybeRecreateObject(data, cached, dataAttrKeys) {
        // if an element is different enough from the one in cache, recreate it
        if (isDifferentEnough(data, cached, dataAttrKeys)) {
 -          if (cached.nodes.length) clear(cached.nodes)
 +          if (cached.nodes.length) clear(cached.nodes, cached)
```

is this part 

`if (cached.nodes.length) clear(cached.nodes)` intentional?

**Comment by isiahmeadows** [comment]
Likely an oversight (`clear` takes two arguments, not one). Go ahead and file a PR.

**Comment by pygy** [comment]
> configContext.onunload are sometimes not called when a route changes

@leiyangyou could you provide a fiddle with a reproduction?

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
