### ISSUE TITLE
Mobile browsers, withattr + oninput bugs

### ISSUE THREAD

**Issue by labe-me** [MithrilJS/mithril.js#1266]
Hello,

I experienced a few problems on Android/Chrome while using oninput and withattr. 

Even on a basic dom tree (https://jsfiddle.net/lbedubourg/oh47t4fh/9/), the fact of redrawing the dom on each event somehow garbage the textarea value and input experience (for instance deleting a few characters duplicates the word and typing "fast" move the cursor before a character).

I cannot change the oninput to onchange since redraws can come from elsewhere (server message) and I would lose the edited input value during redraw.

Using m.redraw.strategy("none") seems to fix things with a hacky feeling but it cannot be applied to every situations where the input must have a realtime result. 

Any tip/remark about this?

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
