### ISSUE TITLE
"SecurityError: The operation is insecure" in Firefox

### ISSUE THREAD

**Issue by qlobafftar** [MithrilJS/mithril.js#1288]
### Description:

In Firefox v47 code like
app.controller = function(){
 var arr = [];
 return {
  arr:arr;
  addToArray: function(){
  arr.push({}) 
  }
 }
app.view = function(){
 return m("div",ctrl.arr.map(function(o){return m("input[type=checkbox]")}))
}
 don't work and the message "SecurityError: The operation is insecure" appears when I try to add values to the arr with addToArray function

The problem was fixed by editing function trySetAttr() in mithril.js 
before:
node.value = dataAttr
after:
node.setAttribute('value',dataAttr)

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
