### ISSUE TITLE
iframe not retained with redraw strategy all

### ISSUE THREAD

**Issue by rhaldkhein** [MithrilJS/mithril.js#1300]
### Description:

I'm trying to retain an iframe on redraw with strategy set to "all" but it seems to be not working. Setting the strategy back to "diff" works as it should be.

I've also used `context.retain` and `subtree:'retain'` in the linked sample code.

The code also confirmed that `subtree:'retain'` works because the text `Content Default` never changes. It's just that the iframe is reloading its content.
### Steps to Reproduce:

I've created a JSFiddle: [click here](https://jsfiddle.net/RhaldKhein/x3zmte5m)

PS. Thank you very much for the awesome framework :)

**Comment by rhaldkhein** [comment]
Ok. Able to fix it by flagging all the node ancestors with `context.retain` all the way up to root element.

**Comment by barneycarroll** [comment]
BTW @rhaldkhein don't know if you worked this out but 1) setting each ancestor to retain is redundant — simply retaining the root ancestor to retain will have the same effect & 2) this will have the same effect as redraw diff.

**Comment by rhaldkhein** [comment]
Hi @barneycarroll , I think I did what you said before but didn't fix it. I've edited the jsfiddle with working solution (retaining each ancestors), and if we comment out the config line of `div.subNode` then it breaks and the iframe reloads.

Edit: [JSFiddle](https://jsfiddle.net/RhaldKhein/x3zmte5m/)

**Comment by barneycarroll** [comment]
@rhaldkein you're right — that's really weird! I'll have a play around to try and get a better grip on why it's behaving that way, but this looks like a bug to me — I'd expect children of a retained node to be retained themselves unless specifically told otherwise 🤔

**Comment by isiahmeadows** [comment]
@barneycarroll So, is this good to reopen?

**Comment by barneycarroll** [comment]
AFAIC yes, it's a bug.

**Comment by isiahmeadows** [comment]
Question: does this affect the rewrite as well?

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
