### ISSUE TITLE
[ospec] Binary not running

### ISSUE THREAD

**Issue by gilbert** [MithrilJS/mithril.js#1355]
### Description:

The line endings in the ospec binary have windows line endings (`\r\n`), which breaks it in bash.
### Steps to Reproduce:
1. `$ npm install --save ospec`
2. `$ ospec`
### Expected:

The file should execute.
### Actual:

```
$ ospec
env: node\r: No such file or directory
```

**Comment by sdougbrown** [comment]
Ahh this is what I was fighting with in #1354 - this makes more sense.

**Comment by lhorie** [comment]
@mindeavor Can you try now?

**Comment by lhorie** [comment]
related: https://github.com/npm/npm/issues/12371

**Comment by mindeavor** [comment]
It works! Can we get a new release? :)

**Comment by lhorie** [comment]
rc3 is out

**Comment by mindeavor** [comment]
Ah sorry, I meant a new release for ospec https://www.npmjs.com/package/ospec

**Comment by gilbert** [comment]
It looks like I'm running into this problem again with `v1.4.0`. Can we reopen?

**Comment by tivac** [comment]
This is probably due to `ospec` not being published from Travis. I think I manually published last time, and forcing line-endings in git is a real thing.

This is probably another sign that this repo should really just use lerna :-\

**Comment by maranomynet** [comment]
I'm also seeing this problem with ospec v1.4.0 - using `node node_modules/.bin/ospec` works though.

**Comment by maranomynet** [comment]
Any news on a release fixing this?

**Comment by pygy** [comment]
I do, but I dont have the NPM credentials

**Comment by gilbert** [comment]
Any updates on this?

**Comment by tivac** [comment]
@pygy has npm access and should be good to publish a patch version that fixes the binary, hopefully!

**Comment by pygy** [comment]
I've just released v1.4.1 (and tagged that commit as ospec_v1.4.1 since I didn't create a full branch for old ospec releases).

Could someone test it, v1.4.0 works from bash here (macOS).

Does anyone remember why we delayed ospec v2? The breaking change is the fact that the reporter will always run async WRT `o.run()`, whereas it would previously run synchronously if there were no async tests.

**Comment by spacejack** [comment]
I tried it on Linux - seems ok...

    $ npm i ospec
    $ ./node_modules/.bin/ospec
    0 assertions completed in 0ms, of which 0 failed

**Comment by gilbert** [comment]
It works! 🎉 🎉  Thank you @pygy!

**Comment by pygy** [comment]
Great!
