### ISSUE TITLE
Setting initial value for range input fails

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#1378]
### Description:

For large values the initial set of range slider does not work as expected. As the redraw happens, value is applied correctly.

This may be a DOM issue which we might get around by applying `value`-property at the end.

### Steps to Reproduce:

fails: http://jsfiddle.net/61d9Lscz/
works: http://jsfiddle.net/x910rmph/

### Expected:

Value should be set right away

### Actual:

Value is not set right away but once a redraw is happening

**Comment by Bondifrench** [comment]
@StephanHoyer I use `input[type=range]` quite a bit with Mithril and never encountered these problems, in your examples, it seems the order of the attributes makes a difference, if you rearrange so `value` comes after min, max and step, your examples are initialized the right way (at least in Chrome).

**Comment by isiahmeadows** [comment]
Seems easy to fix. Feel free to send a PR to prioritize it (maybe again).
