### ISSUE TITLE
Nested components can retain old parameters after unloading and reloading

### ISSUE THREAD

**Issue by kennethklee** [MithrilJS/mithril.js#1403]
### Description:

Calling `m.redraw()` within a parent component controller seems keeps a reference to its old controller even after unloading. It's more evident when there's a nested component and a route change to the same controller.

### Steps to Reproduce:

Parent Component
1. In the controller, retain a random parameter, or a route param.
2. Also in the controller, call `m.redraw()`.
3. In the view, pass the parameter to a nested component.

Nested Controller
4. In the view, render the parameter.

### Expected:

Parent component and nested component should show the same parameter.
https://jsfiddle.net/2hv6wfp1/

### Actual:

Parent component and nested component show different parameters. The nested one retains the last parameter, while the parent has the new one.
https://jsfiddle.net/2hv6wfp1/2/

**Comment by isiahmeadows** [comment]
[Not reproducing for me with `next`.](https://jsfiddle.net/2hv6wfp1/3/)

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
