### ISSUE TITLE
[ospec] newlines in error messages confuse the error reporter

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1495]
### Description:

The presence of newlines in error messages cause a line of said message to be displayed instead of the stack trace

### Steps to Reproduce:

https://runkit.com/58603d35d1b6b10013e1e652/58603d36d1b6b10013e1e653

**Comment by isiahmeadows** [comment]
[I'll note it wasn't exactly trivial for me to nix it in a cross-runtime setting](https://github.com/isiahmeadows/thallium/blob/master/lib/reporter/util.js#L30-L56). Note that if you were to rip the code off, you'll need to remove the calls to `formatLineBreaks`.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.

**Comment by pygy** [comment]
The issue is still present.

**Comment by isiahmeadows** [comment]
Okay. [Note that I did actually find a way to address the case myself, so that could be informative.](https://github.com/lhorie/mithril.js/issues/1495#issuecomment-269485745)
