### ISSUE TITLE
Restore a 0.2.x branch and make a final v0.2 release

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1596]
It would be nice to make a final 0.2.x release with all the bug fixes that had occurred since 0.2.5.

IIRC @lhorie said that NPM wouldn't let him publish pre 1.0 versions now that v1 is out, but I don't think it is correct. I just tried it with the great `foolib2025` which was at v0.0.2. I successully published v1.0, v0.0.3, v0v1.0.1 and v0.0.4 in that order without any problem.

I've started a v0.2.6 change log in #1308, but there might have been subsequent fixes... It's hard to review them without the GH interface though.

- [x] restore the v0.2 branch
- [ ] let's make a release!

**Comment by isiahmeadows** [comment]
For reference, [here's the latest 0.2 commit](https://github.com/lhorie/mithril.js/commit/84d7c722f95344a966b2e9e36706e8a88feeeb63).

**Comment by isiahmeadows** [comment]
@tivac Want to make a 0.2.x release with `npm publish --tag legacy`? That'll fix this issue.

**Comment by tivac** [comment]
Not really, but I can later tonight.

**Comment by isiahmeadows** [comment]
@tivac Ping? (I know this is old)

**Comment by tivac** [comment]
I fucked up `v0.2.6` by forgetting to run a build, then cocked up `npm i mithril` for a bit by forgetting to tag my `npm publish` command, but I think it's all sorted out now.

```bash
$ npm dist-tag ls mithril
latest: 1.1.3
legacy: 0.2.7
```

so `npm i mithril` will install `1.1.3`, and `npm i mithril@legacy` will install `0.2.7`.
