### ISSUE TITLE
Order of background-image matters as to whether it gets rendered in style{}

### ISSUE THREAD

**Issue by kvanberendonck** [MithrilJS/mithril.js#1597]
I haven't put together a reproducible test case yet, but consider this code (from our codebase):

```
      return m('.screen-image', {
        'style': {
          // This has to be at the top for some reason, mithril bug
          'background-image': 'url(\'' + uri + '\')',
          'left': this.renderLeft(),
          'top': this.renderTop(),
          'width': this.renderWidth(),
          'height': this.renderHeight(),
        },
        'class': this.getClass(),
        'title': this.getHelp()
      });
```

If I move `background-image` below `height`, it bugs out and doesn't ever make it into the DOM. `uri` is a path name, like `/images/somewhere/Program Files (x86)/jargon` that has been encoded using `encodeURI`.

**Comment by kvanberendonck** [comment]
Sorry I didn't realize the last question there was an action item.

A little confused, would you like me to attempt to reproduce using a `config` script?

**Comment by tivac** [comment]
What version, and can you repro it in a simple jsbin/jsfiddle?

**Comment by kvanberendonck** [comment]
Version is 0.2.3 fetched from bower.

I'll try a jsfiddle off-work.

**Comment by tivac** [comment]
Ok, might be worth trying in 0.2.5 too. Don't know that there are any specific fixes for this but it probably can't hurt for your repro.

**Comment by kvanberendonck** [comment]
Sorry this is still on my mind, I haven't forgotten.

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
