### ISSUE TITLE
ospec does not print objects deeply

### ISSUE THREAD

**Issue by IBwWG** [MithrilJS/mithril.js#1661]
Mithril 1.0.1, trying to use deepEquals:

```
        o({ a: 1, b: 2 }).deepEquals({ a: 1, b: 1});
```

...results in:

```
[object Object]
should deep equal
[object Object]
```

Maybe that's expected by some, but I think deep-printing the objects (or better yet, just where their first difference occurs) would be helpful.

**Comment by isiahmeadows** [comment]
Maybe using `util.inspect` would help here.

**Comment by pygy** [comment]
And fall back to `console.log` for browsers?

**Comment by isiahmeadows** [comment]
Or pull a dependency, use JSON.stringify, etc. Basically, something better
than `toString`.

-----

Isiah Meadows
me@isiahmeadows.com

**Comment by pygy** [comment]
Oh, yes, my bad, it's a formatter...

**Comment by IBwWG** [comment]
Would it be as easy as just chopping the middle out of https://github.com/lhorie/mithril.js/blob/next/ospec/ospec.js#L206 so objects fall through the `if` chain and get `JSON.stringify()`'d?

**Comment by levicook** [comment]
+1 on falling through to JSON.stringify.

Current work around on my team, is to wrap simple objects in an array. eg:
` o({ a: 1, b: 2 }).deepEquals({ a: 1, b: 1});` becomes:
` o([{ a: 1, b: 2 }]).deepEquals([{ a: 1, b: 1}]);`

Obviously hacky, but helpful because it beats `[object Object]`
