### ISSUE TITLE
TypeScript typings: m.vnode is missing

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1690]
@spacejack @andraaspar 

    Property 'vnode' does not exist on type `Static`.

The fix is trivial, but I'd rather wait for #1688 to land before adding this (or it can be folded into #1688).

**Comment by andraaspar** [comment]
@pygy Can you point me to the documentation, please?

**Comment by tivac** [comment]
`m.vnode` is a low-level thing not really intended for end-user usage, I use it in [`mopt`](https://npmjs.com/mopt) so that the tooling creates the same monomorphic vnodes as the core lib.

I'm fine with it having a type definition, but that's why it isn't documented on the site.

**Comment by isiahmeadows** [comment]
Here's an easy workaround:

```ts
// Add this module (`vnode.ts`) to your project:
import * as m from "mithril";
export default (m as any).vnode as {
    // Note: this could be improved.
    (...args: any[]): m.Vnode<any, any>;
};

// Use it like this:
import vnode from "./vnode";
```

This takes advantage of TypeScript's `any` escape hatch to access otherwise invalid members, but ensures the returned type is in fact mostly correct.

**Comment by pygy** [comment]
@andraaspar sorry, I let this slip...

The signature is 

```
declare function vnode<Attrs, State>(
  tag: string|Component<Attrs, State>,
  key?: number | string,
  attrs?: Attrs,
  children? : NotQuiteSureExactly,
  text?: string,
  dom?: Element
): Vnode<Attrs, State> | VnodeDOM<Attrs, State>
```

`text` and `children` cannot be both present (well, they can but IIRC children will be ignored, it would be better to type them as mutually exclusive).

it is exposed as `m.vnode` and as `require("mithril/render/vnode")`

**Comment by isiahmeadows** [comment]
FYI: TS definition bugs should generally be filed in [spacejack/mithril.d.ts](https://github.com/spacejack/mithril.d.ts), not here.

**Comment by pygy** [comment]
Yes, I know, this was opened at a time we still had the definitions in the main repo.

@spacejack would you mind moving https://github.com/spacejack/mithril.d.ts to the Mithril org umbrella (where you'd keep your commit rights, off course)?

**Comment by isiahmeadows** [comment]
@pygy I didn't realize that. My bad. 🙁

**Comment by spacejack** [comment]
I don't mind moving to the mithril org if there are no objections.
