### ISSUE TITLE
Redraw being sometimes synchronous, it would benefit from a lock mechanism

### ISSUE THREAD

**Issue by FremyCompany** [MithrilJS/mithril.js#1693]
Here is a problem I have:
- I have some property whose value can be updated; when it is, a redraw is necessary, so the setter will call m.redraw()
- Sometimes, updating this property is just part of a longer chain of updates
- Most of the times, this works just fine, but sometimes the optimization where redraw is synchronous kicks in while the state is not consistent yet, resulting if a flash of incorrect content.

```js
model.property1 = value1; // if redraw() is synchronous, the second update will be missed for a frame
model.property2 = value2; // now redraw() will be delayed for sure so improper content displays
```

To solve this problem for my project I created my own synchronization helpers (I don't call m.redraw but some helper that will not trigger an actual redraw if an operation is in progress, and will instead wait for this operation to complete before triggering a redraw to make sure the state is never inconsistent). 

I think this should be part of the built-in library, the current redraw mechanics are kinda annoying, especially if you have to work with promises obtained from the DOM APIs.

Any opinion?

**Comment by pygy** [comment]
There's a WIP PR to make m.redraw always async #1592 I need to fix the merge conflicts in the tests, though.

**Comment by isiahmeadows** [comment]
v2's `m.redraw` has been split into separate sync/async versions. Closing.
