### ISSUE TITLE
m.request fail on Chrome

### ISSUE THREAD

**Issue by riku179** [MithrilJS/mithril.js#1697]
In tutorial of ver 1.0.1, m.request fail on PUT request on Google Chrome.
```js
 save: function() {
        return m.request({
            method: "PUT",
            url: "http://rem-rest-api.herokuapp.com/api/users/:id",
            data: User.current,
            withCredentials: true,
        })
    }
```
Chrome dev-tool says only "XHR failed loading" and redirect to "http://(domain)/?".
In network section, response headers have been shown not all. It says "Provisional headers are shown".
```
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:PUT
Origin:http://localhost:8888
Referer:http://localhost:8888/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```
And, this problems have not happened on FireFox.

**Comment by chebum** [comment]
There are several discussions of this error on the internet. Two probable reasons are: 1) invalid non-serializable data 2) page reloads itself during the POST request.
Looking at your code, I suppose you may have something like circular data in your User.current object. Please try sending an empty object {} to see if it solves the problem.

**Comment by isiahmeadows** [comment]
@chebum Would that be possible for something Chrome-specific?

**Comment by chebum** [comment]
@isiahmeadows i don't know. There is still no sample project to isolate and reproduce the issue.

**Comment by isiahmeadows** [comment]
@riku179 Could you create a pen/fiddle/similar so we can isolate the issue more quickly?

**Comment by riku179** [comment]
@isiahmeadows Here it is. http://codepen.io/anon/pen/NppYrQ
Push "save" button with checking your browser's dev console.

**Comment by riku179** [comment]
@chebum Sengding an empty object {} didn't solve the problem.

**Comment by spacejack** [comment]
I believe this error is due to using http rather than https. The next branch already has fixes for the tutorial, see: https://github.com/lhorie/mithril.js/blob/next/docs/simple-application.md

**Comment by spacejack** [comment]
Sorry, some clarification - the reason for the "redirect" to `http://(domain)/?` is because the form is submitting when the submit button is clicked. The corrections in the latest address this by using preventDefault in the onsubmit handler.

**Comment by isiahmeadows** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=902827.

I can't repro it 100% of the time and there isn't really anything Mithril can do to work around this on our end.
