### ISSUE TITLE
Suggestion: Bundle all stream functions into one script file

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#1700]
For usage via script or in jsbins, it would be useful to have a single stream.js file.

All static methods could be attached to the stream global: stream.combine, stream.merge, stream.scan, stream.scanMerge.

I was also wondering if it would make sense to add scan and scanMerge to the static stream object when using modules. I wouldn't think they add much weight if you've already decided to use the stream submodule.

**Comment by isiahmeadows** [comment]
@lhorie This could be solved by [uploading the stream bundle](https://github.com/lhorie/mithril.js/blob/next/stream/stream.js) to [cdnjs.org](https://cdnjs.com/libraries/mithril).

**Comment by tivac** [comment]
@spacejack is this done now?

**Comment by isiahmeadows** [comment]
@tivac [Nope](https://cdnjs.com/libraries/mithril).

**Comment by isiahmeadows** [comment]
Ping @lhorie... (you have the keys to cdnjs here)

**Comment by tivac** [comment]
@isiahmeadows I don't care about cdnjs.com, unpkg.com works just as well to solve that issue. The only change that needs to happen is us actually releasing a new version.

**Comment by isiahmeadows** [comment]
Okay.

**Comment by isiahmeadows** [comment]
Closing, since the issue here is fixed.
