### ISSUE TITLE
How to access the current route on the first load?

### ISSUE THREAD

**Issue by dontwork** [MithrilJS/mithril.js#1701]
Im making this issue as a follow up to a discussion on the gitter channel. 

Currently there is no simple way to establish, outside of components, what the current route is on the first load. e.g if you have m.route.get() in a module it will be undefined if mithril has not finished the first render.

I don't know what the answer is but I feel like a hook for being able to know when this information is available would be useful

**Comment by tivac** [comment]
Seems like there should be a line added here, https://github.com/lhorie/mithril.js/blob/next/api/router.js#L13

```js
currentPath = defaultRoute
```

Which seems like it could solve this issue, though only once `m.route()` has been called.

**Comment by pygy** [comment]
@tivac I don't think it's enough, IIRC the router will pick the current location and will try to route there before trying the `defaultRoute`... It's a part of the router logic I'm not too familiar with though...

**Comment by barneycarroll** [comment]
For posterity: `m.route.get()` will always return the currently settled route. The one place this may not be what one expects is in RouteResolver.onmatch - a route has not resolved until its onmatch returns so it makes sense for `m.route.get()` to return the last matched route until that point. The route in the process of being matched is exposed to `onmatch` via its input arguments.

[Playground here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgDkMA3VgXleAAdNK1ZcIMAO6JWACgCUfAHzDRo5AEYSrAEzaAzNoAs2gKwBdfACcYAEwCu5GLNVrRsqBDQBrONrSKvEqsnj5w+EzkGDSyAOSssdpYsljWlPZ0+AAyXt7awAAWNmAysQD0AA4YAOYwZfEA1KxoAL7asQAKNTAJ-vLyJK5uyMmpVumZOT75RTAlCWUFlDixbQkAEsswsfLmgyJq8sItwsJjE862lOT2OLT4AEaUtgCe7YtbiQKu5UsrrDIhAdRNQvBAYvIgW5REw4JRYPgoJRqnFzhkYPhahDSkk0ujMTAIUdgaw2kMxBJpGI0M8ekFWMhyaJkrEChovrFNisBkzWLzkpwuDySeZXGSDuUqrUyogpTB2LcHjArLFAeTqFhouQCrIqlZsH5WFUaAVtON0ZDebD4RikSjYmjMliFDjWI6Mc7+lbqHCEXbZMA9QbtMbTaxzXQWsS3OK3OSbGhbMqZFwaUnlAz+XE2RyurVetTafhojQrOE5QqsEqrMLoXySczZILa2pRQcTq15CAyFQsBVoMq8A8MEqoN2QHAYLByDQID68BoAAyIDQaEAtPYgUK+JCoECYHB4LDgorQIikED2KxjxAgAo0GgVOCIMplexoCreaoRZZlY8mqxoAAAR0fBF3wIw-xPQCoHPccaBeCpcFvOByEAioaHXcwWiAA).
