### ISSUE TITLE
cleanup cache of node using m.render

### ISSUE THREAD

**Issue by francescoagati** [MithrilJS/mithril.js#171]
Hi,
when i use only m.render there is the possibility of reset the cache of a particular node?
For example having

```
m.render(document.getElementById('view1'), view(data))
```

i need something like this

```
m.cleanCache(document.getElementById('view1'));
```

**Comment by sbvijaykumar** [comment]
Hi lhorie,
Even if we pass the forceRecreation as true to m.render, it is not clearing its nested nodes from nodes cache. It should ideally delete all its child nodes from nodecache and recreate it based on the request to m.render. Please add this change.

**Comment by isiahmeadows** [comment]
@sbvijaykumar That's a separate bug. Please [file a new issue](https://github.com/lhorie/mithril.js/issues/new) with specific details about your code, etc.
