### ISSUE TITLE
Stream updated after conditionaly halt its parent

### ISSUE THREAD

**Issue by gaspoute** [MithrilJS/mithril.js#1714]
Hello,

I encounter an unexpected behavior when I use Mithril streams, here is the [JSFiddle](https://jsfiddle.net/k9pe1js0/2/). I expect that `count` equals zero when `halt` is `true`. I also try to replace the `map` with a `combine` but the result is the same.

I also write a [test](https://github.com/gaspoute/mithril.js/commit/40f7fd06d013e023355a2b79df6c3465edcf56dc), that will become a pull request if it's really an issue or a misunderstanding.

Gaspar.

**Comment by isiahmeadows** [comment]
I'd say that's definitely odd...

**Comment by isiahmeadows** [comment]
I'd expect the same, since you're updating the entire stream. I'm not familiar with its implementation personally (I'd defer to @lhorie and @tivac for that), though.

**Comment by pygy** [comment]
It looks weird to me as well, but I'm not very familiar with the stream code either...

**Comment by gaspoute** [comment]
A little trick to get around this bug is to update without using the dependent stream returned by the mapping.
```javascript
var halt = true;
var child = stream('c');
parent.map(function(p) {
    child(halt ? stream.HALT : p);
});
```
