### ISSUE TITLE
Route is not resolved on hash change in IE

### ISSUE THREAD

**Issue by uNmAnNeR** [MithrilJS/mithril.js#1734]
Hello!

I [found that](https://github.com/lhorie/mithril.js/blob/next/router/router.js#L107) in IE `supportsPushState` is true, but `onpopstate` will never be called. So links does not work.

Example here: https://jsfiddle.net/1bj54j8v/

**Comment by pygy** [comment]
That's super odd... What IE versions are affected?

**Comment by pygy** [comment]
Could you try this? It is your fiddle, but as a top level page (no iframes added by jsfiddle).

https://bl.ocks.org/pygy/raw/a067feff54d58d36f17bc6851749afe3/#/home

**Comment by uNmAnNeR** [comment]
> Could you try this? It is your fiddle, but as a top level page (no iframes added by jsfiddle).

Sure. Does not work on IE 11.953.14393.0.

> In theory, supportsPushState is false for IE9 and true otherwise, and IE10+versions support onpopstate...

Found this issue for all IE before Edge: http://stackoverflow.com/a/41473506

By the way, mithril 0.2.x worked fine.

**Comment by pygy** [comment]
Thanks for the details. I suppose that v0.2 uses `onhashchange` in hash mode, even when browsers support `pushState`.

**Comment by isiahmeadows** [comment]
@pygy It does.

**Comment by isiahmeadows** [comment]
I think it might've been to work around [this IE bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/)

**Comment by pygy** [comment]
I gave this a crack this morning with little success (many tests are broken by the change, and the mocks do not handle "debounced async" `onhashchange`, which doesn't help...)

**Comment by pygy** [comment]
Sorry, I didn't mean to close this, I didn't know that just mentioning an issue in a commit message closed issues (vs "fix #xxxx" ).

**Comment by isiahmeadows** [comment]
@pygy That convenience feature is *usually* useful in GitHub, but yeah, sometimes, it does get annoying.

**Comment by pygy** [comment]
I'm afraid the fix for this will be breaking: https://github.com/pygy/mithril.js/commit/bd7230fc54c80695187ad94d8f987f3295e0dd3a#diff-08af55052ff6ecc22309ea97e4711428R101

This is impossible to implement for IE9 (and it has never been), but if we want the router to work identically in every env in hash mode, we can't cheat with `replaceState()` when the routed tree is mounted.

This test would have passed in non-IE browsers...

There's also https://github.com/pygy/mithril.js/commit/bd7230fc54c80695187ad94d8f987f3295e0dd3a#diff-08af55052ff6ecc22309ea97e4711428R799 that must be elucidated, it may be a `pushStateMock` bug or a router bug.

**Comment by isiahmeadows** [comment]
@pygy That's concerning... 😟

**Comment by pygy** [comment]
@isiahmeadows Worse, I recently realised that `onhashchange` wasn't debounced as I thought it was due to a JSBin bug(https://github.com/jsbin/jsbin/issues/3078) (and not enough cross checking on my hand)...

**Comment by andraaspar** [comment]
I ran into this recently and had to create a [workaround](https://github.com/andraaspar/ormm0g/blob/master/src/ts/src/util/Ie11HashchangeHack.ts). Just in case it helps anyone.

**Comment by isiahmeadows** [comment]
I'm punting this to post-v2, but I *might* be able to fix it in a future patch release. Specifically, we could detect IE and [see what we can do to work around the `popstate` bug](https://github.com/browserstate/history.js#notes-on-compatibility), but it's not exactly going to be easy to do.

If someone beats me to it, I'll gladly consider merging it. 🙂

**Comment by barneycarroll** [comment]
This ticket is 3 years old, and IE is no longer a support target. I'm closing this because with the passing of time, this no longer constitutes a bug.

**Comment by isiahmeadows** [comment]
@barneycarroll This needs checked against IE11 - MS still supports it: https://docs.microsoft.com/en-US/lifecycle/faq/internet-explorer-microsoft-edge

I say we should put the lid on it August 17 of this year, aligning with Microsoft 365: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666#ftag=MSF278e2c0

**Comment by barneycarroll** [comment]
Excellent. Given our resources I say we just drop support now. There is no sense leaving open the window of hope and opportunity for a browser that is going to be discontinued in half a year.

**Comment by isiahmeadows** [comment]
Sure, let's do that. Just not this immediate next release. How does that sound?
