### ISSUE TITLE
allow to pass more parameters in withAttr function

### ISSUE THREAD

**Issue by bhanuc** [MithrilJS/mithril.js#1747]
Currently you can only pass only one attribute in the handler functions, changing the signature of the function a bit would allow anyone to send more parameters to the handler function: ex

```js
m.withAttr = function(attrName, callback1, context) {
	return function(e) {
		callback1.call(context || this, attrName in e.currentTarget ? e.currentTarget[attrName] : e.currentTarget.getAttribute(attrName))
	}
}
``` 

to 

```js
m.withAttr = function(attrName, callback1, context, meta) {
	return function(e) {
		callback1.call(context || this, attrName in e.currentTarget ? e.currentTarget[attrName] : e.currentTarget.getAttribute(attrName), meta)
	}
}
```

So you can now add an extra parameter like an object, key very easily: ex: 
`m.withAttr('value', callback, null, metaData)`

Use case - While handling an input element, you can pass the value as well as the id of the element without accessing the vnode etc. I think it can have many other use-cases with no real negatives.

**Comment by isiahmeadows** [comment]
@bhanuc Edited your initial comment to make the code snippets more readable.

**Comment by isiahmeadows** [comment]
@MithrilJS/collaborators Is this worth adding, or is my gut feeling here correct in that we should just have people use closures. Also, would it be worth just stripping the `context` argument for v2 (or later), too, just to keep it simple?

**Comment by isiahmeadows** [comment]
We elected to remove `m.withAttr` entirely, so I'm closing this bug.
