### ISSUE TITLE
Add docs for cancelling route resolution

### ISSUE THREAD

**Issue by dontwork** [MithrilJS/mithril.js#1759]
It is a common use case to want to check that certain conditions have happened before allowing for route changes.

Example: a page with a form but also links to other pages, the form data has a flag for unsavedChanges and you do not want to allow route changes but actually want to display some UI to alert the user of these unsaved changes.

**Comment by pygy** [comment]
We'll add this :-)

In the mean time, the solution is:

```JS
'/bounceBack': {onmatch: function(){
  history.back()
  return new Promise(function(){})
}}
```
