### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by kurtmilam** [MithrilJS/mithril.js#1771]
Steps to Reproduce:
1. Make changes in an input that has an `oninput` event.
2. Immediately navigate to another page using the browser's back or forward button.

Environment: Mithril 1.0.1 on Chrome 56.0.2924.87 (Windows 10).

Previous Related Issue: #358

Sample Code:
```javascript
module.exports =
  { oninit:
      vn => {
              const id = Number( vn.attrs.id )
              const stream = M.loadItem( id )
              vn.state.data = { id, stream, initial: stream() }
            }
  , view: vn =>
    <div>
      <label class="label">
        Last Name
        <input
          class="input"
          type="text"
          placeholder="Last Name"
          onchange={ X.setStreamPropToValueAttr( vn.state.data.stream )( 'lastName' ) }
          value={ X.getStreamProp( vn.state.data.stream )( 'lastName' ) }
        />
      </label>
    </div>
  }
```

**Comment by pygy** [comment]
@kurtmilam Just to be sure, does this happen when you navigate to another page, or on routed components, and you navigate back to a previous route?

**Comment by isiahmeadows** [comment]
Also, @kurtmilam, could you verify it also repros with v1.1.0 (the latest release)?

**Comment by kurtmilam** [comment]
@pygy This occurs on routed components when I navigate to a previous route using the browser's back or forward buttons. I believe it's due to the fact that the action that triggers the input's `onupdate` event also causes the input to be removed from the DOM.

@isiahmeadows I have just verified that the described behavior occurs with mithril v1.1.0 .

**Comment by isiahmeadows** [comment]
@kurtmilam One last thing: could you edit your repro down to something that doesn't require external functions?

**Comment by kurtmilam** [comment]
@isiahmeadows I've just confirmed that the behavior persists when the component in question is stripped to bare bones:

```javascript
import m from 'mithril'
module.exports =
  { view: vn =>
      <input onchange={ console.log } />
  }
```

**Comment by kurtmilam** [comment]
I've also just confirmed that the behavior persists when I swap out the JSX syntax for javascript:

```javascript
import m from 'mithril'
module.exports =
  { view: vn =>
      m( 'input', { onchange: console.log } )
  }
```

**Comment by isiahmeadows** [comment]
@kurtmilam JSX is okay. I just needed a minimal workable repro.

How are you redrawing the component?

**Comment by kurtmilam** [comment]
@isiahmeadows I wanted to eliminate all possible variables.

The component is drawn on a specific route. The 'app' is just an experiment based on an extended version of the [simple application](https://mithril.js.org/simple-application.html) (from the mithril docs). The behavior occurs when I change an input on my '/edit/:id' route, then navigate back to the '/list' route while focus is still in the input.

**Comment by pdfernhout** [comment]
I'm seeing probabl ythe same error with Mithril v1.1.6:

mithril.v1.1.6.js:817 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at removeNodeFromDOM (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:817:30)
    at continuation (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:806:6)
    at removeNode (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:794:3)
    at updateNode (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:635:4)
    at updateNodes (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:556:6)
    at updateElement (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:687:4)
    at updateNode (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:629:15)
    at updateNodes (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:537:12)
    at updateElement (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:687:4)
    at updateNode (http://localhost:8334/pointrel20171122/bootstrap/mithril.v1.1.6.js:629:15)

I don't have it isolated to a simple case. In my situation, it seems to happen in a drawing app I am writing when I click onto some SVG objects and the app removes some input fields being displayed associated with a different SVG object. The consequence is it leaves the old input fields displayed alongside new ones.

This might be the root cause and some possible solutions:
 https://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node#22934552

**Comment by isiahmeadows** [comment]
Great...so something we need to work around internally (i.e. don't actually call the callback if we're currently removing the node)? 😦

**Comment by isiahmeadows** [comment]
So finally, a fix incoming in #2286.

**Comment by kurtmilam** [comment]
I'd be happy to work up a repro, but I'm not sure it'll work in flems or code sandbox (just tried in both), since I only saw the error when I used the browser's forward or back button to navigate to a different route in my mithril application while my input still had focus.

**Comment by isiahmeadows** [comment]
@kurtmilam If you have to, drop a `debugger` statement in the view of an offending component and try stepping through it. That might help you in isolating a repro case.

Alternatively, you could do `input.focus()` + `location.hash = ...`.

**Comment by pygy** [comment]
@kurtmilam you can post it as a gist then? 

Filename: `index.html`, load Mithril through https://unpkg.com/mithril@1.1.6, then we can load it with bl.ocks.org which is just a gist viewer.

**Comment by isiahmeadows** [comment]
@kurtmilam Do note that iframes *do* still work with hash navigation and history navigation.

**Comment by isiahmeadows** [comment]
@kurtmilam Found anything reproducible yet? At this point, we're not even looking for anything minimal, just self-contained (even if it means slapping together a full repo we have to clone).

**Comment by isiahmeadows** [comment]
PSA: I don't care if it's a website at this point - as long as you can point me to where the functionality breaks, I'm willing to reverse engineer minified JS and place strategic breakpoints if I have to to isolate this bug.

**Comment by kurtmilam** [comment]
I was able to reproduce this on Chrome 53 (probably the version I was using when I initially reported this issue), but have not been able to reproduce it on Chrome 70 or the latest versions of Firefox or Safari.

I reproduced it using this [flems experiment](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcICqkBOAxA9tgLYB0AVmCADQgBmAljJagNqgB2AhkRGpjgFl8SaOUo1Y+doml8Abp2wACLBGUBeJcAA67JfqVR6YeKiUsAulV0HD+TkgAyx00toBXdgnpSAFAEotG1sDbAh4d2w9UjCAR3cIE18dPRC0nngAC2EzbRAAcQBRABU861S020ioXJBM+HgABzBUAHpWsKIAWjCTLs5G+hJMtXwAa3cBxpJJIlaB+lb3HDAy4MqDAHd6LIBhMJFpek4oFqV4bATyjYBff3WQkiyIdl8PL3gfV973KHhAlIbWyqbAkIwmJSaH5-EhITjwTgPWx3B43coPWCRMLSMzANEPKD2JBmd7ePz0JAApGhcKRaIkOIJJKAoH6DLZYlKPJFUrUalpaq1epNFrtTo9RLwfqDYajCZTGb4OYLJYrVp5JQAaiUFOurKU2z2BxenxOZwuV35ShRFUez1epM+fmh-yCto2IJmWJNkKULqtNuR6NtYE4cggJM8ZNeVPdNIiUSUMQg8UlySttnZOS5IAAChheXrWYKc8Lmm0OhBur0pQtZdhxpNGtNZvNBqq1GB1SAtSocF7sNj4CRdRmDHCEWZPZjByai0DDZl9sgTcdTmYLRB58j7rabrobiA0RxuLx0CDnCYxNQQJJpCb5Io+2pL-BfSz9FJ6OwdlP+4SHFfec5HoCBNkjD4vgCN0NjCBNol8PISGWNQunBeAymfUF0JIIgBjeKMnVeFDsFjfU-VpRMiEQkBOGQnA0JcLodirTDgEyMJaFqVpkB2btexIkckCoJQpFgMJ4QjJMGXwdxEDBb8xjRJRBIYbATAAOVPXsNQ1bVBKgThNNPXdbn8UyDH3dhD2PEAuB4PgQQIYhrwkKQZHgR9lCcwgiHfYIQLAsw5D0dQAD4HmopQAHJv0aOTopE4BRK8TJOHYABzKS7zAfAYDBfAMutJRd0PGhIBgaNmBAABmVAAEYugABgagBWI8qBPBz0EcTgAE9ZOHCgbzvDyvKUXqBrk-zbUC8C3EIqCQuECAyMqOC6STGi8O-MF+sGzCWDHNkaK4ORcJedxDuOkJqLyRFqBg8iQg4iAuJi1p0MSm60jEiTEDMGJBogBT2DGH7LJEvIQVWEALNZCx-G3So7vAOAiMw5aRBmTJGCQbF4ZCRHUQPDqurPWjm1c293IfdAgbkkHGk4+gAA9fGigBiaLdwZxBfCQfBMR4aQSAAI2EPqoZAT6XDYh48llkw8lxK1sREbAIOjaCPyBDaqN8SbBpE6iLxccyA1RedFd4+BWlQCkVaetJ1bULWiN8LHVudvXKIQo25JN3wfOIESvZIeELjAC2430KygwPfwybs08+BmMBxBp+9ZHQCWkClkd2Hi+AqHFuT4CkLRaHc1B2F8k4lHqgA2RpWaUAA1NQ4S4ABuPDsAy78zAAJia1urN0PaprfYB+8H9gGrHtvODk-A+84Vmum2JAskXpql57qyLvYdwtDnoemqUS+aoPif2Ho1D0K0dCuhMPqYFrqQIHXgeL6vxuD6NAcEgb8GVUBNUPpPEijE+gsT8sAMWnBYBjAyg2TwxJOa0E4FgrBPcJbYA1g1VuShcpGCQEoTmSAqE90kISTWnMaqMJ7iAsAjRDJ9VQGLQkyCf7z3Af-eqrce5AKoaA1AAAOYh9VWpCMQKzKUIhJDYHhF8T+7Bv5H2gS-OBqBsjhmUMAORCi4CEBUVIVA6C1BGHUZA9gk9DJi2gFoFhbD+qcO4WMXhf9L4yNZrYwuxctD4MIYItupCKQUKoUgPBhANY9AcPQZYqAapCIlpvMA9AABeYjgmoTScw4wriOFcKFp48+C9L6X3qoA4BYjqlSN8T3beu9qlNQAKT+LFuXSuCCkEoLQewDBEBhkxIIW7UJJC8oRModQ3J2B4kgKSSkvxtDCCoAYUwlx7CHbsGsRALoJSeHlP4VUmpojMqLwabIiA8iuiKNMURNRGjJ5dIaOYvRaggl9NQbJQZ6yIDiIBQCw+R4rAgGsWMZgbAU7dRAEQHYHFGA3mqHwMsoolhFxQYqOY8KsjYEYAAAXqiQYlTdWi4sRVAam8A+qNApmAcS9BGieRuBYG4QA).

Steps to reproduce:
1. Go to the flems.
2. Click on any user's name to open the `/user/{id}` route.
3. Type a few characters into the input.
4. While the input still has focus, use the browser's back button to navigate back to the `/list` route.

et voila!

Screen shot (a little messy because I was running a virtual copy of Chrome 53 on turbo.net):
![image](https://user-images.githubusercontent.com/385695/49113807-c2156b80-f296-11e8-93ef-d9247aa2f675.png)

Apologies that it's taken so long to help track this down.

**Comment by isiahmeadows** [comment]
@kurtmilam Yeah, that reads like a browser bug we can't really work around, especially if [setting the hash directly](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAyBDAngewFd4A6AKzBABoQAzASxgtQG1QA7LAWwjRAFVIAJwCyeJNDIVqsPG0RzeANyyCABAIhqAvKuAAdNqqOqodMPFSrmAXUoHjJvFiQYzF1TQJsEdWQAoASl17B2NBCHgCQUNOYnCARwIIcz99Q1CM7ngACzFLPRAAcQBRABUCu3SMhyiofJBs+HgABzBUAHp28M4AWnDzHqxmumJszTwAawIh5uIZTnahunaCITAKkOrjAHc6HIBhcPE5OiwoNtV4QSTKrYBfAM3Q4hyINj9Pb3hfd-6CKHgQTSWwcGkExFM5lUOj+AOISCw8CwTwcDyed0qT1gUXCckswAxTygTiQlk+Pn8dCQQJRYQiURicQgiWS8FStMyEVypNUBRK5SoHNCtXqjRabU63T6rMGw1G4ymMzmeAWSxWa3aBVUAGpVFTbiCjLsDkc3t8zhcrjchWiqs9Xu9yd9-LDAcE7VswXMcWboapXTbHnbCWwnmAsIoIGSvBT3jSPXTItFVLEEkkUsDDSmuXleSAAAp8AUGw0ivNi1odLoQXr9eCykZjQSTabNWbzRbDdWaMCakA69RCb2CXEkfVChwIpGWL3Ykdmksg43ZQ7IM2nc6WK0QReooOogx3EAY9hcHjoMGucySKggGRyM1KFSDzRX+B+zNGWR0Nh7GdD4lnDfRdFDoCBtmjL4fkCd0tnCJMYj8ApiFWTQekheAKhfcEMOITghg+GNnXeVDBHjLN-XpZNOCQkAsBQoR0LcHo9hrLDgGycIaHqdpkD2PsB1I4h9VUWRYHCREoxTOJCEQCEfwmDFVCE+hBHMAA5M8By1LVdSEqAsA0s992qB4TKMO5D2PShT24XgwQAMTwQRYnIW973keAnzURznM4D8QlA8DLEUQwtAAPieGjVAAch-ZoiBiyhdFE7xsiwNgAHMpPvMA8BgCE8Ey1Q7lUIMj2oSAYFjJgQAAZlQABGazbPPTBcFkm9pFkTzvNUbB8CIAK7SCiCPCI6DQrECByOqeCGRTWj8J-CEOqILDmAnYwaIKDhFDwt4CA2rbMlo5EqFgijQjE0xYAmSDYxgz8rocYlYERH5Ri4v0CgAYgwgoTtM3csyUgowXWEBzJBawAhB06CkgWMsKm8Q5myBgkFxaGHFh9ErMq6A4GI2qABZUAAJgABhakAODs9AlTc7qHwUdBU1kiBiGaLi6AADz8GLfpioMOaICA-CQPBsW4ORiAAIzEHBkoKdoAYu57VfV-EhVxcRBAe4inqB+bqL8AbZOSmjLzcAIceMSzg0XVW+PgdpUCpAodYTIw9c0Q3JrYabZsNU3EItogrb8XyXOS1GucRK4wDtm10UqB5afptq5jAKQ7x6x90EVpBleEtgEvgSgFaIeBZF0GgetQIOXLOVRGoANmaPnVAANU0BEOAAbnwwRMp-Sxqa7x2DFWwb32AEex7YJqqa71QsCIPBh6wPmel2JAchXqnV75wfHYOtgCF0Rfx6p1Q77qk+z4MGfSKYqFgAwnpzBwGAm9kCA29R633vm3J+zRnBIB-JlVAVNn5sAYmhL+rF-LAHllgO6mVmxeFJL9GgWB8H4MHorQQ+smprzyqYJAqhfpIDoYPGQxIDa-TqqwweUCwDNAMjgVA8s3oTCAUvWBoDGpd0HhAuh0DUAAA416NQAKxiMQHzes4gZCCA+rIf+bBAHnzfsgxAnBUC5EjGoYAyjVFwGcpo5eODNCmB0fAmeBl5bQF0BwrhuBeH8MESAu+ijT7n3ikNNBzkyGiO7pQqkNC6FIGIWEtCGioGrFQHVMRitd5gDoAALykSQ-WPQMnsLMJ4nhfDpYCJvsvO+d9GrgMgVIupciAmD33ofOpVMACk8Dq5NDrmgjBEwsGEDYLgiA4z4mkP9hE1QUTqG0PofkxJzg6ApLSafRhzlUAsLYR47hHs2AOIgIUnxVThG1PqZIrKK9mlKIgConoajrHEW0bome8sa5aJMZoXQ6DMHYNGdsiA0jgXArPseWwIAHETCYKwOmZ5eCcD2JxBgt5ai8ArBKFY5chnKgWEinIggGAAAFGrEDJe3doBKUVQC6iAeAOBmhtTAOJOgzQvJ3GsHcIAA) doesn't trigger identical behavior. Given it takes a *seriously* old Chrome version for it to repro, I'm not sure we can fix it. BTW, we only support the *last 2 versions* of Chrome, so you need to create a repro that works on one of those.
