### ISSUE TITLE
Lifecycle methods passed to component called twice ?

### ISSUE THREAD

**Issue by h-ikeda** [MithrilJS/mithril.js#1775]
Please see https://jsfiddle.net/dhtn0zg4/2/

Output1 tests vnode's lifecycle methods and onclick event handler.
Output2 tests component's ones.

It seems that oncreate and onupdate functions passed to component are called twice.
I expected to see "oncreate out of component called." first (because it's passed to vnode in component.) then "oncreate in component called.".
But "oncreate out of component called." is displayed once more.

Is it bug or is there the solution to avoid this ?
Thank you.

**Comment by h-ikeda** [comment]
I understand. I could fix my problem.

Actually, I read the document below and thought to pass attrs directly. But it is usually bad idea when attrs contains lifecycle methods, is it?
https://mithril.js.org/components.html#avoid-restrictive-interfaces

**Comment by pygy** [comment]
`redraw()` on multiple `mount()` calls will be addressed at some point (IIRC it is fixed in #1592)

That example is a bit misleading for the `attrs`, indeed, it will break if there are hooks specified in them.

**Comment by isiahmeadows** [comment]
We've removed the section recommending attribute forwarding in any form, and we are considering in #2250/#2262 adding docs outside the main area to clarify how to correctly forward attributes (basically, pass it like `m(Comp, {attrs: {...attrs}})` and read it as `vnode.attrs.attrs`). However, we've specifically decided to *not* modify Mithril to avoid this.
