### ISSUE TITLE
Investigate duplicated DOM tree issue in routed mount point

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1781]
@modmanx reported a problem where he ends up with a duplicated DOM tree when switching routes:

https://gitter.im/lhorie/mithril.js?at=58e4abacad849bcf425273df

> hi, I updated to version 1.1.1 and when I change routes from route2 to route1 and back to route2 main layout is in DOM twice
>![image](https://cloud.githubusercontent.com/assets/54515/24755510/ddf156b0-1ada-11e7-9bfc-181e7e06f309.png)
>```JS 
>{
>    "/": {
>        render: function() {
>            return m(PageChooseEvent)
>        },
>    },
>    "/:id_event/brackets": {
>        render: function() {
>          appstate.active_page = 'brackets'
>            return m(Layout, m(PageBrackets))
>        },
>    }
>}
>```
> `m("div.page--event", ...)` is what Layout component returns

@modmanx it would be nice if you could provide a JSBin repro. Also, what version were you upgrading from?

**Comment by modmanx** [comment]
Hi,
I'll try to make JSBin repro now. I believe it has something to do because I'm using iframe with youtube embed and enablejsapi parameter set to one.

**Comment by pygy** [comment]
@modmanx thanks for the follow up :-)

**Comment by modmanx** [comment]
Hello again. I found out what do I need to do to fix this but not sure where exactly is the problem. I can not reproduce on jsbin or locally. I will try to copy project and remove as much code to reproduce bug.

Anyhow - All I did was to include app.js code (generated code with webpack) to be last script to be included in body.

**Comment by pygy** [comment]
:+1:

What version were you upgrading from?

**Comment by modmanx** [comment]
Now I'm rethinking and I believe we did not had this code exactly in a state that would cause bug like it's happening now, so I don't think that's bug related. It was 1.0.1 before. I will copy code and set mithril to this version and check if bug is there. Gimme a minute.

**Comment by modmanx** [comment]
I checked and tested with version 1.0.1 and div gets rendered twice if <script src="app.js") is not last one added. Should we set-up some teamviewer if you would like to check our code?

**Comment by pygy** [comment]
I don't really have the time to remote debug right now, sorry :-(

Maybe this weekend, in the evening...

**Comment by nzsg** [comment]
This was easy to reproduce for me. Just stick an m.redraw() in a component view function. Or in my case, the redraw was deeper down through several layers of components! You need to do some interactions on the page to get the multiple duplicate DOM elements to show. If this doesn't help someone fix let me know and I can try and find the time to do a JSBin repro.

![duplicate-dom](https://cloud.githubusercontent.com/assets/26780253/24832363/d2e0d4d8-1d02-11e7-8cc4-35c9f8582579.png)

```
module.exports = {
    view: function (vnode) {
        m.redraw();
        return m("div", "hey");
    }
};
```

**Comment by pygy** [comment]
@nzsg thanks for the input. Assuming @modmanx's problem had the same root cause, it is fixed by #1592 / #1765.

If you need to trigger a redraw from a hook/view, for now you'd better delay it with `setTimeout(m.redraw)` for consistent/non-crazy behavior.

**Comment by nzsg** [comment]
@pygy Thanks, I've got workarounds in place for the crazy that aren't setTimeout. I'm following the discussions and fixes with interest. Mithril is a really neat little package.

**Comment by purefan** [comment]
Thanks to everyone involved in this bug report, I was having the exact same issue and @pygy 's suggestion fixed it for me. 
Much obliged!

**Comment by isiahmeadows** [comment]
So is this close-worthy?
