### ISSUE TITLE
ospec-the-library should throw rather than call process.exit(1)

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1782]
https://gitter.im/lhorie/mithril.js?at=58e4dfe48bb56c2d11797f22

This was raised by @vladpazych on gitter:

>Hello everybody.
>I am trying to setup ospec for tdd, but when at least one test fails - my test server exits.
>Is it expected behaviour?
>I do something like this:
>watch(path.resolve('./test/unit'), { recursive: true }, function () {
>```JS
>  var _o = o.new()
>  _o('addition', () => {
>    _o(1 + 1).equals(2)
>  })
>  _o.run()
>})
>```
>I tried to catch _o.run(), but there is no exception. It just stops server.

We could have ospec-the-binary call `process.exit(1)` instead if ospec-the-library throws

**Comment by isiahmeadows** [comment]
Better: `process.exitCode = 1` from the binary, and invoke an error-first callback when done.

**Comment by pygy** [comment]
Fixed by #2020
