### ISSUE TITLE
Run danger against PRs

### ISSUE THREAD

**Issue by tivac** [MithrilJS/mithril.js#1784]
I would like to implement http://danger.systems/ for mithril PRs.

![image](https://cloud.githubusercontent.com/assets/49545/24785875/ba188c28-1b4c-11e7-8f3b-1cca2141f1e1.png)

They've got a nodejs version that I implemented against `modular-css` as an experiment, it's nice.

Here's my current list of ideas for checks:

- 🛑 PR targeting `master` instead of `next` 
- 🛑 lint failures (since they don't fail the build)
- 🛑 `o.only` in a test
- ⚠️ Request a `change-log.md` entry for `.js` file changes
- ⚠️ Request a descriptor of the semver change required for the PR to land (if `.js` files changed)

Any other ideas? Anyone vehemently against this proposal?

**Comment by pygy** [comment]
I'm vehemently *for* this proposal

**Comment by isiahmeadows** [comment]
I like this proposal a lot myself. I'll note that the `"use strict"` requirement is already mandated by the ESLint settings, so making DangerCI check it is redundant.

**Comment by tivac** [comment]
@isiahmeadows fair, edited. I think the danger-style output is a lot nicer to read than eslint results though. Especially since lint failures don't fail the build.

<br />
<br />
<br />
<br />
<br />
<br />
yet.
