### ISSUE TITLE
Weird behavior with keyed elements in a fixed-sized, but changing list

### ISSUE THREAD

**Issue by hmans** [MithrilJS/mithril.js#1791]
Hello friends,

I'm observing a weird behavior in regard to Mithril's handling of keyed elements in a list. Frankly, I don't know if this is a bug in Mithril, or just a plain misunderstanding on my part, or maybe even just a weird side-effect of how browsers apply CSS animations. Maybe someone can shed some light?

Consider the following Codepen that I've prepared: https://codepen.io/hmans/pen/aJeNpM

**Description:** Every second, an item gets added to the top of a list; this list is truncated to hold a maximum of 5 items. Mithril renders this list, and there's a tiny CSS fade effect on the class used by list entries.

**What works:** For the first five entries created, everything is normal: the new item appears on top of the list and fades in through the magic of CSS.

**What's broken:** Once we reach 5 items, new items keep getting added, and the list is truncated, but observe how now _all_ items in the list get the CSS animation applied to them, not just the newly added item.

I've added a bit of console logging to `oncreate` and `onremove`, and from what I can see there, the corresponding vnodes get created (and removed) exactly as expected, Mithril is definitely getting the lifetimes of these vnodes right.

But it still looks like Mithril ends up recreating the actual DOM nodes, causing the CSS animation to re-apply.

Note that this only happens in the truncation scenario (ie. when the list is the same size as before), and only if we add items to the top of the list. When I change the code to append (and not prepend) items, or when I remove the list truncation, everything works as expected.

FWIW, this happens in the most recent stable versions of Chrome, Safari and Firefox.

**Comment by isiahmeadows** [comment]
Definitely an odd bug, since they're clearly keyed.

**Comment by brlewis** [comment]
I'm curious about whether it's a weird side-effect of how browsers apply CSS animations, but not curious enough to write a jQuery-based equivalent to see what happens.

**Comment by balajisivanath** [comment]
@brlewis This is not browser related issue. When a new item is prepended in a fixed list, instead of inserting that dom element alone, all of the dom elements are rearranged (removed from their current position and inserted again). When we do append instead of prepend, then this issue is not there. i.e only new dom element is appended, previously present elements remain untouched. So I guess the said behaviour must be a bug in Mithril.

**Comment by isiahmeadows** [comment]
@balajisivanath Just out of curiosity, add an expando property to it and see if it's still there after diffing. I'm trying to figure out if it's actually being recycled or not.

**Comment by brlewis** [comment]
So probably a bug in the updateNodes function https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L147

Really tempted to look into it but I should work on something else.

**Comment by pygy** [comment]
Node identity is [preserved](https://flems.io/#0=N4IgTgpgZpDOAWAhArgF1QewHYgFxQEMAbWCAGhFKIgGNUIATPEAOgCtYQKoBLaz3AG1QWAgFsIzFvFRiiXEDWz0sqZiAC+ZEeMm5WHBUtURVzY7FQACVPB5YA5rCsBeK4IC6AbgA6WP9TWPAwA4qYQYASYYK5WAAy+-lhQyFh0PNhWBAwMVgAUohIAlFbAflY2do6wLKkIPFCoeWVYFRXBuFbBYVgRURhgANSDZOVthRCdPiAAKsgOyAypPGCr02MaRYkVtvZOLLAADkQ8NBB5AKxbfhqJfhbWM1UOsS0V2PY8TQBuWBgMEBKbzauxqu0csV+-wgLCiqDAYOe2ysWjG2BokCi5yhAKBYwqFgw1BYRAwDjy03RmPo0zIlR4iL211aILsNQYGDEkL+AJYHLEG1GLOwyEODCxeRxgOB7Sg+VBLHBDhYwVcLjcAGY8Sy2lZCcTSeTpgA5aFWDV0-ldAGqL4ATyshzgEW+jCmICsg3lbL5nLVbilvrERSK+JRgrRWEgYgwrslPMBpTD+phhopIGw0djEFp9MZjmZFVRLO+PAgAHd49DtbrIKhkGBWmJ0wweN9Fc9cwqlSrcl7pu7PXmO3sWBNC+GsLc-PdsJYrE89gAFMD2egxNzA0sVzopNKoDJYPI1tp1hutQRhirNgDkACM0JgsDe6cB0ScaABrTrZBhaKzTAAgjk0xFEKurXi2bYjo4AC0JyWF2zw1GIBCHHkeR7uk2B5EqJ61hA9aNlYzaLo4r5Xm0n4QHanQ9sE4EQTszx0Z2OptJsyJFiGRTeBsNx3FgYgsDGqRNByNDIBIqgsHe-x2nSZEOCua4RMymjaCAExSDQsCcBQxgqGo+gAALUXaMC6M4hAArB9hJiyMB+sAVgYIcBA0PanRxJOOwYG0LluR5XlWAAjJOGgzlgMEvMCd4eZ+DhgBgqQMLBSikmAnQAMQ0HlyKoWADj2J0FyHAAHvEyLuTkeylRVBUEOVsHlsEtidBqcRxA1YxjAQWA8KhB7YLu2QQHZrRxCwAAcsBeBUNyaB4FAnFgn4CMIIANvI+gyKghywLgAD0R2pIciUsEoYhHWIXzwKuRAmaFLDPaFCioHahx6CAhgaB4GhAA).

**Comment by pygy** [comment]
Digging deeper into this, I got side tracked and ended up in `createFragment()`: https://github.com/MithrilJS/mithril.js/blob/9b947f41f04fc923a22cd32820b655fc61b089b2/render/render.js#L65-L74

That function returns an empty fragment. AFAICT, the only place that consumes the return value is [updateNodes on line 228](https://github.com/MithrilJS/mithril.js/blob/9b947f41f04fc923a22cd32820b655fc61b089b2/render/render.js#L228) (`createNode()` and `createComponent()` just forward the value but will not use it... @lhorie do you remember why it does that?

**Comment by pygy** [comment]
This will be fixed in Mithril v2 (it is in the `next` branch).
