### ISSUE TITLE
Continue search of routes

### ISSUE THREAD

**Issue by PetrChalov** [MithrilJS/mithril.js#1792]
In the case of a return onmatch false, continue to search for matches.

For example, if you perform parameter validation in the onmatch method.

Example:

```
   {
        /*action - String param*/
        '/user/:action': {
            onmatch: function (args, requestedPath) {
                if (!isNaN(args.info)) return false;

            }
        },
        /*id - Number param*/
        '/user/:id': {
            onmatch: function (args, requestedPath) {
                if (isNaN(args.info)) return false;


            }
        }
    };
```

In this case, after calling onmatch in the router / user /: action, the routing will not proceed further.

**Comment by pygy** [comment]
This isn't easy to add with the current implementation. The router code is split into a core (`router/router.js`), which matches routes, and a shell (`api/router.js`) which deals with the hooks, and hooks cannot resume the core if `onmatch` fails.

You can also easily handle both cases in `/user/:info`, so I don't see a pressing need for this.
