### ISSUE TITLE
`ospec` package should be published alongside `mithril` during the release process.

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#1801]
[Spawned from a Gitter discussion](https://gitter.im/lhorie/mithril.js?at=58f195a269a692963eb064ea).

@tivac Since this is mainly your thing, could you work on and fix this?

**Comment by tivac** [comment]
I don't think travis can publish more than one package at once via it's [npm releasing](https://docs.travis-ci.com/user/deployment/npm/) feature, but I might be able to figure something out. I'm not in a rush to solve this though.

**Comment by isiahmeadows** [comment]
I just assumed it was via a custom script, not a Travis thing.
