### ISSUE TITLE
"use strict" in global space of stream.js script

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#1831]
This: https://github.com/lhorie/mithril.js/blob/next/stream/stream.js#L1

Should probably be inside the IIFE?

Also appears in https://unpkg.com/mithril@1.1.1/stream/stream.js

Linting rules appear to prevent moving it: "Use the global form of 'use strict'"

One other thing, this is out of date: https://unpkg.com/mithril-stream

**Comment by isiahmeadows** [comment]
That would be a bug needing fixed.

**Comment by isiahmeadows** [comment]
As for unpkg being out of date for that:

1. `mithril/stream` is generally better to use, and [is the one referenced in the docs](https://mithril.js.org/stream.html).
2. `mithril-stream` is out of date [on npm](https://www.npmjs.com/package/mithril-stream).
3. The docs for it are both inaccurate and inconsistent, and *really* should be fixed.

**Comment by isiahmeadows** [comment]
Fixed in https://unpkg.com/mithril-stream@1.1.0/stream.js and https://unpkg.com/mithril@1.1.6/stream/stream.js
