### ISSUE TITLE
Update migration documentation to explain changes in `key`

### ISSUE THREAD

**Issue by dwaltrip** [MithrilJS/mithril.js#1833]
Mithril v1 appears to be fairly strict with how it makes use of `key` attributes. In mithril v0.2.5, you could often get away with mixing keyed and non-keyed siblings, and things would work as expected.

I made a minimal, working example that demonstrates the difference in behavior:
https://gist.github.com/dwaltrip/3e0b4ad7b0187284a36bcdab674e9a15

I personally ran into this while migrating to v1, and it took me a few hours to find the issue (after a few dead-ends, I skimmed the v1 docs again and noticed the stricter language regarding `key`).

It might be worth adding a small section to the migration documentation, in case anyone else has this issue. I'd be happy to write up a first draft and create a PR. Let me know if I should go ahead and do that.

Here's a stab at code examples that could be used, similar to the other sections of the migration docs:

#### v0.2.x

```js
var App = {
  controller: function(params) {
    /* set `this.items` */
  },
  view: function(controller) {
    return m('.item-list', controller.items.map(function(item) {
      return m('.item-wrapper', [
        m('.item-icon'),
        // mithril v0.2.5 will attempt to make use of keys even if siblings don't have keys
        // so the following will usually work
        m(Item, { item: item, key: item.id })
      ]);
    })
  }
};
```

#### v1

```js
var App = {
  oninit: function(vnode) {
    /* set `this.items` */
  },
  view: function() {
    return m('.item-list', this.items.map(function(item) {
      return m('.item-wrapper', [
        m('.item-icon'),
        // a nested array is needed to prevent mixing keyed & non-keyed vnodes
        // otherwise, the Item component will not update properly if the order changes
        [
          m(Item, { item: item, key: item.id })
        ]
      ]);
    })
  }
};
```

**Comment by isiahmeadows** [comment]
Nit: your key should be in `.item-wrapper` for best results with either version.

**Comment by dwaltrip** [comment]
Oh, perhaps I should have mentioned that I specifically did it this way -- the issue isn't present otherwise. The code example is a contrived, minimal example.

Imagine that `.item-wrapper` is one of several special contexts in which the `Item` component can be used. Add a few layers of abstraction, and placing the key on the inner vnode becomes convenient/non unreasonable.

**Comment by isiahmeadows** [comment]
Okay.

**Comment by dwaltrip** [comment]
Looks like this is already being discussed in https://github.com/MithrilJS/mithril.js/pull/1725

**Comment by isiahmeadows** [comment]
@dwaltrip This is what #1725 is attempting to fix:

```js
var App = {
  oninit: function(vnode) {
    /* set `this.items` */
  },
  view: function() {
    return m('.item-list', [].concat.apply([], this.items.map(function(item) {
      return [
        m('.item-icon'),
        m(Item, { item: item, key: item.id })
      ]);
    }));
  }
};
```

Note the lack of `.item-wrapper` - if this is broken, then it's another symptom related to #1713 and #1724.

**Comment by isiahmeadows** [comment]
This appears fixed in the latest website docs: https://mithril.js.org/keys.html#avoid-mixing-keyed-and-non-keyed-vnodes-in-the-same-array
