### ISSUE TITLE
mountpoints should not be redrawn after `unmount`

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#1840]
see https://jsfiddle.net/cmx66/fhb0dtrw/

I think what happens here, is that `m.redraw()` initiates a async redraw. The unmount after this unmounts the tree, but the triggered redraw readds the nodes.

Expected behaviour is that unmounted mount points should not get redrawn at all.

**Comment by pygy** [comment]
I think that monolithic redraws as described in #1765 would solve this.

**Comment by isiahmeadows** [comment]
The current behavior is supposed to be to render an empty tree synchronously, then unsubscribe the root. I believe the bug is in the redraw mechanism, because it shouldn't even see the tree to begin with.

**Comment by pygy** [comment]
Currently `m.mount()` calls `redraw()`, causing the next `redraw()` to be async. Since the mount point array is iterated synchronously over on `redraw()` call, rather than async, the root redraw is scheduled, hence the buggy behavior.

If instead we iterate over the roots asynchronously (as planned in the monolithic redraw update), the removed root would not be re-added.

**Comment by isiahmeadows** [comment]
@pygy 

> Currently m.mount() calls redraw(), causing the next redraw() to be async.

[Derp.](https://github.com/MithrilJS/mithril.js/blob/next/api/mount.js#L19)

Here's how I feel it could be solved:

> If instead we iterate over the roots asynchronously (as planned in the monolithic redraw update), the removed root would not be re-added.

How about we instead schedule a sync, unthrottled initial redraw on the root iff it was not mounted last redraw.

I have a few (IMHO) better, more detailed ideas on how to make the redraw system more sane, that I'll detail in a separate issue, though, to not pollute this one.

**Comment by StephanHoyer** [comment]
For every one who faces this issue, here is a temporary workaround until this is solved in core.

```js
var m = require('mithril')
var origMount = m.mount

var mountEls = []
var mountComponents = []

m.mount = function mount(el, component) {
  if (component) {
    component = Object.assign({}, component)
    mountEls.push(el)
    mountComponents.push(component)
  } else {
    var index = mountEls.indexOf(el)
    mountComponents[index].view = function() {}
    mountComponents[index] = mountEls[index] = null
  }
  origMount(el, component)
}
```

**Comment by isiahmeadows** [comment]
Before I forget, the redraw proposal I meant to link here about a week ago is #1847.

**Comment by StephanHoyer** [comment]
works as expected in [v2](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evfQhoIxRHrAzqxCPVkA3NFpgBKA8dOmhcLSw+FC0AOayAOTmlsSRnr567IkuEDAA7jZ2aA5OaK7u8l4+Jn4ATjDEUmUmWFHyEC6R+pEAjPGJrMasCWjiFfJlGOmyveKSMsQKSioiGlq6emhSUFCelCBwMLC59Ag8AByIB2wcIJg4ePjUcAI09IzMPGwAulRQFgDW+6jnXGJWQhlaAAAQATPgAAxQgC0ZWoUI21XIPBIxAADnBEAB6bEydGfMLXWhYbFYQHAqDgqGw+FQskU6D4fgbYjadHcTbUYHo0SsF6sIA)

does not work in [v1](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evfQhoIxRHrAzqxCPVkA3NFpgBKA8dOmhcLSw+FC0AOayAOTmlsSRnr567IkuEDAA7jZ2aA5OaK7u8l4+Jn4ATjDEUmUmWFHyEC6R+pEAjPGJrMasCWjiFfJlGOmyveKSMsQKSioiGlq6emhSUFCelCBwMLC59Ag8AByIrQAMbBwgmDh4+NRwAjT0jMw8bAC6VFAWANb7qJdcMRWQhlaAbarkHgkYgABzgiAA9AiZDDvmFbrQsAisMDQVAAAKtfBEgBs2Nx0Hw-A2xG0MO4m2ooJholYb1YQA)
