### ISSUE TITLE
redraws can be called before m.route.set() but not get run until after but still have access to the previous m.route.get() value

### ISSUE THREAD

**Issue by dontwork** [MithrilJS/mithril.js#1844]
Just resolved some weird bug where running a delete request, and deleting the resource locally and then setting the route to go to the resource list page was causing some issues and it looks like the routine redraw caused by the m.request of the deletion was getting queued until AFTER i had set m.route.set('properties') and then it was redrawing it based on the previous route as if it had the propertyId from the route which made the app error because it was looking for a property that didnt exist.

**Comment by pygy** [comment]
Could you try to repro in JSBin (using `m.request(''+window.location)` to avoid CORS errors and REM downtime)?

**Comment by dontwork** [comment]
https://jsbin.com/jirolinuku/edit?html,js,output

go to the link, open devtools, click one of the links then click delete then see the error where it cant find the item in the list, because a redraw is happening on the previous page after a m.route.set back to home

**Comment by pygy** [comment]
It actually works as intended (mostly). Blocking redraws pending route resolution would make the app unresponsive while an async route is being resolved.

The redraw triggered by `m.request` could be made async though, that would fuse it with the one triggered by `m.route.set`.

You can work around the issue by adding an `onbeforeupdate` hook to your `other` component that returns false if its model has been deleted.

**Comment by dontwork** [comment]
So is the solution to work around it or do you think the request redraw should be made a sync?

**Comment by pygy** [comment]
The request redraw will be made async when `m.redraw()` becomes always async. It's on the TODO list, but I need some time to work on it...

So, in the mean time, I'd advise you to work around it, however you like. The `onbeforeupdate` approach is more reliable, but maybe overkill (the chance of a user-triggered redraw that occurs between the response and the route resolution is really small, if at all present)...

**Comment by isiahmeadows** [comment]
`m.async` is now always async, so I'll consider this bug resolved.
