### ISSUE TITLE
mitril routes not refresh div

### ISSUE THREAD

**Issue by acodigo** [MithrilJS/mithril.js#1849]
No refresh data in div?
I pass the id, it does not refresh the data obtained with the new id
var FolderList = require("./views/FolderList")

m.route(main, "/list", {
        
        "/folder/:id": FolderList,
        {
        render: function(vnode) {
        return m(FolderList, vnode.attrs)
        }

**Comment by pygy** [comment]
@acodigo your code sample seems incomplete... Could you post a JSBin with an example of problematic behavior?

**Comment by acodigo** [comment]
`'
the index.html
...
<div id="marcas"></div>
  <h5><i class="fa fa-cog" aria-hidden="true"></i> XXXx.</h5>
  <ul>
  <li><a href="#"> Cambiar credenciales</a></li>
  <li><a href="#"> Cerrar sesión</a></li>
</ul>

<div class="column column-75 content column-offset-25" id="main">
</div>
...
`
the index.js
`
var m           = require("mithril")
var MarkList    = require("./views/MarkList")
var FolderList  = require("./views/FolderList")

marcas = document.getElementById('marcas');
main   = document.getElementById('main');

m.mount(marcas, MarkList);

m.route(main, "/list", {
    "/list": MarkList,
})


the marLlist
`
var m    = require("mithril");
var Mark = require("../models/Mark");

let loop = {
	mark : []
	,view: () => {
		return m( "ul", loop.mark.map( (mark) => {
			return m( 'li', m('a', { href: "#!/mark/" + mark.id }, mark.nombre) )	
		} ) )
	}
}

let exp = {
	oninit: Mark.loadList
	,view: (vnode) => {
		loop.mark = Mark.list;
		return m(loop);
    }
};
`

marksFolder.js
`
var m    = require("mithril");
var Mark = require("../models/Mark");

var template = {
	view: () => {

		return m('table', 
			[ 
				m('thead', 
					m('tr', [ 
						m('th', 'Nombre'), 
						m('th', 'Tamaño'), 
						m('th', 'Fecha'), 
						m('th', 'Estado') 
					]) 
				)
				,m('tbody', this.current.map( (folder) =>{
					return m('tr', [ 
						m('td', 
							m('a', { href: "#!/folder/"+folder.id, onclick: load} , folder.name)
						),
						m('td', '-'), 
						m('td', folder.fecreg), 
						m('td', folder.is_check) 
					])
					} )
				)
			]
		)

		return 
	}
};

MarksList = {
	current: []
	,oninit: (vnode) => {
		Mark.loadFolders(vnode.attrs.id);
	}
	,view: (vnode) => {
		
		this.current = Mark.folder;
		return m(template)
    }
    
}
module.exports = MarksList;
`
Problem: When I click on the div links #marcas only refresh the first time in #main. Then do not refresh the list

Regards

**Comment by isiahmeadows** [comment]
@acodigo Could you cut the code size down a bit? There's too many moving parts to easily diagnose the issue.

**Comment by acodigo** [comment]
@isiahmeadows ok
