### ISSUE TITLE
Router issue with m.route.link

### ISSUE THREAD

**Issue by Manidos** [MithrilJS/mithril.js#1854]
Let me start off with saying that I've just started learning Mithril. It's the most beautiful framework I've ever seen. Angular can suck it all day long.
Anyway, I've stumbled upon this issue and not sure if it's normal behaviour or not. 
The code below is from this [codepen](http://codepen.io/Manid/pen/zwLQGG).
The problem is that when I click on `Link three` router fires `routeResolver`'s render function on route `/two`. It shouldn't happen, because `Link three` has neither `href: ''` nor `oncreate: m.route.link`. Also, when `onclick` is not specified on `Link three`, everything is ok.

```
const outlet = document.body;

//COMPONENTS
class Link {
  view(vnode){
    return m('a', vnode.attrs, vnode.attrs.title);
  }
}
class ViewOne {
  view(vnode){
    return m('div', 'view one');
  } 
}
class ViewTwo {
  view(vnode){
    return m('div', this.getLinkThree());
  } 
  getLinkThree(){
    return m(Link, {
      title: 'Link three',
      onclick: () => {} // removing this handler solves the problem (routerResolver's render not invoked)
    });
  }
}

//HELPERS
const getLinkOne = () => {
  return m(Link, {
    title: 'View One',
    href: '/one',
    oncreate: m.route.link
  });
}
const getLinkTwo = () => {
  return m(Link, {
    title: 'View Two',
    href: '/two',
    oncreate: m.route.link
  });
}
const getViewHolder = () => {
  return m('#view-holder');
}

//INIT
m.render(outlet, [
  getLinkOne(), 
  getLinkTwo(),
  getViewHolder()
])
m.route(document.getElementById('view-holder'), "/one", {
  "/one": {
    render: () => {
      console.log('RENDER ONE');
      return m(ViewOne);
    }
  },
  "/two": {
    render: () => {
      console.log('RENDER TWO'); //also logs when clicking on 'Link three'
      return m(ViewTwo);
    }
  }
})
```

**Comment by isiahmeadows** [comment]
@Manidos Not saying this won't get fixed, but `m.route.link` was made to be directly used on the DOM vnode itself, like in `m("a", {oncreate: m.route.link})`.

**Comment by Manidos** [comment]
@isiahmeadows , hey! Thank you for the information. I'll rethink my approach.

**Comment by isiahmeadows** [comment]
Note: `m.route.link` will be called twice due to the common gotcha in #1926. That may be a contributing factor here.

**Comment by isiahmeadows** [comment]
So here's how this comes about:

1. Mithril auto-redraws on event handlers. This is why removing the `onclick` handler seems to work.
1. When you pass `vnode.attrs` through directly as a vnode's attribues object, you run into https://github.com/MithrilJS/mithril.js/pull/2250, resulting in its hooks getting called twice.

This is why this behavior exists.
