### ISSUE TITLE
m.route.set() to current path

### ISSUE THREAD

**Issue by andraaspar** [MithrilJS/mithril.js#1856]
Hi,

When `m.route.set()` is called with the same path as the current path, an additional entry is added in the history. Hence, the back button needs to be pressed twice to get back to the previous path. Since the path is assembled by Mithril – and I know of no API that would allow me to assemble the path –, I cannot test for this equality before calling `m.route.set()`.

1. Maybe the API `m.route.set()` uses to assemble the path should be public?
2. Maybe `m.route.set()` should ignore the second call?
3. Maybe `m.route.set()` should accept a flag to behave differently?
4. Am I missing something?

**Code:**

```JS
var Comp1 = {
  view: function (v) {
    return m('div', 'Comp1')
  }
}

var Comp2 = {
  view: function (v) {
    return m('div', 'Comp2')
  }
}

var Wrapper = {
  view: function (v) {
    return (
      m('div',
        v.children,
        m('div', m.route.get()),
        m('button', {
          'onclick': function () {
            m.route.set('/page1')
          }
        },
          'Page1'
        ),
        m('button', {
          'onclick': function () {
            m.route.set('/page2')
          }
        },
          'Page2'
        ),
        m('button', {
          'onclick': function () {
            history.back()
          }
        },
          'Back'
        )
      )
    )
  }
}

var Page1 = {
  view: function () {
    return m(Wrapper, m(Comp1))
  }
}

var Page2 = {
  view: function () {
    return m(Wrapper, m(Comp2))
  }
}

m.route(document.body, "/page1", {
  "/page1": Page1,
  "/page2": Page2
})
```

Here's a [fiddle](https://jsfiddle.net/andraaspar/xbw8oqaa/). Press the button 'Page2' twice, and you need to press back twice to get back on Page1.

**Comment by spacejack** [comment]
What about:

```
if (m.route.get() !== '/page1') {
    m.route.set('/page1')
}
```

There's also `m.route.set('/page1', undefined, {replace: true})`

**Comment by andraaspar** [comment]
@spacejack OK, how would you implement that without hardcoding the path? Example:

```JS
const PAGE_ROUTE = '/page/:id'
const PAGE_ROUTE_DEFAULT = '/page/1'

var Comp1 = {
  view: function (v) {
    return m('div', 'Comp1')
  }
}

var Comp2 = {
  view: function (v) {
    return m('div', 'Comp2')
  }
}

var Wrapper = {
  view: function (v) {
    return (
      m('div',
        v.children,
        m('div', m.route.get()),
        m('button', {
          'onclick': function () {
            if (m.route.get() != PAGE_ROUTE /* What goes here? */) {
              m.route.set(PAGE_ROUTE, { id: 1 })
            }
          }
        },
          'Page1'
        ),
        m('button', {
          'onclick': function () {
            if (m.route.get() != PAGE_ROUTE /* What goes here? */) {
              m.route.set(PAGE_ROUTE, { id: 2 })
            }
          }
        },
          'Page2'
        ),
        m('button', {
          'onclick': function () {
            history.back()
          }
        },
          'Back'
        )
      )
    )
  }
}

var Page1 = {
  view: function () {
    return m(Wrapper, m(Comp1))
  }
}

var Page2 = {
  view: function () {
    return m(Wrapper, m(Comp2))
  }
}

m.route(document.body, PAGE_ROUTE_DEFAULT, {
  [PAGE_ROUTE]: {
    onmatch: function (args, path) {
      if (args.id == '1') return Page1
      else return Page2
    }
  }
})
```

[Fiddle here](https://jsfiddle.net/andraaspar/xbw8oqaa/2/).

**Comment by andraaspar** [comment]
@spacejack Also, I thought replace would not work with `#!`.

**Comment by spacejack** [comment]
I suppose you'd need to reconstruct the path yourself (there is also `m.route.param` to help.) I'm not sure what the API behaviour *should* be when you set the route to the same as the current; maybe it should replace in the same way the browser does when you click the same link.

**Comment by andraaspar** [comment]
@spacejack Hence my 1st request.

**Comment by barneycarroll** [comment]
The place to account for this is in RouteResolver `onmatch`, where incoming routes can be cancelled before they resolve. `onmatch` is provided with all the data about the incoming route, but can also query `m.route.get()`, compare, and cancel route resolution by returning a promise:

```js
onmatch(params, path, route){
  if(path === m.route.get())
    return new Promise(() => {})
}
```

This issue is superceded by #1759, with documentation coming in #2672
