### ISSUE TITLE
"options.state" isn't reflected to history.state

### ISSUE THREAD

**Issue by tanagumo** [MithrilJS/mithril.js#1857]
Calling `m.route.set` with `options.state` within `onmatch` hook of a RouteResolver, `options.state` isn't reflected to `history.state`.

Is it a bug?

**Comment by pygy** [comment]
It is: https://github.com/MithrilJS/mithril.js/blob/7ee4e002f3354c346da0d1cc390c2d7bbf3ebd31/api/router.js#L42, thanks for the report
