### ISSUE TITLE
When a request fails, don't copy the JSON response over the Error object

### ISSUE THREAD

**Issue by boblehest** [MithrilJS/mithril.js#1866]
When a request fails, currently, the JSON response is copied over the Error object before it is returned:
```js
var error = new Error(xhr.responseText)
for (var key in response) error[key] = response[key]
reject(error)
```

(This behavior was introduced in commit 36e68948593404eaa27a26092391d048498ca435.)

I think it would be useful to bundle this information under a property (e.g. `error.response = response`), otherwise you risk overwriting the original properties of `Error`, and you have to separate the data again if you want to use it (this might be simple, or it might be impossible* — it depends on the format of the response.)

\* Barring any JS-tricks I'm unaware of.

**Comment by isiahmeadows** [comment]
I would consider this a breaking change, but not necessarily a large one.

As for losing data, if the response returns an object with a `"message"` (which isn't uncommon) or `"stack"` (which is much less common), you'll almost assuredly lose some data unless you call the `Error.prototype.{message,stack}` getters directly (from `Object.getOwnPropertyDescriptor`).
