### ISSUE TITLE
Convert false style attribute value to empty object or null

### ISSUE THREAD

**Issue by porsager** [MithrilJS/mithril.js#1867]
Currently mithril throws if a false value is passed to the style attribute since it directly tries to set it on the dom.style property which isn't allowed.

The reason I'd like to see falsy values converted to an empty object are the same reasons as for why [false values in vnodes are converted to empty vnodes](https://github.com/MithrilJS/mithril.js/issues/1014).

Currently I do the following:
```
m('div', {
  style: green ? { background: 'green' } : {}
})
```

Whereas it to me would seem more idiomatic mithril to be able to do:
```
m('div', {
  style: green && { background: 'green' }
})
```

What do you think?

**Comment by pygy** [comment]
Agreed, and more generally, `false` attributes/properties may be consired equivalent to a lack of attribute (unless some properties have different behaviour when set to either `null` or `false`).

#1865 is already refactoring the attributes code.

**Comment by isiahmeadows** [comment]
Note that this general thing was almost discussed to death in #1014, and here's a quick summary of the two main things considered there, including both the good and bad:

1. Checking `true`/`false` is generally safe and would provide a nice, short sugar. It's also fairly trivial to implement, and is non-breaking enough to land in a minor version increment. But some people would quickly start doing things like this and find themselves running into problems:

    ```js
    // This would return `0` when `this.times === 0`
    this.times && m("button", {onclick: () => this.reset()}, "Reset"),

    // It would need corrected to one of these
    !this.times || m("button", {onclick: () => this.reset()}, "Reset"),
    this.times !== 0 && m("button", {onclick: () => this.reset()}, "Reset"),

    // The current equivalent
    this.times ? m("button", {onclick: () => this.reset()}, "Reset") : null,
    ```

    For this particular one, I'm +0 on it, and most others in that issue were weakly supportive of it. It would be nice to have, but I have concerns on how often people will run into this particular gotcha (it's at least easily debuggable).

1. Checking truthiness seems safe and would lead to superficially simpler source code, and it would account for the above gotcha, but would break the more common case of this, which lots of people (including me) do now:

    ```js
    var Comp = {
      oninit() { this.count = 0 },
      view() {
        return [
          // The current tally below wouldn't be displayed as expected
          // until you hit `Increment`.
          m("div", ["Count: ", this.count]),
          m("button", {onclick: () => this.count++}, "Increment"),
        ]
      },
    }
    ```

    Plus, it would cause potential performance issues by requiring internal type checks and non-trivial branching code in a critical path. (It's hit for each *potential* node, including strings/numbers/etc., and regardless of whether it's actually going to be rendered.) So this was quickly rejected by several of us.

**Comment by pygy** [comment]
I was talking about literal `false`, not falsy values... We already treat `false` as empty vdom text nodes.

For attributes that don't have a value, a `""` is apparently truthy (and an absence of attribute is falsy, according to [this branch](https://github.com/MithrilJS/mithril.js/blob/6c06d41f949a6ea24b86e101494e0455e149fa3e/render/render.js#L506-L509), though I'm not sure to what exact attribute it applies, all the valueless attributes I checked had corresponding properties on the element), and `0` cannot be ignored.

**Comment by isiahmeadows** [comment]
@pygy 

> here's a quick summary of the two main things considered there

Note the word "there". I was referring to a very topically similar bug that was more general than this particular suggestion, and was just dropping it here with a summary of the two main ideas raised there. This is closer to the first suggestion, boolean `true`/`false`, which is why I felt the need to bring it up.

**Comment by pygy** [comment]
Ok, gotcha!

**Comment by pygy** [comment]
This would better be discussed in the broader context of #1773, I'm closing this.

**Comment by isiahmeadows** [comment]
@pygy I take back my analysis...I mistook this as "children", not "attributes"... Sorry for the noise. 😞

**Comment by barneycarroll** [comment]
@porsager [more characters but more explicit semantics](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAAQBzAE4wmAHTRKs+LLQCuDABQATWtQ04G+AEa1dATwoTgSiRIBuEGAHdEE7cAlxiGRhKsAJQSALwAfPYOEljaAORQGKYwUHE2dmjR0b6WsB7e+IWy8pkAZKW2EqYY1ADWsppouh5xxUxxgYFRDuzd0bFxEGgADhrEyMSWwzCh1IQwdeYAHgC6abZ9WXMLtTDN0nJMFJvR9HMYaFIwHtohEQclYRIAhG3KmVmBQccfWSdxAHFDmgAPxxPpBJTBNgcECYHB4fDUOACGj0RjMHhsFZUKBDWoIFCcBE8LAQYiEGTQSggDQycg8EjEYZwRAAejZWmG9SRtCwbLJFKpUAAAgBGfASgBsAvJlOg+H4NMm0zwStYK1YQA):
```js
{ ...green && { background: 'green' } }
```

**Comment by isiahmeadows** [comment]
@barneycarroll That won't work if `green` has lifecycle methods or is `null`/`undefined`. (See [7.2.23, step 4](https://tc39.github.io/ecma262/#sec-copydataproperties) and [Table 12, "ToObject Conversions"](https://tc39.github.io/ecma262/#table-13) of the ES spec.)

**Comment by barneycarroll** [comment]
Oh what? When did that get passed? Chrome implementation is lagging behind ATM so it works somewhere. Shame.

**Comment by isiahmeadows** [comment]
@barneycarroll If Chrome doesn't throw, it's broken. (Note that `Object.assign` doesn't do this, so `Object.assign` ≠ rest properties. There's other differences like not assigning/invoking setters.)
