### ISSUE TITLE
Return promise from m.mount and m.route

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#1868]
It would be useful to know when mounting & routing are complete in cases where your app needs to access the DOM (when not in a component lifecycle hook.) I've found with `mount` you need to wait 1 frame, with `route` you might need to wait 2 frames (including the redirect from `/` to `/#!` for example.)

Hopefully this will be easy when redraws are made async.

**Comment by tivac** [comment]
#1592 landed, so this may be worth investigating again.

**Comment by oliverhunt** [comment]
This would be a worthwhile feature for me

**Comment by dead-claudia** [comment]
Closing due to age.
