### ISSUE TITLE
Templating?

### ISSUE THREAD

**Issue by kokujin** [MithrilJS/mithril.js#1874]
I have existing HTML Nunjucks templates and partials, is it possible to re.use and render them in components by Mithril? Thanks

**Comment by ChantOfAnAnt** [comment]
Mithril doen't have such kind of a templating as Nunjucks is. Here, we are dealing with hyperscript concept in form of `m(...)`, as described at [m API page](https://mithril.js.org/hyperscript.html). This gives a little bit more flexibility IMHO, as it is not polluting JS with HTML, or HTML with JS, neither it introduces a new syntax to be aware of, as Nunjucks does.

Closest thing (from HTML syntax point-of-view) is [JSX](https://mithril.js.org/jsx.html#jsx-vs-hyperscript). This is pretty much the same as with other frameworks in the wild.

If you just want to quickly convert HTML to Mithril, than you best help is [converter](http://arthurclemens.github.io/mithril-template-converter/index.html). 

Answering the original question, you cannot reuse them in existing form, they need to be rewritten appropriately, which is not hard, but tedious with big codebases.

**Comment by kokujin** [comment]
@ChantOfAnAnt , it was a busy evening, actually, I meant HTML templates, which sometimes, in my case, are normal HTML partials without any Nunjucks logic: I will check up converter. Thnaks
