### ISSUE TITLE
How to deal with 0.2.x bugs?

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#1877]
We've got a [bunch](https://github.com/MithrilJS/mithril.js/issues?q=is%3Aissue+is%3Aopen+label%3A0.2.x) of 0.2 stuff still alive, with all but two being bugs. There were also previous talks of a [final 0.2.6 release](https://github.com/MithrilJS/mithril.js/issues/1596), which never happened. How should we address this?

1. Should we patch these bugs or leave them?
2. Should we go ahead and make that final release?

My thoughts on them:

1. We could probably get away with just leaving them. It's not our current dev branch, and we no longer have any need to support it.
2. Probably so, since 1.0 was only released ~5 months ago, and people are still migrating.

**Comment by futurist** [comment]
At least I'm still using `0.2.5`, and merged some fix by myself. I have below point:

1. I really want to switched to `1.x`, but the project was too deep into `0.2.5` and the switch within a short time (maybe 1 year?) is impossible, for the project, the only choice is to make it more stable based on `0.2.5`, and keep watching `1.x`, find a chance to switch, maybe next big version or next refactoring of the whole project.

2. I'm really understand some issues listed for `0.2.5`, and I'm also suffered with some, if a new final version can be released, with some important issues fixed, that's really good news for the mithril community, think no one would deny it?

3. `0.2.x` is battle tested, people maybe don't want it to join new battle, but it's growned, and should give it a right position in the history.

**Comment by isiahmeadows** [comment]
@lhorie @tivac @pygy Ping...

**Comment by tivac** [comment]
@isiahmeadows I've seen this, I just have no time to cut a `0.2.x` release atm. If somebody else wants to tackle it you have my full support.

**Comment by isiahmeadows** [comment]
@tivac I'd willingly do it myself if I could. All that really needs done is this:

```sh
# Ensure you have a clean Git state

git checkout v0_2_x
npm install
# Update `m.version` in `mithril.js`
grunt
npm version patch --force
npm publish --tag legacy-v0.2.x

git checkout next
# Return to what you were doing
```

**Comment by pygy** [comment]
@isiahmeadows there's some work needed on #1308 as well (it was closed with a slew of other issues, I had missed it).

**Comment by isiahmeadows** [comment]
Okay. I didn't catch that. It was blindly closed along with numerous other old PRs.

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
