### ISSUE TITLE
m.request XDomainRequest

### ISSUE THREAD

**Issue by andraaspar** [MithrilJS/mithril.js#1880]
Hi,

I can see no API to let me use an XDomainRequest in place of an XMLHttpRequest on IE9. Am I missing something?

**Comment by pygy** [comment]
It is poorly documented (only mentioned in the [signature table](https://github.com/MithrilJS/mithril.js/blob/next/docs/request.md#signature) without explanations), but the `config` function can return an XHR-like object to override the one it was provided.

**Comment by andraaspar** [comment]
Thanks for clarifying.

**Comment by isiahmeadows** [comment]
Closing as this appears resolved.
