### ISSUE TITLE
Gandalf added dependencies in package.json

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#1894]
This flew under the radar until v1.1.2 was released.

https://github.com/MithrilJS/mithril.js/commit/6c06d41f949a6ea24b86e101494e0455e149fa3e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

@tivac could you take a look?

**Comment by tivac** [comment]
This is a npm@5 thing, oops. Will need to tweak the Travis install command.

Sorry 😌

**Comment by pygy** [comment]
Hey don't feel bad, your release scripts and instructions worked once again flawlessly :-), and the ground shifted beneath your feet...
