### ISSUE TITLE
ospec/bin/ospec breaks on npm publish from Windows

### ISSUE THREAD

**Issue by lhorie** [MithrilJS/mithril.js#1900]
Repro steps:

From terminal in a mac, using NPM 5.2.0 and ospec 1.3.0:

```
mkdir test && mkdir test
touch index.js
npx ospec
```

Expected:

- run an empty test suite

Actual:

- dies with the error `env: node\r: No such file or directory`

**Comment by lhorie** [comment]
Released a 1.3.1 to fix this

**Comment by tivac** [comment]
Was `1.3.1` just a no-op publish to have it be from a non-windows PC? Sorry about that, I forgot all about that stupid npm bug.

Did you `npm deprecate ospec@1.3.0`?

**Comment by lhorie** [comment]
yeah, I did now
