### ISSUE TITLE
CR: Optional (automated) text escaping for text nodes to prevent XSS attacks

### ISSUE THREAD

**Issue by gixxi** [MithrilJS/mithril.js#1910]
Is there already a feature escaping all text nodes of the DOM rendered from the VDOM in order to prevent certain types of XSS attacks.

Thanks for any advice
Kind regards
Christian

**Comment by StephanHoyer** [comment]
Its default behaviour

**Comment by gixxi** [comment]
@StephanHoyer 
ok, thanks for getting back on me
