### ISSUE TITLE
How to properly test a mounted component

### ISSUE THREAD

**Issue by ftaiolivista** [MithrilJS/mithril.js#1915]
Hi.
This is not a bug report but a request on clarification on how to test Mithril.

I have setup a Mithril project and using AVA Js to test some component.

I'm using Browser env to mockup the browser environment.

In my test I do:
* Declare component class
* Mount componet as default route
* check excpected HTML in document.body.innerHTML

If I do this I got error becaus body is still empty. So I put 1 second timeout
to let mithril do the rendering.

* Declare component class
* Mount componet as default route
* whait 1000 then check excpected HTML in document.body.innerHTML

And the test works.

But I found with multiple tests working in parallel 1 second may be not sufficient.

Is there any predictable way that I can use to wait for Mithril to done all the rendering
before go on and check document body?

Thank you

Mithril 1.1.3

**Comment by StephanHoyer** [comment]
Have you considered mithril-query. It currently does not cover class-based components tho

**Comment by ftaiolivista** [comment]
Thank you for the suggestion. Mithril Query looks helpfull. But I think the Mithril Query will help test on vnode side not on resulting DOM.
Testing the updated DOM would be more significative I think... or not?!

**Comment by StephanHoyer** [comment]
Yes, you're right. If you want to test real DOM, mq is not the right tool.

But testing real DOM is not required in most cases. If you want to test that, you should consider using a real browser to run the tests in.

**Comment by barneycarroll** [comment]
When you need to test Mithrils DOM output. either use `requestAnimationFrame` to allow for delays of asynchronous redraw, or use explicit [`m.render`](https://mithril.js.org/render.html) or [`m.redraw.sync`](https://mithril.js.org/redraw.html#mredrawsync) to force synchronous updates.
