### ISSUE TITLE
Select box options not matching state on select change event

### ISSUE THREAD

**Issue by robinchew** [MithrilJS/mithril.js#1916]
I have a select box with options 0 to 5. Select box onchange event will always set the selected state to 5. On first selection of any option, it does select 5,  however not in subsequent selections.

## Expected Behavior
On any subsequent selections, the option should remain as 5.

## Current Behavior
However, subsequent selections, does not remain 5.

## Possible Solution
Hoping i'm not the one to fix it.

## Steps to Reproduce (for bugs)
https://jsfiddle.net/7tj9pyet/ with Mithril 1.1.3, tested on Chromium and Vivaldi.

**Comment by ArthurClemens** [comment]
When you replace `selected` with `disabled` it does work for that attribute. Somehow `selected` is removed.

**Comment by isiahmeadows** [comment]
I found what the issue is: Mithril *does* have special handling for `selected`, but it's only if the field is the currently active element (and `<option>`s are not themselves the active element - it's always the parent `<select>`). [Here's the offending line.](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L536-L538)

**Comment by robinchew** [comment]
Thanks @isiahmeadows. Is removing `&& vnode.dom === $doc.activeElement` considered a fix?

**Comment by pygy** [comment]
Good catch @robinchew, and @isiahmeadows [is correct](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ADAOgEwoDQgHsBXAFwAdTkSAnI+fAZ3gQGMT4plwISALaiLAACARgxiAzBgBWDEPgBmg+HKQBtUADsAhmERIQMufhYFN7c1zAYwxcwAooBFkT3mMAIwJQAnrgAEwAA6mv5h-mYQmjxI-gpEmmwQZvYAbpre8ACUgSHh-kEk6ZkYDCTa7KXM8GwcAJKaUPAAHv4AvP5oeeEAvrjdYakQ8ADusfGJJMmhaRlNOcGh4YXU8CRE1KFg9kEgUBCpu-1L+YXbAORMrCTnx-mnJIv394VmLLzamgDm8LH2OW0AHyBfzFJqlcqVK41dhQBpNVodACs-h6A2eqLuGLCanOAC0AKIAJQA8rd-OcSQA5Ank84AFQA6mSAgyABJEgm01kAMRJAFUiXSeXUAGq0gC6Nm0ZHs9lg2g8zACEABgPR2IuBDIUzMtw12JB0NqUFiYPgEIqFuNsPhLXabQ6EH8AH4KTaOOdYudzpiDdiFUrYFkQ1jnlrYPqTi8SGp-csSLsAMrVNj+akEiLUfy8CBfXjwagBT5Qfw+Yj+EaCWD+H4kfwi8UBEa597+CAMfwtMgwjgBJUsbREJgRBT+G0RRIfb7wLupeDuI7x04gFPXBsColZ-ywAgjQvFxr+Opd5o9tONzMkAj+VZgbRRcep2H90jt+tOFT+Kkk+kYXbxoUUr3rKnZAv4FywBA5IMCGIbomimg9FkIQgD0Er4FBmgANaqBoIAbLAXC8CQ5AMEgAD0FEJGQ2FfBgphgBRkB8AIwhiJI8ggCQPg9lwshcWQFTvCoyBqGoIj4PUjQtLsXEDFx-gAD5Kf4FQ0PIIgAGy4FgaC4BIEjaRIBlGVpEgYRJJiwrs-gAGR2YpOzRv4inmhgnC4NpukACymSIACcJmGYFFm4FZ3EHPABIIG4iaaIp9wqaCcwWk41hCas5gxfAcUOh0-gACROCwGDaEk845XF6IoQl+CFIhhQTEkZjyFgfkABx4IZWBGaZvUiBKEroT0QA) (search for `vnode.dom.parentElement` for the fix)

**Comment by robinchew** [comment]
Thanks @pygy. Should I create a PR based on your fix?

**Comment by pygy** [comment]
@robinchew :+1: PR most welcome! I can help with the tests if needed...

I hadn't yet seen your previous message before posting mine. Removing the `&& vnode.dom === $doc.activeElement` would also fix it, I don't know which version would be faster...

**Comment by robinchew** [comment]
@pygy I tried to write the test, but I hit a problem the moment I do: 
```
o("render select options", function() {
    var select = {tag: "select", children: [
        {tag:"option", attrs: {value: "1", selected: ""}},
    ]}
    render(root, select);
})
```
```
TypeError: Cannot set property 'selectedIndex' of null
    at Object.set [as selected] (/home/robin/work/mithril.js/test-utils/domMock.js:471:43)
    at setAttr (/home/robin/work/mithril.js/render/render.js:503:17)
    at setAttrs (/home/robin/work/mithril.js/render/render.js:470:4)
    at createElement (/home/robin/work/mithril.js/render/render.js:89:4)
    at createNode (/home/robin/work/mithril.js/render/render.js:39:21)
    at createNodes (/home/robin/work/mithril.js/render/render.js:26:5)
    at createElement (/home/robin/work/mithril.js/render/render.js:104:5)
    at createNode (/home/robin/work/mithril.js/render/render.js:39:21)
    at createNodes (/home/robin/work/mithril.js/render/render.js:26:5)
    at updateNodes (/home/robin/work/mithril.js/render/render.js:149:25)
```
Sounds like I need to mess with domMock which I think I won't. Can you take over? Also how do you run just a single test? I don't think you need me to remove `&& vnode.dom === $doc.activeElement` for you.

**Comment by isiahmeadows** [comment]
It's a pretty easy fix to the mock: just add support for `parentNode` (which is pretty trivial and exactly what you might think). @pygy I'm already on it BTW.

**Comment by isiahmeadows** [comment]
@robinchew Try [`vnode.dom.parentNode`](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode) instead.

**Comment by robinchew** [comment]
The `parentNode` key is there but it has `null` value, and the `render` function wants to get `selectedIndex` of `parentNode`, hence the error above. Sorry I'm not sure what you mean by trying `vnode.dom.parentNode`, instead of what?

**Comment by pygy** [comment]
@robinchew I think he meant instead of `parentElement` that I use in my flems... thanks for giving it a try :-)
