### ISSUE TITLE
Setting the Content-Type header in POST requests do not overwrite default header

### ISSUE THREAD

**Issue by tskillian** [MithrilJS/mithril.js#1919]
If you make a POST request and set the Content-Type header, it will not overwrite the default Content-Type header but rather will get appended to the default header. This does not happen in GET requests. I have not attempted this with any other types.

## Expected Behavior
The expectation is that setting a header in POST requests actually means setting the header, rather than appending to some default header.

## Current Behavior
The Content-Type header set by the user will get appended to the default header

## Steps to Reproduce (for bugs)
Look at the network tab for the below fiddle after running, you'll see the POST request made by the code and see that the Content-Type header is not what the user set it to.
Repro: https://jsfiddle.net/2bmk0zjs/2/

**Comment by tskillian** [comment]
Found the culprit.. mithril assumes that setRequestHeader would overwrite (like any sort of setter/getter...). For some crazy reason this is not the actual beheavior of the method:

The XMLHttpRequest.setRequestHeader() method sets the value of an HTTP request header. You must call setRequestHeader()after open(), but before send(). If this method is called several times with the same header, the values are merged into one single request header.

Source: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader

**Comment by pygy** [comment]
Thanks for the report @tskillian, [here's the culprit](https://github.com/MithrilJS/mithril.js/blob/1da69da4dd86707475c241eac1285dbdf76ad993/request/request.js#L70-L72).
