### ISSUE TITLE
Example how to make simple spinner for AJAX request ?

### ISSUE THREAD

**Issue by riston** [MithrilJS/mithril.js#192]
The basic solution what I would use is based on promises 'resolve' and 'reject'. Also one boolean flag variable needs to be used to mark the state. The possible case which is not handled is the timeout, if the server gives no timeout in some meaningful time then there should be client side timer for that. 

Is there any better ways to implement the basic spinner ?

**Comment by mjiricka** [comment]
To make it work, I had to do this (cosmetic changes are not important):

```
m.requestFeedback = function (args) {
    var completed = m.prop(false);
    var complete = function(data) {
        completed(true);
        m.redraw();

        return data;
    };

    args.background = true;
    args.config = function(xhr) {
        xhr.timeout = 4000;
        xhr.ontimeout = function() {
            complete();
            m.redraw();
        };
    };

    return {
        data: m.request(args).then(complete, complete),
        ready: completed
    };
}
```
I do not know how the previous example could work, unless `m.redraw` would return its parameter in some older version.

Usage is following:

```
var req = m.requestFeedback({method: 'POST', url: '/service/', data: Controller.vm});
req.data.then(status => {
   console.log(status);
});

```

**Comment by isiahmeadows** [comment]
@mjiricka I think Leo just made a mistake in his snippet. The proper fix would be this:

```js
m.requestFeedback = function(args) {
  var completed = m.prop(false)
  var complete = function() {
    completed(true)
  }
  args.background = true
  args.config = function(xhr) {
    xhr.timeout = 4000
    xhr.ontimeout = function() {
      complete()
      m.redraw()
    }
  }
  return {
    data: m.request(args).then(complete, complete).then(function (data) {
      // Here's the edit
      m.redraw()
      return data
    }),
    ready: completed
  }
}
```

**Comment by mjiricka** [comment]
@isiahmeadows Thank you for your reply! I noticed `throw` instead of `return`, that is a good idea. But is it important to call `m.redraw` in different promise, not immediately after setting `completed(true)`?

**Comment by isiahmeadows** [comment]
@mjiricka Not really, but you probably should at some point in the chain, if you want any changes reflected back in the view.
