### ISSUE TITLE
Why are we documenting our promise polyfill?

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#1931]
It's one thing to document its existence, but [why are we documenting in high detail what's little more than a polyfill](https://mithril.js.org/promise.html)? It just seems odd to me why we're doing that.

Instead, we could just be linking to [MDN's docs on it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which is even better detailed, and maybe linking to [Bluebird's "Why Promises?"](http://bluebirdjs.com/docs/why-promises.html) and a few blog posts on how to use them and why they exist (which MDN also already does itself).

It's not like we provide *any* features beyond what the native version offers - it's a pure polyfill.

**Comment by lhorie** [comment]
The original reason was to document what it is that this polyfill specifically actually does, rather than generically explain what promises or promise polyfills do. I think that now that there's stuff like Promise.finally and unhandledrejection/rejectionhandled events looming in the horizon, it's important to describe exactly what we support.

**Comment by isiahmeadows** [comment]
@lhorie [Not at the moment](https://github.com/MithrilJS/mithril.js/blob/next/promise/promise.js).

Also, as far as I see, there's no existing requests for [unhandled rejections](https://github.com/MithrilJS/mithril.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20unhandled%20rejection), [handled rejections](https://github.com/MithrilJS/mithril.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20rejection%20handled), or [a `finally` extension](https://github.com/MithrilJS/mithril.js/issues?page=1&q=is%3Aissue+finally&utf8=%E2%9C%93).

(You may want to add it once [this proposal](https://github.com/tc39/proposal-promise-finally) hits stage 4, though.)

**Comment by lhorie** [comment]
I mean that those things exist in various degrees of completion elsewhere but not in our implementation

**Comment by isiahmeadows** [comment]
@lhorie I'm aware. But here's why I feel we don't really need to specify anything on our own:

1. We specifically advertise it as a *polyfill*.
1. We only really implement what's required by spec.
1. We don't specify any additions to the polyfill.

**Comment by lhorie** [comment]
For what it's worth, we do link to MDN, and people can deep dive there if that floats their boat.

I think it'd be a little weird if the docs for promises were just a bunch of links. Besides, the document is already written and it's not harmful, so I don't see why not just keep it.

**Comment by isiahmeadows** [comment]
> I think it'd be a little weird if the docs for promises were just a bunch of links.

I was thinking of less than even a page - just a note or small section on the main page stating that this bundles a `Promise` polyfill, with a link to MDN and maybe a couple other resources on promises.

> Besides, the document is already written and it's not harmful, so I don't see why not just keep it.

I'm okay with that. It just seemed odd to me that we were even going in much depth over a simple polyfill.
