### ISSUE TITLE
onmatch should be lifecycle method

### ISSUE THREAD

**Issue by tehChromic** [MithrilJS/mithril.js#1933]
**onmatch** to be a regular lifecycle method. 
 
## Expected Behavior
When I navigate between /#!/load/123 to /#!/load/456 I ought to be able to hook into that change in any component. Ideally onmatch is a regular lifecycle method triggers any time a route parameter changes.

## Current Behavior
Currently onmatch only works on a top level routed component. This is not ideal as there are potential cases for a route match needing component level hook. Currently there is no good way for me to know in a component when a route parameter has changed within a route.

## Possible Solution
Make onmatch happen in every component. Decouple it from render so it works more like oninit or oncreate. I do like that it provides the param in the passed arg before the m.route.param changes.

I realize that onmatch is a kind of conceived of as different kind of component called a "resolver" and that there are potentially good structural reason for this. Specifically deferring render with a promise and returning a component to be rendered might be something that we want only be happening at the root component level. 

However I think that onmatch could be simpler and more effective as a more basic lifecycle method - I can handle my own loader components within a component that render while I'm waiting for data to load, and I can switch routes or render different components within my model logic, however I can't figure out when a route change has provided me a new m.route.param() value from my subcomponents without hooking into component data higher up. That's an anti-pattern to me.

## Context
The use case is simple: when my url changes parameters but the route doesn't change, I will want to trigger major changes to data and interface even though I don't want a complete re mount. I may want trigger loading data from multiple places, in multiple components. Onmatch is a lifecycle hook.

## Your Environment
* Mithril 1.x
* Chrome
* Linux / Desktop
* jam.musicintelligence.co

**Comment by isiahmeadows** [comment]
First, I'll note you're thinking of [route resolvers](https://mithril.js.org/route.html#routeresolver), which aren't components at all.

Second, consider this:

- If a child component needs the route parameters, just pass them to the child like in `m(Body, {params: vnode.attrs.params}).
- If you want to create a component that accepts a body, you *can* pass them a component via an attribute: `m(vnode.attrs.component, ...)`.
- Route changes cause the tree to be removed and rebuilt, so you won't be able to observe route changes that way, regardless. You'll have to handle this in your model regardless unless you plan to re-implement [this file](https://github.com/MithrilJS/mithril.js/blob/next/api/router.js) to instead diff the existing component.

**Comment by isiahmeadows** [comment]
In particular, with the way route changes work, you won't be able to persist state across route changes unless you re-implement `api/router.js` (linked above).

**Comment by tehChromic** [comment]
Thanks for reply!

I am aware of route resolvers and although they aren't components they behave like them at the root level of routed components. onmatch in a route resolver works like a component lifecycle to my way of thinking. I understand that there's a lot going on here that I'm not completely informed on.

To reply to your statement here:

> If a child component needs the route parameters, just pass them to the child like in `m(Body, {params: vnode.attrs.params}).

It isn't a problem to pass a model into sub components through attributes like you say here. If I do that then I have to test against the attribute value that I have set in some higher component. That's fine, but since I don't know when the m.route.param changes, I have to set that attribute value on each render.

I could also store a route param in any component and test it against m.route.param value, and trigger my data changes if they don't match - that's simpler. However again I have to test on every render, since I have no way of knowing when my param changed - no lifecycle method exists.

Instead I am using a route resolver because this way I can hook into onmatch, however I am using it exactly like I used to use a component, only I've swapped "render" for "view" and added "onmatch". This works well, and my "render" works like a "view" did, and now I can get my data to reload when a route param changes ... however I'm left thinking that maybe the "route resolver" concept is really more useful as simply onmatch as a life cycle component instead of all the route resolver stuff, which I don't really need in this case - I handle all my promise async loader stuff in the component anyway, so no need to defer render, etc.

Does this make sense?

**Comment by isiahmeadows** [comment]
Okay - if I'm understanding this correctly, you want a way to detect when routing actually happens at all. That's not something Mithril *currently* offers, but it seems pretty simple to implement.

/cc @tivac?

**Comment by tehChromic** [comment]
Absolutely right: when a route url changes a life cycle method that fires on any component that is rendered in that render hierarchy.

Thanks!

**Comment by tehChromic** [comment]
Hi!
Was hoping this would show up in v2! Maybe it slipped under the radar with everything going on? If so: bump!

Here's the pattern in my components that I think a lifecycle method is appropriate to replace:

```
view:function(vnode){
  if(vnode.state.id !== m.route.param('id')){
    vnode.state.id = m.route.param('id')
    // go fetch something new
  }
  return (<div>...</div>)
}
```

Instead I think this ought to be

```
onmatch:function(vnode){
  vnode.state.id = m.route.param('id')
  // go fetch something new
},
view:function(){
  return (<div>...</div>)
}
```

My components need to know when to update based on a change to the route.

Thanks!!!

**Comment by isiahmeadows** [comment]
@tehChromic If the first works, why would you need a second hook?

**Comment by tehChromic** [comment]
The first fires every time the view is rendered which is way too often. The proposed lifecycle fires only when the route changes. The issue is that a route can change, providing a new param, but I have no way to know if the route matches the existing route, so I have to check on every view render. So if I go from:

/#!/composition/21

to

/#!/composition/22

I have no method to tell me my route param changed. I only know by checking in the view over and over. This seems like a poor solution to a common case.

**Comment by isiahmeadows** [comment]
@tehChromic Have you considered putting it in `onbeforeupdate`?

**Comment by cavemansspa** [comment]
@tehChromic maybe you can use: https://mithril.js.org/route.html#key-parameter ?

**Comment by isiahmeadows** [comment]
@tehChromic Every URL change, including route params changes, results in a re-render if you're  - you don't need to check that manually.

As for performance concerns:

- `if (vnode.state.id === m.route.param("id"))` is *really* cheap - the `m.route.param("key")` is internally just doing `return params[key]`. It's more expensive to create a vnode than to do this.
- The case where it changes is only hit when the above check fails, which is *less* often than your hook (which fails to check if the parameter actually changed).

**Comment by tehChromic** [comment]
I understand what you are saying regarding cheapness. However one thing I don't think is clear: this proposed enhancement is a lifecycle method that is called ONLY when a route changes, inclusive of changes within the matched route. That's why there is no check in that hook - it's purpose is to be called when the change happens.

If you are saying that's more expensive than running an if check on each view render, OK. But I given how often a view renders compared to a route change, I think it may not be. In any case, it's also a design issue IMO, as this really is a lifecycle method of its own and shouldn't be tacked onto the top of a view. But that's my opinion I suppose.

**Comment by ancmikesmullin** [comment]
FWIW I implemented this via wrapper, like so:

```js
app.layouts.Main = (opts, child) => {
    return {
        async onmatch(args, requestedPath, route) {
            // NOTICE: execute promise without waiting, but still catch and log any errors thrown
            //         this means render happens immediately; is not delayed by async work happening in background.
            //         also means async fn must call m.render() when its done to display changes.
            //         this enables a very responsive feel, as clicks respond immediately, while page components load incrementally.
            if (null != child.onmatch) {
                const p = Utils.fire(child.onmatch, args, requestedPath, route);
                // NOTICE: returning a Promise is optional, but if you choose to do so, any errors thrown will still be caught and logged
                if (p instanceof Promise) p.catch(console.error);
            }
            return child;
        },
        render(vnode) {
            return m(MainLayout, opts, vnode);
        },
    };
};
```

where `MainLayout` is just a component which renders my layout wrapped around `v.children`

and my utility function `Utils.fire` is defined as:

```js
Utils.fire = (fn/*::?:(...any[])=>any*/, ...args/*:any[]*/)/*:any*/ =>
    'function' === typeof fn ? fn(...args) : undefined;
```

I find it efficient because it only fires if one of the route patterns matches, and only for the top-most component (not all components).

I register the routes like so:

```js
app.routes['/kingdom/genus/:genusId/species/:speciesId/:mode'] =
app.layouts.Main(GenusEditView);

app.routes['/kingdom/genus/:genusId/:mode'] =
app.layouts.Main(GenusEditView);

//...

m.route.prefix = ''; // uses root /
m.route(document.body, app.DEFAULT_ROUTE, app.routes);
```

Net effect: 
- Same component instance is reused / shared by multiple routes.
- `onmatch()` is treated like a lifecycle event method for the top-most component (just below the layout component).
- User can alternate between two related routes without causing `oninit()` `oncreate()` `onremove()` to execute--only `onmatch()` and `view()` will execute. This also means the elements are not being removed and re-added to DOM.
- A lot of logic is saved which would otherwise be trying to maintain state between the two routes, and accurately diffing the `m.route.get()` to determine if the route has changed, and how the change applies to the current view.

**Comment by tehChromic** [comment]
I see that. Cool stuff!

My use case is a bit different as I am using route param changes to figure out controller/model in sub components. 

So if I have a route like you have: '/kingdom/genus/:genusId/species/:speciesId/:mode'

Maybe I'm using :mode in a sub, sub component to figure out which mode I want to render - maybe that's a component or maybe it's just a different layout or whatever. 

I understand that onmatch is not a component lifecycle exactly, but it would seem like it is appropriately called "hook" - any component might like to know when the route data is changed within a route - that's a no brainer.

I don't like the onmatch pattern for exactly the reason that it is only available as a top-level non-component rendering utility - that doesn't seem to me much different than having a main component that wraps sub components that are rendered based on a param string value, which I also do.

Obv your method fixes that, but doesn't get at my need quite.

Isiah is right that I can test m.route.param('mode') in an sub component view and compare it to that component state and make changes - it works fine. 

And I understand that the component lifecycles are tied to stuff that happens to components, so that's sensible.

But it still doesn't seem right to have route logic testing at the top of the view for a use case that seems pretty standard. 

Maybe what is lacking is a method of m.route that lets one listen for change within a route. 

Like m.route.onchange((params)=>{

})

Or something. Even so, I still want to know the change is happening within the context of a component, so it really seems like a proper hook to me.

**Comment by ancmikesmullin** [comment]
It's not called `route.onchange` but that's essentially what it is in my example. The return value of the function is ignored, and it doesn't wait for the function to complete before first-pass render. It keeps the component instantiated between routes, instead of tearing it down and rebuilding it--unless you move away from the group of routes which are sharing the component. 

There are several problems with the `m.route.param('mode')` approach. It was the first version I tried. In my experience it returns a value inside `oninit()` but not `view()`. I worked around this by getting the params once `oninit()` and storing them in `v.state` for later. This implies you only have one route and it is wildcarded broadly enough to cover all cases. (In my case, the wildcard syntax did not provide the pattern matching flexibility I needed, and I had to compromise with an ugly url). Determining when the value changes and triggering some action means watching on every `view()` and doing the diffing yourself. This eventually leads to creating your own `oninit()` `oncreate()` `onremove()` equivalents--which means you are essentially recreating the lifecycle system. Eventually you realize there is no way to preserve vnode instance state between routes unless you persist it somewhere (ie. global scope, or static singleton). At this point its like WTF.

My workaround above leverages existing the lifecycle system and simplified out a lot of code related to above problems.

**Comment by cavemansspa** [comment]
how about using regular browser event listening @tehChromic ?
[experimental flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmiFxiAAgAyGAJ60ArrIC8MgBQBKGeoB8M4BJkyATjGIrzaY6bMyAbhBgB3RNuDVC0ACaWaKx6hjJYWgDkERQyPv6BMeERAEZqxPTR9naOZvTUUBDUANaeuvpGJtk5ZlK0sPhQtADmWlj45qqM+E1WkWC0tBE6Og7VMhBgre2dMPgADhjm2H0DQ-rqmhEAjEOjY2HTarNwvREA9ABMZwCCZ1vXu1XVMFAne2NtHUf4J8SRdzc7g8Rk8zKw9uwZBEfBg0D0hiCwRJwWgJFJZABhXxQPz6bQhCoOSzWWxZHL0CBoCDEUoE4y1eqNFrQ7G4yCWXEUqnEIbsPYudy08pk-bEmx2JKZFn+GQAWihMgA1Acvl0en8dDFkO99shwgBlFTJLH+GLAIowRSeehYDDEHz4C2KXTBAC6FB1Hy0huNrLkEGkTER+zMruDORRSKCaPo0hkPpNOLxZVClTMYtJaccXOpQtTDNmTMicCNcST7JgnKp3N5HqeAo8+OFWbGGYlkSlJeSZdx8oiSpVM26vT04cckZkKJR6PjRsTfn9gbsmhThOybkpflobnwGD8fgAok4RIvGGgYOZIja7T5MloYHSCw1mpEE36A2e5fKCkuLwiiVY4oirk1a5k2+axnUhYvhEXY9j+n4VlWlLUrW-KuI2q7AdUbZhB2MSwaWrIIUwcoKsqnxDuqZRjlGUYojGaBxvQACyN6EEeIh4uebgyJxDBXmgtr2oQjwzteInJmAKiSMQED0GULYyLAshOtx7gyAAInaMC6HsKkyHAGDHn4AAKizYHAex7NJsnyRKukLEsWBwDECzEIQMSqg+2E5AZPHmc5cB4gAUvqADyAByPzEOYlJNBMzpOZZtGOBMWhGSZgWWTIACEGwyAFFkuXoSljJllbZS56luFVVmgtUamaDxWk6XpDU5BuaBbjufgBu5Pj8X8rHsUNqV0fsT5FslLluXankWDMY4TmYOCOpayZ0k6ey4TgyI6LoADcEgSJRRxaFu1AqDgDD4MktB+IoBEArc9yZFmDjnIg-S0GciDJIsf0AwAXhEnhlTIEk+NaQnsXWrZMH4F55kY4QKMoaiJFo84yGcABUZpOjDwkOk6LoyHjZwyMMEIOPtlA0LQWBzNAF54ADyQvAzJywNQcmxngFwAAyIAALAA7GwHAgJgOB4Pg1BwAIjPCMwPBsO6IAFGgRQICgnByzwWDUoQcXkFQNjkDwJDEHMcCIGcZwyXMRRNArTNnMbHlmwAAhc+BC-goueybZv4MbaD4PwDPEIoczcCAcDUHFcyiKwrqsEAA)

**Comment by tehChromic** [comment]
That's a bright idea caveman! Of course that's exactly what I'm looking for and I'm an idiot!
