### ISSUE TITLE
Shared attributes for different component results in concatenated class names

### ISSUE THREAD

**Issue by s-ilya** [MithrilJS/mithril.js#1941]
This is how I'm using shared attributes object for styling:

```js
let attrs = { style: { left: '100px' } }
m('.label', attrs, 'Label')
m('.tick', attrs)
```
## Expected Behavior
I would expect both `.label` and `.tick` to appear in DOM tree with the same style.

## Current Behavior
It includes in DOM tree two components with the same class `.label.tick`

## Possible Solution
https://github.com/MithrilJS/mithril.js/pull/1942

**Comment by isiahmeadows** [comment]
Closing per #1942
