### ISSUE TITLE
Add option to globally disable autoredraw system

### ISSUE THREAD

**Issue by oldrich-s** [MithrilJS/mithril.js#1951]
Would be great if there was a global option in mithril to fully turn off autoredraw system. Something like `m.autoredraw = false`. See my comment here: https://github.com/MithrilJS/mithril.js/issues/1853

**Comment by isiahmeadows** [comment]
I could get behind this, although the way to change that should probably be different. (Maybe `m.redraw.setEnabled(enabled)` - we can also unregister a callback in the process.)

**Comment by czb** [comment]
Sounds good ;)

**Comment by dead-claudia** [comment]
You can do this by using `m.render` directly. The prototype of that method is actually `m.render(dom, vnodes, redraw)`, where `redraw` is an optional redraw function to assign to request another redraw.

Closing, since it's pretty easy to set this in a unidirectional loop.
