### ISSUE TITLE
How to re-enter a route? 

### ISSUE THREAD

**Issue by justb** [MithrilJS/mithril.js#1954]
Just like "window.location.reload()" this function, but do not reload the resource.

**Comment by isiahmeadows** [comment]
Does `m.route.set(m.route.get())` solve your problem?

**Comment by justb** [comment]
First thank you for your answer, but it does not work and the page does not respond at all.
My first solution is to enter one other route and then get in it, but it changes history.state. The second is to recall the method that in oninit lifecycle.

**Comment by tivac** [comment]
Gross hack, but you could call the two other routes with `m.route.set("...", null, { replace: true })` which will replace the history entry instead of adding a new one.

[Docs on `m.route.set`'s 3rd param](https://mithril.js.org/route.html#mrouteset)

**Comment by justb** [comment]
Thank you very much, this is indeed a viable way.

**Comment by tivac** [comment]
@justb "viable" is a... strong word 😓 Glad it's working for you though! An option to force re-match a route when calling `m.route.set()` doesn't seem outside the realm of possibility. Would be worth filing an issue about if this is functionality that you'd find useful!

**Comment by justb** [comment]
😓My English is not very good, but i am working on it. Thank you!

**Comment by tivac** [comment]
Oh sorry, your choice of words there was totally fine!

I was pointing out that my workaround is terrible and mithril should provide you a better option than calling `m.route.set()` twice with a weird-looking param!

**Comment by GCSBOSS** [comment]
Isn't there still a better alternative to this?
