### ISSUE TITLE
Repeating DOM (input[type=file] has a ~readonly value, causing crashes)

### ISSUE THREAD

**Issue by rbt** [MithrilJS/mithril.js#1956]
On submission of the form with a file selected, the DOM repeats. I was attempting to make a progress bar for a file upload when this appeared.

Seems to be broken in both 1.1.3 and Next in both FireFox and Chrome.

The main issue seems to be the round-trip of e.target.value for a file selection box. I've run out of brainpower to simplify this further but it almost certainly could be.

Order of the elements also seems to matter. Putting new material (version string in this case) after the form doesn't seem to cause the repeat.

https://codepen.io/rbt123/pen/WEPdby

**Comment by isiahmeadows** [comment]
After toying around, I'm finding weirder things than even that... ([pen, as minimal as I can get it](https://codepen.io/isiahmeadows/pen/ayMByy?editors=0010))

- No wrapper element is required at all for any of them
- It can easily be reproduced with `m.render` directly
- The duplicated element need not be of any particular type; even a string works
- The duplicated element *must not* be rendered on the first pass.
- For some reason, I can't reproduce it with anything other than an `input[type=file]`.
- The `onchange` event listener must be a Mithril-known one, but it need not re-render on click.
- The `input[type=file]` *needs* to change first, and the value "set" to whatever the new file is. (Mithril avoids setting the value when it's equal, so the spec'd error never happens.)
- The `onchange` listener *must not* update the state if it re-renders.
- The button click *must* update the state and re-render.

***Super*** odd...

**Comment by pygy** [comment]
I moved it to [flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ArMIA0IAZgJYy6oDaoAdgIYC2EamAFvPVPiLAPbWL9mIAL54aDJumy4CvfhEHoA5AFdIAAjDwATsQRKAOtSMB6E+oAixbXHjE+YUyafqAjBnUBhKHoDW6+BYIdQAjFXh4PnUAd2JAnnDNaFtiagBzdVp1EhgXdXyAWnUAAy1ddOL1AAdy+DB1Plhg2mokAKDQ8MjqdWJ6qB5YX2QXACYPACVoHlo2qto0iDwkmARM7NIl9oV1WB8h7c6IvjzCkrLUtMqa1LqGnohaWBYj7t393yMYeHUAN1ooCpggBedRKQzUORadQ2VoQbTqUGEHxVREAPnU9AwsKQ8IAFEhBipGPwMCEeEgAJ7LChGfL5MzqAAqLD66moFOCbI5Pxx8OQhxI2mhdkYyzCPzZfJsSDp9MZtEIiARj2eryiez86jxiuVhwsAHkALK9epC6GwGy0RBIACUcvyyOIqIAZC6wRd0ko8A71IyilMAI4qawQerFVJVcIUeCUqoQYE5CAAXUqLTaWWK-0BEEqzxai3URR5mhUNhiLEpvv96gAcjxSyFIMGFLyFLiETZg6GkMtoqy1WyAWAGxTZT15eYivXEO1rYcfFoFPD1AAqehqeCr0LBXwc6I9SLqI1xFi6KBFzJIJCXXrwavmfK-YiZxpWxCVQlh9k8H46YhpIsCKBMEYRpL69B4kokbRrG8aJpsybeuowDZkCyyNCwBYQHiEC2ihvpPgCQKIuoEAYPAtDaIs8AYGhECEWR2LINotDRKRhDDgxE75MIwi2j6PF+uYACCVTxq09TUBA7GlP+FT3O8fgQVBErdMhwCNB8qDavhwIYtKeI6ECtqiGCABCXR8EoAlGMm9rUIZDkiGIIB0IwzAYLAYAyNwfACPAQjCMmBA+NQvjkFQIBlpw6BsPAVRgKgZgqNQVS+GkXk8PQJj0Ke54AALuO4ADMXBwZIIA4CIybCEAA) for toying around with Mithril itself, and I get this error every first time I click the button after picking a file (look at the real console, flems only shows the last one that's been thrown):

> InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

Not sure how that error ends up confusing `m.render()`, but it does.

Do we consider that a user error (`value` should not be set programmatically), or do we add it to the list of `input.value` exceptions?

**Comment by isiahmeadows** [comment]
@pygy Good spot! (I totally overlooked that part...)

> Do we consider that a user error (value should not be set programmatically), or do we add it to the list of input.value exceptions?

I'd add this as another exception, provided it's the same string. If it's different, it's a user error, but if it's still the same string, we should accept it, so it still works with the common two-way binding pattern:

```js
m("input[type=file]", {
    value: this.value(),
    onchange: m.withAttr("value", this.value)
})
```

**Comment by pygy** [comment]
We'd also need to special case the empty string (to reset the value)...

**Comment by rbt** [comment]
@pygy: Yep. Prior to submitting the ticket I changed my code to check the field type and skip setting the value for "file" fields. It does indeed solve the issue.

For a Mithril fix, I'd be perfectly happy if it threw an error.

**Comment by isiahmeadows** [comment]
[Still repros in `next`](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEByAK54ABDE4AncmE7qA3AB0oVgPQ2dAeTBhNBmDoDu5Tux0BZb3YjeB0ARlZwgGYdTCh8HVt7HWS7A0wPAHNvVkhGG0ZA4IV8wsp5GBsoRAAPThKfYPKrRJ0AEXIDRBNyaBhElvCdAGF4YwBrHQAhTU5OaE9AiBm9RCRuqAyYnQokVh0ANUQ3HqgdbCMBd2gwRFYWgCY9gCVViEx47EwM2+SAZVWupwtjtEEQdD4hDowKMwBMAEYzOZQPaHY7zMCYGAY-CIPrWKB2HT-RA6ABUpIAovsAJIAGXJOlGVXcHnYxl85EYnxM4LZ7k62EQmE45A2UMx2NuzSg0Mx7l+EGYvy8nDAvmAVmSyWU+gMmhMEAMAAoAJQ6DWnLVWnzkGCsUijbA6AC820w8DwlktyTE0qtDvI2GV3jVpvNmqtWptdoDTtdhk0iC9Vt9+Kt304wdV7DDFsjWs6nFcp2j9sdya1qdTOqBHncrqqHiJisQWdDJq90tlMHctMwAE8lkC81qa3qDcaAG5QCA4s0j-Ol+AQDHwABijpdbo9SYjPr9WrhmFhGQMSziAAUzzce-9utBc3vI4SACpGDLfAw6KoEdxzHRwiSOJYP2BA6JoAiUI4MwZBAoqbAAjomiY6OwmI6PgwqYHc3qRuQpA6EadasBmbY5maABkFE6AAhEuK7uhugbzk++bJPRq5MXG4J6ruaZsVahJroaNxbAiMq+BABGdPgaTEaxbGkIahFIEC5BbgArAADGYOjqQAPDoABsWk6XpOgANSutpLG4QJVp4JwL6cogQ5GqQEH3lAj52fZ+Y6ggtzLhkRrqE8FKtE8ACCADq6iWXpHYKX5VqMKwMlyaayX2RIiUVn5qYCam2X4YRHGMY6tkpTohbFjoNCMKF7CROoYLqAAEkKOIGOoJpgo16jYK14a+X5YyIP2KA6Oo5D4Oo2UpmCAAGAQNFBqIwCcOgACTAGlk5HJt0BiEtJoALr5ZGYg6KsugLvZtUGKcA3NcNHVdUcvWXSmB77vxySTuQiAeEa06zogVVsYS5JUnSDJEh4ODYPBOiGt1qMERCuj3N+4PuGqsTfCy7CIBCX7eDViCCsKeICY9pw0AtWoDQwk6sMwUCaMNpZHieZ4QfgV4rriMB3iKD4mn1TPJANyiCAIw1gziORsvAslCFLo06BdT5Vl2WA9lM7z7EDTb3WO+pzFOM5ziNAmlrGW6kO6nrZQ7lCIPs7ooa66jmLrv06IDwM+QJqlB6bW7Rp2Wvh6K2AzA42Di7AW73fb-aClN6ggvNWtiN9Wrx4nycnDANDqJO3uIOoZ1bsHHj2h7XvwImunQ5SNL0qS4KZ65BG6ijCJAtCQoGPA-aoZgBiMB58CB1axecEnKfl+o1xoRsNd166HkyinRoQ3bKUN2WgZR7xhf5qfIItz7N2sJw08ZqwVet3xRUx3TpN1Q1oVKTPYajMtapVCkvVgS9hpLxXmXTW1UBrDyRKwRB0AaCcD7s6FBUAzo0AYMwZ0MBNBwgKJwM6w104pWuDCMYh8kCMEhtVfMxFYxkVNFfHKRBpY6FyuoaYsxoC9U4VrM651Lp63xFYPeXkapDkQC+CAfhZyaCQEaRR+BlGgihHCBhjJSaozhHIS69Nj75mgIwYUoZn4wDBJ0JCuJBCC2FOwHRAlCStFWAOKEnRhQowhDoRgSikDgUgiEbw6h3DaAIDhaqpUjQ0QgAYlxlCDFbkbP4QJH8UrFRAQWH+T19GGOyhIbKnQ4hHFBjbI+FD8zGMan2QcMwwRKwhuw4puEC5WGyeHfmghaS2iBK6YAHT8Q9MQH0-QFcbAwGwAbdgtctyjPkWojRRpJjG1NklfEaVRlGnwCuTQHNODINnP2NqUyZmYjmTY2R4zOCbL4HgNYq8RChFCAAThQFpcQkgQB4JkDkHsfA5aqBEOIM6JAmRjGoCgOgvzpAiBIUESgAABKotQ+CuF4GgLgnBcAoDsBBbAYwMg5EVPUJF8BkWPC0qwLSABaAwYAIjksaAoPg6DBQiCxEYZOYKxBAA)

**Comment by isiahmeadows** [comment]
Not a blocker for v2, but it's something I want to get fixed *soon*.

**Comment by isiahmeadows** [comment]
The root cause is a lot more subtle than it looks: Mithril [doesn't know how to deal with errors during rendering at all](https://github.com/MithrilJS/mithril.js/issues/2273), much less errors from DOM manipulations. It stems from `input.value`'s setter throws for `<input type=file>` when it's not set to the empty string, but [you can reproduce it with just components and normal (non-throwing) DOM nodes](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaETAVwBcIAlReCTQlAM03jxOYEskZUBtUFEwBbZGgB0ACwoj4xdFAqIlqECAC+RIaPEgJAKz4lISlRTUB6SwAJaUfIgBON6GEREbVG1yhcKXGxcAF6INk4QEBQAOlDWNgAiEIgwUADkFDYimBTKLgDu-lI2+VI5ngZkMJkUZZn+aTA+fgFBofix8TBkYO4wMMxk8PAAnhKxIhJOKo5OABT4EGBkYkoSAEYQ+COe-AC6AJSxnbYJiMzOXhA2kCLY0OZXNtjTAG6PtRGFUADmsa+YFwAYQgdxsAF4bMBYjYbK8uIh8igbIMoGAAtA5q8oFtEAcoTDYV4pF8bFBETYAKJOCLzaIgZTVelHKCwjSxdlQE42AAGFCcIxsEmFKN8bFGPJ8TWmAEcyFxpvgbDBfO5iWFnLTnhFsJgfjkUtyIJRXMxeZNpg5nDzxkoBQTWVkpjNnAslitzBstjsbPxCbC-Y6iVk5mlsGlPMAANaIEbItJcfBpLQ2MOAvVOHDFACMaQORH9Nj2BaDIZBd3zhMOHNFwmGguhjotLvmi2WqwoXu2u0LgeDsJEofDkZjcdTieTnjTmZ+mewxQATHmS8Hi4XB+XsJXHdWoJyFHgkOiuNA+GhswBmFAL7OabQgYRiNQSMD9BSmZSqNCaYsgeC+KMz0EB9dDUEQiicHgAAEFwkAAGCQABYFDIJx5DQGQKFwFBrDIKBsCjH4X1BSxwM+aDYIQxDSIgngJHAqBDGMBkRmwPQYDASDsAsDQ9g0IA).

This is blocked on #2273.
