### ISSUE TITLE
Idea: support streams in the core rendering algorithm

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#1958]
I feel if we're shipping stream support by default, something so often useful, I feel we could at least make it a little more integrated. That's arguably the main reason I haven't started embracing them yet - they don't really simplify much for me (yet).

Although this is admittedly a bit ad-hoc and inelegant, maybe adding support for a `vnode.state.view` stream (checked by function + `.map`), instead of a standard `view` method?

**Comment by cidelbaterpnu** [comment]
Hmmm

**Comment by isiahmeadows** [comment]
I'm retracting this for now. You can always do `stream.map(() => m.redraw())`, and I'm not convinced it'd fit in well with how Mithril renders things. Plus, we don't really want Mithril core to have a dependency on Mithril streams - that's kind of by design.
