### ISSUE TITLE
Calling m.redraw within view call chains results in duplicated elements

### ISSUE THREAD

**Issue by klick-barakgall** [MithrilJS/mithril.js#1962]
Hello,

So I have a tree of components (admittedly overcomplicated) that sometimes during their renders discover that they need to change their state and trigger a redraw. I try to do this using a zero settimeout so that it finishes the current draw cycle before it starts the redraw, but I seem to miss them from time to time, and I believe this is causing rather odd behaviour.

Specifically doing so results in duplicated and then later orphaned DOM elements.

I was looking through the documentation and I didn't see anything that explicitly disallows calling redraw from within the call chain of a view function. Is this officially unsupported? Or is this being caused by something else I'm doing wrong?

I created a sample codepen. The pen will randomly call redraw from a child component, just hit increment a few times and you should see a bunch of duplication happening. https://codepen.io/anon/pen/JrPbVo

EDIT: changed the codepen in a minor way, should not affect any tests already run.

**Comment by pygy** [comment]
@klick-barakgall in v1.x, m.redraw shouldn't be called from the hooks (`oninit`, etc...) or the view, I'm sure it is documented for the hooks, if it isn't for the view it is an oversight.

v2 will have async redraws by default, and an additional `m.redraw.sync()` method.

**Comment by klick-barakgall** [comment]
Thanks I guess I just missed it. I have changed all of my m.redraw calls to trigger on `setTimeout(..., 0)` to avoid this issue.

Thanks @pygy.

**Comment by pygy** [comment]
You're welcome :-)
