### ISSUE TITLE
Classhelper into core

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#1967]
I'm heavily using a small helper to generate classnames.

```
const classy = def => Object.keys(def).filter(class => def[class]).join(' ')
```

I think it would be great to have that built in.

[snabdom](https://github.com/snabbdom/snabbdom#the-class-module) has support for this too.

## Expected Behavior
```js
m('div', { class: {
  isActive,
  someRandomClassname: someRandomCheck(),
  [someStringVar]: true
}, 'Hello world'})
```
should be equivalent to
```js
m('div', { class: compact([
  isActive ? 'isActive' : null,
  someRandomCheck() ? 'someRandomClassname' : null,
  someStringVar
]).join(' ')}, 'Hello world'})
```

## Current Behavior
Does not work.

## Possible Solution
add this to class handling `hyperscript.js#L54-60`. Would love to create a PR if wanted.

**Comment by isiahmeadows** [comment]
-1 from me. Try https://github.com/JedWatson/classnames, if you don't want
to roll your own.

**Comment by cavemansspa** [comment]
this seems like a practical addition to me considering that generating conditional class name lists are commonplace in a mithril app.

maybe just add as m.classy as a convenience function?

there was further discussion related to this on gitter regarding @porsager bss lib.  was that also a consideration for moving under mithril community?

**Comment by tivac** [comment]
Utilities like these shouldn't be in mithril.

`classnames` is a perfect example of a small, targeted, optimized lib that handles this use-case excellently.

**Comment by tivac** [comment]
I just saw [`classwrap`](https://github.com/jbucaran/classwrap) which seems promising as well.

**Comment by StephanHoyer** [comment]
I know all those libs and I still find all of them way to much. The proposed one is much simpler and a allows everything that those libs allow but in a uniform simple way. No flattening, no mix and match of arrays and objects. Just one object. And sure, I can roll my own, thats what I already do.

But since this is a pretty obvious use case and has only a small performance impact (one string/object check) I thought it would be worth adding.

**Comment by StephanHoyer** [comment]
maybe one could use a property `classes` for this.

```
m('div', {
  classes: { ... }
}, 'hello')
```

**Comment by maranomynet** [comment]
Adding `classes` prop would bring a **fourth** way to declare classNames on elements.

```js
m('div.class1', {
        'class': 'class2',
        className: 'class3',
        classes: { class4: true },
    },
    'Class War!'
);
```

Regardless of that, IMO this feature should be handled outside of mithril core.

**Comment by StephanHoyer** [comment]
just created https://github.com/StephanHoyer/classies
