### ISSUE TITLE
Lifecycle methods order in docs/components.md?

### ISSUE THREAD

**Issue by matildasmeds** [MithrilJS/mithril.js#1969]
Reading the [Lifecycle methods section](https://github.com/MithrilJS/mithril.js/blob/next/docs/components.md#lifecycle-methods) in docs, I was wondering why is `onbeforeupdate` placed after `onremove`. Is there a specific reason for it? Would seem perhaps more natural to place it before `onupdate`, to match the actual order of lifecycle events.

(Btw. I like the docs a lot so far, they seem complete, clear, not overly verbose.)

**Comment by pygy** [comment]
@matildasmeds that's a good point, no idea why.
