### ISSUE TITLE
Tracking bug for DOM mock issues

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#1978]
Just a collection of things I've encountered:

- [ ] `select.selectedIndex` is broken, blocking the fix for #1916 (#1918)
- [x] [`option.value`](https://html.spec.whatwg.org/multipage/form-elements.html#htmloptionelement) does not have the [`[TreatNullAs=EmptyString]` extended attribute](https://heycam.github.io/webidl/#es-DOMString), but [the mock acts like it does](https://github.com/MithrilJS/mithril.js/blob/next/test-utils/domMock.js#L447-L449)

If you discover anything else that needs to go here, please let me know, and I'll update this description to add it.

**Comment by isiahmeadows** [comment]
Ugh...why can't I edit this... :-\

**Comment by robinchew** [comment]
Is select.selectedIndex fixed?

**Comment by isiahmeadows** [comment]
Nope. Only the other has.

**Comment by StephanHoyer** [comment]
@dead-claudia Still an issue?

**Comment by dead-claudia** [comment]
Probably forgot to close.
