### ISSUE TITLE
Official MithrilJS stance on TypeScript?

### ISSUE THREAD

**Issue by RodericDay** [MithrilJS/mithril.js#1985]
It would be nice if there was either

- an open issue(s) for working on ensuring compatibility ([TypeScript works with raw js files](https://www.typescriptlang.org/docs/handbook/compiler-options.html))

or 

- a statement in the docs addressing that the compatibility will be handled exclusively via [auxiliary definition files](https://github.com/spacejack/mithril.d.ts), and never a part of the main project, just to quell any questions from newcomers

**Comment by tivac** [comment]
Ideally @spacejack's repo would move under the MithrilJS org, but that's their call to make.

I'd certainly merge a PR adding a disclaimer in the docs that Mithril provides best-effort typings but it's not a focus for any of the maintainers.

**Comment by spacejack** [comment]
I've been planning to move that repo under MithrilJS, I was just hoping to get it back in sync with DT first but haven't had a lot of time to do so (they've drifted pretty far apart.)

The types are "officially" maintained under DefinitelyTyped, and PRs can be made there. My repo at this point serves mostly to discuss issues or experiment with new ideas.

For the Mithril docs, I'd suggest something like...

> Unofficial Typescript type definitions are available via DefinitelyTyped. They can be installed with:

    npm install @types/mithril

> Issues and PRs can be made on the DefinitelyTyped repo.
>
> For documentation, examples and other discussion please visit MithrilJS/mithril.d.ts

Anyway, I'll try to get my repo in shape this weekend and move it over to MithrilJS.

**Comment by isiahmeadows** [comment]
@spacejack You might also want to include issues in that list, too. (It'd also provide better visibility to your repo.)

**Comment by tivac** [comment]
Fixed in df4ce63eb0abf931e4bfd9625df0281a3e792e83
