### ISSUE TITLE
"Avoid restrictive interfaces" docs section hits its own gotcha...

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#1986]
## Expected Behavior

A correct set of docs...

## Current Behavior

In the ["Avoid restrictive interfaces" section of the component docs](https://mithril.js.org/components.html#avoid-restrictive-interfaces), it offers the advice to send `vnode.attrs` directly to the component. This is bad because [it can result in vnode lifecycle hooks being fired more than once](https://github.com/MithrilJS/mithril.js/issues/1775), and nobody expects that.

## Possible Solution

Three options:

1. Use my [`censor` helper](https://github.com/isiahmeadows/mithril-helpers#mithril-helperscensor) in the docs
2. Move my helper to core and use it in the docs
3. Ignoring lifecycle hooks from vnodes with identical `vnode.attrs` to the component's received `vnode.attrs` during rendering.

The last point IMHO is probably the best of the lot, although it doesn't catch the case of `{...attrs}`. In the latter case, they can still use the `censor` helper to remove lifecycle hooks before adding their own things.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

See my [`mithril-helpers/censor`](https://github.com/isiahmeadows/mithril-helpers#mithril-helperscensor) docs, which also explain this. (That was also the driving reason for the library in general.)

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by barneycarroll** [comment]
Good catch @isiahmeadows, somebody recently came to the chat room with a case of a component API which on the surface appeared generic but internally made assumptions about the shape of children. I reached for this section of the docs but found it completely unhelpful and ended up not sharing it, although by rights it was exactly the place to describe this problem space. I think a rewrite is in order.

**Comment by isiahmeadows** [comment]
@barneycarroll I've seen it probably half a dozen times at least where what seemed like a Mithril bug was really someone using lifecycle methods on unsanitized `vnode.attrs`.

**Comment by isiahmeadows** [comment]
I'm attacking this by doing both option 2 and 3, and I'll file a PR once I'm done. Basically:

- With view templates rendered within a component's `view` method, lifecycle methods are ignored on attributes used directly within views. I'd rather not force the user to wrap the common case, and we can dodge some excess allocation on top of it. As an added bo
- With templates nested within things like `view` attributes (like in `m(SomeComponent, {view() { ... }})`), I'm providing `m.censor(attrs)` for that case. I don't want to have to introduce a stack for that, and I don't want to keep adding abstractions ad infinitum just to keep the veil of it being magically "correct".
- With object spread, you have to use `...m.censor(attrs)` anyways, because there's no way to track that.
    - This carries over to JSX spread. We could create a Babel plugin to correctly address censorship of spread attributes within `<Foo {...attrs} one="two" />`, but this would remain unnecessary for single spread attributes with nothing overwritten. (We kind of should have one anyways to correctly transpile JSX fragments to `m.fragment` - `pragmaFrag:` isn't sufficient here, and there's no way to specify fragments with attributes. We could also stand to optimize the result better.)
- `m.censor(attrs, extras)` is also useful for when your component also wants to intercept some of the attributes, but not all, which is another reason I'm including it.
