### ISSUE TITLE
Extremely poor render performance in IE 11

### ISSUE THREAD

**Issue by kvanbere** [MithrilJS/mithril.js#199]
IE 11 is taking between 100x and 1000x longer than Chrome and Firefox to render pages in our app (what takes 10's of milliseconds in the other browsers seems to end up taking seconds). This is more of a meta-issue to discuss how we can make this less extreme.

Also refer to the benchmarks here, where vue.js sometimes wins/ties over mithril whereas it gets easily beaten in other browsers (and angular is as fast as Mithril in IE9? huh?):
http://jsperf.com/angular-vs-knockout-vs-ember/351

Definitely don't feel like I'm blaming poor IE performance on mithril! It is incredible how fast it is already, and we're absolutely spoilt as it is. /But/ IE-specific optimisation is something worth researching.

**Comment by Li-ReDBox** [comment]
I just noticed this delay in IE with simple array pushing when I was doing study. On page, I used `v-for` rendered a list of objects (based on the grid example). Then I push a new object to the array through console. It will take 1 - 2 seconds to get updated. What I found interesting is, when I added `console.log(Date.now())` in `timerFunc`, it will update "instantly" to my eyes. Strange IE!

**Comment by gyandeeps** [comment]
## Perf for mithril vs reactjs on IE vs chrome

#### Use case

We have created our own framework based on our needs but then started looking for vdom implementation to support that. Thats is when we started using `Mithril`.

What we use from mithril:

* `m` - to create dom elements
* `m.render` - to mount the main node

What we used from reactjs for this test:

* `react.createElement` - to create dom elements
* `ReactDOM.render` - to mount the main node

Our framework is built in a way where its easy to replace the element creation and mount portion logic with any external implementation. :smile:
Here is what we saw when we render a `table` which uses `div`s with 3 columns.

##### IE-10

Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 37-41 | 38-44
500 | 162-165 | 147-166
1000 | 335-355 | 285-305

##### Chrome

Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 27-35 | 57-62
500 | 85-91 | 176-185
1000 | 125-175 | 295-315

**Note:**

* All times are in `ms`.
* Did 15 runs each with manually refreshing the browser.
* 1000 rows were basically just to get some numbers and its not a real usecase.

#### Observations

* Mithril is way better on chrome with a great margin.
* Mithril is slightly slow on IE-10 but its very close
* Based on the margin its definitely something to do with native stuff with IE
