### ISSUE TITLE
Node.appendChild is not an object

### ISSUE THREAD

**Issue by starsolaris** [MithrilJS/mithril.js#1991]
Mithril throw error to console

## Current Behavior
TypeError: Argument 1 of Node.appendChild is not an object.
```
	toFragment https://unpkg.com/mithril:730:22
	updateNodes https://unpkg.com/mithril:544:59
	updateFragment https://unpkg.com/mithril:640:3
	updateNode https://unpkg.com/mithril:615:16
	updateNodes https://unpkg.com/mithril:524:12
	updateElement https://unpkg.com/mithril:674:4
	updateNode https://unpkg.com/mithril:616:15
	updateComponent https://unpkg.com/mithril:688:9
	updateNode https://unpkg.com/mithril:619:9
	updateNodes https://unpkg.com/mithril:524:12
	render https://unpkg.com/mithril:969:3
	_16/</run0 https://unpkg.com/mithril:1032:4
	throttle/< https://unpkg.com/mithril:986:4
	redraw https://unpkg.com/mithril:1014:4
```

## Steps to Reproduce (for bugs)
[Example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHhLID4AdNAAl7YwMAE259+AuNQBOEAA7FecadQC8XECWJy4iAPR6ArmjkBrAOb46WPVgjFCsqBo4s9U2QrH83hIaJ4fACNaYQBPbwE9EPCxX1IoDhAAXwp0bFxEAgArBCo6BiZiPAA3DGleYQxiDF5VXmQeLmJUDSgIOGINRGANAEZ8PoAGACZu3pAQgA9u5ABmAE45kb6KPr6ANgBWVZWADi2KOb29gBYAXVT+waG58Y1p2dO+raGNtc2din3D47PLijXPpzIb3Sa0GZIeZLFZrLZbOanb59A5HE4XK4gAbAvpgx5Q56vd4vBFIn5o-6YgYjEZ3JATfEoLZ7BZ7EbfADsKMO5L+GMBWPwIx2eIhs2ZrPZc2GGz2yNRfIB10RG1FkJQ+1Oh1OGw2t3lv3RSsFiI5atmI1OtyGFB1ermBop-OV8PNBJeb1tuv1vKNVPwezpPQeYqhErZFA5HI2HMdiuSCbSbQ6XXpQNGbpQi2Wq3W2123KdxuxQz2meQW0tIzlea+vspApLC3LWx1wI++bjfsbgxB5ezsJJiK7DeuKzGafB6vmpwWlc5hfrzsFVf7MNW0recqXxaFpyDDNDKEJns3spHy+pHNBk8Z0JzR1n853-pGXPLJ-eiLn7JfiYm7SdGC2IHP2XJzLGtIggWCrdmOfQTsGU6zN+z5cqiL49isB4htOEHApB6E8oW8YJucgJoM0rQgIBqY9P+yZAZOAwgohh7TqcexDFsCwUnM7x-sk5FNC0AEpsBQpDGat5HsglrWguGEkXBK6luWIwbCsZJEReu60ls6lWiCRwytuymjiu-HqZpfRImeZmwZSZEUVRYlMfRqRuXRwAMTR4n0mRPDnAA3E0aAFJ0vAALIwDUAAi1S1PUvSUcQtGIA0wmpfQMhCIwGVgMY1DEBA9AABQAJS8ClEi8HIhhwIQlUiVcqUlBAMAAO4FUVJX0LwlXVSJzTSLFhjSHwWBlRocAlOYGgUENqXNM07VdQAQhCGUAORDLwe3bAiWy8IdcxbNtLldFdzRyKNcAwNIJQwAAgnAcgwMVABK1SlTtaD0DAF3DddxCdGEsAZRonUQMIDgZcMQwAKTBbwfgQOYJDw0MSOhSAwPNKkDT41dU0zcQ4MwAt1Xk+9kMgIwUzEHo1BwHAGitStIMrSAo3FdVnTSLQpgwBlADE2MAGIS9jKMC0LMAALTQ7DhBY0MKOQFAUAZf9aAwMFyQaMTzQVZdnPNDF8WJfgtH4FgGByGVhXhX1fBlVUNRVSl5sg6NxDjXwHsYDbKa8AAZGHvAAPJBNkH3EPgwthHA7vW7RFV2w7Tu9aVbsw17wP8D7sCKNMdSVGnKbIDD5z4GXAD8Fc1CHnTV8Itdlzrhha6Fy1c8QfsB7wZcR7wpM8-HVPAFMGXTMgQzkbwYSzxCyB9Ivytw8Pq8jIvaMY8QK9TPMlwVb3PsE2fxPJBVwPnFfqWG2gyTn2gJe8BA5fqzwzvFbndUNSagXVKEVaCwBtrQcwZUIAPwtrFDACVm60XLkHauIURJYHwKNYQ0gMCdUqqFLoqUIAAGoSHnxKmAAan9VD1CDjbJg5gHC31St7K6g8JoUKfs0e6xAAAqEAcC0EMMQMq9VGqLSGA-bhaBMFYGEQwd2tBqCGBwAwOuoQwiLUtggxKD9KA0FoFgOQ0AHp4CCBgIIMByCeRAJgHAeArCswMQURgzAsgpEuEAA)

## Your Environment
On FF 52.4.0 and Edge 15 reproduced on every run, on Chrome 61 not every run.
Windows 10

**Comment by pygy** [comment]
Thanks for the report. While trying to reduce this, I ended up with [another weird issue](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4AdNOKnUsAB0lLgANwgwA7gApg1QtGXSmrAJTAPsTq0miSWC4A5MoQdpEUksgeXj5oALp+rKwmWPipyjDSLrLyCREWlgnIJpKJEdGx8ZIAjH5pFDV1UTFxCQBMbR1hXQ29kgDMbSYZfjl5TAVFJcRlLhVVncjtm-U9TQAsbWkmfrNoufmFxXIr4WtWG8PIu40JAKxT6adzl0s3q+tEpt2oljl8zmwOCBMDg8PhqHABDR6IxmDw2O0QFAIGgANYIFCcWE8LAQYiEaTQSggELkHgkYiWOCIAD0LPUaEsuIA5vDaFgWaTyZSoAABZr4CVvQVkinQfD8anEAyWbggRWsNKsIA):

```
const root = document.body
const cmp = {view({children}){return m('div', [children])}}
m.render(root, m(cmp, [
  [m('div', 1)],
  [m('div', 2)],
  [m('div', 3)]
]))
m.render(root, m(cmp, [
  [],
  [m('div', 4)]]
))
m.render(root, m(cmp, [
  [m('div', 5)]
]))
m.render(root, m(cmp, [
  [], []
]))
```

leaves the DOM as  `<div>4</div><div>5</div>`.

Something is amiss in the land of nested fragments.

**Comment by pygy** [comment]
Making [some progress](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4AdNOKnUsAB0lLgANwgwA7gApg1QtGXSmrAJTAPsTq0miSHl4+aKysJmDqpsQQ9JIYxMTScC4AHn6SwCaSMjDBofmFRZL01D5pMC52efb4PupwMDaSGeowANzh9HC0sPhQtADmLkY0tYyS05IA1JK57BVF9OqWynUNTXYtMG0dSt19A2hDI2OT01s7cwvLqxTrVWg+WLR29Y35B612p0zv1xMMYKMJlMQJ9vh0nis-GswpJYtETCYsIc0MoYNIXLJ5BRJFgXBZLK8UViwNIMOMtMQXGkMlkAOROACMrL8xOQpNZyggdlZxOZmRcrOoXJ5kg5fgAujyKtTafSREz0uL2QAmbm8-mC4WizVs6i6mXahVKqn4Gl0hkalkSpwAZj1kj5EsNItSJol1DdMpdVpMfj8JjB1yhrMAKARx7mY7G4-GE4jE0nk4nK22qh1itkAQXdyEVWZtdrVDDc7A9BqFPvz-oALO6m1bJAB6DtdTxwSQQPuWWQ6DA6KAGHsdIe0McwLCh8OmQbgyGTWPxxdYqLJglyNMkslWSlFFX29WN9kAVmLdaNvqdkuvMsvIbQYYjy6ja7jMYTaC3TA7qm6aHhS2YVnmfqsgAQsWpYkjmZ5VheADCcGLu+aAmGwHAgJgOB4Pg1BwAIND0IwzA8Gw8pUFAEBoAA1ggKCcARPBYBAxCENI0CUCAITkDwJDEJYcCIF2CSWAx4xEbQWAdhxXE8VAAACHL4Opl4KZx3HQPg-B8cQBiWNwIAGVQlhpB48BIMgdkAAxUNkxAAMoQGO9HjDKIA0cgAC0HJUNIPkUMggUgHAhC0OoUDKAASiFyCOSAMDUAY1DkL5AVUJ5iXhbgvnJcSlyLkYxBlRV5VVSFLouhQLoAOwUNqHINQAHNqzWtR18ryqwfVAA).

**Comment by pygy** [comment]
Making [some more progress](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAW94AcyoHoCBXAOxwGsBzAOlgHsBbAxgS3gwCdWoABARhqCArC3ZceNAFZgQAGhAAzHhFmoA2qFIBDRhDQgaWRlHkgGpRJYMgAvnK2796abIUWr8AxbDwABJz09P4AvH5I9LDEepY0AEb0SACeADqkPv6wjDh+YcAAbqwQAO4AFMCwGDxInBCktgCUwLXwxJykfpXVtfW2aYpkCKz0HdrYnGClAB4NfsBpfgEQre1zC4t+I7C1YxCl+bMFNLXEkLl+8JzEEADcnSNg9DA0UPRUpSnmO4h+n34A1H4ZvZ1osRsQcEhdvtDvljhBThBzpdrncfE8IC83h8QBCoT8-oDgXJQZtSLVGPR8nsDnM4SczmEUbd7qRHs9Xu9PhSqUjCUCGiCOn4+vU0mlGPDSEgIJxSoFgnI-IxSlkcCThZLFJxtFQYvBSmNLpMAOTFfgmhpK9Qqk1IVj5E1Ko0TUom2AWq1+fgNAC6VvWWp1erqBpdpuKACZLdbbfbHc7xqbYNGvZG-QHNTRtbr9Yak27igBmGN+G1u+NOvzht2wEteosZtINBppdEc7EmwAoBD3LRKpTK5Qr4EqVWqlYHs8G8zWTQBBUvqf0TrM5kOWcr2Mtxh1V2ewAAspYPGb8RAuVTAflYV5wgTi2jiUCSF6Rd-oT4gjGbrfSDwxWLvN2va-pKPSDvKQQjsqqrZBqixBrmob5sahbCIuO4JtWBbuuhXrCE2pAtm2-4dkBPZdn2pBgXUEHDqOsHqpOa4zjhABCi7LsqU5IRus4AMKcb+xGkGkdgOCAOh6AYdBgG45gjJ4Ni2L6ChQKwpAUGomiSU4BhsBw3CmAobSmOgWC4PgRBkJQtAMMwBkSHwggiGIhmSDIZjwEkODOCAnkKDgYyVKoaDqOFAAMChgL+KTwHFCXxfArCKH4pQgKp6gALT8AotSwEksDqaQVAZXI6i5eAGD0MQUBIAASnAhUwH4ABkrV+DgQRQH4ACEYSkLVPVleoUUgG1HX0DQ8C6rkIRlUWRZyMIB5yJGEX8AewhrRtW2ZaNCiJYlKVpSNOV5U1RUaaVmWVWA1W1Q1l0te1nXdX1A1DX4I1jX4AA+f1+L42icGVkbbQeABsO2Q5Dq3rbDB77WNR1JSd6WZedID5c110jXdD11Y1BVFUir1dU8H1+INUDDZlv2vVNM1gxD0ORvwRYRVF7OcxFyMKFM8AAMqsE+11emdlWg7d0WEw1P0KM9ksKHjMsgPo9MKEqbKxUlqNxQtS1FgA7Gt-AABxbWblvCPzIDinrjuJfjKupaU901UTz1kx1FM9f11NfYz02zSEYfKlSj7PDNVCzArIAaZAnDwAAcvQZX8NDxtsxbxvbez5t576voqbYQA) on my sample case: replacing `recycling` with `shouldRecycle && pool != null` in the condition before `insertNode` makes the `4` disappear. IIUC, the only nodes that must be inserted are those that come from the pool when `shouldUpdate` is true...

Still that doesn't get us rid of the 5, nor does it solve @starsolaris' crash.

**Comment by isiahmeadows** [comment]
@pygy I *seriously* look forward to seeing this PR...

**Comment by starsolaris** [comment]
@pygy I checked your example with fix in my worlkfow. I cannot reproduce exception. But i still has another problem (I thought it was because of exception): [Example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgAmGYhmkBeacgA6adcQ1bi24OpBQIcfUmnBW7TdoNGTZo4kvXbxALoV3uu8UPGpuYuVjZ69oFOFgEAjPgATPEAzM6WRgBGtAAeqcgArAAcAJwF8RTS8QDsMQV55fE1ddJJBQUALB7WYX6G4frmjsFpfX5GcUkADJWpAZk5FvnFpeUtBUkAbPWNK60dNv2jIwcgcXl5MxnZuYUlZc27W7U77Z3ufqxvxB96Xj6fvaMBkELkc7Cd8EULiA5rkYkV1usYuUJo8mqs9pppFjsd93u5fnpfP0AoMZtZvH0ScDom4fpoPABuQ5CMzSACyMEUABEFEpVADiIMXMgCdp6NRJDAFDAXGAAK5oajECD0AAUAEphtjpAAHOVwQga9zdYhiCAwADusoVSpVaGkGuGfklxDlkntWFVRjgYgA5kZygK-GbLQAhbIuADkE2kMfWZySeWk8byicjFMB2h1krgMEkYhgAEE4DqYEqAEoKFVRtD0GDpz5+MwAT1gLiMFogsmIhBcMQmEwApAzpIQYBBfSQ+wPh0ZG19ykTAZ7vcRWzAA5Y16X2yBGFliAB6ahwOBGE2Z8ySpWWMySWgAaxl0gAxAOAGLvgcju+PmAAWk7bte2kfsJhHSAoCgFxazQGAGQ+EB520dUMwOfoOW5Xl8EGfAsAwHVVXlRVlXoB15EUTUg3Q7QXTde0KIwHCgmkAAyVjpAAeXSXgy2IfAn2bOBVUY5izHVPCCKIm1SPtVUuyoz4sUBWBiGkOYVDkbDBmQLsPHwDSAH4tMUMSdD0gzsmkGC5SgplQX6Oj3XUqz2OkFcQGvcxAyyFw5mQCYvGkZs-OyZAYiCoCe1CrJkHiIKxwnKcXNipJOnVezL1YDL52yz4PByvRvlYTK0FU6QIE08DNGI20yL1A1HQFFlaFgHDaF9eTCu0TCMB5UzBk0xjdMZdwsHwSVZEkDALQ1Jl9D0CAAGolsy5UwAdSrlFUUTYDQX0e3VdxqKctA1txYhc2IAAVCAcFoOViFVBrCHKGJCtxNBxqwB6GBE2hqDlHAGEs2Rm3KXr+owQq2A4EBMBwPB8BPAQaHoRhmB4NgvECNAHwQFBOERngsAgHtJGgSgQDdcgeBIYgdTgRBD0PBUdQfX1kdoLBD1J8noAAATiU5ebJwgKagfB+Cp7duBAaWqB1BRqDHAnkHVlEQDgI6HO0CANtVEAvGQf8kU8stm2oEx9qNihwqoA0HqgWRywtq2YDYjidVoVrpAAQlUNBbKgaRbYCqhPekWh8EUX0VGUW2kiSCg8jaCh4gmGI2jqDOs7yY3w6Qmj1odMPTaoa9Let30w7Nx3bJdt3YEj73fYD6Qg6g0Pjc16QAB8++kMwpFt+I6jaTYM4RNOp-WDo7cLy99dL43y-N6gq4gG3jbrwgncbjf3Zbn2Q-bzuQ7D3u3OjxRR-HyeYkmFEGifgvNYPABlCB0mr1Du7ttekha4Oz3g3csl8qBNzLmbLeNcd6QIgZQDu2tkLoUTsnJIlR041Gztg9o+cF6a1QYCYBIBl6qnrs7V2h9m5uVbqfQOwdI43wwHHbaqgfoSB-jAGOrDNSIK3rmSQxAABytBbYxE2JUB+BRKg5xqHIjwnROhAA)

Mithril does not remove some nodes (green rectangle on screen)

**Comment by pygy** [comment]
@starsolaris Thanks for verifying.

The rectangle remaining on screen probably has the same cause as the `5` not being removed in my reduction. Needs more digging (maybe this evening CET) :-)

**Comment by starsolaris** [comment]
I cannot make example for now, but in next branch with fix i get new exception:
```
TypeError: node is null
removeNodeFromDOM@mithril.js:833:7
continuation@mithril.js:820:8
removeNode@mithril.js:810:3
removeNodes@mithril.js:789:10
updateNodes@mithril.js:623:4
updateFragment@mithril.js:668:3
updateNode@mithril.js:643:16
updateNodes@mithril.js:553:12
updateElement@mithril.js:702:4
updateNode@mithril.js:644:15
updateComponent@mithril.js:716:9
updateNode@mithril.js:647:9
updateNodes@mithril.js:553:12
render@mithril.js:1023:3
_16/</run0@mithril.js:1086:4
sync@mithril.js:1066:52
throttle/</pending<@mithril.js:1041:5
```

**Comment by pygy** [comment]
@starsolaris Could you try with [this version](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAW94AcyoHoCBXAOxwGsBzAOlgHsBbAxgS3gwCdWoABARhqCArC3ZceNAFZgQAGhAAzHhFmoA2qFIBDRhDQgaWRlHkgGpRJYMgAvnK2796abIUWr8AxbDwABJz09P4AvH5I9LDEepY0AEb0SACeADqkPv6wjDh+YcAAbqwQAO4AFMCwGDxInBCktgCUwLXwxJykfpXVtfW2aYpkCKz0HdrYnGClAB4NfsBpfgEQre1zC4t+I7C1YxCl+bMFNLXEkLl+8JzEEADcnSNg9DA0UPRUpSnmO4h+n34A1H4ZvZ1osRsQcEhdvtDvljhBThBzpdrncfE8IC83h8QBCoT8-oDgXJQZtSLVGPR8nsDnM4SczmEUbd7qRHs9Xu9PhSqUjCUCGiCOn4+vU0mlGPDSEgIJxSoFgnI-IxSlkcCThZLFJxtFQYvBSmNLpMAOTFfgmhpK9Qqk1IVj5E1Ko0TUom2AWq1+fgNAC6VvWWp1erqBpdpuKACZLdbbfbHc7xqbYNGvZG-QHNTRtbr9Yak27igBmGN+G1u+NOvzht2wEteosZtINBppdEc7EmwAoBD3LRKpTK5Qr4EqVWqlYHs8G8zWTQBBUvqf0TrM5kOWcr2Mtxh1V2ewAAspYPGb8RAuVTAflYV5wgTi2jiUCSF6Rd-oT4gjGbrfSDwxWLvN2va-pKPSDvKQQjsqqrZBqixBrmob5sahbCIuO4JtWBbuuhXrCE2pAtm2-4dkBPZdn2pBgXUEHDqOsHqpOa4zjhABCi7LsqU5IRus4AMKcb+xGkGkdgOCAOh6AYdBgG45gjJ4Ni2L6ChQKwpAUGomiSU4BhsBw3CmAobSmOgWC4PgRBkJQtAMMwBkSHwggiGIhmSDIZjwEkODOCAnkKDgYyVKoaDqOFAAMCjivAKSxV4qnqAAtPwCi1LASSwOppBUOc6WZdluUAD5FdeYAAEpwAVj4wKUTxIEq+SkIkqi-nF7XwKwih+PKVVZRpVCHDFHVxfk2icH4OBBFA5z1TQU1PMN8VxfVs1QEgdBbGMdXrfN01tct8CiiNCVyOoqUgKSiwgIlUUgGNE03XI-AHpGz3CM9ACcB4HgAbF9P2-Yl6h3UiYRPclF2lAtM0AIRhKQxBQDNABkKObOtADK8Djf4AB8YRzTAOUcH4SWTdNLx1FQHCzCVPXQ9NuQI0jUCzGjSwZf1OUNBDF2KNoUCQBDd1LXFT2fR9-BFl9AAcEUHnLCvA3dYAHSdcVdT1EMpWlfWFXzChgBg9BI0glVczAfgczDfjw34iPI34IsKNb6P0DQOO5SEIRPUWMvCIr-CfZ9Rb-cHodA2dIMKGDzuJbrICM08dss07HP1QAotKfgExjG3EzTGBkxTTxUyTGB06VpTJzNPsO6z7Po-l3ODYbSiC8Lt3RaJh0SzL0tyJGEWRr9UXD6PEUq9Fh2a91pQ6xdLcG4lF3G6b60WwVSI20z9uOzNLsgH49O+ONT2Rh9f1DxFRYAOwfcP9-CNPIBx4vCi16nDfp+763Z0gXOhNdqF1JuTGG5ci5VwZrbeuB8m6cwKgNXmq8FACyFvobul1e4dX7s9GWw9Zb8FljfIhstX4a06vPD+IBl4DXbuvM2W8so73RrbferN45nTum7TYnttAXyvv9YeodUoiKLPwV+78E5Q3YWnVGf8kAAElpQQCmEA-OkCwGlygFoyuJ9q5fzgY3XhdCebt3QV3bhPcToSylgQ6WEVH6OJftHO6Ux4CY1YE+ZBSoaGcAYSbJhR99Y0Poagt+R8lRsnVrPeKfsZb3yHtLb6ySizfQoTguJuCIla1KIwze+tWE6O-gfXhHsvbMzCJSMan5+GDS4THEAGlICcHgAAOXoE9fg-077CJepGRWkYBkHlfkwX8NDKFzx6h4NR-gOG-z8E1FqNAIiMC8QALzBvI3hsMMDaDACoxAVAdSdRGAAWWWCbJAkxlkyhoOGBB3lfL0G6nczElSfZhE+L4bgOVPiHDPAQAAKgAeQACKgouKoTIpx4BMD8NAL8oYwBiziXk2GsyPF7SeLMLF8AcV1zLO830aKTrQDOPiwl81TgYH2M1GUsSTqiiPpQwRb0SGRllty8e3L5a+l9CpWwQA) that disables the pool altogether?

**Comment by starsolaris** [comment]
@pygy i checked this version: no exceptions, no not removed nodes. 
Also, I don't fully checked it mithril or not, but no longer leak memory in my app.

**Comment by isiahmeadows** [comment]
@pygy For context, Inferno has the option to disable pooling, which avoids certain glitches with custom elements. We may want to investigate this option, too (if for anything, just testing).

**Comment by pygy** [comment]
@isiahmeadows #1675 [sets `vnode.reuse` to `false` for custom elements](https://github.com/MithrilJS/mithril.js/pull/1675/files#diff-000bdfae56251b0715111d2b18c9de3cR97), and lets users opt in/out of the pool with conservative defaults: `vnode.reuse` is set to `false` b a before ook that can touch `vnode.dom` fires. This assumes that you wont touch a parent or a child node from a hook.

@starsolaris you had memory leaks otherwise?

**Comment by isiahmeadows** [comment]
@pygy Oh okay. I forgot about that. (I've literally never used it outside Mithril core.)

**Comment by starsolaris** [comment]
@pyty with the version that disables the pool, i had no memory leak for now.

**Comment by starsolaris** [comment]
@pygy is there any progress on this issue?

**Comment by pygy** [comment]
@starsolaris No progress last week, sorry. Hopefully I'll finish this in the coming days.
