### ISSUE TITLE
`shouldRecycle` not used in one spot

### ISSUE THREAD

**Issue by valtron** [MithrilJS/mithril.js#1992]
See: https://github.com/MithrilJS/mithril.js/blame/8b56c7091169c0fb057d7afac041a23a4700bcdb/render/render.js#L237

Changed in: https://github.com/MithrilJS/mithril.js/commit/632677e00c3d6d960a646f4a96a47c4f9b7f7c4c#diff-000bdfae56251b0715111d2b18c9de3cR200

From the other changes in that commit, it looks like the [line after](https://github.com/MithrilJS/mithril.js/blame/8b56c7091169c0fb057d7afac041a23a4700bcdb/render/render.js#L238) should use `shouldRecycle` instead of `recycling`.

This "bug" causes components to get `oninit`'ed unnecessarily: see https://jsfiddle.net/3hnjft4u:
- run and open inspector
- delete items 1.1, 1.0 in that order
- check inspector output: the logged "oninit 1.3" is unnecessary

I'd gladly make a PR for this.

**Comment by pygy** [comment]
Thanks for the report!

At a glance, your analysis [seems correct](https://flems.io/#0=N4IgtglgJlA2CmIBcB2AHAOhSgNCAzvAgMYAu8UyIAFqaQA75ID0zArgHb0DWA5hsQD2YZpFLUAThFgABAIwYFAVlERxU2BgBW+EHgBm0+LqQBtUBwCGYREhAZaYWHpBCO5d1RABfHBeu29joubh6kVAikAAQAclEAvFEADADcADocGfqcZBCCHFEc8BQAShQSlgDuABQAbhyCUPAAlFHAGWmkUIJlUBU1zekc3h0c2Ry5+VHdvf3Vre2ZpG74gggYvBKCbPTVaSAS5VX7gx2kYBiHHE0S1d3EbDbuGABGjQCeOFFg1TGN8F9gNNLKRLEgogARACCABUoVFvM1TksVmt4BhYIJeHsQLUIPBKlFiJZYLB8PsvjFkZ1UetNtt6ABRa7zIadOKJVIZEaZCawSz4fCxf5tM75CAcNR1BpNBZnTr1f4YfCg8gYKAgywJKKKpoYEGkCT4dWatmkGn5VbrTHY4AAcjtSH24sl5r0UW4SF16JVIPRGtBGG48HeiLNPM6ZzxBOl-zlS3ZUQA1Ik5GbOpFgaDtd7lar-ab5ctLWiMVjqvbHfto5UKR6kAHLEGQ2Gi0XDqQ2BICj87WxYHavo2MIIXloMGBLLs7l8IK14gA+UUJ82kTPbcgSdOrzOHMCCWrwCTa3svNh0fKDtpRfLEWAQYieqLwBJLoHD0fj-D0e-EeDVCAvjkQZCmKKBZiqWNZRSBEES+fYAA8Tm3ToIH0KJqlId56HgQR0KgKIAEJ4kSO0VSkDheDteNI1XToNyPbVTH2ABxLYdiiOsoGbT5vl+f5ASzMFpgRZoAF0UNIbxnzJF9Flo2iGOPRJTF7CV6HPK95LonTahJNh4HBKAvnyYN3h2cEX0Xa8PzHUwIDE7V0VBCReHgUgMD02ADJgopSiOGpvRAiMdM6REhwktspKijsux7ao7XvLSPRDIyeLgqJTD3A8jxM88jzE6lV0RIqeQjMYclIPICm4GpuBMscaMNdy4uvMzwXqm8x3BT8ESGcrM2hOFtVqhKSivZiljtJJBzOUa7TkCaiwWjAZpwIt5oURavkmhTSBWhQ1qig7FFmldCvWlcVoAJjO2jNowABmJaV06FbHtWu6dPe07Lr2n7br+1cLrOEGpsBs47Wey7CrZCYSzpdjdn2PpjhAZELiuG47kEB4ng8t4oF4n4-iaQTG3BIb4RKoZaXRekdmZKBWQyDlkiGEJhHoIwJCoF5LBeIgfD8EArBsKgBEFTn3HgTw7B8MS8HvDhuBMcxRYCKgxEkaQXC7Zw7FoBgmFYTgeH4IQRG1jR5EUDAVGt6RtF0PAsJwqhgjwegQWIahjGQUxA6SPAENIABlCAXmV3hmi+EBFdMABaOQ8F5hOU4IahtlgcD45wUxg5AeBiHeO886TjOJV4cuM8QBPC6+Dh8GaKK9rzx7HpwR7cGuuR0GunBe-7sSxO8UegA) (this example uses a version of Mithril patched according to your suggestion and the problem subsides).

But it's getting late, I'll revisit this tomorrow or on monday (if someone else doesn't beat me to it).

**Comment by pygy** [comment]
Yup, PR welcome!
