### ISSUE TITLE
Missing a step in NPM Installation instruction

### ISSUE THREAD

**Issue by Godje** [MithrilJS/mithril.js#1995]
The instruction is missing the step where I have to import Mithril.js in the index.html file. In the instruction there is no step that explains that.

Instruction I followed: https://mithril.js.org/installation.html#npm

* Version used: 1.1.5
* Browser Name and version: Mozilla Firefox
* Operating System and version (desktop or mobile): Linux. Loki 0.4.1

**Comment by tivac** [comment]
[Better?](https://github.com/MithrilJS/mithril.js/blob/5400501aa7d650d39c0e06fa219c4a1e0f296cb9/docs/installation.md#quick-start-with-webpack)
