### ISSUE TITLE
Bundling doesn't work correctly for me.

### ISSUE THREAD

**Issue by Godje** [MithrilJS/mithril.js#1996]
I follow the steps of NPM installation 1to1, exactly step in step.

The problem I am facing is that I want the webpack to bundle mithril.js into the bundle (which is expected) but it seems to not.

I did `let m = require("mithril")` just like in the example. Although when I run my **built** index.html file, it tells me that `ReferenceError`. Means that the `m` is not a thing and is not imported into my bundle. 
Although when I type `console.log(m.render, m.mount)` it logs correct functions into the console. If I am loading newest mithril from CDN, it works fine, and components render as expected, but I need bundling because I am doing a production project.

## Expected Behavior
Successful rendering of component on the page.

## Current Behavior
`m is undefined`;

## Possible Solution
I have no idea

## Steps to Reproduce (for bugs)
follow everything that is in instruction and then run the index.html file.

## Environment

* Version used: 1.1.5
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Linux Loki 0.4.1

**Comment by tivac** [comment]
Can you provide a gist or something of your `package.json`, `index.html`, and `src/index.js` files? I just ran through the instructions and with the addition of `const m = require("mithril");` in `src/index.js` everything worked fine.

**Comment by Godje** [comment]
https://gist.github.com/Godje/200570bace846d45d50bc9386066aa5a

**Comment by Godje** [comment]
You can close the issue. The problem was the missing import of mithril in the <test-module> file. Although the calls of miss were called from the main file, the problem appeared to be fixed when I imported mithril into the `test-module.js`
The bad is on my side.

**Comment by tivac** [comment]
Ah, that'd make sense. Since webpack bundles up within closures the `test-module.js` wouldn't have access to the `m` defined in `index.js` and would barf.

Glad you got it figured out!
