### ISSUE TITLE
Builds are breaking because of an invalid JSON response from the Closure Compiler API

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2005]
## Expected Behavior

Builds to work, of course

## Current Behavior

[Broken](https://travis-ci.org/MithrilJS/mithril.js/builds/294250342#L502) [builds](https://travis-ci.org/MithrilJS/mithril.js/builds/293839417#L502) over invalid JSON being received.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Broken builds are bad. I think we can agree on this.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by tivac** [comment]
👀
