### ISSUE TITLE
Unexpected output using `m.trust()` on attributes

### ISSUE THREAD

**Issue by sagold** [MithrilJS/mithril.js#2008]
Using `m.trust()` on attributes renders the javascript object into the markup, resulting in a string `"[object Object]"`.

## Expected Behavior
`m("a", { href: m.trust("http://example.com/?a=a&b=b") })` should result a markup like
`<a href="http://example.com/?a=a&b=b"></a>`

## Current Behavior
`m("a", { href: m.trust("http://example.com/?a=a&b=b") })` is actually returning
`<a href="[object Object]"></a>`

## Context
As the ampersand got escaped in the url i wanted to find a way to keep the url clean. Using `m.trust` was the first obvious try. I cannot tell if it should help me in passing through the original url, but the output of a javascript object is definitely not what should happen.

## Steps to reproduce

1. goto your [homepage](https://mithril.js.org/)
2. Run `m.render(introduction, m("a", { href: m.trust("http://example.com") }, "Introduction"))` in the console
3. Log the result with `document.querySelector("[href='[object Object]']")`

## Your Environment
* Version used: 1.15
* Browser Name and version: Chrome, NodeJs, Firefox
* Operating System and version (desktop or mobile): desktop

**Comment by isiahmeadows** [comment]
[`m.trust` returns a vnode, not anything that's considered a valid attribute](https://mithril.js.org/trust.html). Also, in general, you don't need to escape attributes - that's something specific to HTML, the markup language, itself, rather than the underlying data model.

(In case you're wondering, `m.trust` as a vnode uses [`insertAdjacentHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) under the hood, since the DOM is sanitized by default if you don't use `innerHTML`.)

**Comment by sagold** [comment]
Ok. Got it. Thanks for your reply.

**Comment by sagold** [comment]
By the way. Do you have any suggestion on how to circumvent the escaping of ampersand? The initial reason to try `m.trust()` was to generate an url like `"http://example.com/?a=a&b=b"` instead of `"http://example.com/?a=a&amp;b=b"`.

**Comment by isiahmeadows** [comment]
It should just work. If the ampersand is being escaped, then something else is going on outside of Mithril. If you're using a generated URL, you may want to consider looking at where the string is coming from, to ensure it's not pre-encoded.

**Comment by sagold** [comment]
Yes you are right. Its `mithril-render-node`. Thanks for your quick help!

**Comment by isiahmeadows** [comment]
If you're having issues with that, file an issue [in that repo](https://github.com/MithrilJS/mithril-node-render).
