### ISSUE TITLE
Possible memory leak in unremoved event listeners?

### ISSUE THREAD

**Issue by TerryHibbert** [MithrilJS/mithril.js#2009]
Could be just an implementation error on my part, but I'm getting some runaway listener counts which seem to be growing memory usage over time.

## Expected Behavior
Old listeners should be removed.

## Current Behavior
New listeners are created but old aren't getting removed leading to increasing listener count and memory leak.

## Possible Solution
I'm not sure of the details, but removing or reusing the old listeners somehow. Or let me know where my implementation is off.

## Steps to Reproduce (for bugs)
The effect is most pronounced with the 'mousemove' event.
Here's an example: https://codepen.io/TerryHibbert/pen/QOjJdB

## Context
I'm making a realtime, event driven single page app that could be used for hours at a time. Stability and performance is key to the success of the project.

## Your Environment
* Version used:
* Google Chrome - Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS 10.12.6

Thanks.

**Comment by pygy** [comment]
Hi @TerryHibbert thanks for the report, AFAICT this is [fixed in the `next` branch](https://codepen.io/anon/pen/oobeKM) thanks to @isiahmeadows's patch that also added support for EventListener interface support.

We may want to backport that fix to the V1 branch as well.

**Comment by dead-claudia** [comment]
Closing as it's a v1 issue, and we're well into v2.
