### ISSUE TITLE
Children being rendered twice

### ISSUE THREAD

**Issue by soulofmischief** [MithrilJS/mithril.js#2010]
When conditionally rendering vnode.children, they will frequently be rendered twice, and when the conditional is false again only some children instances are removed. In Chrome this can cause a buildup of duplicate child components.

## Expected Behavior
Only one instance of vnode.children should be conditionally rendered

## Current Behavior
Multiple instances of vnode.children are being conditionally rendered, and sometimes only some instances are removed in Chrome

## Possible Solution
EDIT: Wrapping the return value of renderChildren in a div seems to resolve the issue? Is returning vnode.children directly undefined behavior? Because returning ({ vnode.state.show ? vnode.children : null }) directly in the view function also produces the bug.

## Steps to Reproduce (for bugs)
Mount this ES6 component and rapidly adjust the width of your window back and forth to keep triggering the conditional render. Eventually duplicate children build up in Chrome. In Firefox, two instances of vnode.children seem to be consistently rendered and removed.

```
import m from 'mithril'

function MyComponent ( vnode ) {
  return {

    renderChildren() {
      if ( vnode.state.show ) {
        return vnode.children
      } else {
        return null
      }
    },

    oncreate( vnode ) {
      vnode.state.show = window.matchMedia( '(max-width: 599px)' ).matches
    },

    onbeforeupdate( vnode ) {
      vnode.state.show = window.matchMedia( '(max-width: 599px)' ).matches
      m.redraw()
    },

    view() {
      return (
        <div>
          { this.renderChildren() }
        </div>
      )
    }
  }
}

function App() {
  return {
    view() {
      return (
        <MyComponent>
          Hello
        </MyComponent>
      )
    }
  }
}
```

## Context
I'm trying to create a higher order component that conditionally renders its children based on the result of window.matchMedia. The full component selects the appropriate media query with a switch statement that takes a provided attribute as an argument.

## Your Environment
* Version used: 1.1.5
* Browser Name and version: Firefox 56 (64-bit) & Chrome 61.0.3163.100 (64-bit)
* Operating System and version (desktop or mobile): Fedora 26
* Webpack + Babel + JSX

**Comment by pygy** [comment]
Hi @soulofmischief thanks for the report, I'll look into this tomorrow.

**Comment by soulofmischief** [comment]
@pygy I updated the report with a solution that seems to work, but I am uncertain if my current code should be considered undefined behavior or not

**Comment by pygy** [comment]
I was editing my post above with the following, but you replied in the mean time so here I am.

The culprit may be the `m.redraw()` you call from a hook. This is a common gotcha in Mithril v1 that will be fixed in v2. You may want to replace it with `setTimeout(me.redraw)`.

Also, if I were you, I'd inline the `window.matchMedia( '(max-width: 599px)' ).matches` condition if `renderChildren` rather than putting it in the state.

Re. your edit, returning `vnode.children` is totally supported. If delaying the redraw doesn't help I'll dig further.

**Comment by soulofmischief** [comment]
Returning setTimeout(m.redraw) or setTimeout(m.redraw, <ms>) didn't seem to have an effect. Is there another thread where this bug is explained in more detail? Is it a race condition?

The real component uses a switch block with an attribute as input that sets the state to the appropriate matchMedia query before each update. So the example I provided is a little convoluted because I didn't want to change too much. Is state still a bad use case for this?

**Comment by soulofmischief** [comment]
Apparently, even when wrapping `vnode.children` in a `div`, if the browser initializes when the `matchMedia().matches` returns false, once it becomes true `vnode.children` gets rendered twice almost every time.

**Comment by soulofmischief** [comment]
The following refactored component (with state removed) still causes the error:

```
import m from 'mithril'

function MediaQuery( vnode ) {

  const hooks = {
    renderChildren() {
      return (
        <div>
          { vnode.children }
        </div>
      )
    },
  }

  return {

    ...hooks,

    onbeforeupdate( vnode ) {
      this.renderChildren()
      m.redraw()
    },

    view() {
      return (
        <div>
          { this.renderChildren() }
        </div>
      )
    }
  }
}


export default MediaQuery
```

**Comment by isiahmeadows** [comment]
[Not reproducing in `next`, if I'm translating the JSX properly](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4wAVzTViEegAIAsgE8AwrSwAHeiIAUcgG5paAExhyAlHOAAdNHLkAnGMXEO7NtLfv2naUw5VCaGNfHUsPb28IMDkdAHcIP1o4-CwMYmpCBRhjCAw9AHIdNIAPAFoE42JCRDkAVgBOBo0S8wKLVPTM+HMvSO8nFzc5LB1rEFz9cYoDI1N8TODfXrtvdls++3oAIxgwWidxDWN0mD1DEzNwze9qiDh8X39ApaYwm-ssR5yHDDj31b2daeQEGCAwf7XUE+ZyuOyjcaTaZyO4PJ4wAJBKAhN7mFaRVh9QloYm2ODOAAqEBwtHExGK3xCfxmAEYAAwcla2L5YWkMHTGWjUcQ4Bj4bYmJQzCRSGTyMJWPr6DAOOR0SSMVUAXjkbL6gzhitB+nBkKN-UcsOGo2Uak02gYM2Q4wp8GIcnGcgA1Gq+ZqvV6ALr4tZE2yscxsDggTA4PALOACGj0RjMHhsQNUKCJADWCBQnDjPCwEGqDmg+H4lBArnIPBIxA0cEQAHoW784gBzUsLdQtktl6D8fulwjlqCVuAttAwErEEeDidVqjEJQabggKusQOsIA).

**Comment by soulofmischief** [comment]
I reproduced the bug with 1.1.5 using your Flems link, but could not reproduce it with `next` either. 

This is very hopeful. 

The counter was a neat idea, but didn't actually increment whenever the children duplicated.

**Comment by isiahmeadows** [comment]
@soulofmischief Note: you *may* want to consider using the children passed to your view instead of the children passed on initialization. Chances are, you're falling into [this common gotcha](https://mithril.js.org/vnodes.html#avoid-memoizing-mutable-vnodes), just indirectly.

```js
// Note that I'm passing `vnode` as applicable, rather than using the original
// `vnode.children`
function MyComponent() {
  return {

    renderChildren( vnode ) {
      if (window.matchMedia( '(max-width: 599px)' ).matches)
        return (
          <div>
            { vnode.children }
          </div>
        )
    },

    onbeforeupdate() {
      m.redraw()
    },

    view( vnode ) {
      return (
        <div>
          { this.renderChildren( vnode ) }
        </div>
      )
    }
  }
}
```

**Comment by soulofmischief** [comment]
Interesting, for some reason I had it in my head that passing the vnode from the closure component was idiomatic. Thanks for the tip, I'll look into it.

**Comment by soulofmischief** [comment]
I still have this issue in `1.1.5`, but seeing as how it is fixed in `next`, I will close this issue. Thanks for the help.
