### ISSUE TITLE
Add Warning Banner to archived documentation

### ISSUE THREAD

**Issue by RodericDay** [MithrilJS/mithril.js#2013]
Sometimes search engine top result links lead to archived documentation, which is misleading and confusing for the user until one figures out they're looking at out-of-date docs. It happened to me with `m.route()`, for example. 

It would be helpful if archived docs had a big red banner somewhere visible reminding the user that these docs are old, and where they could find the latest version.

**Comment by cavemansspa** [comment]
@tivac / @isiahmeadows this came up again on #2028

is adding a warning banner to the v0.2 branch's .md files the solution for flagging the old docs, or can we proxy those links somehow wrapped in a warning?

**Comment by cavemansspa** [comment]
How about something like: https://github.com/cavemansspa/mithril.js/blob/v0_2_x/docs/auto-redrawing.md?

Any idea how to change background and text colors in the warning message?

**Comment by tivac** [comment]
It needs some CSS changes in `style.css` for each archived version < 1.0.0, along with updates to all the `.html` files.

Those files aren't generated any more, they just live in https://github.com/MithrilJS/mithril.js/tree/gh-pages/archive and will need manual/tool-based updating of the HTML & CSS.

**Comment by cavemansspa** [comment]
😨 -- okay.  thought it was just a change to the v0_2_x branch.

**Comment by pygy** [comment]
@tivac there are ~1300 pages (~30 pages per release times ~45 pre-v1 tags), automation is needed here. Even checking that everything is alright will be herculean.

**Comment by isiahmeadows** [comment]
Here's my thought: append a script after each HTML file that's loaded from the root and that appends a collapsable `position: fixed` header, along with its relevant CSS, noting that these are old docs and where to find the most current version. This could be run on all archived HTML files, and then done to every new archive generated. Something like this:

```html
<!-- Appended before `/<\/body>\s*<\/html>$/` or at the end if it doesn't match -->
<script src="/notify-outdated.js"></script>
```

```js
// notify-outdated.js
;(function () {
var version = /^\/archive\/(v\d+\.\d+(\.\d+)?(-[\w\.]+)?)\//.exec(window.location.pathname)
if (version == null) return // In case this is added to what's currently live
var style = document.createElement("style")
style.innerHTML = `
#notify-outdated-container {
    width: 100%;
    background-color: yellow;
    color: black;
    /* Other CSS styles... */
}
#notify-outdated-container .notify-outdated-close {
    /* Style the close button */
}
/* Don't cover the headings when printing, but don't affect the layout on screens */
@media screen {
    #notify-outdated-container {
        position: fixed;
        top: 0; left: 0;
    }
}
`
var container = document.createElement("div")
container.id = "notify-outdated-container"
container.innerHTML = `
<button aria-label="Close" class="notify-outdated-close">×</button>
<p>
    This site includes the archived docs for Mithril ${version[1]}. If you're looking for the
    latest version, Mithril {{pkg.version}}, please click <a href="/">here</a>.
</p>
`)
container.firstChild.onclick = function () {
     container.display = "none"
     container.visibility = "hidden"
}
document.head.appendChild(style)
document.body.insertBefore(null, container)
})()
```

**Comment by tivac** [comment]
I'm about 90% of the way done w/ a version of this, not collapsible though because it's not so big that it prevents usage. Hilariusly large PR incoming in a few.
