### ISSUE TITLE
Defy ospec objective and allow custom reporter callback for o.run()

### ISSUE THREAD

**Issue by zyrolasting** [MithrilJS/mithril.js#2019]
PR at #2020

## Context
ospec declares that it disallows custom test reporters. I want to advocate for the opposite position.

I maintain several apps and SDKs that must provide unit tests, integration tests and functional tests. My deliverables are built either for Node.js or the browser, and tests may be bundled into the app itself. All of the tests for each should run with the same one command, returning a exit code equal to the number of failures.

Given this, I want programmatic access to `ospec` results that I may easily consume and deliver in a custom CI or test procedure. I don't want to parse what another reporter outputs to get this information, which is the consequence of black-boxing reporters.

## Current Behavior

The `report()` function in `ospec.js` [assumes STDOUT and STDERR are sufficient for reporting](https://github.com/MithrilJS/mithril.js/blob/next/ospec/ospec.js#L237), blocking all access to the results array. This forces consumers to run `ospec` as a child process and pipe its results to a stream that may parse results from a string.

But that's assuming you run tests in Node. If you run ospec tests in the browser, an entirely different approach is necessary to extract results.

## Possible Solution

Pass a custom, and optional reporter callback to `o.run()`. If the callback is not present, fall back to default behavior. The function accepts the test results array as its only parameter.

If you want details on how this would go, consider the following two cases where I run a bundled browser app and a bundled Node app. Note how the custom reporter exists to talk back to the test runner, which then translates that into an exit code.

# Browser app case

## Runner script

    const {Chrome} = require('navalia'); // headless Chrome
    const WebSocket = require('ws');

    const wss = new WebSocket.Server({ port: 6262 });
    const chrome = new Chrome();

    wss.on('connection', (ws) => {
        ws.on('message', (results) => {
            // Clean up
            chrome.done();

            const {appName, failures} = JSON.parse(results);
            const nfails = failures.length;

            if (nfails > 0) {
                console.error(`${appName}: ${nfails} failures`);

                for (const {message, stack} of failures) {
                    console.error(message);
                    console.error(stack);
                }
            }

            // Non-zero exit code will fail CI build.
            process.exit(nfails);
        });
    });

    await chrome.goto(`file://${__dirname}/dist/index.html`);

## In the test build's `index.html`

    o.run((results) => {
        const report = {
            appName: document.title,
            failures: results
                .filter(({pass}) => {
                    return !pass;
                })
                .map((result) => {
                    return {
                        context: result.context,
                        message: result.message,
                        stack: result.error.stack,
                    };
                });
        };

        const client = new WebSocket('ws://localhost:6262');

        client.send(JSON.stringify(report));
    });

# Node.js case

## Runner script

    const child_process = require('child_process');

    const handle = child_process.spawn('node', [`${__dirname}/dist/index.js`], {
        stdio: 'inherit', // So the results printed in index.js appear in this process' STDIO streams
    });

    handle.on('close', (code) => process.exit(code));

## In the test build's `index.js`

    o.run((results) => {
        const failures = results.filter(({pass}) => !pass);

        for (const {message, stack} of failures) {
            console.error(`${message}\n${stack}\n\n`);
        }

        process.exit(results.filter(({pass}) => !pass).length);
    });

## Anticipated discussion points

* **Should the results array be deeply copied before sent to the reporter function to protect data integrity?** I'm thinking no. If ospec gives me data that's not meant for modification and I modify it, that's on me.  
* **Should the results be passed as is, or in a different representation?**. Be aware that passing the results array as-is means that future changes to a test result object is a breaking change for reporters. If someone is concerned by someone knowing more internals, I'd argue I have to know internals to parse ospec's stdio streams anyway.

**Comment by pygy** [comment]
@zyrolasting: @tivac is working on that in one of his branches :-)

**Comment by zyrolasting** [comment]
@pygy: Fantastic! I'll reach out to him.

**Comment by tivac** [comment]
I'm very in favor of having a programmatic API for accessing results, there should be a sane default reporter (the current one) but if you want to build your own when using the API I see no issue with that.

Not convinced I'm going to finish my work on it though, the internals of `ospec` are just twisted enough that it's crossed my threshold for pain and I may just the delete the branch and wash my hands of it.

https://github.com/tivac/mithril.js/tree/ospec-timeouts is the current work I've completed, it's very messy but someone dedicated could surely pull out just the reporting-related changes into a worthwhile PR.

**Comment by zyrolasting** [comment]
@tivac I'll see if I can pull it through. Thank you.

**Comment by pygy** [comment]
Thanks for the PR @zyrolasting!
