### ISSUE TITLE
The recycling pool can leak memory in keyed mode.

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2023]
It has already been mentioned in https://github.com/MithrilJS/mithril.js/issues/1991#issuecomment-340107437 by  @starsolaris, and it is more obvious now that the pool-related logic has been made explicit in #2021: if your key space is not finite (using an increasing counter or random numbers as keys) the DOM node pools can leak memory. The nodes that are removed are added to the pool, then moved from pool to pool as they are never recycled.

The cleanest solution would probably be to disable the pool by default for keyed nodes, by setting `vnode.reuse = false` as per #1675.

Alternatively, we could document the potential leak and tell users to opt out of the pool if they know their key space is too big. I'd rather provide a safe default personally.

At last, we could peg the lengths of the pools, but that would entail array slices (if we want LRU eviction), and thus `O(N)` copies (even if slices are "copy on write", we do append to the pools).

@starsolaris, waiting for #1675 and explicit pool control, you can add a dummy `oncreate` or `onupdate` hook to the problem nodes. Mithril doesn't add vnodes whose DOM node may have been mutated by hand to the pool.

Edit: re. LRU, actually I got it the wrong way around. The most recent nodes are located at the begining of the pools so we could just stop adding nodes past a given length.

**Comment by leeoniya** [comment]
if pooling in Mithril is done solely for the purpose of resource optimization, you guys should re-evaluate the need for using pools at all. it may not provide the benefit it once did in newer JS engines and instead introduces harder problems like this one.

**Comment by pygy** [comment]
@leeoniya I think it is the case, though you'd have to ask @lhorie for a definitive answer.

**Comment by leeoniya** [comment]
from personal experience, the domvm v1 had vnode pooling which seemed to improve perf. after refactoring some internals (with changes beneficial for the GC) i found that removing it became a net win. i think many vdom libs have discovered the same. you can see what @lhorie had to say about it in https://github.com/MithrilJS/mithril.js/issues/1669#issuecomment-283774457
