### ISSUE TITLE
Add documentation for integrating 3rd party components / libs

### ISSUE THREAD

**Issue by cavemansspa** [MithrilJS/mithril.js#2039]
The question comes up on gitter periodically.  I don't see any docs in current website.  Old docs had [Integrating with Other Libraries](https://mithril.js.org/archive/v0.2.5/integration.html)

Happy to take a crack at putting a doc together for current site.

Please comment if you have any suggestions / best practices to include in doc.

[FullCalendar Example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHigjQGsACAJxigBeADog4xAJ6w4hGDGKjuhfmBEgSxAA5xEAel3UAJmgBWcfNSi0ArobBQM-C7Sy6MJjAA9d7AEZxdMGsoKGoMWDRDR10AZnwAdnwABkDg0PCmKN58LA4LODhRAD4QAF8KdGxcRAIzShp6RmYagDdHbgAxNIBhDMj2wW5gYTQR4WJ6an4MRkRuAAoWtFpDGABKbkEiobGFYjo0OFpYfCsAc3mAci6Q3qh+3kRESenGS7WR7i-vr4ASReWq3whhca3wQVufSy82GaB+8O++m4mmsxG4EhsvG4tE0xAg9Dg3AwkW4YRCvgw1E4hNk-E+CO4pQ+cMZFHpuxaEBgAHc5gCVutNttYeNxj9+MRrLw4VgroYIC13vSvqVuCNSmM0FgcjYGPMQdRrDgGPhfCsJBQdqNiJyeXylgKNlsrQy+PIpXDkMrXdxZZdCABGS6Wy53TKOd5slk+33zG5QMMPZmugC63o1aCZZQqIEwODw+QQVAOTWIeDKKao7C4CBQlXzNVyxGU0HqUvINQ02j0umsaE0nDOzlcTZbUAAAgH8FOAKy6Ue8aD4OpUSSaaogOrlesbrAuJhlqjtvBdnT6PsDod0Ef7hjjgBM04AnPh7-Pb8Rl0WQGuN1uc3mf4AI7WDAvASG2vAduoxBaGevb9oOw66CYIFgRI45xI+Aa6PK4goWh4FfvUv54P+O54BC6QRFkkHQaePYXkh16pCEZLhrwmEJMkuEQPhVHsQ8xGrhI65kQgpQpqUQA)

**Comment by pygy** [comment]
@cavemansspa That sounds like a great idea!

**Comment by isiahmeadows** [comment]
Closing per #2047
