### ISSUE TITLE
How to set body class?

### ISSUE THREAD

**Issue by millken** [MithrilJS/mithril.js#2044]
`<body class="page1">`

**Comment by isiahmeadows** [comment]
Is there a reason `body.classList.add("page1"); m.redraw()` wouldn't work?

Note that you can't modify attributes on the node you're rendering to via Mithril alone.

**Comment by StephanHoyer** [comment]
`m.redraw()` is not even required.
see [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvLfLSgV1oAoATS81nWvgBGlLgE8SAAmAAdNJMkA3CDADuiSRwCUkgLwA+SVg4ByABYBGE1PMwoUSpNWUATlC4mtcgL5e0cuBgaABUIHDYaDm09Qx4+ARphUTF8cigMODgAGQg4RIwuLg4ZEABzFxh6Eq0pACYABkatEG8SdGxcRAJyTJAyKlp6GjwRcXxyyvlZeUkhDHIAa3K2NC4NCaq0bxaAXTIoCDQFhBR2nEYIGjMXaD6QVjc8MxoaAAc4RAB6T-ZXpdTKFhPlhLtdoAABCz4KEANmBoJuUCIpBANDEr06IGIu28QA)

**Comment by millken** [comment]
this ok!
```
    view: function() {
        document.body.classList.add("layout-auth");
        return ....
```

**Comment by isiahmeadows** [comment]
@millken Try in [`oncreate`/`onupdate` instead](https://mithril.js.org/lifecycle-methods.html), to save yourself a lot of rendering perf:

```js
oncreate: function() {
    document.body.classList.add("layout-auth")
}
```
