### ISSUE TITLE
Turning `false` into empty text nodes can lead errors with keyed lists

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2046]
False values are turned into unkeyed text nodes, which can lead to [issues in keyed lists](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4AdNFnzSmymNIAUs+RUnIwGKHBiOsNoyGUQAbj6OwADWMAaIkgCMrACUALqxJmYWaFa29sSOzq7unt6+AUGSwCaSkmERkgBMjmWS9OoADsoYjDaxwOK0sPhQtADmBcSEEHCScIS06lDKkmjykpAWPrGsJnGJbBwgmDh4+NRwAjT0jMw8bPFUUBBoIQgonPs8WBAj0tCUIOrS5DwkYhNOCIAD0oPUaCaIQGh1oWFBbw+0AAAlF8OiAGyI96ET5QfD8b7EAxNbggImseKsIA):

## Current Behavior

```
const root = document.body
m.render(root, [false, m("div", {key: 1})])
m.render(root, [false, m("div", {
  key: 2, 
  onupdate(){console.log("this should not fire")}
})])
// logs "this should not fire"
```

## Possible Solution

turn `false` values into `nulls` that are gracefully handled in both keyed and unkeyed scenarios.

**Comment by pygy** [comment]
I couldn't find docs on this feature (searching the docs for `false` and `&&` didn't turn anything relevant.

**Comment by tivac** [comment]
Your solution seems fine, it'll go as part of `2.0` anyways so we'll just need to document it as part of the breaking changes.

**Comment by pygy** [comment]
The thing is, #2021 actually makes it worse since it changes the way keyed/unkeyed nodes are detected.

Up to now, isUnkeyed has been detected as 
```
		if (vnodes[i] != null && old[i] != null) {
			isUnkeyed = vnodes[i].key == null && old[i].key == null
			break
		}
```

The new logic is 

```
	if (old[start] != null) {
		isUnkeyed = old[start].key == null
		break
	}
	if (vnodes[start] != null) {
		isUnkeyed = vnodes[start].key == null
		break
	}
```

Which is more sensitive to the issue. It has the advantage of not going backwards, but it makes this bug worse.

Ideally, I'd like to tag children lists as tagged or untagged as soon as possible (in `createNodes`, unless the list is empty or full of `nulls`) and add a `vnode.children.keyed` boolean tag, and rely on that for diffing. 

But there is [this test](https://github.com/pygy/mithril.js/blob/f0cbbcf1fb4370f466c79477cdbaedb98ccee95f/render/tests/test-updateNodes.js#L977-L985) that seems to enshrine some kind of keyed => unkeyed transition. Not sure it we should honour it...

**Comment by isiahmeadows** [comment]
@pygy [Found the commit that introduced the behavior](https://github.com/MithrilJS/mithril.js/pull/1516). Just FYI.

**Comment by isiahmeadows** [comment]
@pygy What's the status on this?

**Comment by pygy** [comment]
IIRC it is fixed in `next`
