### ISSUE TITLE
NPM API key format changed recently

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2048]
@tivac I looked at the Travis npm release log (because of https://github.com/npm/registry/issues/249) This may be relevant for you:

```text
Preparing deploy
NPM version: 5.5.1
Authenticated with email npm@patcavit.com
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
```

(I eneded up posting this accidentally as https://github.com/npm/registry/issues/250, sorry for the confusion)

**Comment by tivac** [comment]
It's been saying that since we set things up, afaik we're using the correct key format but I haven't bothered to verify since deploys have been running fine.

**Comment by pygy** [comment]
:+1:
