### ISSUE TITLE
How to do redirection with m.route correctly?

### ISSUE THREAD

**Issue by ghost** [MithrilJS/mithril.js#2059]
For example I want my application to redirect automatically from `#!/c`  to `#!/b`.

At the first glance it works as expected by using `m.route.set` in the `view` method of a Component or in the `onmatch` method of a RouteResolver. Am I a using it as intended or are there other, more correct ways?

Here is my example code: 

```javascript
const menu = {
  view: function() {
    return m('nav', [
    	m('#', 'current route: ' + m.route.get()),
      m('a[href=/a]', {oncreate: m.route.link}, 'a'),
      m('a[href=/b]', {oncreate: m.route.link}, 'b'),
      m('a[href=/c]', {oncreate: m.route.link}, 'c'),
      m('a[href=/d]', {oncreate: m.route.link}, 'd')
    ])
  }
}

const a = {
  view: function() {
    return [
      m(menu),
      m('#', 'page: a')
    ];
  }
};

const b = {
  view: function() {
    return [
      m(menu),
      m('#', 'page: b')
    ];
  }
};

const redirectToBWithComponent = {
  view: function() {
    m.route.set('/b');
  }
};

const redirectToBWithRouteResolver = {
  onmatch: function() {
    m.route.set('/b');
  }
};


m.route(document.body, '/a', {
    '/a': a,
    '/b': b,
    '/c': redirectToBWithComponent,
    '/d': redirectToBWithRouteResolver
})
```
[There](https://jsfiddle.net/7Lgpjysh/12/) is a live version of it.

**Comment by cavemansspa** [comment]
@odzhychko -- a component's `view:` function needs to return a vnode (i.e. result of `m()` call).

in this snippet:
```
const redirectToBWithComponent = {
	view: function() {
  	m.route.set('/b');
  }
};
```

**Comment by barneycarroll** [comment]
For posterity, there is a distinction between the two: using `route.set` inside an `onmatch` means that route `/c` will never resolve and therefore not create a history entry - so it acts more like a server-side redirect. If the redirect happens in the view then that is a function of the route at `/c` which the user will get some flicker of. So redirecting in `onmatch` is more desirable!
