### ISSUE TITLE
m.mount no return value

### ISSUE THREAD

**Issue by yulei745** [MithrilJS/mithril.js#2068]
0.2.x version m.mount return value, 1.x m.mount no return value, how to do upgrade

**Comment by isiahmeadows** [comment]
@yulei745 Could you give more info on your specific case?

Note: `m.mount` accepts a component, and the [lifecycle](https://mithril.js.org/lifecycle-methods.html) does this, so you may be able to adapt accordingly:

- Call `m.mount` with component:
    - If an existing tree is mounted, call `m.mount(elem, null)`
    - Else, clear any existing children
    - Invoke component `oninit`
    - Invoke component `view`
    - Call `m.render` with its result
    - Invoke component `oncreate`
    - Return
- Call `m.redraw()` (or on implicit redraws):
    - Invoke component `onbeforeupdate`
    - Invoke component `view`
    - Call `m.render` with its result
    - Invoke component `onupdate`
    - Return
- Call `m.mount(elem, null)`:
    - Invoke component `onbeforeremove` if it exists
    - If necessary and if its result is a thenable, await its result, return, and execute the next steps in the `then` callback
    - Call `m.render` with no children
    - Invoke component `onremove`
    - If we didn't need to await, return

**Comment by yulei745** [comment]
@isiahmeadows 
look case
`
<div id="modal"></div>

<script type="text/javascript">

class ModalManager {
    oninit(vnode) {
         this.component = null;
     }
    oncreate(vnode) {
        this.dom = vnode.dom;
    }

    view(vnode) {
        return (
            <div className="ModalManager modal fade">
                 m(this.component);
            </div>
            );
    }

    show(component) {
       //use bootstrap modal
        this.component = component;
        $(this.dom).modal({'show': true});
    }
}

class loginmodal {
  view() {
     return '<div>loginmodal</div>'
  }
}

var modal = m.mount(document.getElementById('modal'), ModalManager);


modal.show(loginmodal);
</script>
`

**Comment by isiahmeadows** [comment]
Try something like this:

```js
let state

m.mount(document.getElementById("modal"), {
    view() { return m(ModalManager, {oninit(vnode) { state = vnode.state }}) },
})
```

The lifecycle methods are also available as attributes, and although it's not documented ([even though it should be](https://github.com/MithrilJS/mithril.js/issues/2070)), `vnode.state` points to your component's state.

**Comment by yulei745** [comment]
In other words, less state machine management, if there are many components, the state is not very managed.

**Comment by isiahmeadows** [comment]
@yulei745 If you're needing something that scales, your app will need a lot of refactoring. Also, note that v1 is a breaking upgrade, and accordingly, [we've compiled a migration guide to help you out](https://mithril.js.org/change-log.html#migrating-from-v02x), if you haven't read it already.

**Comment by yulei745** [comment]
Thank you, I probably know how to get it
