### ISSUE TITLE
Random `key` param does not recreate component inside RouteResolver

### ISSUE THREAD

**Issue by ACXgit** [MithrilJS/mithril.js#2071]
I have a tree of components like this: `m(Layout, m(A), m(B))` where I want to:

1. keep `Layout` and `A` fixed
2. recreate `B` on route change.

Point 1 is easily achieved with RouteResolver as in the [Wrapping a layout component](https://mithril.js.org/route.html#wrapping-a-layout-component) example.

## Expected Behavior
I was trying to achieve point 2 forcing a random `key` param on `B`, as I knew that a component with a random `key` param should always being recreated

## Current Behavior
`B` is not recreated across route changes

## Steps to Reproduce
[Example flem](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAikoHNOYAnVgLysIAE3o0IkPoIB8rABTAAOmlatqENBDZrEC4AGsYATwC+ASlmsmcSrHwdO80eMkRpAalYApAMoB5ADl8Fl5NTkljeSNjVgB+fRiLVj0AclTLL1T1LS0aDJIVNWoAVwAHEQw6FMSTZIE5GzsYBy5nMVo3Tx8A4NDwyOiTeNqzSzSM1iyc8sq6AqLWADd3AHc1Db15SwbWLHlUgAsAJlSSYQ6JKV5zQrQLFRUbNgAZDGNKErYhZVVlta2wHIh2gIl49HqcmQizU+yOAEYzqxUgAlT7VJFYfC8dEtHg0ba3GGsYlwkpQM7EtTIVIAekR5zppwAuvgsBgyvIcV8YLIqRs4VAIEj+Rs9gcMEjfmKZRtqORwVVeXosdy6A5NAY7rLZYdwWAZXo1TBtTq1KZzqKZcbTWaiX9ZfbHbbWE6NsTgaDwWhTcyVKZHmhnqxgABBc4AIVMglYaBg6wACjiAB5RYAWkOLfE1RQZmI7OSOHi8IbGcz+8toFSq3HyESUcglHC0fAAI0oImMjPpUsWdMRemlG29Yl4egAJHyHQL5G8Pl9zvtQ7dxRHzsBWDE9AARJX4NCUVbbVgWN0Wvu006D4kjvgTqey-Zz9GL+TL19rkObkw7vcHo+WKepoBvc5ggKYzJkEKaAGAgKDoNguCICAWDaHq0AgGQJS8FAeCHDQNBlHAiC0rSJRoGUBicPgVBYLSqE0OhUAAALwvgbEAGz0WhYRQEQpAgDQxhlEhIDEOBzKmEAA)

## Your Environment

* Version used: 1.1.6
* Browser Name and version: Firefox Nightly 59.0a1 (2018-01-08) (64 bit)
* Operating System and version (desktop or mobile): Windows 10

**Comment by ACXgit** [comment]
I've just came back on this with a fresh mind and I finally spotted the problem, which was my mistake. Here's the [updated and working flem](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAikoHNOYAnVgLysIAE3o0IkPoIB8rABTAAOmlatqENBDZrEC4AGsYATwC+ASlmsmcSrHwdO80eMkRpAalYApAMoB5ADl8Fl5NTkljeSNjVgB+fRiLVj0AclTLL1T1LS0aDJIVNWoAVwAHEQw6FMSTZIE5GzsYBy5nMVo3Tx8A4NDwyOiTeNqzSzSM1iyc8sq6AqLWADd3AHc1Db15SwbWLHlUgAsAJlSSYQ6JKV5zQrQLFRUbNgAZDGNKErYhZVVlta2wHIh2gIl49HqcmQizU+yOAEYzqxUgAlT7VJFYfC8dEtHg0ba3GGsYlwkpQM7EtTIVIAekR5zppwAuvgsBgyvIcV8YLIqRs4VAIEj+Rs9gcMEjfmKZRtqORwVVeXosdy6A5NAY7rLZYdwWAZXo1TBtTq1KZzqKZcbTWaiX9ZfbHbbWE6NsTgaDwWhTcyVKZHmhnqxgABBc4AIVMglYaBg6wACjiAB5RYAWkOLfE1RQZmI7OSOHi8IbGcz+8toFSq3HyESUcglHC0fAAI0oImMjPpUsWdMRemlG29Yl4egAJHyHQL5G8Pl9zvtwyHWDE0vWALRoSg0DfghUwJXZCyL+QR87AVcmPQAESV+G3q22rAsbotfdpp0HxJHfAnU9lfY53RU9l0vNdkU3bdd33RV5hfW5xXPFcILvdVH2fV9TQDe5zBAUxmTIIU0AMBAUHQbBcEQEAsG0PVoBAMgSl4KA8EOGgaDKOBEFpWkSjQMoDE4fAqCwWlaJoeioAAAXhfA5IANnEuiwigIhSBAGhjDKKiQGIfDmVMIA).

The problem was that _[An array of vnodes must have only keyed vnodes or non-keyed vnodes, but not both](https://mithril.js.org/keys.html#avoid-mixing-keyed-and-non-keyed-vnodes-in-the-same-array)_, so adding a fixed `key` to component `A` brings back the desired behaviour. Well... RTFM :)

**Comment by tivac** [comment]
I wonder if there could be a louder error  around that particular requirement, it's way more subtle than I'd like.

**Comment by barneycarroll** [comment]
Do we have a canonical description of why this is an insoluble problem? I'm pretty sure there are problem cases involving keyed objects moving amongst variable length lists that present hard problems where it's impossible for the vnode reconciler to determine intended behaviour — but this certainly isn't it.

React goes a step further than Mithril and warns against any non-keyed elements in a programmatically generated sequence of children, but in that case it's obviously obnoxious because as we all know, in the absence of explicit keys you implicitly use index. Can't we mix and match to produce intuitive behaviour, and just throw at the times where it's deterministically impossible to determine intent?

**Comment by isiahmeadows** [comment]
As I mentioned in the Gitter channel:

> Yeah...that would be a nice invariant to check in the normalization routine...
