### ISSUE TITLE
`m.route.link` should also double as a component

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2072]
**Edit:** Better API

**Edit 2:** Strike a part that has 0% chance of making it, per #2219.

This came up previously as a feature request (maybe a few months after v1 was released), but I can't remember where.

Basically, it'd be a little more ergonomic to use `m.route.link` as a component rather than with all sorts of attributes. Here's my basic API idea, to maybe get the ball rolling:

- `m(m.route.link, {...opts, tag = "a", attrs = {}}, ...children)`
    - `tag` is an optional element tag name, defaulting to `a`.
    - `attrs` includes various lifecycle methods, attr names, etc.
    - You can use standard lifecycle hooks to access the underlying element, since it's the same vnode passed to and consumed by the component.
    - For practical reasons, it's a closure component.

- ~~`m.stripMagic(attrs, ...extras)`~~
    - ~~Basically, pulling a modified version of [this](https://github.com/isiahmeadows/mithril-helpers/blob/master/docs/censor.md) into core because it'll be needed for the component anyways (for reasons documented in that link), and it's a common need.~~
    - ~~Maybe, it might pave the way for handling some of it in the vnode normalization code? (ref: #1986)~~
    - ~~Better names for this might be nice. (I've already gone through several just trying to think of something presentable.)~~

**Comment by isiahmeadows** [comment]
It'd be really nice if this somehow made it to v2, BTW.

**Comment by CreaturesInUnitards** [comment]
@isiahmeadows 
by "also double as...", do you mean to keep the existing behavior, alongside this component flavor?
