### ISSUE TITLE
Mithril scanned as Trojan/Generic.ASVCS3S.3FA

### ISSUE THREAD

**Issue by rebootcode** [MithrilJS/mithril.js#2076]
It sounds weird but files inside "mithril.js" is considered as trojan.

VirusTotal URL - https://www.virustotal.com/#/file/d7d810b95725ca20774614866cff1dca438552f9a3960f298c88b6f99f9ffaa3/detection

**Comment by isiahmeadows** [comment]
@rebootcode That would be a bug in the one antivirus that "detected" it. Every other AV that was run over the file according to that URL didn't see a thing.

**Comment by pygy** [comment]
Thanks for the report @rebootcode.

That's most probably a false positive indeed (we'd have noticed if anything nasty had cropped up in the source). Ironically, here's the Anity contact page:

![screen shot 2018-01-22 at 20 32 32](https://user-images.githubusercontent.com/54515/35249828-de7259e8-ffd3-11e7-9fe3-565fb71542f0.png)

So I sent a message to VirtusTotal instead.
