### ISSUE TITLE
Howto force oninit with m("a[href=/]", {oncreate: m.route.link})

### ISSUE THREAD

**Issue by pericazivkovic** [MithrilJS/mithril.js#2078]
I have forced oninit with key usage in routing like described here (https://mithril.js.org/route.html#key-parameter). I would like to have same behaviour for href links that use `oncreate:m.route.link`.

How can I specify `{state: {key: Date.now()}}` for hrefs ?

**Comment by tivac** [comment]
I think you want to update them like this:

```js
m("a", { href : "...", oncreate : m.route.link, onupdate: m.route.link }, "...")
```

That should ensure that even after being changed they'll always be handled by Mithril. Not 100% sure that's what you're asking for though, can you provide some more context if that answer doesn't help?

**Comment by pericazivkovic** [comment]
if I'm on page `http://base-url/#!/todo/1` I would like to triger component `oninit` function when the clicks a link (on the same page) that points to http://base-url/#!/todo/2. At the moment only `onupdate` is triggered which I can not use due to some other reasons.

Like mentioned in https://mithril.js.org/route.html#key-parameter, this can be accomplished by using key that has `{state: {key: Date.now()}}` without polluting the URL. This works if called from JS function quite nicely. 

Question is: how can I set `{state: {key: Date.now()}}` for href links that are created with `oncreate:m.route.link` so that component `oninit` is executed after click on that link (your suggestion does not help here).

**Comment by tivac** [comment]
Oh gotcha.

For that you can name the route parameter `key`.

`/todo/:key` will force the `oncreate` to trigger when you change the active `todo`.

**Comment by pericazivkovic** [comment]
Thanks, that works indeed
