### ISSUE TITLE
`m.request` throws empty an error when connection is lost

### ISSUE THREAD

**Issue by samuelgozi** [MithrilJS/mithril.js#2079]
m.request returns an empty error when making a request while the user is disconnected from the internet. By empty I mean, that it doesn't have any properties. as if its an empty Object`{}`.

## Expected Behavior
Im not sure what is the right error to display, but any error would be better than an empty error.

## Current Behavior
Throws an empty error.

## Possible Solution
Im currently checking `navigator.onLine` when an error is thrown, but there probably is a better solution.

## Steps to Reproduce (for bugs)
1. Turn of the internet connection.
2. Run any `m.request()`.
3. Try to `console.log()` the error.
4. You should be seeing an empty error.

There is a code example in the bottom.

## Context
Im building an offline first application, and there are some forms that the user can submit even offline.
Im trying to figure out if the request error is due to a server error, or a connection erro in order to show a helpful error to the user.

# Your Environment
* Version used: 1.1.6
* Browser Name and version: Chrome 63.0
* Operating System and version (desktop or mobile): MacOS High Sierra
* Link to your project: Its offline but you can replicate it by using this code:
```javascript
m.request('https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC,USD,EUR')
	.then(response => {
	  console.log(response);
  })
	.catch(error => {
  	// console.log(error);
    
    // To see the properties of the error
    console.log(JSON.stringify(error));
  });
```

**Comment by isiahmeadows** [comment]
@samuelgozi What does a raw XHR do? Also, is there any way to detect whether it's rejected due to being offline (as opposed to a network timeout or something)?

**Comment by samuelgozi** [comment]
@isiahmeadows There might be a better way, but from my testing, adding a listener to the `error` event on the request object, and looking at the `event.target` it returns, if the status of that request is `0` then I think its safe to assume that there is a connection error. Since the request is on status "unsent" and an error was thrown.

**Comment by isiahmeadows** [comment]
@samuelgozi We now pass the raw status code via `err.code` and raw response text via `err.response` in the rejected exception. You can now detect this via `err.code === 0` as applicable.
