### ISSUE TITLE
[suggestion] Add support for trusting bits of SVG (IE10+)

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2096]
From a Gitter conversation: we could support trusted SVG strings by leveraging the DOMParser API (whose `parseFromString()` method is supported by IE 10+).

Something like this would go a long way:

```JS
const parser = new DOMParser()
const nodes = parser.parseFromString(
  "<svg xmlns=\"http://www.w3.org/2000/svg\">" + src + "</svg>", 
  "image/svg+xml"
).firstChild.childNodes
// append the nodes
```

[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J44AJ2oACALxSABgB5GAD2JSw9YgFow2aAE8ZAHRABBcRAxQpAOQzjxtAO6mNW7XAgAvGCZAATADs+ABsblAQaDDahDAQAOYk-gAsbpoM2s7xScT+AEa0UAAmpgB8xmhSUspwAA4YVSr+AMxBbkamAQCsbqo6jdSEtOL+cMQOxG7WiWg4DPkYcDCR0f5YEMXFsOUAKgZ1MIhSAEoAsgBiF1ItAAwAmlIA9FKhd1IAygAyFJ9PtscAIwALQAwgARQEBFopbqhIIADkUT2I9UaFSqNVRDSarXaICknRAoVufRgam0g2Go1M40m00iCTmIkWy1WflMGy2OxAGOq1QAqpV+Vi0VVxgZYAUlisojE4IQIGBiIg4ABXfLlLDI7Ho4X8453ADWADVfoAkwH11VqOKkEqlplZsuinkVytVGvKaB1Yr5BqkgNC+BC+Hw3VuAAlvL8AJJW0W2+0ckBO9mupUq9Wa3knH04v3VIGA263Mz6vN670o8nEMrySqVITjKQNcTLcSyKTRZxScEAeTOAAUHO2ABQASkb9GbxHEMBgndb7fwS5gFycWA+s6iCVHpkUcAAbgkpCoyGg4CZjKYSMQ6ognk9nM-8M4WvgRgkngES7cnkeEmvco3AAajtSQpDA-d-2PCpKGqUwICwDAEhgGCEhAs8oFMSc0EqLB8DnNBihgcRR2KWhqDVeZiHwQpigMX4sD3EAAOQZxNmIQgZBJW4AF1TF+YB6GoOcMEYUdgAorBWHHYB9Wk-AMDqQ5iNBRUSlHWd53wSA22IdToGKXSIH0wySlw1hZPHSgaFoLA6mgUi8EWfIVjYDgQEwHA8Hwag4AEOzhGYHg2D4qhViNBAUE4HyeA2LjLHIKg1XEcgeFvOo4AfJ41TQOojQSPz7KeBLCCSgABQF8Gq0JSogRLoHwfhbOIA5uBAFrWD41ggA)

**Comment by isiahmeadows** [comment]
Closing per #2097 (somehow, this fell through the cracks...)

**Comment by pygy** [comment]
Thanks! I forgot to cross-reference this.
