### ISSUE TITLE
No whitespace between inline elements

### ISSUE THREAD

**Issue by pockata** [MithrilJS/mithril.js#2108]
## Expected Behavior

When Mithril renders a component with two `span` elements (it can be any element with `display: inline/inline-block`) the generated code should be equal to writing the two inline elements on multiple lines.  

This example should clear things up a bit:
```js
m("div", [
    m("span", "left"),
    m("span", "right")
]);
```

Should generate
```html
<div>
<span>left</span>
<span>right</span>
</div>
```
which should render as
```
left right
```
but it doesn't.

## Current Behavior

The generated output is
```html
<div><span>left></span><span>right</span></div>
```
which renders as
```
leftright
```
## Possible Solution

A workaround is adding an empty span element or a space character at the end of the first string.
```js
m("div", [
    m("span", "left"),
    m("span", ""),
    m("span", "right")
]);

// or

m("div", [
    m("span", "left "),
    m("span", "right")
]);
```

For a JSX-styled code, you can add a `&nbsp;` between the two tags.
```jsx
<span>left</span>
&nbsp;
<span>right</span>
``` 

## Steps to Reproduce (for bugs)

Here is a link to a [pen](https://codepen.io/pockata/pen/LdWyVp) showing both scenarios side by side.

## Context

I was trying to use this method for creating even spacing between inline elements;
https://codepen.io/absolutholz/post/evenly-spacing-elements-with-text-align-justify

## Your Environment

* Version used: 1.1.6
* Browser Name and version: Firefox 61 (Nightly), Chromium 65 
* Operating System and version (desktop or mobile): Arch Linux

**Comment by spacejack** [comment]
This is intentional, otherwise you wouldn't be able to omit unwanted whitespace fragments. Here are a couple of shorter ways to add it when desired.

Hyperscript:

```javascript
m("div", [
    m("span", "left"),
    " ",
    m("span", "right")
]);
```

JSX:

```jsx
<span>left</span>
{" "}
<span>right</span>
```

**Comment by pygy** [comment]
@spacejack  is correct, this is by design.

**Comment by pockata** [comment]
@spacejack @pygy Thanks for explaining, it's a reasonable approach.  

I would like to advocate for adding a note about this in the API section for hyperscript because the behavior is not immediately obvious. I'm not willing to say how much time I spent trying to figure out what's wrong with my CSS.  

If you're interested in a PR about this, I could prepare a one over the weekend.

**Comment by tivac** [comment]
@pockata always interested in a PR to flesh out thin parts of the docs!
