### ISSUE TITLE
mithril x jsx configuration update.

### ISSUE THREAD

**Issue by spankie** [MithrilJS/mithril.js#2109]
## Current Behavior
setting up a mithril app with jsx throws errors when using webpack v4.2.0 with the configuration instructinos @ https://mithril.js.org/jsx.html
webpack v4.2.0 configuration is different from that of v3.10.0 which is the last version i know works well with the configuration instruction.

## Context
setting up a mithril app with jsx throws errors when using webpack v4.2.0

**Comment by vasilrimar** [comment]
@tivac Simple fix here #2110.

**Comment by tivac** [comment]
@vasilrimar Thanks!
