### ISSUE TITLE
Setting textarea content as content (instead of value) does not work in Edge/IE

### ISSUE THREAD

**Issue by bit-less** [MithrilJS/mithril.js#2123]
Setting textarea content as content, instead of setting it as the value, doesn't render the content in Edge or IE11.

## Expected Behavior
Expect textarea content to exist on Edge/IE when set as content instead of value.

## Current Behavior
No content is injected into the textarea as verified in the DOM.

## Steps to Reproduce (for bugs)
`m.mount(document.getElementById('a'), { view: function() { return m('textarea', 'hello') } });`
`m.mount(document.getElementById('b'), { view: function() { return m('textarea', { value: 'world' }) } });`
See also: [https://codepen.io/anon/pen/qoeYRp](https://codepen.io/anon/pen/qoeYRp)

## Context
The workaround is to set content via the value property; but, since it's a content accepting element natively, it should work on all browsers as content.

## Your Environment
* Version used: 1.1.6
* Browser Name and version: Edge/IE
* Operating System and version (desktop or mobile): Windows 10 Pro desktop.

**Comment by pygy** [comment]
Could you test [this sample](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5iAD2IACALxSAJrWoBXHA3zUATjAyMAorDXEAFAB0QjSRm0ZzASlNpFKo-gBGteQE98GAA5+TPIAwoTQ8sYSxA5oQowMsgpKqiIaNowAKjCSAHKeMGbgtLT2jlG+AUGh4cZxInaUIHAwsNTEEPQIPADMiABM3WwcIJg4eBpwAjT08aI8bAC6rEA) in IE/Edge?

Does the "foo" text appear in the textarea?

It is in essence what happens when Mithril renders your example.

**Comment by bit-less** [comment]
Yes, that works.  Similarly, I could do: `var ta = document.createElement('textarea'); ta.textContent = 'Hello'; document.body.appendChild(ta);` and that works in Edge and IE.

**Comment by bit-less** [comment]
That works too.

**Comment by pygy** [comment]
Thanks... Not time to dig in further right now. This isn't critical since there's an easy workaround, but it would be nice to figure out why this happens and then fix it.

**Comment by bit-less** [comment]
Agreed. At least we have something out documenting it now. Thanks.

**Comment by barneycarroll** [comment]
This [issue doesn't materialise in Edge anymore](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE5MAJjAkAKabWoBXHA3wAjWtICeFAATIAOmgMGs8gOSMAHsQxSMVw1cIwoUWlYCUFU+aWNjD2jjDOhsAGAG4YUCowiAZWAO60ElDSVgasfqYAuj6UIHAeMNTEEPQIPADMiABMbBwgmDh4+NRwAjT0jMw8bPlUUBBoANY1qK1cYhDEhBLQ+PzFKhl4JMQADnCIAPT7Kmjb4wDmnbRY+1jzi9AAAg34AAz4ACw3d0tQKz3Eum23BK1CW21ErHyrCAA)
