### ISSUE TITLE
Preserve Component State Independent of Location

### ISSUE THREAD

**Issue by yossicadaner** [MithrilJS/mithril.js#2135]
BS"D

Is it possible to preserve a component's state even it gets moved to another listing of children?
Say I have 
 - Left Sidebar
    - Chat
and I move Chat to Right Sidebar
 - Right Sidebar
    - Chat

I know I could technically store and reload the state values, but it is possible to do this in another way, say by just providing a common `key`?

**Comment by spacejack** [comment]
@yossicadaner I don't believe you can, at least not without an undesirable amount of hackery.

You can preserve the component instance if it moves within a list of siblings (in an array, using keys) but I don't think you can if it moves arbitrarily across the dom tree.

I think your best bet is to externalize its state.

**Comment by pygy** [comment]
What you are trying to achieve is not supported. It could be achieved for a fixed version of Mithril, using a unholy amount of hackery, but any such hack could be broken by a Mithril point release that tweaks the diff/patch algo. So I wouldn't recommend it, at all.

As @spacejack suggested, you can achieve what you want by externalizing your state to a common object or stream.

```JS
const chatState = {
   log: [],
   currentDraft: "",
   cursorPosition: 0
}

const Chat = {
    view: () => m(".chat", 
        chatState.log.map(msg => m(".", msg.author, ": ", msg.text)),
        m("input", {
            oninput() {
                // save the current draft and cursor position
                // submit on "enter"
            },
            oncreate(vnode) {
                // set the cursor position
            }
     )
}
```

**Comment by yossicadaner** [comment]
> It could be achieved for a fixed version of Mithril, using a unholy amount of hackery, but any such hack could be broken by a Mithril point release that tweaks the diff/patch algo. So I wouldn't recommend it, at all.

Possibly there are simpler methods of doing this. For example, if mithril provided control over initializing the `.dom` attribute/ the dom node or from an existing vnode?

**Comment by pygy** [comment]
In order to do that, we'd have to provide expose the nextSibling (and optionally the parent node, but that can be obtained from client code already by passing it as an attr)...

It may be something we'll do at some point (rather than `domSize`), in order to get rid of fragments (DOM fragments, used under the hood, not `m.fragment()` vnodes).

I don't want to commit to it though, or to ensuring that patterns that rely on it keep on working when we update the diff code.

**Comment by leeoniya** [comment]
some food for thought...

domvm achieves this by offering imperative component instantiation via `createView()` and allowing these component instances to be injected into any other domvm tree via `injectView()` vnodes. this way it does not have to track keys globally.

https://jsfiddle.net/phtd6vqb/

**Comment by pygy** [comment]
@leeoniya That's neat! I'll have to dig into domvm at some point.

I've tried to have it move back and forth between the "left" and "right" panes, and it starts in the top one, then blinks below... Am I doing something wrong?

https://jsfiddle.net/dvkm3qzm/

**Comment by leeoniya** [comment]
heh, no it should work, time to dig! :D

**Comment by leeoniya** [comment]
fixed!

**Comment by barneycarroll** [comment]
Mithril Machine Tools has a mechanism for this via the [`Mobile > Unit`](https://github.com/barneycarroll/mithril-machine-tools#mobile) composite component. The `Mobile` component has a view which exposes the `Unit` component: `Unit` components identified with the same `key` attribute can be rendered anywhere within their `Mobile` context and retain state and DOM.

[Here's an example of the 'mobile' chat box.](https://flems.io/#0=N4IgtglgJlA2CmIBcA2ALAOgEwHYA0IAZhAgM7IDaoAdgIZiJIgYBW5BAxgPbUAu8fZCAhgADlwBOvAATAAslwBGJeAF9phCVzDSA5JF4ALCSQC0YWh0MRq8U7y5dYpXQB1q7hDMu8IAN3gAZVguGQBePQRCXjcPajAMMC4AVz4ACiguDmSGPgxFLigATzxZd2lpPwh4AHckaTSASmkwgD5pCnKK6TA03VhaRXhYXTwu7r0AYUNaGXFSCF8eJFHx7t7dUmH4DhjS4DWJv1pYZPh6n38gkN4x6gmJnitaagBzeDT4RoP7h4nLgLBUItaTwDC8WgSd68DDHU7wQ7dVSI1R3P4VCj9eDRUZ6DgCXgSeC43QmV6GGIAXUStFEaQAHi12hsuKIltRcfTGo1EY00d0+Ws1hsoP5ccBSLwigh6gADRGi0iiAZFeqvExQADciPV0Hs8DEA349VcICiMnxfCJ0jJFNN2t+EwsUJs9QAjAbpAAGB0TWWooWO9ZpBTKBClACq1EWTMRGKxONKukthOJSdtVJpdLSpBupRsUHgXKZ0jjwd0or84sl0vO0nlQfR0gKEkLEndokZpCc0F9Te6uqgpm4pzA1HqABJgNJc8DVH2m-67mWnX1DFgKDWEGF+PTeKYThBXuOU-AJJTcbPeIK4v3up1G-2ry0whEAddgSvugAyb89NJRos+wANbwKqeIzDEAaPneIpivsW51g2d5Ni2bYdl2PZal+TaiLQMA2K87oGguKFOpCryutIHpgKRZGyvyZGPNQHBErMHzfDh-bcNQ3YIBgISvH0rHwOxUAAIS6DyMEodBTEPDwySiFA7FND88l-DxfFgoJfRKSp-ASVJXF-HJGnQSZDwbIYADMJLTLMkk3pZq66LuEJsRQWg1KQYRoBeSYKAEPTwNIyQLG80hGKFUBaMpXA1PcgxcAETmMUxN7ydJZGUulfyZeiBUTEV0gFZS7iqI0IAEFsCC7BAPDkEwWAAJxIG6NkgKouVmjYwFNVQIB0AwQgGMYJCsOwIDJBIsBCBSvCiKQSAAPQrakojAa8GDcGAK1jSYsAAAJYBgXoYGg+2LONsCTdVIBSqIjAgKQrEQGyXWUqoQA)
