### ISSUE TITLE
Does ospec have its own CHANGELOG.md?

### ISSUE THREAD

**Issue by maranomynet** [MithrilJS/mithril.js#2138]
I was looking for version info about `ospec` and noticed that it doesn't seem to have a proper change log of its own.
..or am I missing something?

**Comment by pygy** [comment]
Nope, but it should have one.

If you want to do it, you can grab some bits in the main changelog (see https://github.com/MithrilJS/mithril.js/blob/next/docs/change-log.md#ospec-improvements for a start, there are other ospec mentions in previous Mithril releases, but they are not tied to specific ospec releases... they could be pooled into a `pre-v1.4 improvements`, unless you feel like tracking the exact version numbers).

**Comment by maranomynet** [comment]
Sure.
I may have some free time later today.

**Comment by pygy** [comment]
Great! you can add it as `ospec/change-log.md`, in #2137

**Comment by maranomynet** [comment]
I did as much as I reasonably could.  Someone in the know must take care of the rest.

**Comment by maranomynet** [comment]
Adding this in such an obviously half-baked state to 2137 just messes things up, so I reverted those commits and put them in a standalone pull-request #2139

**Comment by pygy** [comment]
It would have been good in #2137 as well, I don't think anyone cares about the details of pre v1.4 history :-)

Thanks again for the PR1
