### ISSUE TITLE
Losing input events

### ISSUE THREAD

**Issue by purcell** [MithrilJS/mithril.js#214]
I have a mithril component with a big list of stuff which gets filtered `onkeyup` as the user types into a search field.

The filtering is pretty slow, but what concerns me is that some key events get dropped as the user types. It seems like events disappear while the view is getting recomputed. Is this behaviour expected, and if so, is there an idiomatic workaround I'm missing?

You can try it out live [here](http://melpa.milkbox.net/).

The relevant snippet is this:

``` js
m("input.form-control[type=search]", {placeholder: "Enter filter terms", autofocus: true,
                                 value: ctrl.filterTerms(), onkeyup: m.withAttr("value", ctrl.filterTerms)}),
```

and the full code for the component is [here](https://github.com/milkypostman/melpa/blob/master/html/js/melpa.js#L178).

Cheers, and thanks again for mithril!

**Comment by naveennagan** [comment]
let m = require("mithril");

let keymap = {
  "13": "enter"
};

let keys = {
  onKey: function (keyVal, callback) {
    return function (e) {
      e.redraw = false;
      var key = e.keyCode + "";
      var keyInput = keymap[key];
      if (keyInput && keyInput === keyVal) {
        setTimeout(function () {
          m.redraw();
          callback();
        }, 0);
      }
    };
  }
};

module.exports = keys;

**Comment by isiahmeadows** [comment]
@naveennagan Could you file a new issue explaining what went wrong?

**Comment by naveennagan** [comment]
@isiahmeadows  i was just giving a solution for losing input events. 
My approach was to pause redraw for sometime and then upon capturing enter key, push the callback to event loop(in timeout ) and then trigger the callback.

**Comment by isiahmeadows** [comment]
Oh okay. Note that this bug was filed for 0.2.x, and we're on v1.1 now.
