### ISSUE TITLE
[ospec] Testing thrown exceptions

### ISSUE THREAD

**Issue by maranomynet** [MithrilJS/mithril.js#2146]
Hi. What would be the idiomatic pattern for ensuring errors are thrown?

Here's what I'm using right now, but it feels clunky:

```js
try {
    doSomethingAwful()
    o(true).equals(false) // <-- the clunky bit
}
catch (e) {
    o(e.message).equals('WAT')
}
```

**Comment by pygy** [comment]
Generally I do

```JS
var threw = false
try {
  crashHere()
catch (e) {
  threw = true
}
o(threw).equals(true)
```

Not sure it is less clunky. You could replace your clunky line with `o("this assertion ran").equals(false)`, which will output `"this assertion ran" should equal false`.

**Comment by maranomynet** [comment]
Yes, I guess this could work.
```js
let error
try {
    doSomethingAwful()
}
catch (e) {
    error = e
}
o(e && e.message).equals('WAT')
```

But I like the "this assertion ran" idea, which makes me think that something like this could be used generally:

```js
o.fail = (descr) => {
    const f = o('A o.fail() running').equals('failed test')
    if (descr != null) {
        f(descr)
    }
}
```

```js
try {
    doSomethingAwful()
    o.fail() // <-- less clunky
}
catch (e) {
    o(e.message).equals('WAT')
}
```

**Comment by RobertAKARobin** [comment]
Addressed by https://github.com/MithrilJS/mithril.js/pull/2255?

**Comment by isiahmeadows** [comment]
@RobertAKARobin I updated #2255 to close this bug once it's merged.
