### ISSUE TITLE
Streams `toString` / `valueOf` behaviour clashes with DOM diff early exit

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2150]
Thanks @cmnstmntmn for discovering this: streams semi-automatic string coercion behaviour conflicts with virtual DOM diffing algo, which will skip diffing a stream reference in place of a VDOM node. [Here's an example: interpolating `value` without explicitly invoking it will ensure the text node forever stays at the initial value](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgDcMoBXGVgXlZZ8LAE4xsACgCMASgA6aRcKyVutSQBNK5bjlr4ARpU0BPEq2CLWratwAOmjHUStJsgQD5L1m63uSAOQASjCaohgA7q4ABpw8MDGsEHCsuqLitFCmroGsANQcXLwKaDYAviS+vuwQMNFuHvzevjZYQYbcNDTUgRZWZX421ORQEOQA1q7uXj6DQzbxvJJLMDOFcq1+5VuVrFuLxTBbpeWyIGRwMLDkNBDUCIggACyIzwBsIOUAumRjaBNHqgQJgcHgsBAaAALUTQC4gbiiKB4KHdexwRAAekx6nsEwA5vgqFhMRDobCoAABaT4GnvUmQmHQIikEA0Uz2XBPODkWH2GhfEjobBckBkplQAC0YgkWHhiORT1RNHRWJxaDxhOJDPJ0GlNHE2GptPwAAZMTLsCz4ezOXgeXyBT9ykA).

[It was my idea to give streams `toString` behaviour, and in hindsight I think it was a terrible mistake](https://github.com/MithrilJS/mithril.js/pull/1148): the effort saved through avoiding those parentheses unleashes a world of ambiguity. I had already convinced myself the original idea was conceptually bad in [#2050](https://github.com/MithrilJS/mithril.js/issues/2050#issuecomment-379964822), but this points to a problem caused by opinionated tolerance in many places - vnode normalisation should also be fixed to cater for the other end of this issue.

**Comment by pygy** [comment]
Oooh yeah, let's ditch that!

**Comment by spacejack** [comment]
Yeah I got burned similarly today. I had changed a boolean var into a stream, and in my view I had:

    isCondition ? m('.foo) : m('.bar')

It's especially hazardous when refactoring things into streams. And Typescript can't do much with `valueOf` either so it won't help out.
