### ISSUE TITLE
ospec: make bin work for old node version

### ISSUE THREAD

**Issue by futurist** [MithrilJS/mithril.js#2160]
## Expected Behavior

Ospec command line should work with old node version, like 0.12

## Current Behavior

```bash
$ nvm use 0.12
$ ./node_modules/.bin/ospec
```

It will throw

```
const o = require("../ospec")
^^^^^
SyntaxError: Use of const in strict mode.
```

It's totally ES6, which is not work in old node.

## Possible Solution

Transpile the ES6 to ES5.

## Your Environment

* Version used: node 0.12
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pygy** [comment]
@futurist as much as I care about ES5 compat for Mithril itself, I'm not sure it is worth it to pursue backwards compat on the Node side.

For legacy projects, you can keep on using legacy `ospec`, and for greenfield projects, I can't see why you'd want to use a pre v4 Node... Are you using nvm in your test suite? For Travis?

See [ES6 support per version](https://node.green/) and [Node download stats per version](https://nodejs.org/metrics/summaries/version.png).

**Comment by pygy** [comment]
I think that @futurist wants to run the test suite in an ES5-only environment.

If we ever introduce a transpiling step let it be for TypeScript in strict mode (no implicit any), not  for the basic features we're using here (`const`, `let` and arrow functions, but only for readability, we don't even rely on the lexical scoping of `this` and `let` bindings).

So I'm not against going back to ES5 in `ospec/bin/ospec.js`.

**Comment by futurist** [comment]
thanks! can you publish a version to npm?

**Comment by pygy** [comment]
@futurist `ospec@2.1.0` is out
