### ISSUE TITLE
Ospec mangles context in async report logs, times out with 'elapsed' figures < specified timeouts

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2162]
I've been using #2159 to run tests for my infamous Island component - I need it in large part to avoid #2194 - and I've discovered further horrors in async tests, which can be glimpsed from this screenshot:
![2018-05-24](https://user-images.githubusercontent.com/83627/40501480-e4bc0d10-5f7f-11e8-94c4-7908f4c9a03d.png)

Notice:
* `async test timed out` from the last failure presumably corresponds to the in-media-res log of `# elapsed: 31ms, expected under 40ms` - but 31ms *is* under 40ms...?!
* The first failure reads ``Island > `first` flag: is `true` during local order draws`` - but the assertion (``is `true` during local order draws``) doesn't belong to that test (```first` flag``). 

[The tests are here](https://github.com/barneycarroll/cascading-components/tree/master/src/packages/Island/tests), and will only run in a browser environment served via HTTP with the project root as base URL (ESM dependency, innit).

This is really grim stuff 😟

**Comment by pygy** [comment]
@barneycarroll I get the following error after running `npm start` and loading `Island/tests/index.html`:

```
(node:26602) ExperimentalWarning: The fs.promises API is experimental
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
{ SyntaxError: unknown: Unexpected token, expected { (17:6)
  15 | };
  16 | const frames = (n = 1) => n && new Promise(window.requestAnimationFrame).then(() => frames(n - 1));
> 17 | import('../index.mjs').then(({ default: Island }) => {
     |       ^
  18 |     o.spec('Island', () => {
  19 |         o.beforeEach(() => {
  20 |             document.body.replaceWith(document.createElement('body'));
    at Parser.pp$5.raise (/Users/pygy/src/cascading-components/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/pygy/src/cascading-components/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/Users/pygy/src/cascading-components/node_modules/babylon/lib/index.js:1749:33)
...snip...```

Node v10.1.0, babylon 6.18.0.

**Comment by pygy** [comment]
Here's how... What Node version are you using?

```
$ npm ls babylon
cascading-components@0.0.2 /Users/pygy/src/cascading-components
└─┬ zwitterion@0.27.0
  └─┬ babel-core@6.26.0
    ├─┬ babel-template@6.26.0
    │ └── babylon@6.18.0  deduped
    ├─┬ babel-traverse@6.26.0
    │ └── babylon@6.18.0  deduped
    └── babylon@6.18.0
```

**Comment by barneycarroll** [comment]
Oh God, sorry. Zwitterion is a mess. I have been doing monorepo by hand and it's a disaster (Zwitterion was meant to be the "don't make me think" approach to serving browser-ready ESM, but cross cutting concerns make that unreachable for the time being).

Running a simple `http-server` from root is the way to do this ATM.

**Comment by pygy** [comment]
@barneycarroll The `# elapsed: 31ms, expected under 40ms` message is actually coming from the ``` `local` flag ``` test, because `done()` is being called twice (as is the `onupdate` hook) and the `isDone` logic is bad.

Try https://cdn.rawgit.com/pygy/mithril.js/d97fe817778fdc13c9f446b146422126cd37bdf0/ospec/ospec.js for an ospec version with fixed detection (and better stack traces in general).

The  ``` `first` flag``` view should read

```JS
          m(Island, API => {
              return tests.shift()(API)
           }
```

not 

```JS
          m(Island, API => {
              return tests.shift(API)
          }
```

There are still issues (the test does timeout), but they are probably Island-related.

**Comment by barneycarroll** [comment]
Thanks for your help with this @pygy. In hindsight the problem with async contextualisation points to a deeper problem: these two tests rely on using `m.mount` and `m.redraw`, and thus cannot be run in parallel without creating new Mithril & DOM instances per suite. IMO this is a serious blocker to using ospec for testing 'natural-usage' Mithril components.

**Comment by pygy** [comment]
@barneycarroll ospec runs async tests in series. The `done()` callback triggers the next test... But there might have been bugs with timeouts, they'll soon be fixed though. 

You could `m.mount(root, null)` in `o.before` to ensure a clean DOM state.
