### ISSUE TITLE
Seemingly a bug in the documentation generated from markdown

### ISSUE THREAD

**Issue by chocolatkey** [MithrilJS/mithril.js#2164]
In the docs for vnodes, https://mithril.js.org/vnodes.html, I noticed a rogue parenthesis here:
![image](https://user-images.githubusercontent.com/13407784/40525811-550efe94-5f97-11e8-97c4-4309e9f98998.png)
and the html code is `...<a href="https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics">immediate mode</a>) API...`.
The markdown code for that section, which is `[immediate mode](https://en.wikipedia.org/wiki/Immediate_mode_%28computer_graphics%29) API` renders just fine on GitHub (https://github.com/MithrilJS/mithril.js/blob/next/docs/vnodes.md), so it seems the parenthesis is somehow "leaking" during the static site generation process.
I figure the authors of this repo are a lot more familiar with their docs' build process, so I'm not doing to dig deep and try to figure out what's going wrong, but I feel that it should be noted as a bug.

**Comment by isiahmeadows** [comment]
Fixed now.
