### ISSUE TITLE
Should ospec register a succesful test when `done()` is called?

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2166]
Currently, `ospec` adds [one success](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5aACgA6IaRQAEYAK5pqxCPXEATejACUc4JLRy52tDHG6jrK2iO18AJ2WXKIODFir1aBDwAsiADsbBwgmDh4+NRwAjT0jMw8bAC6VFAQaADWfqjhXGJwAA4w1G6KjuQ8JMRFcIgA9A3KRVkA5tG0WA20xaUAAgBM+ACM+AAMPX3U+PxuxACeJXhw1I4QRaKsKaxAA) to the result list when `done()` is called, either by user code or when resolving a promise.

It makes little sense, except for the fact that it keeps the total number of assertions constant in the face of an async erroneous termination with `done(error)`.

Should we keep that behavior?

**Comment by barneycarroll** [comment]
It makes my test suite look much more impressive at a glance but it's misleading. Take it out I reckon.

**Comment by pygy** [comment]
Let it be! We loose 1000 "assertions" in the Mithril suite.

**Comment by pygy** [comment]
Actually, it is documented in the readme... I think I'll keep that behavior (Chesterton's fence).
