### ISSUE TITLE
Doc: simple application example in flems is broken

### ISSUE THREAD

**Issue by ArthurClemens** [MithrilJS/mithril.js#2169]
The linked example in https://mithril.js.org/simple-application.html does not run:

```
Can't find variable: User
```

**Comment by pygy** [comment]
@ArthurClemens it seems to be Safari-specific (I didn't test IE/Edge, but it works fine in Chrome and Firefox. Possibly a Flems bug, cc/ @porsager

**Comment by pygy** [comment]
I assume I had an old Flems version cached in Chrome and Firefox. Thanks @porsager!

**Comment by ArthurClemens** [comment]
I see that the example works again.
