### ISSUE TITLE
Docs on mithril.js.org list a feature not shipped with current release

### ISSUE THREAD

**Issue by pockata** [MithrilJS/mithril.js#2173]
## Expected Behavior
Docs on mithril.js.org should reflect the code in the current release and vice versa.

## Current Behavior
The docs for the 1.1.6  release list a feature on the `m.request` module that will make it no longer reject the Promise on server errors (eg. status >= 400) if the caller supplies an `extract` callback. The code was added in commit 80b6a1af0d02309167788ed7a95aa1f275e07653, and the documentation on the site reflects it, however the 1.1.6 releases on Github and npm ([unpkg](https://unpkg.com/mithril@1.1.6/mithril.js)) do not.

**Comment by pygy** [comment]
Thanks for the report. 

It is a breaking change, it was deliberately not included in the 1.x branch, it will be part of the 2.0 release.

We'll clean up the docs.

**Comment by isiahmeadows** [comment]
Fixed since v2.0.0-rc.0 is now released.
