### ISSUE TITLE
url interpolation: add support for querystring

### ISSUE THREAD

**Issue by purpleKarrot** [MithrilJS/mithril.js#2190]
Make sure that all four varriables get interpolated in the following url: `/:var1/:var2?foo=:var3&bar=:var4`.

This can be done by replacing the regex `/:[^\/]+/gi` to `/:[^/?&]+/gi` here: https://github.com/MithrilJS/mithril.js/blob/next/request/request.js#L144

Note also that the `/` does not need to be escaped.

**Comment by dead-claudia** [comment]
`m.request` currently supports a `params` object that allows appending arbitrary query parameter values, and other utilities also offer similar functionality.
