### ISSUE TITLE
Bundle isn't strict?

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2191]
[The latest bundle](https://raw.githubusercontent.com/MithrilJS/mithril.js/next/mithril.min.js) is not in strict mode. I thought this had been addressed previously...?

**Comment by pygy** [comment]
Hi @isiahmeadows!

Good catch, it looks like a closure compiler thing, that only happens in the minified build.

**Comment by isiahmeadows** [comment]
So maybe replace it with a dev dependency of `uglify-js`? (It's cheap to install in CI - it has zero dependencies.)

**Comment by isiahmeadows** [comment]
BTW, UglifyJS generally compresses better than Closure Compiler for unannotated code, so it might not be a bad idea to switch either way.

**Comment by isiahmeadows** [comment]
This appears fixed in the latest bundle.
