### ISSUE TITLE
Allow CSS vars to be specified via `style` attribute

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2192]
## Steps to Reproduce
[In this example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvLfAJ3oBMZmAKNy8gVxy18AI0psAniQAEyADppp0rFwDkI-jRrVVM4HBoTYiacFUBac1SiVmqk6oBMAVmcyADB9UBfbzNUASjBsAISqAJQkCkoq6praaLqmBkYwJmaW1rb20qqe0vkuzj5+uQBCUPwwYZHR0nWxIna1ivWtjfE6etTkrBh0JgBu0gC8AHzSg-i8TCmw+HAwNAAKzJQADpyGapmUNnb+RR5e4aWBwTVR7WoaWl2mPX0Dk6MTUzMLhvOLK2ubzNsLFY9tl-PlCq4ImcKlVLgoALrhEBkRawcg0CDUBCIEDuRAuEB+dDYXA4-DkOCkCjUOgMHG3BKmOoiDDkADWAHM1vw0GwTMwOSyuIMMNxdvtIgV8ABmcIAbjqWWYJiUqoFQpFYuBEpkAEZ8O55XU2BA4OsoBgJCqlBA0FBbTBzCIbOyFa11hg2Ca0BzrVLnDAsG6lGJmBxlaqlLr1gAPaRwPYQNhu7zIkComDozFobG4xAADkJ8LI9rQbOxqBAmBwjAgNAAFsxoGn+MwoHh61p1nBEAB6Xs89ac8mULC9rB1xvQAAC+v1ADZx5Om1AiFTDJs8HBehB1jQi94gA)…

## Expected Behavior
The first line of buttons should appear the same as the second.

## Current Behavior
The first line of buttons do not have the CSS variable declarations applied, because CSS variables must be declared via `setProperty`

## Possible Solution
[Use the explicit `style.getPropertyValue` & `style.setProperty` APIs](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables#Values_in_JavaScript) instead of [treating `style` as a POJO to be assigned to](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L777-L781)

**Comment by barneycarroll** [comment]
Was worried about the potential perf considerations of this but it turns out React implemented this a year ago and it [*improved* perf](https://github.com/facebook/react/issues/6411#issuecomment-290583221)

**Comment by isiahmeadows** [comment]
@barneycarroll If *that's* the case, then let's do this.
