### ISSUE TITLE
What's the next steps for Mithril? 

### ISSUE THREAD

**Issue by volnei** [MithrilJS/mithril.js#2198]
First of all, thank you all developers that make and mantain this brilliant framework!!! <3

There are any roadmaps?

Although development is fully active, I miss a roadmap so that I can keep up with developments and eventually collaborate with it.

Tks!

**Comment by isiahmeadows** [comment]
@volnei We don't have any clear roadmaps, but we *do* have quite a few things [in this project](https://github.com/MithrilJS/mithril.js/projects/2) you might be curious about. We also have a milestone for [post-v2](https://github.com/MithrilJS/mithril.js/milestone/8), which you may be curious to check out.

**Comment by isiahmeadows** [comment]
I just created the project today, so you can be forgiven for not seeing it.
