### ISSUE TITLE
problem using tsx with mithril

### ISSUE THREAD

**Issue by evnix** [MithrilJS/mithril.js#2199]
I am trying to port a mithril based js app to typescript.
The final thing to get right is JSX props. (JSX works as expected when not using props)

```
Container.tsx:17:38 - error TS2339: Property 'data' does not exist on type '{}'.
items.push(<Item data={myData}/>);
```

I solved it by using https://github.com/andraaspar/mithril-tsx-component

Is there any other way I could achieve the same result without using the above 3rd party component?

**Comment by spacejack** [comment]
@evnix Glad you got something working. Typescript-related issues should probably be [posted here](https://github.com/MithrilJS/mithril.d.ts).
