### ISSUE TITLE
Seriously terrific job with the documentation! You sold me on using Mithril!

### ISSUE THREAD

**Issue by sergiotapia** [MithrilJS/mithril.js#2202]
The 10 minute guide. Terrific, showed me what's what instantly.

The mention of user authentication, routing and file uploads instantly tells me this team cares about developer UX. Another major win.

Finally the framework comparison was just phenomenal. 

Great job guys, it's *rare* to see this kind of love and dedication given to documentation. Inspirational!!!

**Comment by isiahmeadows** [comment]
Thanks so much! Always appreciated.

Since there's nothing immediately actionable here, I'll go ahead and close this.
