### ISSUE TITLE
small inconsistance in the install tutorial

### ISSUE THREAD

**Issue by emchateau** [MithrilJS/mithril.js#2210]
In the installation tutorial the instructions for Mithril bundler are not consistant with the alternative with webpack

https://mithril.js.org/installation.html#mithril-bundler

`"build": "bundle index.js --output app.js --watch",`

instead of 

`"start": "bundle src/index.js --output bin/app.js --watch",`

**Comment by RobertAKARobin** [comment]
Can you make a PR with these changes?
