### ISSUE TITLE
Router events

### ISSUE THREAD

**Issue by felagund18** [MithrilJS/mithril.js#2211]
Hi, Mithril users :). 
Is it possible to implement ```onpoproute, onpushroute``` events.
```
var User = {
	oninit: function () {
		//fetch data from server
	},
	onupdate: function () {
		//fetch data from server causes infinite m.redraw()
	},
    view: function () {
    	...
    }
}

m.route.set('/user/1')
m.route.set('/user/2')
```
When goes to ```/user/1``` only ```oninit``` function is called, then ```/user/2``` only ```onupdate``` function is called but i need to get a new data from server. So i have to get data in function ```onupdate```. But using ```m.request``` leads to ```m.redraw()``` then ```onupdate``` function is called again. It causes infinite ```m.redraw()```.

How can i get data from server in this case.

## Possible Solution
```
onpushroute: function () {
    //fetch data from server
}
````
## Your Environment
* Version used: 1.1.6
* Browser Name and version: Chrome

**Comment by cmnstmntmn** [comment]
@felagund18 have a look https://github.com/MithrilJS/mithril.js/blob/next/docs/route.md#key-parameter

**Comment by cmnstmntmn** [comment]
here's an [example](
https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9GIAEAWmmS6WAA70RcADpoAbhgBOkqBDjFJAXknANkyfQhoIxRJIDmMYgFU4MHXApXLkzQgYAHdHAAoASlMAPkksMIByWigE338rZABGCgAmCgBmCgAWCgBWAF18LAxFMJgoGLjEg1TzAGsYAE9HevZJdKsmhIxWizRBwcIdGDBHBLEEyQBqSXqKAat6ammMRkcsfB1aAFdGfAM0Nv8+hIBJRixJVvqIiIG38ckP1g0NbT1jp49GYxps7HYHJIwpo0LQACYwKImWKgwYudxAgBCnVucOhsIR+F2xG8+A6nQ+VnY-kCIXCMPhiMayA2Q0ImVaCQ8XkWKwZhOJpPJEXWnwm8TUIAwyCmMxM8wS5UlvmAWx2ezihxOZwubRuACVXMcdONiLR9IZiAlKYMlWgfmgNBIZHJCPVFF51GgwMc0NRiBB6M5XNzvGFAV5cVFUVYhHBkjB8LYwLREuiA2gnJII95rf4BtNiMbxgdpgBHY7wYhhGMTOKuQjwxySgDiAFEACrK-piuvGqCOJ5iHNwBIDVg2qz4YhutBhH1+gP0MLTODKNCeCK1yTOwgYNBw2CSODHajUeBeiYTgb4ai7aiEee+-2BudeI46Les3f7w8wVY6B+47fL8jres+S7jOiobYri4ZAlG5gDHGCZJt6qYJOi2YIQAInMvg5lG+a9oWxaauWlZGDWrJWDgM5Nv0IDtl2lA9nWgz9oO8wjgsyzYZGcLATeM5ME+i6viu8Drpu24-geR4nmeF5Cb2t73o+C4vsu760J+247lIe7yf+Ok6CprA9k6UiyHEJwMJINSKBopbajAYRwrQ1DHDgDD4AARvCnRpCAYjdrWkqhUgFpGKKEwRYg5KSo4OaiteYGUCAniwFpG54DkACciA5DkbAcCAmA4Hgt5wAIND0IwzA8Gw5RULqCAoJwlU8Fg9hTNAGX9ngJDEIocCIBIvqKG0Ti3rQWBiD1M46NAAACmT4OtABsC29ctUD4PwGXEJ0Hp4HA2wQIooisOUrBAA)

**Comment by felagund18** [comment]
Thanks, @cmnstmntmn, it works

[example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAhkBeacgCMFAEwUAzBQAsFAKwUAbAF0AOmnMSZAVTgx504OenT6ENBGKJpYAK5pqYgh6aQAKAEpHZxdpIThaWHwoWgBzUIByd0908Oj2aLEIGAB3bz8AoJCIqLQY2RhiX0larAzfKHSKWXwsDAAHUIAPaTkAPhq6l0kGppaMqAhO6VaAAwxkQmmwOQB6XztJHYASYEHWYxWu4HpqaYxGbyx8SVpfRiT3AGt2aUHw3NqMVY-zy5lY5nMTxebxgoQAJrRqL4cAx8AAjWhwgCeXVMID2Bx2SjxV2iLjxBPsO0QnxgWLx3ls9jB4UoIDssECwTQCB4SgADIgNGwOCBMDg8PhqHABDR6IxmDw2MYqAs0J9eagxVw8FhPJtoPh+GymuQeCRiH04Igdns0H1PikpbQsDs9cQDVAAAJKfC+wxu-WSQ3GqjELF9bjs24QPqic6sIA)
(but only works with parameter ```key```)

**Comment by cmnstmntmn** [comment]
great!

**Comment by cmnstmntmn** [comment]
@felagund18 you may close this issue if everything's fine ;)
