### ISSUE TITLE
oncreate is not called at the end of the render cycle?

### ISSUE THREAD

**Issue by derMart** [MithrilJS/mithril.js#2218]
Hello, consider this example using mithril 1.1.6:

```
m.mount( document.body, m(
    {
        oncreate: () => {
            console.log(vnode.dom.classList[0]);
            console.log(vnode.dom.offsetHeight);
        },
        view: () => m('div')
    },
    {class:'height100'})
);
```
Let's assume that the class 'height100' will set the height of the div to 100px.
The console output will be undefined and 0.
The documentation states:
```
oncreate is guaranteed to run at the end of the render cycle, so it is safe to read layout values such as vnode.dom.offsetHeight and vnode.dom.getBoundingClientRect() from this method.
```
So I would assume that oncreate is called after the class is assigned to the div and the correct height can be read, but it is not. Bug or expected behaviour? In the last case please update the docs.

**Comment by pygy** [comment]
There are a couple of errors in your sample: 

1) m.mount takes a component, not a vnode, as second argument.

2) passing a component literal to `m` is in general a bad idea (clashes with diff semantics)

3) You're passing the class as an attribute to the component. What you probably want is this.

```JS
m.mount( document.body, 
    {
        oncreate: () => {
            console.log(vnode.dom.classList[0]);
            console.log(vnode.dom.offsetHeight);
        },
        view: () => m('div', {class:'height100'})
    }
);
```
Using `m.render` with your original sample

```JS
m.render( document.body, m(
    {
        oncreate: ({attrs: {class}}) => {
            console.log(vnode.dom.classList[0]);
            console.log(vnode.dom.offsetHeight);
        },
        view: ({attrs: {class}}) => {
          return m('div')
    },
    {class:'height100'})
);
```

**Comment by cavemansspa** [comment]
running example: [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmjABXNNWIR6AAgDCtLAAd6IgBQBKRcAmLFRxQCcYxKWbQHTx+tQsZGiRdoBuaWgBMY+gF4APjtbY3DFIThaWHwoWgBzbTEQVQ0tBkRER2dGPRSKRS9fGHwfNXxqKAw4OAAZCDhiXXtFdlaPCBgAdzdPbz9AkMMwiIsrG0UsbQByfDBaWnwAIwwzGcKZtM00ERmW0bbTVglWEzQJLHwsWhlibXLqKRwGFd8AT0KR406evqGptpthlmqddJQQHAYLA5Ao0AgeAAORAAJgALGwOCBMDg8JVahChIxmDw2ABdKhQCBoADWCNQ2K4eCwEGIhDM0Ah1nIPBIxHUcEQAHohTJ1DSEpU1EKWWyOVAAAIARnwKoAbDLWezoPh+BDiO91NxIU4IOpRKwyawgA)

**Comment by derMart** [comment]
Thanks, and ah sorry, the minimal example was set up incorrectly. Of course, I am mounting a component not a literal. The point here is to set the class for the component from outside, here is the not so running example: [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmjABXNNWIR6AAgDCtLAAd6IgBQBKRcAmLFRxQCcYxKWbQHTx+tQsZGiRdoBuaWgBMY+gF4APjtbY3DFIThaWHwoWgBzbTEQVQ0tBkRER2dGPRSKRS9fGHwfNXxqKAw4OAAZCDhiXXtFdlaPCBgAdzdPbz9AkMMwiIsrG0UsbQByHwgPGcKZtM00ERmW0bbTVglWEzQJLHwsWhlibXLqKRwGfAAjXwBPQpHjTp6+oantVYziG8qjU4G4ZmBaLQZqwtjDKCA4DBYHIFGgEDwAIwAVkQACYALQABkQhLYHBAmBweEqtXhQkYzB4bAAulQoBA0ABrdGoClcPBYCDEQhmaDw6zkHgkYjqUEAejlMnUnISlTUcsFwtFUAAAhj8PqAGwaoUi6D4fjw4jPdTcBFOCDqUSsZmsIA)

@pygy Thanks, I'd like to achieve the second with m.render, but at least in my chrome 60 something the syntax: view({attr: {class}}) => {...} is invalid.

**Comment by derMart** [comment]
Edit: But it seems this has nothing to do with the oncreate, sorry. The css class is not set at all....wonder why?

**Comment by derMart** [comment]
I got it, I have to pass the class to the subcomponent manually. like: [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmjABXNNWIR6AAgDCtLAAd6IgBQBKRcAmLFRxQCcYxKWbQHTx+tQsZGiRdoBuaWgBMY+gF4APjtbY3DFIThaWHwoWgBzbTEQVQ0tBkRER2dGPRSKRS9fGHwfNXxqKAw4OAAZCDhiXXtFdlaPCBgAdzdPbz9AkMMwiIsrG0UsbQByHwgPGcLiv3wXYjM4Qpm0zTQRGZbRttNWCVYTNAksfCxaGWJtcuopHAZ8ACNfAE9CkeNOj0+kMptpdhliH8qjU4G4ZmBaLQZqwjijKCA4DBYHIFGgEDwAByIADMAFY2BwQJgcHhKrV0UJGMweGwALpUKAQNAAa3xqCpXDwWAgxEIZmg6Os5B4JGI6lhAHoFTJ1NyEpU1ArhaLxVAAAIARnwRoAbFqRWLoPh+OjiN91NwMU4IOpRKxWawgA)

Thanks, from the documentation it was not clear that I need to do that for a complex component as it is done automatic for the build in HTML tags.
