### ISSUE TITLE
Make a v2.0 sprint

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#2223]
Although a lot of stuff is done now there are still some things to do to stamp out v2 of our beloved mithril.

Maybe we can do a 2 day sprint to fix all remaining issues together. Maybe we can also attract new contributors and entourage old ones to get back on the mithril track.

I would propose a primarily online event with gitter and github as the main communications plattform. People in the same area can organize some local events to get together. I would do such a meeting in Leipzig/Germany and I already know a few mithrilers here that would probably come an help.

What do you think about that?

**Comment by StephanHoyer** [comment]
Weekend vote here

**Comment by StephanHoyer** [comment]
2 weekdays vote here

**Comment by isiahmeadows** [comment]
BTW, if we want to go with a sprint, we should look to do it somewhat soon - v2.0.0-rc is out.

If/when we do, I'd suggest using https://gitter.im/mithriljs/Lobby for communicating during the sprint, so we aren't interfering with the main channel.

I just found this bug, or I would've commented earlier.

We should also aim to get a list of priority bugs to crunch while we're at it.

**Comment by isiahmeadows** [comment]
Oh, and a heads up: [I created a couple projects](https://github.com/MithrilJS/mithril.js/projects) which should help make it easier to crunch through them and know the state of everything.

**Comment by dead-claudia** [comment]
@tbreuss I think we can. 😉
