### ISSUE TITLE
Simple Application tutorial has issues

### ISSUE THREAD

**Issue by ohenepee** [MithrilJS/mithril.js#2228]
[Here](https://mithril.js.org/simple-application.html) if you search for **index.js** on the page, you'll realize that it was first mentioned here **Let's render the view from the entry point file src/index.js we created earlier**... yet the statement says **we created earlier** which makes you start looking in case you mistakenly missed/skipped something.

**Comment by 7h3m4dS0u1** [comment]
@ohenepee the index.js file was created during the installation process. https://mithril.js.org/installation.html

See this paragraph in https://mithril.js.org/simple-application.html

"To install Mithril, follow the instructions in the installation page. Once you have a project skeleton with Mithril installed, we are ready to create the application."

**Comment by ohenepee** [comment]
Oops... I guess I missed! Actually I least expected it to refer to something which was created on a different page, especially since `Simple Application` tutorial itself is a full-page tut.

**Comment by 7h3m4dS0u1** [comment]
Yes, I think it's need more clarification too.
