### ISSUE TITLE
Add Flow support

### ISSUE THREAD

**Issue by soulofmischief** [MithrilJS/mithril.js#2230]
I'd like to see Mithril added to [`flow-typed`](https://github.com/flow-typed/flow-typed).

We could probably just run the TS definitions through [`flowgen`](https://github.com/joarwilk/flowgen) and then clean it up from there.

**Comment by charlag** [comment]
I want to point out that besides generating TS types we have working declarations at Tutanota:
https://github.com/tutao/tutanota/blob/master/flow/libs.js#L16
and we would be willing to upstream them
It's a little bit of a mess right now with multiple definitions overlapping and spread across the file but it could serve as base.
