### ISSUE TITLE
Bundled version mismatched with source

### ISSUE THREAD

**Issue by starsolaris** [MithrilJS/mithril.js#2232]
Bundled version of mithril.js from next branch has some code mismatch with source:
https://github.com/MithrilJS/mithril.js/blob/next/mithril.js
line 1143: 
`key !== "href" && key2 !== "list" && key2 !== "form" && key2 !== "width" && key2 !== "height"// && key2 !== "type"
`
in method
`function hasPropertyKey(vnode, key2, ns)`

but should be `key2 !== "href"`

like in source render/render.js

**Comment by pygy** [comment]
Ooof... The bundler strikes again :-/

Great catch @starsolaris! Thanks for the report...

... though I wish this hadn't popped up, I haven't been in the bundlers for eons, and while it may be short, it is anything but simple...

**Comment by spacejack** [comment]
@isiahmeadows I'm wondering what's the "least blocking" of options - fix bundler or switch to Rollup?

**Comment by isiahmeadows** [comment]
Neither is really "breaking", just it needs fixed, and switching to Rollup would likely be a *lot* more time-consuming than just fixing the bundler.

**Comment by spacejack** [comment]
That's what I meant, which would take more effort. Are there difficulties in using Rollup beyond making a config?
