### ISSUE TITLE
Should missing files fail bundle?

### ISSUE THREAD

**Issue by reergymerej** [MithrilJS/mithril.js#2240]
If a file is not found during the build, the bundler logs the error but does not fail or exit the process with an exit code.

## Expected Behavior

exit process with non zero

## Current Behavior

```
File does not exist: /Users/jg/mithril.js/bananas.js
```
Missing file is logged, no failure.

## Possible Solution

If a file is missing, log it, but also exit with an error code.

## Steps to Reproduce (for bugs)

https://github.com/reergymerej/mithril.js/commit/11f6e560400619f411f10ca94eb02c6bd5210df2

1. Import a missing file in `index.js` and `npm run build`.

## Context

I was just exploring and fat-fingered something.  This is a question for the maintainers.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by isiahmeadows** [comment]
The bundler is primarily for Mithril itself. I do find it odd that the bundler reports a status code of 0, though - PRs accepted to fix that. (Note: you can just set `process.exitCode = 1` before the thrown error.)

**Comment by reergymerej** [comment]
I'll get on it.
