### ISSUE TITLE
Question: Best practices re-running oninit when setting the same route with multiple attributes in route

### ISSUE THREAD

**Issue by Niklas81** [MithrilJS/mithril.js#2245]
This question is related to the behaviour described in #1180.

I have routes where more than one attribute can change and should prompt oninit to reload, as oninit loads my data for specified page. I solved this automatic reload by having a main component:

```
var mainComponent = { oninit: function(vnode) {
                                vnode.state.get = vnode.attrs
                                
                                /* 
                                More stuff here that loads data
                                */
                    },
                    onupdate : function(vnode) {
                        if (vnode.attrs !== vnode.state.get) { this.oninit(vnode) }
                    },
                    view : function(vnode){ /* insert view here*/ }
}
```
and a subcomponent with an onupdate method containing :

`if (vnode.attrs.pageData !== vnode.state.pageData){this.oninit(vnode) }`

Basically, the main component checks if the url has changed, and then reloads oninit, whereas the sub-component checks if the data it just received is different from it's current state. The sub-component won't need to check if the url has changed, as that would prompt a reload of the main component, and thus the sub-component is automatically reloaded as well.

My questions are: is this considered anti-pattern and if so, is there a better, recommended way of doing it? I am aware of the key attribute, but to my knowledge that only works if you have just one attribute that can change in the route, not if you have multiple. Besides, I prefer choosing my own names for attributes, rather than calling everything 'key'. So, again, is there any reason why I should take another approach of solving this, and if so, why?

**Comment by Niklas81** [comment]
While your example route has two parameters, it will still just re-run oninit when paramater 'c' changes, won't it?
Suppose you have a route:

/news/:article/:discussion

From one discussion under an article, you can link both to another discussion under the same article, as well as another discussion under another article. This means you will need to use a 'key' attribute for both attributes. Can this be achieved in any better way than the example I provided? Does your example handle this scenario?

And is there any reason why I shouldn't use my way of doing it? It seems more automatic, as I won't need to parse user-generated content and add keys to their links.

**Comment by cavemansspa** [comment]
here's [another version](https://flems.io/#0=N4IgtglgJlA2CmIBcA2ATAOgIwA4A0IAZhAgM7IDaoAdgIZiJIgYAWALmLCAQMYD21NvEHIQIAL54a9RswBW5XgKEimAHWqEArtR5sIAgAQAFWgHN4ACgCUh4BsOGHhgE7w2Wl9TvPHAiNQQbEiGlsC0bGwupOK2ALwAfD7ejqn81KR8CBiwfGaWAOSmFkhI-oFsBXiGEVGk1r6Gko0AbhDwAO4hNoaJyampYIVVhgUs8LC5BQ0pjuLO89SLGmAYLnxaQpZQfDxaDIIYAEZ8UACe1WogAPTwUEHXWFfV9rNON3cPSLRXIcXweEaV1u9zY12+Ln0PAQ4PupD2pFIBmovxM5ngGg0sUxKOoCDYhn4OgJcUMWEBKQA1vAzr1DDooPBiNQ7hTHLRIRBofA6eTnHCEUijKSAKzODT4wzQOmkdwASUE8BcLVosEsPT6r0cEEIlgAhJYiYJDABSMnWWxa1LU2mko0EgDUozwBUMToFWkRyMaq3Wm3gGFlbEKIIerqd9rdo2u4cMHq9Amq1C0kxepDYEXgIWANpCNvE4kMtlSC2cOv1ho2xrNaAt-WtNLpHKhCCjVQKEarbB9aw2QkD7hDnzBsebXNbToKMaj9qTKdgaYzQmzucM+cLxccpZSzgADmF7SFZ2uaXmaZJDB0AjsOjldhFkaw3IQZo57Q6HWXdZGkihLY1uQ5BUhGVVVLGgV8G1tQw0DbF0ozFN59wKWBaHTQkWFoagLBGSDHF9PsAyDIdQWnJ1YMnMjDBFOdUzsdNMxXU8TzOAsiwGbcLywAAGXjrG4EBZQQPRkXIJgABZuKQXAJCkEA6AYUQMB4REBPSFQ2FECQAF0CFgAJKTEqh5JkURIDYFgXBIATPC4Jh2DYXdSCQa5rh0XdKTMZS+DAa5zMskgAAEsGwDAUD8oIAtgDAFAEtgzl3WR4Ss3dNPEbTxCAA) that hits a few different permutations of article and discussion changes. e.g. same article different discussion, and same discussion and different article.  seems to work as expected triggering the `Page` components `oninit()` lifecycle method.

imo, i would leverage the framework as opposed to explicitly calling `this.oninit()`.  but perhaps i'm misunderstanding your issue.  that being said, if your current approach works then it's probably fine.

**Comment by Niklas81** [comment]
Ah, that works rather well! How would I put that inside an a tag, rather than putting m.route.set() inside e.g. an onclick?

Also, with my approach, I could append a query string to the url (e.g. `/news/a-cool-article/2127127912?a=1&b=2` ), and page could re-run oninit should I want it to. Can this be done with the regular approach you use? Depending on situation, such functionality could both be desirable and undesirable.

**Comment by Niklas81** [comment]
One weird thing about using `m.route.set('/news/some-article/2212121', null, {state: {key: 'some-article/2212121'}}` is that key could be any two things with a comma in between (e.g. 'some,stuff'), and still it will use the parameters specified in the route (in this case 'some-article/2212121' )...

**Comment by Niklas81** [comment]
Got it, `m('a', { href: '/news/some-article/212121', state: {key: '1111,ooo'}, oncreate: m.route.link }, 'some article')`

**Comment by Niklas81** [comment]
Hmm, please ignore my last comment. I tried that while my own solution was in place. How DO you pass along key attributes in an ordinary `m('a')` in the same way as in `m.route.set()`?

**Comment by isiahmeadows** [comment]
@Niklas81 You can use `oncreate: m.route.link({state: {key: true}})` as an attribute, which does basically that. It's also a little more intelligent, since it ignores left clicks, control-clicks, etc.

**Comment by Niklas81** [comment]
Hmm, appending `({state: {key: true}})` to `oncreate: m.route.link` renders me a blank page. Using this with mithril-node-render gives me the error `TypeError: Cannot read property 'setAttribute' of undefined`. Any ideas?

**Comment by isiahmeadows** [comment]
Wait...that's a thing that hasn't been released yet, then. 🙂  (I cross those up occasionally...)

If you'd like a simple wrapper for now, [it's basically this](https://github.com/MithrilJS/mithril.js/blob/next/api/router.js#L55-L69):

```js
m.route.link = function link(args) {
	if (args.tag == null) return link.bind(undefined, args)
	return link({}, args)
}

function link(options, vnode) {
	vnode.dom.onclick = function(e) {
		if (e.ctrlKey || e.metaKey || e.shiftKey || e.which === 2) return
		e.preventDefault()
		e.redraw = false
		route.set(this.getAttribute("href"), undefined, options)
	}
}
```

**Comment by Niklas81** [comment]
That might explain it then! :)
To be honest, the "recommended" way of handling this is increasingly feeling more like anti-pattern than my very simple, DRY solution that doesn't require a bunch of additional code for each link. I'll try this tough! Always good to have a few different ways of achieving intended results.

**Comment by Niklas81** [comment]
What upcoming version of Mithril will that method be available in btw?

**Comment by isiahmeadows** [comment]
@Niklas81 v2.0 and v1.2. v2 is likely to get cut first, since it only hinges on #2219/#2246 (both relatively small PRs), and I ran into some glitches in the backporting process for v1.2 (see #2243/#2247 for the current status of that).

**Comment by Niklas81** [comment]
Ok, cool. Currently I'm getting a bug when using this (existing functionality): clicking a link works, going back works, but then clicking this same link again messes up the whole page; parts of the page gets appended or prepended to existing page. Looks really weird.
