### ISSUE TITLE
Forbid mixing keyed and non-keyed vnodes in the same array

### ISSUE THREAD

**Issue by ACXgit** [MithrilJS/mithril.js#2248]
## Expected Behavior
Make [this antipattern](https://mithril.js.org/keys.html#avoid-mixing-keyed-and-non-keyed-vnodes-in-the-same-array) explicit by throwing an error.

## Current Behavior
Currently there's no clear way to understand why a keyed node isn't behaving like expected if you forget to add the `key` attr to all the other nodes in the same array.

## Possible Solution
As [discussed in Gitter](https://gitter.im/mithriljs/mithril.js?at=5b8d2c8df86b741b0501ce64) with @isiahmeadows, a possible way to make this explicit would be to throw an error in case of mixed keyed and non-keyed vnodes in the same array.

One possible approach could be acting on the [in this file](https://github.com/MithrilJS/mithril.js/blob/next/render/vnode.js) (thanks to @barneycarroll for pointing me here), changing it from:

```javascript
Vnode.normalizeChildren = function normalizeChildren(input) {
	var children = []
	for (var i = 0; i < input.length; i++) {
		children[i] = Vnode.normalize(input[i])
	}
	return children
}
```
to something like:

```javascript
Vnode.normalizeChildren = function normalizeChildren(input) {
	var keyedCount = 0
	var children = []
	for (var i = 0; i < input.length; i++) {
		children[i] = Vnode.normalize(input[i])
		if (children[i] != null && children[i].key != null) keyedCount += 1
	}
	if (keyedCount > 0 && keyedCount !== i) throw new Error("Avoid mixing keyed and non-keyed vnodes in the same array")
	return children
}
```

Some tests fail after this change (I suppose they will need to be adapted), and I have noticed a slight performance decrease in the perf test, so I don't know if it's a good idea at all.

## Context
I keep falling into this trap because it's easy to forget it, and it could be hard to debug. The antipattern described in the docs could also be easy to miss for newcomers.

**Comment by yossicadaner** [comment]
By doing so you can limit existing functionality of keys.
https://github.com/MithrilJS/mithril.js/issues/2434

**Comment by isiahmeadows** [comment]
@yossicadaner [My workaround](https://github.com/MithrilJS/mithril.js/issues/2434#issuecomment-502757490) is not mutually exclusive with this, and in fact works *with* it.

**Comment by isiahmeadows** [comment]
If anyone wants to incorporate a check into the renderer for this, I'd definitely be willing to consider it. Do note that I want to see performance numbers before *and* after this - this should *not* be a costly check.

Such an addition would be as simple as a loop similar to this in the line after [this](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L278) (and removing the `else` after it) and removing [this newly unnecessary block of code](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L289-L294) as well as the existing declaration of `start`:

```js
// This differentiates whether the children array is keyed at the same time, to
// not duplicate work on a very performance-critical path. Note: you're not
// likely to get any faster than this without inflating code size by a *lot*,
// and the wins will likely be marginal.
var isKeyed = false, start = 0
for (var i = 0; i < vnodes.length; i++) {
	if (vnodes[i] == null) continue
	start = i
	isKeyed = vnodes[i].key != null
	while (i < vnodes.length) {
		if ((vnodes[i++].key != null) !== isKeyed) {
			throw new TypeError("Keyed and unkeyed elements must not be mixed within a single fragment's or element's children.")
		}
	}
	break
}
```

**Comment by yossicadaner** [comment]
I wasn't as elaborate as I should have been. 
- div
-- IMG
-- text
-- toggleable elm (keyed)
-- some elm

**Comment by isiahmeadows** [comment]
@yossicadaner Could you give me an idea of how mixed children should work from an implementation standpoint?

- We use an algorithm leveraging the [longest increasing subsequence](https://en.wikipedia.org/wiki/Longest_increasing_subsequence) to accelerate keyed fragment diffs.
- We use a fast (but suboptimal for dynamic lists) iterative diff for unkeyed fragment diffs.
- A mixed diff would have to somehow blend these two.

You do have to be mindful of several corner cases here, some awfully subtle and insidious. Here's a few examples:

- `1:A _:B 2:C` &rarr; `1:A 2:C _:B` - does `B` get moved, `C` get moved, `B` removed and reinitialized, or `C` removed and reinitialized?
- `1:A _:B 2:C` &rarr; `1:A 3:D _:B 2:C` - does `B` get replaced or not? (Intuition says no, but it's hard to generically code for this.)
- `1:A _:B 2:C 3:D` &rarr; `1:A 2:C _:B 3:D` - does `B` get moved, `C` get moved, `B` removed and reinitialized, or `C` removed and reinitialized?

*Note: `N:A` represents an element `A` with key `N` and `_:A` represents an element with no key.*

Oh, and you have to code a generic solution for all of these, not just solve them individually. These could occur multiple times in a single list, like `1:A _:B 2:C 3:A _:B 4:C 5:D` &rarr; `1:A 2:C _:B 3:A 4:C _:B 5:D`. The perfectly accurate solution here is technically [quadratic](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) (read: nested loop, if you aren't familiar with computer science), something that's obviously not a good idea to include in a highly performance-sensitive context like Mithril's renderer. (It's so sensitive that even a mild constant slowdown checking keys are either all present or all missing is potentially concerning.)

If you can think of something that's 1. feasible and 2. not going to lead into a massive blowup in renderer size, I'm all ears. 😉
