### ISSUE TITLE
Old class name stays in the DOM when it is getting re-rendered with undefined

### ISSUE THREAD

**Issue by just-boris** [MithrilJS/mithril.js#2258]
## Expected Behavior
When I re-render a component with undefined className property the old className value is getting removed from the DOM

## Current Behavior
The old class name stays in the DOM

## Steps to Reproduce (for bugs)

The simple code shows that:

```js
const app = document.getElementById('app');
m.render(app, m('div', {className: 'hello'}));
m.render(app, m('div', {className: undefined}));
```

[Live demo](https://jsfiddle.net/just_boris/adtgvsx9/)

After the second render class name should be empty, but the previous value stays.

Also, it works correctly when I use `class` instead of `className`. The difference in behavior for the two properties is very unexpected.

## Context

I came across this behavior in the following code

```js
var className;
if(props.active) {
  className = 'active';
}
m('button', { className: className })
```

This code pattern is very common, and that was not expected, that it will be broken.

## Your Environment

* Version used: 1.1.6
* Browser Name and version: all browsers
* Operating System and version (desktop or mobile): n/a

**Comment by isiahmeadows** [comment]
@just-boris Is this also the case with `mithril@next`? (You can try `https://unpkg.com/mithril@next`, if that helps.)

BTW, `mithril@next` was just released, so it's okay that you didn't test it with that.

**Comment by just-boris** [comment]
It doesn't happen with `next` release.

Okay, we will have to wait for the next release.
