### ISSUE TITLE
Improve Issues Template

### ISSUE THREAD

**Issue by koolamusic** [MithrilJS/mithril.js#2263]
I intend to submit a PR that would improve submission process of issues 
differentiating bugs, from features and enhancements
 :smile:

**Comment by barneycarroll** [comment]
We're all ears!

**Comment by koolamusic** [comment]
Something that works and looks like this 
![issues](https://prnt.sc/lbgpp0)

**Comment by isiahmeadows** [comment]
Fixed by #2271, just that didn't auto-close this.
