### ISSUE TITLE
'Provider' components: core contributions necessary?

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2272]
At @isiahmeadows' prompting I'm filing this as a conversation starter for whether there are any concepts from my proponents pattern(s) that might be better exposed via changes to core.

We've already stopped aggressively pre-normalising children on consumption, which makes it easier for people to author their own function-consuming components.

Perhaps a good talking point to kick off on is whether we could somehow bring `Inline` ([source](https://github.com/barneycarroll/proponents/blob/master/src/packages/Inline/index.mjs), [demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJHWGABwDoArBAGhAGMB7NAFxibxgA8i6AnRgAgAmMMBgCuUfkKgYAnnwC8APj4Q0RUfyUAdNHz180MAO58ACtzpYIcGAApu8OlABuMBcuA79+m4wAqEDh0Gra2AJTufJ663voOcE6utqrqjGFesQC+lIIw0jLpMXqZYSDUNrA0jBAMCIggAAyIAEwAnCDZ6Ni49QCydAIYUORUtAzMrPX0aHD81TQA1gp84ZHmltYwJPGJdoU6HFy8uSLi-NF6zhDGiCvANAAW0AIOaCXuGXpYtgDkJD98ADUfAARgADT76EEYRYAcwsojQAj4AGIwOjIXoQXR2ABaOAPDACOgmFENckARj4DWpfGaMCwfBIzQArAzMXwiESBKpYd4KeyivouHAINUGPpIOwYAIOYw6ERYvoWQ0AKQc2BgfhKlXqoV6RjcDAzMA8Rl8Q3GggYZi2XG6nL2tWFJVYDB4owQASMB56VoADmcRg5brxDxgEFhD34AecDzlRpmYpquhIABY4HwYBgbLjVLjgowOQqYWK5PoGpCwTkLrEGDQHDaYLdbMBiVhbsBZjJYDlVIZuAAJCNRxiZd5KKIcvTd2AkEs0MvLCk6acWiCLcIkH0sWxYbYyo1GF1ZSir-V8Bgg4Q8GAOLB0VwttuWCfKQwmdZWGz2RwuNyTrWSrtiQs5bAuS7yNS55KnoIHcgAoq4TAADLWBMd6-JaSbioYSI-DkOz-ie3glJC2Qco8zyvJCYRnm8ZT4HkMBVCmdQgBSaaIBS7SdCAmA4HgADqGBineIyMdMEyMGwnA8JIwhiBIKwRIBGTOBg3B8FAqhLFBH58L0GBEDBfAOIwojcLoQF8Fcxh8LcziRLYa7OCQNqGnAJA6WgCwcgA-HwrkkFRUAvCwHKIMFoXhWgyANAAuiFTxha8tg+QsES0fRkL1o2zC3EQd6irM9HeAwohEIMBWcsV6E5UKDD3o+za2ZENl6BAYC2G5HncF5GUkbEvWMJ53m6SQUgwLabntkNFFoLlaDXqaDjNU+KkfBeX6bO5UBQC5F56MgJCnRlJAaVAojwOESVukQtg0EMUAAPIAEIAEpDXoJ6ZDof2LWg0yzHwT37e9H3LDmMhA21akxEIIKiLCsJ3hkGQYEYon8DtNh7QdyDTiNnmQgAZKTtnuaN-XzstN5rQyLVkxTxM01e9N3ozrghc9PWgYwTY5M4dGmcN-NNrTK23utMDM5TswS+zq2cw+3NgwdbkK8wQsizECUnhk+4OC8mPhP957A-wkBIhDyxOfDehGClbh87AaCwj6fAAD5e3wACEfMC7CksczL3u+6zmbk5TfVeUr0tczAYRDfblOqArQNuD7lMxa84e2fFCWmeZlm6M45uA5btX9ehdvtRkVcC9wqOaHw1sCBDPX7DEXV87H42+SnVNjedvi2E3LeTZYOQT9NhSZIxFQsbh7EAMwUtxaYdJQXSCfUACSaA+VsFCSeMLAyfUhzyScSlW4irEMF3tZV2AyyHUqbm5ywhdBUK5NyhkEVOgb8v4pVioXZK1EWAKHkFBH4YAH64R+MzDkYDoFxUSlA1KEUYjdz0CXKyKwORgEhP5DkH9YJ6DACQIgFh5SMCAW4aONC6F0AYUwi61xgxHT4OQ3hegDLdVOu5ZuogcBMDgN9fQUUBFt1sCIzSsJxEXykRyIasilQdX0HZIwz81wEOmqXYhcjvCRy4cYAx+h+FUM-sPGmuiFGnSUSoyR0ilSaNsWY+xXlv6Ay8e4vgAMlTBL4PPbeu8eggBeuiCS1ApIXzwFXIqNcQZQXth4DIL0QRkGXiQBYMAZBwD7tTKRJBVoIRhA8ceTD65Ck1gLZgJAYDIUYF5bkNSir4P0J6JEJJ3ICAEEhC+aFZgsEwowoqQtxbawtNwa6v154W1qHMbM3BiRGF0Okupx0RENIli01RSUKlVM6QBTJQpekbIPKrGAwzULoXGdwM50ytYwBnvMpOGQyJvHPNfY4QhTjKQyXcdS3CHKbW0PU7BsUGp6AYKoMUELVgOx0TMrYhzJHLAMgAZWmt8uFl4gb5TcIVOqpUMgVSqk2CFKSSqMDKkSsOtxmCaQ2WgQlhIkSwHuYwW45ypxCl7lsSZbhVAx1KXwaOftZqWBCuMUSMxbAiqUXPMI2jI7IBFUwhKyruneGFQeE2Jg-ZwLbkMGwgSjaHlNvNAlpl44OEqtVVq0hmBpIuWY5Ybr4BFhiAtEoET+LdDwLjcSp94nn0mCAf5CkgXnDBTcOGihIToJwZgpKfjWx7PRSUQlCK0BiluNDWGIKbLZNyVUdycBRSwjQHzN5NY0FDGurcHRdAvTUkZd4O8FhuBtsuB25EDRu1xD-K4AQtwRBQBsKOwxlbmCTvNTO95HIipIl5G2w010518F8IwWAS7l2zvIvquZcgNXooui2gCfBMbYwlWNNh35ZYXn2U0oiE7ljbtfaRSET1GCPD1Zet5zTuB9uWL+sWoGHALplN+z55FITW2ehetBV7108ndssadNh0Ogf3YehD11Rb6Gtcas2QpQkLUpXTZWzqmwtjQCSGe4Y0CqU9foXuzGjA+NoRYF9-szU7jQHx59mxpE8e3BgYOBaxS2B479eiC9yjMUfjMPAq8uIUiDQJKJcSxhMESfUQIRx+AEBgMQbwYABN8D+AAegs8QFBgNTM3xEmJLS1DbMOY88wbgLm3PHEPsfSUPmSD2ZC6oGAgWsBmb4DEt+sQbOWDsxFxLsX4thq0ilxkDnssuZ0EF-g-RBhQGs+F+zpWhiFaBisvgABBIgiplh-ABMCcEGRTRMFxCIKwUA5BwCtPiO8XUMhckGbyWIAosA6AhIDWA-AZMOHg1BXDr6dD7gfIiRgthiQ0FcYwEg2IBAyCbTEXRLYON-28N8JrRAcghl+A8Ck7XQRgmYOwRguIhiRl0DQC+d5qx2eHPtOgPxdZKgoVYv2y3LOyl4TY2x3w-N3hyBlSIVivi2ES+drx3gaA6UWPynZ+PvBw9W3Mkjpj9ALTJ9kG7ZO+Ao+xmjqIGUGdY9iN8arUBHs06VD8N6cgpKqFEFN+UfBRA2AtE8TMopZkES54LmQwQ73wksxaOgFpe0QBBLAWXvIvJK4F9z34IIAuQ6Z94H4g4MCuDvQYDcbhBgyD9ib63P1d1UKtwE73+hAmeKod8KLhg8f47k3yu4by3yCut6B8TMv5DK7IweAAjtdWYz3RpEDgIgez9mKAMCINIAHDwnBCG4NuIBG4BhbHoFgezIo2n2de4Erx242O2Ccw9AUq9k5c7p-jrnl3o+NNasARPMBxwcZT98bLNYp8M9bJh3kORe08CFjezs1QD3vNBAMGQmRljABn85FP3hV-uwv3wm-2OfhEDe+CT733ft1tBoD7g1Y7-6B+ChOgRIa+nIsAOYbgWMYoIiLmnuAeN+QenuG+3AN+gUP+hMpurovwj+QI72P+3gL+P2Ok7+AORmWkOB+g9AUAPASoKINA5IpB3+aBsEPwAAqg8AWA8CQHwDipYNNE8NhkYBfHwEYBYO7IgFAdAQHoSuIczhgQ4E-vNlId4NCHCAiEiKiGADQDQKQXoBNlhnyPoDNloQfusneLENQbQQwd4PQQofoAgaQe3rYkXAwXAdbqgdYd8D8A8M0AROuHvr7uIaQSdjIKBCXvJvZloDoPZmECQPdLYFyEaPCMZL6JOIYe4Y-jkHEctokfYX7j-o4dbsnP7sUNIn4fPKUKppUCvHgGmBvA0LiGmM0IgA0B0AlNQBlHUKgMGnvCAFYD6NwNAIxJZFAHgNGIwLnvnvZoiEQAsMHA3vZj0Q8H0VAAAAIUgkCrEABscxYoCx0ABmoqeAcADYEARAMkfEemeAIINaAx3AQx9QIxYxBekx0x8qjelxcAKxaxJALI9mbxexTCBxRxJxzRmQQAA)) into core. 

Inline is a pattern where every aspect of component behaviour is defined inline, at the call site: thus you can write encapsulated, stateful component code directly in the middle of a view without needing to write a definition in one place and an invocation elsewhere. This super-declarative crutch is extremely useful for iterative development, even if in practice state concerns can often be abstracted out and the Inline component ditched.

Inline is similar to `m.fragment` - a vnode entity with no default behaviour but that can nonetheless consume and execute lifecycle hooks and store state - except for the fact that fragments can't expose their `vnode` to the underlying tree (in their case, an array of children defined ahead of time).

Two ideas suggest themselves: 
1. Fragment API could be extended to allow functions instead of vnode children, in which case the function would be executed with the fragment `vnode`  as its argument (and `state` as `this`) to compute the subtree.
2. On the other hand, this doesn't cater for inline closure components - and being able to rely on inline closures in hyperscript can be extremely powerful (no more vnode juggling, transparent referential access to non-exotic user-defined state). Perhaps `m.inline` could be provided as an alternative to `m.fragment`? ([demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJFgOgjSmJgICsEAaEAYwHs0AXGFvMAVzTuYiYAEASRJkAFADcAlMAA6aAQMZo4zAWAEBeAWPmL9AiQToALaABMATm2QAGALoC9+gGQvnB5gE8ADjAYaRqYW1mh29sZmUFZsWpraAORcPHxMCR4CbhmKQVExYQ6RIWzOUvLO1syclgq6CgbqGQD82TqtBmAEPpYMzL2+MJku6l09fd5+BBIQMADu7QIt9Q36aHPqYgRbGJYA5pw4LHBlyw2IC4pgm9t7B2zMx60nBueninJv+tNzkjIXApVqrV-gYjBhmMxLHApjN5p8VksVkjDARwZDod9ZtdUbdDg9nsj9K9CQ0wRCoUVoqF-gSVgBfVoM+onJnyQjEUhrLTqbi8fhoMR-eqAmoCLBiEScmDUARbHH7PGPNB0kC0OAwWB8pgIRAgADMAFZEHqAIwgOnUdDYXC6yg0ehMVjsXWELAMbjMMTmBh0O4sAgAIwY5i8Mo+OVhiB0Ui0AD4nKd2aI1mJklqFABhKAMODVGCC8MNWBqRge7m2cqfEUKQsrTFRwVx-7ihIBzgQtJhph0Uh0ADWDZjmnjwCU7pYAGoJwI6RaBAksxB+wI+gIMOZzCuGPOZaWWLT9EyDHSYwmT6qQOrNakVHg9YgTQBOc32Wicvs61AgTA4PBYCDMCYljQBe1RQHgJgQj4cCIAA9LB3A+H2uzGAwWCwf+gHAVAAACJoEPhABsGEAUB0B2heEw2pedDAT4zAvnSQA))

```js
m.inline(function Closure(){
  let count

  return {
    view: () =>
      m('button', {onclick: () => { count++ }}, 'Click to add to ', count)
  }
})
```

**Comment by isiahmeadows** [comment]
@barneycarroll I relabeled this as an enhancement since "meta/feedback" was meant for stuff that's more community-related and less technical. Just a quick FYI. (I'll update the label description to reflect this better.)

**Comment by barneycarroll** [comment]
[createContext](https://github.com/barneycarroll/mithril-machine-tools#createcontext) is in Mithril Machine Tools. Think we’re better off working on these things externally and keeping Mithril solid as an integration target.

**Comment by isiahmeadows** [comment]
@barneycarroll I *really* like your solution - I hadn't even thought of that. 🙂

**Comment by barneycarroll** [comment]
This last year has been a very slow but deep revelation as to how powerful the Mithril lifecycle is!
