### ISSUE TITLE
Make `m.fragment` shadow `m`'s signature overloading logic

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2275]
## Expected Behavior
`m.fragment`'s signature should be as tolerant as `m`, allowing for optional attributes, optional children, and the possibility of variadic children.

## Current Behavior
`m.fragment` throws unless it is given an attribute object as its first argument and an array-like as its second.

## Steps to Reproduce (for bugs)
| Invocation | Error |
| --- | --- |
| `m.fragment()` | TypeError: Cannot read property 'key' of undefined |
| `m.fragment({})` | TypeError: Cannot read property 'length' of undefined |
| `m.fragment([])` | TypeError: Cannot read property 'length' of undefined |
| `m.fragment(_, vnode, ....?)` | Silently fails to render anything |

**Comment by barneycarroll** [comment]
LOL there are tests to account for the validity of these outcomes, but because none of the low-level tests go through the public API, they can't account account for the fact they're impossible to achieve with it.

https://github.com/MithrilJS/mithril.js/blob/next/render/tests/test-createFragment.js

**Comment by isiahmeadows** [comment]
I'm vehemently *for* this.

**Comment by pygy** [comment]
Wouldn't we rather define `m.Fragment = '['` and let `m()` tolerate it as valid? That would le us support JSX fragments.

**Comment by isiahmeadows** [comment]
@pygy I like that idea better, and almost suggested it. I just wasn't sure if we wanted to put the magic in `m` or in `render`.

**Comment by isiahmeadows** [comment]
We could also modify `m.fragment` to return this component if a single attrs argument is passed (making it a closure component):

```js
var FragmentComponent = {
    view: function (v) { return v.children },
}
```

**Comment by pygy** [comment]
@barneycarroll this:`m('div, {view: v=> m(...)})`?

If so, I'd rather not use "view" for this, since a `view` methods is what we use to duck-type components already. I know it isn't a conflict, but it could be confusing for new users. Or maybe not... We'd have to A/B test it :-)

@isiahmeadows that would make sense... I kind of like `m.trust()` as a function though, but it is probably a matter of habit.

**Comment by isiahmeadows** [comment]
@pygy 

> I kind of like `m.trust()` as a function though, but it is probably a matter of habit.

I'm similar, but for similar reasons. Changing habits is pretty easy, though, and this one's as simple as `m.trust(foo)` &rarr; `m(m.trust, foo)`.

**Comment by isiahmeadows** [comment]
@barneycarroll 

> Would this be a good opportunity to introduce view attributes? It's a short leap from what we're suggesting above.

Or alternatively, we could do something slightly simpler: https://github.com/MithrilJS/mithril.js/issues/2050

**Comment by barneycarroll** [comment]
@isiahmeadows excellent ideas. This is another point where the tests account for functionality which is inaccessible from the public API: text and HTML nodes have full lifecycle tests, but it's impossible to achieve this with `m`.

I think it makes sense to have these things as a kind of baked in component to be passed in as the first argument of `m`.

Thus `m.fragment` would be invoked as `m(m.fragment, ...rest)`.

This would make JSX readable and opens the door to `m.link` and `m.inline`.

**Comment by isiahmeadows** [comment]
Also, it'd make Babel/JSX users happy: they could set `pragmaFrag: "m.fragment"` and just use JSX fragments. But this is more a happy side effect than a real *feature*.

**Comment by barneycarroll** [comment]
@isiahmeadows @pygy regarding inline views, may as well leave this to `m.inline`. That way it's the functionality of a specific component rather than Mithril-wide magic.
