### ISSUE TITLE
Simplify vnodes structure and better leverage `m`

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2279]
<details>
<summary>Updates</summary>

- Change `m.vnode.text` to `m.text`
- Clarify how keyed elements work in `m.keyed`
- Add new behavior for keyed elements outside `m.keyed`
- Modify normalization
</details>

*This is part 1 of a broader proposal: #2278.*

This is the first major step of how Mithril would become a lot more component-driven and less component-oriented. I would make most primitive vnode types components, simplify the vnode structure a little, fix normalization, and fix key handling to be much more predictable and consistent.

## Changes to existing vnode types

I would change all the magic string tags to function as new built-in primitive components instead.

- `m.fragment` would become a built-in primitive component, for simplified internals and better consistency with the rest of the framework. Migration is easy: replace `m.fragment(attrs, children)` with `m(m.fragment, attrs, children)` and `[...children]` with `m(m.fragment, ...children)`.
	- This could be implemented in userland via `{view: v => v.children}`, but it exists as a primitive for performance.

- `m.trust` would become a built-in primitive component, with the children automatically joined. Migration for this is equally easy: replace `m.trust(text)` with `m(m.trust, text)`.
	- This joins all its child strings into a single text string, and it doesn't support fragment children.
	- The `vnode.children` property is set to the raw string itself, not an array of children.

- A new `m.keyed` built-in primitive component would be added for keyed diffs. This fixes #2248 by instead just not providing the ambiguity and forcing the user to state their intention. (We could even have TypeScript help enforce this invariant that all `m.keyed` vnode children have keys.)
	- As a side effect, this will likely increase performance by making the check incredibly cheap and jumping straight to either [here for unkeyed](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L291) or [here for keyed](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L308).

- A new `m.text` built-in primitive component would be added for text nodes. This is primarily only used when normalizing, and it'd work as it does now.
	- This joins all its child strings into a single text string, and it doesn't support fragment children.
	- The `vnode.children` property is set to the raw string itself, not an array of children.

These primitive components use single-character tags for their values, reusing the values used to represent them now:

- `m.fragment === "["`
- `m.trust === "<"`
- `m.text === "#"`
- `m.keyed === "."` (As suggested by @pygy)

## Updates to normalization

Normalization would change to always flatten the children, but it would continue to retain `null`/`undefined` values. It would also normalize non-vnode children to text at the hyperscript level, before the renderer sees it. And finally, for `m.text`/`m.trust`, it would merge all children into a single string.

## Updates to key handling

Keys would become a little more special, and all around a little more predictable.

- Inside an `m.keyed` vnode, keys are tracked and moved around by identity.
- Outside an `m.keyed` vnode, if a key changes, the node is simply removed and reinstantiated.

This would enable things like `m(DatabasePage, {key: databaseId})` for easy in-place replacement without resorting to complex patching, while still allowing for more proper keyed list diffs and patches with `m.keyed`.

## Changes to vnode structure itself

Since it's now unused, I'd remove the `vnode.text` property from vnodes. Instead, the relevant text value is put on children. This is equally easy to check as it previously was, since it's as simple as `typeof vnode.children === "string"`.

Also, `vnode.children` is always an array for all nodes that aren't either text vnodes or trusted HTML vnodes. For the cases where it makes a real difference, it's pretty easy to check for a few special cases, assuming the lengths remain the same:

- `vnode.children.length === 0` - Clear element if necessary, skip update process
- `vnode.children.length === 1` - Optimize insertion
    - `vnode.children[0].tag === "#"` - Set `.textContent`
    - `vnode.children[0].tag === "<"` - Set `.innerHTML`
    - `vnode.children[0].tag === "["` - Unwrap old/new and recurse
    - `vnode.children[0].tag === "."` - Unwrap old/new and jump to keyed insertion

**Comment by StephanHoyer** [comment]
Sounds reasonable.

If I have a keyed list I would have to do this?

```javascript
m('ul', m('.', [
  m('li', { key: 'one' }, 'one'),
  m('li', { key: 'two' }, 'two')
]))
```

or is there a simpler way?

**Comment by barneycarroll** [comment]
I'm intrigued as to why `m.vnode.trust` merits a new object, whereas the other vnode type shorthands are all attached directly to `m`. Typo?

**Comment by barneycarroll** [comment]
Not keen on `.` as a reference to keyed lists, because it looks like a typoed className selector prefix.

@stephanhoyer that's the general idea. Mithril currently keeps options open for any given list of vnodes to be keyed or unkeyed, and barfs when it changes partway through. By contrast React shouts at you if you create vnodes in a map without introducing keys. In both cases you have library confusion trying to work out intent and user confusion trying to make the intent explicit — our idea is that by forcing the keyed container as an explicit invocation, we can reduce all those irritating author expectation shortfalls and improve library logic by forking the algorithm more cleanly.

**Comment by StephanHoyer** [comment]
Now as I thought about it some additional thoughts. I really like the simplicity and the power functions, so also like the way `m.trust` works atm. Thats also why I created [tagl](https://github.com/StephanHoyer/tagl). I almost never use `m(abcComponent, attrs)` in my views but rather wrap them in a function `abcView(attrs)` and instantiate the component in the file where the view function is defined.
```javascript
const abcView = (attrs, children) => m(abcComponent, attrs, children)
```

For quite some time I imagine a component API that matches to this school of thought. It's similar to closure components but much simpler and IMHO less confusing, because it omits the concept of a component-vnode completely. It also allows any arguments for great flexibility.

```javascript
function abcComponent(attrs, ...args) {
  // called once
  return view(attrs, ...args) {
    // called on redraw
  }
}

// usage like before
m(abcComponent, attrs, ...args)
```

I also imagine this is much simpler to compute with shorter stack traces and therefore better debuggability.

The logical continuation of this would be to have a `m.component()`-function again 🙈, an use `m` only to create stateless hyperscript-vnodes.

This is quite the opposite route and pretty much a backrole to the 0.x API.

**Comment by StephanHoyer** [comment]
@barneycarroll I got that, good idea. Only wonder about the API here.

```javascript
m('ul*', [
  m('li', { key: 'one' }, 'one'),
  m('li', { key: 'two' }, 'two')
])
```

or even

```javascript
m('ul*', [
  m('li*one', 'one'),
  m('li*two', 'two')
])
```

**Comment by isiahmeadows** [comment]
@barneycarroll @StephanHoyer Those built-in "primitive components" aren't really *userland components*, just they're used like it. Just to reiterate:

> - `m.fragment === "["`
> - `m.trust === "<"`
> - `m.vnode.text === "#"`
> - `m.keyed === "."` (As suggested by @pygy)

The first three will result in minimal renderer change. The fourth is quite arbitrary, so I'm open to whatever.

> I'm intrigued as to why `m.vnode.trust` merits a new object, whereas the other vnode type shorthands are all attached directly to m. Typo?

No, but first, let me correct a couple things:

1. It's `m.vnode.text`, not `m.vnode.trust`.
2. We already expose `m.vnode = require("./render/vnode")`, so no new object is added here.

The reason I'm exposing it from that module is because 1. that's where the normalization exists, and 2. the only places where I'd need to use it are in `render/vnode` and `render/render`. I'd be okay with instead exposing it through `m.text` and just using `"#"` internally - it'd make more sense from an API perspective, too, and I forgot about the reader's perspective.

**Comment by isiahmeadows** [comment]
I fixed `m.vnode.text` to `m.text`, BTW.

**Comment by isiahmeadows** [comment]
[See this comment.](https://github.com/MithrilJS/mithril.js/issues/2278#issuecomment-442003421)
