### ISSUE TITLE
Use Closure components for stateful component examples

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#2291]
As time goes on and with classes becoming standardized in JS, Mithril's original `vnode.state` / `this` conveniences are starting to look a bit strange to newcomers. I think we should feature closures for all stateful component examples, with `vnode.state`, `this` and classes documented in the section on component state.

**Comment by isiahmeadows** [comment]
This was fixed by #2292, just it didn't auto-close this.
