### ISSUE TITLE
How to pass parameters to component when m.mount?

### ISSUE THREAD

**Issue by yulei745** [MithrilJS/mithril.js#2302]
How to pass parameters to component when m.mount？

**Comment by barneycarroll** [comment]
For those who come across this looking for an answer, the solution is to mount an anonymous component and use its view to pass the attributes in to the desired component:

```js
m.mount(document.body, {
  view: () => 
    m(App, {desired, attributes}) // <- pass in whatever you want here
})
```

**Comment by yulei745** [comment]
@barneycarroll I just think this is not elegant enough.

**Comment by isiahmeadows** [comment]
@yulei745 BTW, [this is noted in the docs](https://mithril.js.org/mount.html) as the preferred way.

> To pass arguments when mounting a component use:
>
> ```js
> m.mount(element, {view: function () {return m(Component, attrs)}})
> ```

All it is is an anonymous component returning what you want from its view.
