### ISSUE TITLE
Add a timeout/sleep utility with auto-redraw

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#2304]
This may fall under the too-trivial-to-bother category but it might be a convenient feature that works in the spirit of `m.request`. Instead of writing:

```javascript
setTimeout(() => {
	state.done = true
	m.redraw()
}, 1000)
```

We could have:

```javascript
m.sleep(1000).then(() => {state.done = true})
```

Or:

```javascript
await m.sleep(1000)
state.done = true
```

We'd need to expose the [finalizer](https://github.com/MithrilJS/mithril.js/blob/next/request/request.js#L13) from `m.request` so it could be re-used here.

Alternately would it be helpful to expose the `finalizer` utility so users could build their own redraw-on-completion promise chains?

**Comment by isiahmeadows** [comment]
I'm feeling a strong 👎 myself. [It's not hard to find on npm](https://www.npmjs.com/search?q=sleep), and it's literally a few lines of code to write yourself:

```js
function sleep(ms) {
	return new Promise(function (cb) { setTimeout(cb, ms) })
}
```

And the `m.request` finalizer is a whole different beast - it tries to detect when the promise chain fully ends, and it returns a recursively wrapped promise. I wouldn't mind making it a bit more robust and then exposing it, but even then, [I'm hesitant to include it in core itself](https://github.com/MithrilJS/mithril.js/issues/2284).

**Comment by spacejack** [comment]
> it tries to detect when the promise chain fully ends, and it returns a recursively wrapped promise

Yes, this was the rationale for `m.sleep` as opposed to simply promisifying `setTimeout`. And a timeout that redraws is a utility I seem to need in almost every project. Anyway, I'm not too strongly attached to the idea of it being in core and perhaps the finalizer is less necessary with redraws being async in V2.
