### ISSUE TITLE
`this` returning wrong element reference in v2

### ISSUE THREAD

**Issue by bit-less** [MithrilJS/mithril.js#2319]
### Mithril Version: 2.0.0.-rc.1

2.0.0.-rc.1 issue (not 1.6)

When triggering an event from a hyperscript binding, the `this` returns the element interacted with **instead** of the element the event was bound to.  However, this is **only** a problem if the interacted element is a nested child of the bound element.  See example/demo below.

## Expected Behavior
Using the example, anywhere you click on the `<h2>` should work and the `this` should be the `<h2>` element.

## Current Behavior
If I click on the `<strong>` inside of the `<h2>`, it breaks because it returns the `<strong>` element instead of the bound `<h2>` element.  Again, this is only a v2 problem.  v1.6 and native JS work as expected.

## Possible Solution
?

## Steps to Reproduce
[Demo](https://codepen.io/anon/pen/vQvYrZ)
1.  Click on the black text and see the console returns the correct `this`.
2.  Click on the blue text and see the console returns the `strong` element instead of the bound `h2`.
NOTE: I have the JS dependency pointing to v2.  You can modify that to v1.6 to see that it works with that version via the gear icon on the JS pane.

## Context
Common element binding context.

## Your Environment
* Tested on Chrome (latest)
* Windows 10 Pro (latest), desktop

## Code snippets from demo:
```css
h2 > strong {
  color: #08f;
}
section {
  display: none;
}
section.active {
  display: block;
}
```
```js
console.clear();

'use strict';

function toggleShow() {
	console.log(this);
	this.nextElementSibling.classList.toggle('active');
}

const Comp = {
  view: vnode => m('article', [
    m('h2#step-1', { onclick: toggleShow }, m('strong', 'STEP 1:'), ' Install and configure Git'),
    m('section', 'My visibility gets toggled when the heading is clicked.'),
    ]),
};

m.mount(document.body, Comp);
```

**Comment by barneycarroll** [comment]
Here's the [1.1.6](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOS2fc2DAJwAoBKANwAdNCIDkAVzgwABHBpcI5GmOGi0YCWmURqMmpQDmh2AGUAFpQDu-GcBFCaTFmyhGeNcxDiCHNT974aDAAHjQAorA4tKYQAEZQEGiG7FAYcHAAMt40+AbGsDxiGDoAbjBivmgAvg7a1PIyAMKUWAAOMgC8diIyMqUQMFaI-WiUACaynQB8MlhF3DRKsGIkMsi9fXNF5gBMAMTyMG0AtACMq3Yy1BxKANYj+SYwFtYy1WvzYvJc1IaXYlMABVwgAFGRnRCVNZiGQASWYNAwUCgMgwaHGMiYkEMEi4sgA4hAVHwSJs+l9pDpqACALIAT363ni0GJjMMMBocH0RmemKs5no+kFMkFGHGSUMMm8WMS5DuMHG+Gh5JkAF1SSJqmoRFh8FhKFoaDxxpRyBJork4hN6WsWu1BCAyNJYNTmHgzgA2RC7ACcIA+6GwuEQBHIGSdFGodAYob2MlmPz+PTQfSobi4I32AAYABxgNS1ZgwN0pvoSuBtNL0kZjYKFkRUpbUfAlJblMsyCtVjA1mQJM13QuRl0l5vu0O5xBnANqsiJNB3BAoIM4PBYYnmRRQAACZ3w+89kbxUDw5n8bTgiAA9NetG07ikqFhrxvPNu9wf8J7X5vt0RSBAGh6TaEMQDgchFDaGhZ2qIA) version and the [2.0.0-rc.1](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOS2fc2DAJwAoBKANwAdNCIDkAVzgwABHBpcI5GmOGi0YCWmURqMmpQDmh2AGUAFpQDu-GcBFCaTFmyhGeNcxDiCHNT974aDAAHjQAorA4tKYQAEZQEGiG7FAYcHAAMt40+AbGsDxiGDoAbjBivmgAvg7a1PIyAMKUWAAOMgC8diIyMqUQMFaI-WiUACaynQB8MlhF3DRKsGIkMsi9fXNF5gBMAMTyMG0AtACMq3Yy1BxKANYj+SYwFtYy1WvzYvJc1IaXYlMABVwgAFGRnRCVNZiGQASWYNAwUCgMgwaHGMiYkEMEi4sgA4hAVHwSJs+l9pDpqACALIAT363ni0GJjMMMBocH0RmemKs5no+kFMkFGHGSUMMm8WMS5DuMHG+Gh5JkAF1SSJqmoRFh8FhKFoaDxxpRyBJork4hN6WsWu1BCAyNJYNTmHgzgA2RC7ACcIA+6GwuEQBHIGSdFGodAYob2MlmPz+PTQfSobi4I32AAYABxgNS1ZgwN0pvoSuBtNL0kZjYKFkRUpbUfAlJblMsyCtVjA1mQJM13QuRl0l5vu0O5xBnANqsiJNB3BAoIM4PBYYnmRRQAACu3w2YPJy45HwM7IeKgeHM-jacEQAHoH1o2ncUlQsA+N55t3uD0eTzPL9N23IhSBAGh6TaEMQDgchFDaGhZ2qIA) as flems
