### ISSUE TITLE
Object with "attributes.tags" property transforms into VNodes

### ISSUE THREAD

**Issue by nedpals** [MithrilJS/mithril.js#2322]
## Expected Behavior

Mithril shouldn't touch any incoming JSON responses from XHR/transforming strings into objects that contains a nested property "attributes" with "tags" key inside into a VNode. In short, no modifications to the object.

```
{
  ...some data,
  attributes: {
     tags: ["hello:world"]
  }
  ...
}
```

## Current Behavior

Objects/JSON from XHR with the said keys are transformed into VNodes for some reason. Even outside the Mithril component, once the data with the said nested property is imported, it transforms into a VNode.

Example:
```
{
  ...some data,
  attributes: {
     tags: [
        {
           ...regular vnode object,
           children: "hello:world"​​​​​,
           dom: #text "hello:world"
        }
     ]
  }
  ...
}
```

## Steps to Reproduce

1. Create a state with this object: `{ attributes: { tags: ["hello", "world"] } }`
2. Use JSON.stringify to render it inside any view or console.log the object/state.
3. Expand the contents until you see the tags are now VNodes.

## Context

<details>
  <summary>Additional Information</summary>

## Your Environment

* Browser Name and version: Firefox 63.0.3 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro (64-bit), desktop
* Link to your project: https://github.com/nedpals/sulatcms
</details>

**Comment by CreaturesInUnitards** [comment]
@nedpals have you tried this? 
https://mithril.js.org/request.html#casting-response-to-a-type

**Comment by isiahmeadows** [comment]
@nedpals What does your `m.request` call look like?

**Comment by isiahmeadows** [comment]
I will point out the implementations of neither `m.request` nor `m.jsonp` even reference `m.vnode` internally. The only thing view-related they are aware of is an injected `m.redraw`.

**Comment by isiahmeadows** [comment]
Also, with the internal renderer, Mithril requires values to be objects with a non-`null`, non-`undefined` `tag` property. Anything else gets coerced to a string.

**Comment by nedpals** [comment]
@CreaturesInUnitards hmm lemme try that one.

@isiahmeadows it's just gitlab API pulling the file contents then parses the front-matter into a JS object.

**`m.request`** Code (from here it only throws out a string)
```javascript
   fetchFileRaw(blob_id) {
    return m.request({
      path: "https://gitlab.com/api/v4/projects/:repo/repository/blobs/:blob_id/raw",
      data: {
        repo: encodeURIComponent(Global.repo),
        blob_id: blob_id
      },
      deserialize: (value) => { return value },
      async: false
    })
  }
```

**Processing the data** (This is where it gets processed, then turns into an object
```javascript
fetchFileRaw(file_raw)
       .then(fileContents => {
            return files.map((file, i) => {
              return {
                attributes: // this is where it gets only modified
                  fm.test(fileContents) && fm(fileContents[i]).attributes,
                file_path: file.path,
                filename: file.name,
                contents: fm.test(fileContents[i])
                  ? fm(fileContents[i]).body
                  : fileContents[i]
              }
            })
          })
```

Or maybe I'll try using other key instead of `attributes`. I'll close this one.

**Comment by isiahmeadows** [comment]
@nedpals And if this helps, you generally shouldn't render XHR data directly to the page unless you're fetching a simple string.
