### ISSUE TITLE
Can't find variable: e onclick at .js:106:12 handleEvent at mithril@next:1187:61

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2323]
Mithril 2 throws the exception above when it tries to handle `event.redraw = false`.

**Comment by isiahmeadows** [comment]
@barneycarroll Is this fixed by #2320? Also, could you post a flems? (A stack trace would be nice.)

**Comment by barneycarroll** [comment]
Can't reproduce using what I thought was essentially the same structure, I only managed to get it to happen on a flems I wrote on mobile, and flems wasn't persisting the URI 😭 . I'll close until I can reproduce.
