### ISSUE TITLE
There should be a dropdown to select docs for previous versions

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#2334]
Documentation for previous versions have been available under `https://mithril.js.org/archive/vX.X.X` [since basically day 1](https://github.com/MithrilJS/mithril.js/tree/70b24895394b314da45e3a4d27ee24fa90a3fd2c/archive/v0.1). These should all be selectable from the most recent https://mithril.js.org version, so it's easier to point people to old versions and so it's a lot less confusing to newcomers.

FWIW, it's not like there isn't tons of precedent - Vue, Bootstrap, Angular, and many others already do this for major versions. But unlike those, we happen to have a *very* streamlined docs archival process, so ours would be almost trivial to add.

**Comment by mike-ward** [comment]
I'm currently working on this.

**Comment by dead-claudia** [comment]
Been fixed for a while. Current listing: https://mithril.js.org/archives.html
