### ISSUE TITLE
Changing the order of vnodes  with cached content has weird results.

### ISSUE THREAD

**Issue by darionco** [MithrilJS/mithril.js#2338]
### Mithril Version: 1.1.6
I am working on a 3D mapping application where you can get tooltips attached to geographical locations, when the user moves the map around (since it's 3D) the render order of the tooltips has to change some times to accommodate for perspective changes.

The tooltips hold large, static,  expensive to create content so I create and cache the vnodes (remember the content is static so no anti-pattern here as per the documentation).  At runtime I reorder the tooltips and create new vnodes with their updated positions and then add their respective cached content vnodes.

When the tooltips do not change render order everything works as expected, but as soon as they change order the content starts shifting from one tooltip to the next and sometimes it gets duplicated (depending on the type of content).

## Expected Behavior
That the static content stays inside the appropriate tooltip.

## Current Behavior
Content jumps between tooltips and gets duplicated.

## Possible Solution
1. Recreating the static content vnodes every time the tooltips position is changed
2. Making the tooltip a new component every render also seems to work:
```
m(() => { view: () => m('div', content) }
```
rather than
```
m('div', content)
```

## Steps to Reproduce
https://codepen.io/anon/pen/vvGKzo?editors=0110
- Change the `heightOffset` value on the top right menu
- Observe how the tooltip number changes as the tooltips cross the center line
- Comment line 14 and uncomment line 15 to use `m.trust`
- Change `heightOffset`
- Observe how content changes tooltip and gets duplicated every time the order changes.

## Context
Recreating the vnodes every frame would be too expensive as this is an application that runs in real time and the tooltips can hold a lot of information and sub-nodes. It would be better if mithrill could respect unchanged vnodes.

## Your Environment
See the example under reproduction steps.

**Comment by fuzetsu** [comment]
I think this might just be a keying issue, it seems to work if you add a key property to your tooltip.
If you change the order of vnodes within the same array you need to give them keys so that mithril can maintain the right references. 
```js
m('.tooltip', {
  style: `bottom:${50 + Math.floor(t.y * config.heightOffset * config.heightRange)}vh; left:${Math.round(t.x)}px;`,
  id: t.id,
  key: t.id
})
```
https://mithril.js.org/keys.html

**Comment by darionco** [comment]
duh!
that was my bad, keying totally works.

Thanks!
