### ISSUE TITLE
Mithril should offer an escape hatch to avoid its magic attribute vs property handling

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2340]
### Description

Mithril should offer two magic DOM attributes as an escape hatch for its magic attribute vs property inference (basically `key in vnode.dom`):

- `props: {...}` for properties, even if they don't exist on the target element
- `attrs: {...}` for attributes, even if they *do* exist on the target element

### Why

On some custom elements with unusual APIs, they have attributes and properties with identical names, but the similarly-named attribute might have different semantics than the property.

Plus, [some recent discussion on Gitter](https://gitter.im/mithriljs/mithril.js?at=5c137b69b18e825e3b28c9fe) revealed that `video.muted = true` on Safari sometimes does the wrong thing.

It also opens the door to less hackish workarounds for when there's a browser bug that Mithril doesn't currently have a workaround for, so people don't need to descend into lifecycle hooks for a quick fix.

### Possible Implementation & Open Questions

It'd basically just be moving [these two](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L690-L712) into their own helpers and adjusting `setAttrs` and `updateAttrs` to do two loops, one for inferred stuff and one for non-inferred stuff.

Note that for `input.type` specifically, we should still [keep our IE hack](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L702-L703) and not honor any explicit `props: {type: "whatever"}`. The HTML spec requires `input.type` to be mirrored with the `type` attribute, so this has no effect on modern browsers.

I'll also simplify attribute updating a little (like avoiding the overhead of `setAttr` [here](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L744)) and fix a bug where [this function](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L733) is only called when creating attributes the first time.

### Is this something you're interested in working on?

Yes.

**Comment by isiahmeadows** [comment]
As per discussion on Gitter between @barneycarroll and I, we've decided to just document how we do resolution and encourage `oncreate`/`onupdate` as appropriate when it fails (which is almost never).

**Comment by pygy** [comment]
@klick-barakgall We've all been there :-)
