### ISSUE TITLE
Extend route synstax

### ISSUE THREAD

**Issue by andershol** [MithrilJS/mithril.js#2354]
### Description
Change the route matching syntax to allow constrains on the route interpolations.

### Why
It would be nice to be able to have route like "/:pageid" and "/about" to co-exist and declare that "pageid" in that example is an integer.

### Possible Implementation & Open Questions
Currently I am using a little helper function to implement this, with a routing syntax inspired by aspnet, so the code look something like this, where constraints have been added to the parameter interpolations in three different ways:
```
m.route(siteRoot, "/", fixRoutes({
  "/{pageid}": PageView,
  "/something/{code:int}": PageView,
  "/something2/{id}": PageView,
  "/edit": About,
}, { 'int': '\\d+' }, { 'pageid': '\\d+', 'id': 'int' }));
```
But the "fixRoutes" relies on the internal implementation details of "route" (e.g. that the routes are not being escaped). So this issues is a request to make the "fixRoutes" function redundant or to at least not remove this "extension point".

### Is this something you're interested in working on?
Perhaps, but I think there is little code involved.

**Comment by isiahmeadows** [comment]
If you could simplify the design a little, I'd be a little more in support. (I've run into other cases where I could've used it.)

Alternatively, a means from `onmatch` to skip a route (maybe by returning `m.route.skip`, `"skip"`, or similar) and move to the next route could work. This would let you make a `guard({param: /re/, ...}), onmatch?)` helper that works like this:

```js
function guard(re, Comp) {
    return {
		onmatch(params) {
			if (
				Object.keys(params).some(key => !re[key].test(params[key]))
			) return m.route.skip;
			if (typeof Comp.onmatch !== "function") return Comp;
			return Comp.onmatch.apply(Comp, arguments);
		},
		render(vnode) {
			if (typeof Comp.render !== "function") return vnode;
			return Comp.render.apply(Comp, arguments);
		},
	}
};
```

And for yours, you could do this instead:

```js
const int = /\d+/;
m.route(siteRoot, "/", {
  "/:pageid": guard({pageid: /\d+/}, PageView),
  "/something/:code": guard({code: int}, PageView),
  "/something2/:id": PageView,
  "/edit": About,
});
```

You *could* still do a `fixRoutes` with my proposal, but it'd be relatively complicated to implement.

**Comment by andershol** [comment]
What kind of simplification are you looking for? (it is just that "simple" is rather subjective) For my current project I am really only using the form demonstrated for "pageid", i.e. the same pattern is used for all occurrences of each parameter name and I have few parameter names, so you might not need the other forms (but fixRoutes is just 9 lines, only one non-trivial, it wasn't a big deal to add them all).

I considered something like what you suggest and I think this is similar to issue #1792 , but as you say it requires changes to mithrill and I needed something now. I don't like your particular guard suggestion as it has the patterns (or "types") repeated for each route and the goal for me was to make a compact/readable syntax,

Maybe what I want is to give "route" a proper extension point so my extension could be less of a hack, i.e. issue #2055 .

Btw, here is a link to a page describing aspnet routing that I was inspired by:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing

**Comment by isiahmeadows** [comment]
@andershol I'm aiming for "simple" from an API perspective, the minimum viable addition that enables you to create what you need - I'm not keen on internalizing a complicated utility or feature without it being similarly broadly useful, especially if it's a syntax extension.

And for your request, #2055 is *not* what you need - that deals with letting people read routes from things other than `location.hash` and friends.

You *could* still implement your `fixRoutes` as you have them with my proposal, just note that this strips the extra curly braces on either side:

```js
// This uses `guard` as defined above, but you could just as easily inline it.
// Wholly untested, so you may need to test it first.
function fixRoutes(routes, types, paramTypes) {
	const fixed = Object.create(null)
	for (const route of Object.keys(routes)) {
		const clone = {...paramTypes}
		const fixedKey = route.replace(/:([^\\\/]+):([^\\\/]+)/, (_, param, type) => {
			clone[param] = type
			return `:${param}`
		})
		const regexps = {}
		for (const key of Object.keys(clone)) {
			regexps[key] = new RegExp(`^${types[clone[key]]}$`)
		}
		fixed[fixedKey] = guard(regexps, routes[route])
	}
}
```

**Comment by isiahmeadows** [comment]
@MithrilJS/collaborators I'm leaning toward a "nope" here aside from adding a simple `m.route.SKIP` to skip to the next route from `onmatch`. This sound okay?

**Comment by andershol** [comment]
It seems that you in RC6 have removed the "extension point" that made my fixRoutes possible. So a m.route.skip would be very much appreciated.

**Comment by isiahmeadows** [comment]
@andershol If you'd like, feel free to file a PR. I'll warn that the routing implementation is a bit of a mess, but the two relevant files are `api/router.js` and `router/router.js`.
