### ISSUE TITLE
m.request self signed certificate

### ISSUE THREAD

**Issue by dlepaux** [MithrilJS/mithril.js#2362]
## Expected Behavior
m.request() function work fine in my production environment (server side). But not in my webpack-dev-server (with self signed certificate).

## Current Behavior
I got an unhandled error when m.request() is call, the route is reach, but the issue append when the response is sent.

## Steps to Reproduce
I have open an issue on the webpack repo
https://github.com/webpack/webpack-dev-server/issues/1636 [closed]
And also done a exemple to reproduce the issue:
https://github.com/dlepaux/webpack-dev-server-issue-exemple

## Context
I am working on an isomorphic application, so I need to execute m.request() on server-side.
The issue does not append when we use `axios`.

```
const data = await axios.get(`https://localhost:3000/api/v1/efforts`).catch((e) => {
  console.log('Efforts: Catched error', e);
});
vnode.state.efforts = data.data;
m.redraw();
```

## Solution
Leave m.request to axios... :(

<details>
  <summary>Additional Information</summary>

## Your Environment
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): OSX 10
* Link to your project: https://github.com/dlepaux/webpack-dev-server-issue-exemple
</details>

**Comment by isiahmeadows** [comment]
What specifically is your error?

**Comment by dlepaux** [comment]
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443}
[object Object]
    at process.<anonymous> (/Users/dlepaux/code/webpack-dev-server-exemple/webpack.dev.babel.js:12:11)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:485:27)
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Node NOT Exiting...

**Comment by isiahmeadows** [comment]
@dlepaux To clarify, are you running Axios in the browser outside Electron/NW.js/etc. and it still somehow working in this case? [Browsers are *supposed* to reject self-signed certificates for XHRs](https://stackoverflow.com/questions/4490723/javascript-xmlhttprequest-ignore-invalid-ssl-certificate), so Mithril will see this as an error no matter what. FWIW, [there's no way to tell from JS-land in browsers certificate errors apart from DNS or similar errors](https://stackoverflow.com/questions/31058764/determine-if-ajax-call-failed-due-to-insecure-response-or-connection-refused), so there's nothing Mithril can do here. According to the first link, you could add the self-signed certificate manually to your trusted store locally, and that should let XHRs work as usual (and by extension, Mithril's `m.request`).

**Comment by dlepaux** [comment]
No it is running on Server Side.

**Comment by isiahmeadows** [comment]
@dlepaux Then per the [first link](https://stackoverflow.com/questions/4490723/javascript-xmlhttprequest-ignore-invalid-ssl-certificate), there's nothing Mithril can do for you. You won't even be able to get the native XHR or `fetch` API working. The proper fix is to add the self-signed certificate to your machine's trusted store, and adding a certificate to a store is something you can easily Google if you don't already know how to do that.
