### ISSUE TITLE
Support inserting unescaped strings in templates

### ISSUE THREAD

**Issue by dymk** [MithrilJS/mithril.js#238]
Perhaps there's a way to do this already, but the documentation for `m()` does not mention it.

How would one go about inserting an `&nbsp` in a template? It seems that Mithril escapes strings by default, which is nice, as that means safety by default. But, there aren't any flags, or "safe" wrappers, to override this behavior and write a view like: 

``` js
m(".zone-num",  {class: z.zone_status_class()}, [
  m("span", "Zone"),
  "&nbsp;",
  z.num()
])
```

Currently Mithril escapes the `&nbsp;` into `&amp;nbsp;`.

**Comment by elbow-jason** [comment]
+1
