### ISSUE TITLE
Mithril with BSS - Better Style Sheets

### ISSUE THREAD

**Issue by alfredocodekit** [MithrilJS/mithril.js#2382]
BSS fits perfectly with the Mithril ecosystem. Even the author exemplifies with mithril.

https://github.com/porsager/bss

**Comment by isiahmeadows** [comment]
The issue tracker is for questions, feature requests, and bugs regarding Mithril. This belongs on something like [awesome-mithril](https://github.com/orbitbot/awesome-mithril) or linked to [on our Gitter channel](https://gitter.im/mithriljs/mithril.js).
