### ISSUE TITLE
Ospect: Any appetite for `.includes` and `.notIncludes`?

### ISSUE THREAD

**Issue by RobertAKARobin** [MithrilJS/mithril.js#2385]
### Description

Add Ospec tests for `.includes` and `.notIncludes`.

### Why

I frequently want to test whether `Set A` is a subset of `Set B`. The way to achieve this now is something like:

```js
o(["a", "b", "c"].includes("b")).equals(true)
```

...which is a little clunky to write, and yields a failure message like:

```
false
 should be
true
```

...which isn't super helpful. I do want to be sensitive to Mithril keeping things minimalist, though.

### Is this something you're interested in working on?

Yes

**Comment by isiahmeadows** [comment]
I'd be okay with this if it's generalized to also try `a.includes(b)` and `a.indexOf(b) >= 0` as fallbacks. It's also worth discussing if `Symbol.iterator` support should exist or not.
