### ISSUE TITLE
Assertion descriptions documented in the README don't work

### ISSUE THREAD

**Issue by RobertAKARobin** [MithrilJS/mithril.js#2391]
## Expected Behavior

According to the [Ospec readme](https://github.com/MithrilJS/mithril.js/blame/next/ospec/README.md#L45), this:

```js
o(1).equals(2)("addition should work")
```

...should yield something like this:

```txt
addition should work
1 should equal 2
Error
  at stacktrace/goes/here.js:1:1
```

## Current Behavior

It throws two errors: one a standard Ospec failure...
```txt
1
  should equal
2 
```

...the other not:
```txt
o(...).equals(...) is not a function 
```

## Context
* The readme is inaccurate
* This feature is useful for making tests more verbose

## Your Environment
* Browser Name and version: Chrome 72.0.3626.109
* Operating System and version (desktop or mobile): Mac OS 10.13.6

**Comment by isiahmeadows** [comment]
Found the issue: [this](https://github.com/MithrilJS/mithril.js/blob/next/ospec/ospec.js#L294-L296) needs moved down a couple lines. PRs welcome!
