### ISSUE TITLE
TypeScript Definitions for 2.0

### ISSUE THREAD

**Issue by godenji** [MithrilJS/mithril.js#2394]
### Description

There are typings available on DefinitivelyTyped for Mithral 1.x, but not yet 2.x

### Why

TypeScript users would benefit from typings for 2.0 (not to mention hopefully using TS 3.x with Mithral)

### Possible Implementation & Open Questions

When is 2.0 GA release coming?

### Is this something you're interested in working on?

I only just discovered Mithral via Lichess' open source github projects.

**Comment by isiahmeadows** [comment]
Please file this over in https://github.com/MithrilJS/mithril.d.ts, where the types are developed.
