### ISSUE TITLE
"JavaScript" is inconsistently capitalized

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2398]
[Throughout the docs](https://github.com/MithrilJS/mithril.js/search?q=Javascript&type=Code), I'm only seeing "JavaScript" capitalized in two ways, both incorrect:

- "javascript"
- "Javascript"

Out of that entire search, only the occurrences in the code block language tags and the MDN URL are correct - everything else needs fixed.

-----

This is an easy bug to fix, so if you want to file a patch, feel free to do so. We've already got #2397 to kick it off. And it'd make a good first pull request as you don't really need to get into code much.

**Comment by Ayushjain9501** [comment]
Hey!
I would like to work on this and correct them.

**Comment by isiahmeadows** [comment]
@Ayushjain9501 You can start out by forking this repo, cloning it locally, and making the changes you want. This [GitHub Help page](https://help.github.com/en/articles/fork-a-repo) goes into pretty good detail on this, if you're not as familiar with Git basics. Unlike most repos, our main branch is `next`, so before doing anything else (including creating a branch for your patch), you should first switch to that branch.

**Comment by Ayushjain9501** [comment]
How is the change log supposed to be updated?

**Comment by Ayushjain9501** [comment]
Ok! seems like I misunderstood the Issue.
I'll redo it and make a PR then
