### ISSUE TITLE
vnode to html

### ISSUE THREAD

**Issue by eGirlAsm** [MithrilJS/mithril.js#2399]
### Description
is there have a function vnode to html

```
import m from "mithril";


var template1 = {
    view: function(content) {
        console.log(content);
        return m('template', {
            id: 'tab-main.html'
        }, '<ons-page>' + content + '</ons-page>')
    }
}

m(template1,m('p','hello world')) 

output

object object
```

**Comment by 1337M0nst3r** [comment]
I don't really understand what you want to do, maybe you could provide some more information but if you want to get the dom representation of a vnode maybe vnode.dom will help you: https://mithril.js.org/vnodes.html

**Comment by StephanHoyer** [comment]
https://github.com/MithrilJS/mithril-node-render

1337M0nst3r <notifications@github.com> schrieb am Sa., 30. März 2019, 13:35:

**Comment by eGirlAsm** [comment]
> I don't really understand what you want to do, maybe you could provide some more information but if you want to get the dom representation of a vnode maybe vnode.dom will help you: https://mithril.js.org/vnodes.html

for example
m.expand('p','hello world') -> return string  <p>hello world</p>

**Comment by isiahmeadows** [comment]
As @StephanHoyer pointed out, the correct thing to use for this need is https://github.com/MithrilJS/mithril-node-render/. It *does* also work client-side, but it's generally unnecessary.

The original comment's code does *not* require this, however:

```js.diff
 import m from "mithril";
 
 
 var template1 = {
     view: function(content) {
         console.log(content);
         return m('template', {
             id: 'tab-main.html'
-        }, '<ons-page>' + content + '</ons-page>')
+        }, m('ons-page', content.children)
     }
 }
 
 m(template1,m('p','hello world'))
```

**Comment by eGirlAsm** [comment]
```
let div = document.createElement('div')
m.render(div, m('p', m('span',m('i','ok'))))
console.log(div.innerHTML)
```

**it works for me**
