### ISSUE TITLE
Uncaught TypeError: m is not a function

### ISSUE THREAD

**Issue by designMoreWeb** [MithrilJS/mithril.js#2406]
I followed the tutorial and am trying to run the program however i am getting the error in the console:

> Uncaught TypeError: m is not a function
  and the code is 
`var m = require("mithril")

var UserList = require("./views/UserList")
var UserForm = require("./views/UserForm")
var Layout = require("./views/Layout")

m.route(document.body,"/list",{
    "/list": {
        render: function () {
            return m(Layout, m(UserList))
        }
    },
    "/edit/:id": {
        render: function (vnode) {
            return m(Layout, m(UserForm, vnode.attrs))
        }
    },
})

`

the error is given by : 

>  return m(Layout, m(UserList))

**Comment by osban** [comment]
Are you using Webpack? If so, try `var m = require('mithril').default`On Apr 14, 2019 20:46, Divy Tolia <notifications@github.com> wrote:I followed the tutorial and am trying to run the program however i am getting the error in the console:

Uncaught TypeError: m is not a function
and the code is
`var m = require("mithril")

var UserList = require("./views/UserList")
var UserForm = require("./views/UserForm")
var Layout = require("./views/Layout")
m.route(document.body,"/list",{
"/list": {
render: function () {
return m(Layout, m(UserList))
}
},
"/edit/:id": {
render: function (vnode) {
return m(Layout, m(UserForm, vnode.attrs))
}
},
})
`
the error is given by :

return m(Layout, m(UserList))

**Comment by designMoreWeb** [comment]
I am using it and still getting the error

**Comment by osban** [comment]
Cool 👍 
Yeah, all the requires should be like that.

**Comment by isiahmeadows** [comment]
This will be fixed by #2366 once resolved.

**Comment by dead-claudia** [comment]
Resolved per linked issue.
