### ISSUE TITLE
If we are selecting any event and clicking on view,after clicking on OK it is giving an error message

### ISSUE THREAD

**Issue by zaidmir5** [MithrilJS/mithril.js#2412]
function checkExistingSchemaName(schemaName){
			var array = [];
			var dataObject;
			
			$('#tableEventCatalog tbody tr').each(function() {
				var values = [];
			
				$(this).find("td").each(function() {
					values.push($(this).text());
				});
				array.push(values);
			});
			
			$table = $('#tableEventCatalog').bootstrapTable({
				data: array
			});	
			var dataObject;
			var result=true;
			dataObject=JSON.stringify($table.bootstrapTable('getData'));
			var parsedData = JSON.parse(dataObject);
			$.each(parsedData, function(name, value) {
				var dbSchemaName=value.schema_name;
				var areEqual = schemaName.toUpperCase() === dbSchemaName.toUpperCase();
				if(areEqual){
					result=false;
					toastr.clear();
					showNotification(false, schemaName + ' is used in pre seeded event catalog, please use a different name');
					return false;
				}
			
  			});
			
			return result;
		}
Actual result:
When i click on ok button it gives me message showNotification(.......),

Expected Result:
There should be no error message on clicking ok.

**Comment by osban** [comment]
@zaidmir5  It would be useful to post the relevant Mithril code, and how this function is called.

**Comment by zaidmir5** [comment]
if(areEqual){
				result=false;
				toastr.clear();
				showNotification(false, schemaName + ' is used in pre seeded event catalog, please use a different name');
				return false;
			}
here if condition is satisfied and it gives the message ....
![image](https://user-images.githubusercontent.com/48056293/57772522-39e72d80-7733-11e9-99f5-221aaaaece0f.png)

**Comment by osban** [comment]
@zaidmir5 So far I haven't seen any Mithril code (like where is that 'ok' button you mention?), and neither something like `onclick: e => checkExistingSchemaName(e.target.value)`.

**Comment by zaidmir5** [comment]
//onclick of row event catalog end
						
						$('#tableEventCatalog').bootstrapTable({}).on('check.bs.table', function (e, row, $element) {
							var dataObject=JSON.stringify(row);							
							var parsedData = JSON.parse(dataObject);
							modifiable = parsedData.modifiable;
							
							if(modifiable ==='true'){
								$('#editEvent').prop('disabled', false);
								$('#deleteEvent').prop('disabled', false);
								
							}else{
								$('#editEvent').prop('disabled', false);
								$('#deleteEvent').prop('disabled', true);
							}
						});

**Comment by zaidmir5** [comment]
@osban if you check the above code if condition is satisfied and when i click on the ok button it gives me the error message refer to screenshot what can i change after the if statement ,so that i can close the model when i click on ok button

**Comment by osban** [comment]
@zaidmir5 if I understand correctly, your `checkExistingSchemaName` function shows a modal with the `showNotification` call? If so, how does `showNotification` look like, and how do you display the modal?

**Comment by zaidmir5** [comment]
@osban 
![image](https://user-images.githubusercontent.com/48056293/57773969-ea0a6580-7736-11e9-8a69-0a9b2b5b8ff8.png)

**Comment by osban** [comment]
@zaidmir5 I suppose you could close the modal in an `onfocus` event in your 'Schema Name` input field.

**Comment by isiahmeadows** [comment]
@zaidmir5 The Mithril issue tracker is for questions and concerns that *pertain to Mithril*. Please keep that in mind when filing issues. Thanks!
