### ISSUE TITLE
Classes in first and second args to m() not merging as expecting

### ISSUE THREAD

**Issue by onlyskin** [MithrilJS/mithril.js#2413]
## Expected Behavior
On both initial rendering and when a diff and render occurs, classes in the first and second arguments to `m()` are expected to be merged. (https://mithril.js.org/hyperscript.html: "If there are class names in both first and second arguments of m(), they are merged together as you would expect.")

## Current Behavior

On initial render of the below component, the div element successfully receives only class `big` (first path of ternary). On click, it correctly receives class `big` and `blue`, (second path of ternary) but on a further click, (first path of ternary again), the div incorrectly receives no class.
```
const Page = {view: ({attrs: {text}}) => {
    return m(
      '.big',
      text === 'not blue' ? {
        onclick: e => globalText.content = 'blue',
      } : {
      	class: 'blue',
        onclick: e => globalText.content = 'not blue',
      },
      text,
    );
  },
};
```

## Steps to Reproduce
Open, then click on 'not blue', then click on 'blue'. The final 'not blue' should still have class 'big', but it does not.

https://jsfiddle.net/onlyskin/x7jgoep5/23/

```index.html
<head>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mithril/1.1.6/mithril.js"></script>
  <style>
  .blue {
    background-color: blue;
  }
  
  .big {
    font-size: 3rem;
  }
  </style>
</head>
<body>
  <script>
    const globalText = {
    	content: 'not blue',
    };
    
    const Page = {view: ({attrs: {text}}) => {
        return m(
          '.big',
          text === 'not blue' ? {
            onclick: e => globalText.content = 'blue',
          } : {
          	class: 'blue',
            onclick: e => globalText.content = 'not blue',
          },
          text,
        );
      },
    };
    
    m.mount(document.body, {view: () => m(Page, {text: globalText.content})});
  </script>
</body>
```

## Your Environment
Chrome 74.0.3729.157 (also seeing same behaviour in Safari)

**Comment by osban** [comment]
This might be because in `function compileSelector(selector)` the .class is only pushed to the classes array, and not also assigned to `attrs.class` (and thus not saved in `state`). The problem seems solved when changing `else if (type === ".") .classes.push(value)` to `else if (type === ".") {classes.push(value); attrs.class = value}`, but maybe I'm overlooking something...

**Comment by osban** [comment]
@onlyskin You could also choose to do something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIA5lFoAjDFAAqMAB5SAvJOAAdNLuJDGDRJIDk5-a337xUgAoZpMSdr1pJkgG4QYAdzMACgBKNwA+SX0vLywg83x5CGlzCh1omK9qKAw4ODNZBSVVDXxjEQoMzPpsiGoAazNXTUjgQsUVdWIy+hMtSQBCduKunuEGSQB+C3koAFcYczNLG08Y9iqZOQ6S7vKJgB8DizRaKVmFqzWQ61s0LHwsWjmGIIATWmo5nAZE2jeAJ5pJwuEKUEBwGCwajECD0BA8ACMAGZEAAGNgcECYHB4Mp5cH7UQ8RLzVweLyKBrSABOzzQbwAtHQ5DSzBcYABuW4GNCJZLpNZgXqMuAQABeMDMyJpMCw3LQrHBkOhsPheAAbIhEYy0ei2ABdKhQCBoeoI1DYrh4LAQYiEGnQcFzGnkHgkYgAB3yAHofS9PfVpD0sD7bfbHVAAAKI-CxjVhu0O6D4fjg4gAz3cCHUR2e0TsTi4njyAlUF1ukAe72IP0BoMhn2luAx-AAVjjTbyqYEIAzWbwcFzEHzhtYQA), separating the `class` logic from the `onclick` one.

**Comment by onlyskin** [comment]
@osban Thanks! I worked around it by setting the class attr to empty string in the first branch, that seems to force the correct behaviour.
```
const Page = {view: ({attrs: {text}}) =>
    m(
      '.big',
      text === 'not blue' ? {
      	class: '',
        onclick: e => globalText.content = 'blue',
      } : {
      	class: 'blue',
        onclick: e => globalText.content = 'not blue',
      },
      text,
    )
}
```

**Comment by osban** [comment]
@onlyskin Yes, as long as the `class` attribute is always present (even if empty, `null`, or `undefined`), things work fine. I think usually something like `{class: condition ? 'classname' : ''}` is used, which is why not many people run into your issue 😉

**Comment by isiahmeadows** [comment]
This is a bug. `class` should not be removed wholesale in that scenario. However, [it will be fixed in v2](https://jsfiddle.net/twhnz1d5/1/).
