### ISSUE TITLE
Doc JSX : babel-core and babel-preset-es2015 depreciated

### ISSUE THREAD

**Issue by souricevincent** [MithrilJS/mithril.js#2415]
Already, sorry for my english.

In the documentation for JSX there is lib depreciated.

`babel-core` should be replaced by `@babel/core`.
`babel-preset-es2015` should be replaced by `babel-preset-env` and `.babelrc` should look like:
```
{
  "presets": ["env"],
  "plugins": [
    ["transform-react-jsx", {
      "pragma": "m"
    }]
  ]
}
```

**Comment by LosEagle** [comment]
also `babel-plugin-transform-react-jsx` should be `@babel/plugin-transform-react-jsx`
