### ISSUE TITLE
Travis is currently failing to talk to GitHub

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2417]
[This relevant line](https://travis-ci.org/MithrilJS/mithril.js/builds/538753119#L560) is showing an issue with the `after_success` script. Just a friendly reminder to myself that this needs fixed and fixed quickly.

**Comment by isiahmeadows** [comment]
This is a v2 blocker, BTW.

**Comment by isiahmeadows** [comment]
So diagnosed: the SSH key was initially presented as non-existent, and now it's successfully installing. So it's not an issue with docs generation, but just a general SSH setup issue that suddenly appeared. All fixed now (by swapping out SSH keys)!

**Comment by isiahmeadows** [comment]
Reopening since the underlying issue wasn't solved (repro'd locally, having a similar setup and figured it out from there).

**Comment by isiahmeadows** [comment]
Updated the title. Insult to injury: the key isn't authenticating, either. Need to test if I can repro that locally and fix it if necessary. (*Hopefully*, this is the case.)

**Comment by barneycarroll** [comment]
Can we close this @isiahmeadows ?

**Comment by isiahmeadows** [comment]
Closed. Things seem to be working now.
