### ISSUE TITLE
m.request issue with mithril 2.0.0-rc.5

### ISSUE THREAD

**Issue by fuzetsu** [MithrilJS/mithril.js#2419]
### Mithril Version: 2.0.0-rc.5

A JSON api request that worked in all previous mithril versions, and that works with standard fetch/XHR does not work with 2.0.0-rc.5

**To be clear**: most requests seem to work, maybe it's only an issue with CORS requests (based on the error)?

## Expected Behavior

Should return JSON response

## Current Behavior

Throws error.

## Steps to Reproduce

[See this test here for a reproduction and comparison with other methods that do work.](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqEAB4ARgFdOnaAD4AOlAAEygLLlO7AE6Vl2sKwCsS0QHopM+acuyoiles069B1gBZTF6XYcSf1o4AYoicYOxetoH+VvZKqgAaABIASpEB9nx4SGCc5NDUaEYoAJwgAL5E9EwsIKwAVtQkkAJCnCItMJzKktrwygC8ygDkXJy4KGZmAO6zrNoE+JqskIxm2maY8PANcFDDSuSM2BDa3Qj4asqk2hCMI4zOuvAAAgBMrAAMXwC0bu4HKBKTrdeAQADmg2UAA9BnJlMB4spOghECskJhtAAKACUSIWnF6KmwWOheKg5SUwIK3XYmCg+CQ2hgUJoSNxcOUjHmiAAjpJEF0sb14DjWFohFiweCcUR2TjORc1Dz+YLOMK+mKJVApRDZfK4UjVKRQuENaKjaplOL2JKFiyBvD7btoLjyVarTbJdL9Y4OY6EZaQTCdFCoIhpsoEmoADJJGTYFJ8gVC91W6E6VgQbCS4bg0LDIg9TWWjPaHkwE6wRAAFQAnjmocNGtBAR6y1moGDMPgof74dLSZn7VW8GnVB28AzcUjKVAALpUqAAQW02kwddYNzuWPwEDAkmYAlY+c4AFEkEfODAAEJ1muYcEAORqWOGUX2suUWPEnCgRfIfAyU5H8-07MB4HIMAAGsoTpBkmRgGhAOheccXJLJEByPIChEN5ik+CoqhABhmBEFYYCafhBGENAKnnEhIKgaDCjoEiahER4tGed4vl+NwjD4EURDGCYpkkKBsGg8EVjuMwuJcV4Pm+T4-kMIx5KeShWEeKBdj4TgG1qGAwF0bB2nKedyiAA)

## Context

<details>
  <summary>Additional Information</summary>

## Your Environment

* Browser Name and version: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows
* Experienced the same behavior on Edge 41.17134.1.0
</details>

**Comment by osban** [comment]
When adding a `catch`, it returns `{ [Error: null] code: 0, response: null }`, maybe that helps.

**Comment by fuzetsu** [comment]
Thanks @osban , there's also this in the console:

> Access to XMLHttpRequest at 'https://www.reddit.com/r/all.json' from origin 'https://r.flems.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by fuzetsu** [comment]
Also, request headers with rc.4:
![image](https://user-images.githubusercontent.com/848652/58646157-d0d6ec80-82d2-11e9-808f-be494557ae09.png)

and request headers with rc.5:
![image](https://user-images.githubusercontent.com/848652/58646136-c583c100-82d2-11e9-96fe-b8922ac8c3f7.png)

🤔

**Comment by sphynx79** [comment]
Same problem mithril@2.0.0-rc.4 work fine with http get request but when upgrade to mithril@2.0.0-rc.5 not work.

**Comment by fuzetsu** [comment]
@sphynx79 is your request cross origin like mine?

**Comment by isiahmeadows** [comment]
[Simplified it and repro'd it without Mithril, just with both native `fetch` and native XHR.](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqEAB585AG4ACMFhgwAvAB0QAJwgB3VQD5lUadPFTZ8paqwAjRPF37DhgGKJOYdintGA9BMl6DRpYArpyc0NLk+CpkLm4AtFAQcZACQpxxnACe2Ih2AYYAchDSAAYAwtCCAnEAKtmIJZ6iXsGh0P5NrWEGkdGksexxmuScgylV6Vk5eQ7SAOoj7KUVqdV1OY0BzV3t+s2+HVDGMnKYCtEa2iD+hsemZ+YgVjYzDgAaABIASh5bPlI3QIhboRKKqAAe7DUCSS4zSGXqr0KxXKlXh6waTRawN2UE6OJ6YJAkOhw1GyTR1SmuWunkMC1Gy0p6Qxm1u2LaUH8+wBfDwSDAnHI0GoaAATCgAIwABiIkoArCgABwgAC+RHoTBYIFYACtqCQ4cI0KQglBBcKDAASfqudgACkiRGkEGwnBgAEppMBPPgIGAgswBKwAOYuACiSCDnAAQpkAJL4R34D2saBychgADW0kU0lN5qF4XtXp9+XzA3tAHIuJxcCgvF5NM3WGoCBJOKxIIwvGovJh4PA9XAoFXna73R66dJWKMhPaCxbi2pS9I25wgmoDGpZ4hwZwS9JVVPy7P2PPF0WDPa2zBsCLEKuUnAkKx4BAQzfEHeH17j55VX0QC8SgS9LWkK0SWTZ0UgoENS19f1AzSUMIyjNI40TZNU3TeBMxzPMwOLBDy0kTA1GkElc2kKBEE0aQ3gAWQAGQ+UJsC+RAAEcgm-A8T1mEk0xyKBqwAcXDGox2kGt2JgBsmxbNt8A7LsIB7PsByHfVoCrASHCE6A20wfBMhgThMEENxMCgMNqKI68SNmQxyFIaR7SE4zTIAZQswRc0UPMABYnOcwxnwQRA3w-DyoVbb971gRAaj3Th9NmYCMunVz3Ng8h4NkaA4NildpyEvAoCTfTgOA-QbUrVRbXiRIKVWSZERAE96rte1GoGIZFlaiYEWmYhvXPEzEDUeTvU8VQVmGjFVBQaRVBwbA8LASzLS8HSoAAblkdhyLwThFBCUg4iVVQiCA-8QMgqFeuJKEYSG+FqVULqoIhV6yTGZkRppZ0HPcklQvKlxOJ4viPkQSa1Gehb0Q6501uwDbM226BdpHQ7rOmlxzs4S7rs6oCPT5GxECXWARDFIKUAAZnlOIGZQeVpTVDUQAYZgRC7BQ+CNTgBcuaQAGoZ3FstDEYciQ3IKAMldFbJUQRh9qA-R9FbLRpB2AxZekCQ7ywTIVssd9sy1gJ5bURXlbCbAVulVh5Q123VSpgUr1FEBFUlAB2NUAF1VSAA) TL;DR: PR incoming, just the solution isn't as obvious when you go into the details of the problem.

------

Here's what's going on:

- Mithril v2.0.0-rc.5 is now setting `Content-Type: application/json; charset=utf-8` for known JSON requests unless `Content-Type` is explicitly specified in headers. (This is before the `config` is run, so you can set it there, too.)
- [The WHATWG Fetch spec only whitelists `Content-Type` attributes that can skip CORS checks](https://fetch.spec.whatwg.org/#cors-safelisted-request-header):
	- `Content-Type: application/x-www-form-urlencoded`
	- `Content-Type: multipart/form-data`
	- `Content-Type: text/plain`
	- For the purposes of this section, stuff like `charset=utf-8` don't matter. Just the MIME type.

So prior to introducing that MIME type (as recommended by other specs/RFCs/etc.), Mithril was requesting JSON with an implicit `Content-Type: text/plain` (the browser's default) for `GET` and `TRACE` requests, and this of course doesn't require CORS checks. This was the behavior in Mithril v2.0.0-rc.4, and in Mithril v2.0.0-rc.5, I changed it to apply that check for *all* requests instead.

For context, here's how some other libraries handle it:

- jQuery doesn't. They don't add headers at all that the user doesn't provide.
- Angular [does what Mithril v2.0.0-rc.5 does and just blindly adds it to everything](https://github.com/angular/angular/blob/3511f08a81ce4a4e6e72e926224bf223ae1f0c2d/packages/http/src/backends/xhr_backend.ts) (pardon the very Java-like TypeScript)
- Axios [will add it only to requests with bodies, but it still adds it to everything](https://github.com/axios/axios/blob/master/lib/defaults.js#L52).

I'm going to follow roughly what Axios does and only set the body if it's `!= null` (before serializing), ignorant of method.

**Comment by isiahmeadows** [comment]
Fixed and published in a new prerelease.
