### ISSUE TITLE
contenteditable attribute has different behaviour depending on case

### ISSUE THREAD

**Issue by onlyskin** [MithrilJS/mithril.js#2424]
## Expected Behavior
contentEditable and contenteditable should have the same behaviour (https://mithril.js.org/hyperscript.html#dom-attributes: Mithril uses both the JavaScript API and the DOM API (setAttribute) to resolve attributes. This means you can use both syntaxes to refer to attributes.)

## Current Behavior
Specifying attribute as `contenteditable` results in correct input behaviour, while specifying attribute as `contentEditable` results in broken input behaviour with cursor moving to the start of the input box.

This occurs whether the content editable attribute is specified in the tag string or the attrs object.

## Steps to Reproduce
See the following example: (typing in green input box has correct behaviour, typing in red box has incorrect behaviour, only different is capitalisation e.g. `contenteditable` vs `contentEditable`)
[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evVFoB3GACdqGODER6A5M4rHTdnFDsOnr9xM9ADcIGAsnWQBKPQBeAD4PUz0sWSTklzd05NTnZCFGYXkIYgx1WABdNwNsjNN6CDQAByliJxg4+L1iQgg4fHMrW3sO2L0YfFLrAHMYYkmYAA9iAGF6QuJAurq4Ym1YJ2BNa3kbfwBGJsW9OFooCHk9aesYJmd2WuT2FMnrKV3ZD0+gNLDZfDAolEtnVcvl1iIAKLFUrlGBVfRGILbepoRotNrjTrdXr9LwwHwjOLjSYYGZzBbLNbCBjQ7E3PYHAzHU7WC5XG53B56F7yd6surfcTEP4AoGkrgUhyQ8UZKLGVhRADclBADlg1GIEHoCB45wArIgAMxsDggTA4PD4ahwAQ0eHMHhsCpUe5oADWJtQdq4YhKhGs0Hw-B1Ums5B4JGITTgiAA9KmZE0-dMnbQsKmsGGI1AAALnfDlgBsBaLkejVD2TW4uuoEaaolY3uDDp4hZ6xajcD0BREMGRZVgbCAA)

## Context
Mainly just very confusing and spend a lot of time not understanding why contentEditable wasn't working.

**Comment by isiahmeadows** [comment]
I see the issue: our existing `contenteditable` workaround [here](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L126-L128) and [here](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L499-L501) doesn't also check for the camelcased variant. Thanks for the report!
