### ISSUE TITLE
Re-define purpose of `key` attribute

### ISSUE THREAD

**Issue by yossicadaner** [MithrilJS/mithril.js#2434]
Currently the `key` attribute is defined for the sole purpose of key ordering. However, keys are used not just for ordering but for identifying a view bound to a property. 

For example, in a toggle component:
- Toggle button
- View based on toggle view [keyed]

Re-initializes component  upon toggle button change

**Comment by isiahmeadows** [comment]
You can already mostly do this by wrapping the element in question in a single-item fragment:

```js
[m(Toggle, {key: whatever})]
```

I'd be okay with updating the docs with this pattern if it doesn't already have a section on this, but no special support needs added.

**Comment by yossicadaner** [comment]
@isiahmeadows Yes, I agree. My request is for updating the docs so that new members don't consider expanding or modifying it's functionality for a single pattern.
