### ISSUE TITLE
Error handling of blobs in m.request

### ISSUE THREAD

**Issue by iJebus** [MithrilJS/mithril.js#2438]
### Mithril Version: 2.0.0-rc.6

I'm not sure if this is expected behavior to be honest, but it caught me out.

## Expected Behavior

When `m.request` has `responseType` set to `blob` and an error is returned, the error returned should be an [Error ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).

## Current Behavior

When `m.request` has `responseType` set to `blob` and an error is returned, the error returned is a `blob`.

## Possible Solution

If an error has occurred, ignore the `responseType`?

## Steps to Reproduce

1. Make a request to a known-bad URL with `responseType` set to `blob`.

## Context

There's an API ([url-to-pdf](https://github.com/alvarcarto/url-to-pdf-api)) I'm hitting that returns a PDF, but it often crashes so I need to be able to handle these. Also just, handling errors in general.

I actually originally found what's probably a separate bug in that if `responseType` is set to blob and `extract` is defined, no error is caught at all and normal flow occurs. However maybe it's intended to be that way and manual error checking should be done as part of extract?

<details>
  <summary>Additional Information</summary>

## Your Environment

* Browser Name and version: Firefox Quantum 67.0.3 (64-bit)
* Operating System and version (desktop or mobile): Windows 10
</details>

**Comment by isiahmeadows** [comment]
Could you provide a [repro](https://flems.io/mithril@next) to clarify?

> I actually originally found what's probably a separate bug in that if responseType is set to blob and extract is defined, no error is caught at all and normal flow occurs. However maybe it's intended to be that way and manual error checking should be done as part of extract?

Yes, that's intended behavior - in many cases, when you're manually extracting, an error might be returned with status 200 or, more commonly, a legitimate non-error returned with 4xx.

**Comment by iJebus** [comment]
Thanks @isiahmeadows, with your comment and some more time to read through the requests code I now understand what's going on. TL;DR it's my bad and there isn't a bug, just my misunderstanding. The longer version is that I was expecting Mithril to try parse an error response as JSON regardless of the `responseType` specified, which it doesn't (and probably shouldn't /shrug), and I was misreading my console output. Sorry to have wasted your time!
```
