### ISSUE TITLE
m.parsePathname: extra slash is returned

### ISSUE THREAD

**Issue by AlexPetrov7311** [MithrilJS/mithril.js#2440]
### Mithril Version: 2.0.0-rc.6

returns an extra character '/' when using the a function

## Expected Behavior
when I used the function `m.parsePathname('https://example.com/cart/add?par1=1&par2=2');,` 
I expected to see
```
{
  "path": "https:/example.com/cart/add",
  "params": {
    "par1": "1",
    "par2": "2"
  }
}
```

## Current Behavior
now returned `path: "/https:/example.com/cart/add"`

**Comment by osban** [comment]
@AlexPetrov7311 In Chrome/FF/Edge it seems to [work as expected](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgAOUuDACKAVxiSAngGVikiGgDm0gLzSwKtNWIR6ACji79BitIAmGYhgAMASmnAAHTQA6zBpW3dPLxNTNBUoKD9I7xN-ViCQiDD7R0MY0wCQQukAHxLpBz0841j4xOlJGGIVSTQ0jNDwyqd8akIpAEFiW1986UKAfkK-buqK3IN8OCgIahhbAEYfDokZET14VNnFuFkV4cKAMmmXOgtGSThU4HTg4jBaGVtd6QhUrwA3L9pAAeaT7CDwfCwQzEQhAiAAakRfkCbxCP32GlSEPgyAgAF0lmcIBcQMZph0MVJpABrGAaDapVwwOgsgCqACUAJIAYVoWFk9BEtixyC8BO26OIPwkUDU0VMWOhTAMcLGACZpBM3KzaByefzBcKGKKGJpkBtJdJEOMikVpVlwnKFWNCro1NNpC6YIrpB6YFTGFBFL9sj7FTU7WAMCHAyA-BHUjG40GfrAxDAQ6l6YziedbAB6AIBAkl5ATErlwtSkLUmTUFpwT7MjzeINO2y5jb4fQsgAeAHkwLZCsgvQA+aQAWi20gzWbg+CFslsteIIQ+Xx+vD9gOku9B85gmZDKth8IPXmRqKD9ePp9SC5DyF3BJcaBg-eIABkT1mn3-F9D0RaQrTvGUaQgOAADkVCwAAjdRUk-b8-0fKNCmKMppAAQmgmCMBg2x5EeGBuVNVDfyAlwNl8dc60gmRoIANVjNRUkPGpTGfJcYTVQgZzAiDO2fN17VvaVGJ+btANPJdllWdYvBcXcfHwXhaH0NcIMybI7mER5kG7AkYmkOIEkkxjrOIAyHjgYyGStVIBkkSQMA0Xs4Fc9yNFsRtHk+PwdQC5tJHPASbWkLxdOIV4bJCMTTDs9QHJM5EIPijdss7Vj2JgPxQs+ZBn1M0wIwgxcYDDcIiskEqgLK2pLOkOqGtPMrflg+CkJkHVkFM20XggurUja0qgyyrLGmaVo3DbGK0HitAflIxQAAUPEITAcGTCwrBsNBbBaeo0XvABHNRNAogc-RO3s0AHYdRxAKYEx2Gl+jgQgbq-O7JCgB6npHQoAGJKTeH5LvUDQAFFHr9L6fsev6j2iHV7v49VbSR37+0W+95DheHXD9aHrpR-G0e1aRybhhGorpvGCaYuQtq1Ux7sUtYRhcInCBJ3x8EaM4MB54sAkLYANQoVhC2cO1i3eyGaVI7AnlMYa3k7XD+Y1Pw9dSQolY6Kr-A7bI9fFUzcMwkAlYN9mjft4pQL1i3wj1iL1SnJlLkuNm4Q1ZAvaxwTpzApqChdhNA8IDm441JYVh5lSZy2DossLQtpBg2hGFtOF4GqqRqsaTMyNcaQkOoDAVFDAADNblCu7QFgb6QMFkWQmFcJ41ZweyOmz6R6CgbEnSL7FXHoAByYhwX7aDiHwaR1tgDBQxntB57MFZZH9QgYCwfAOk7JnKeiCdTFGZvVBhnQqgMY6AeTpTbAv27pFAjYXDpwWfB8ykOrdcnZcaX2kNfaKjsyL300I-JwL9Abc3WOAr+P9AFs3clgOA64ZotDaMAfmto9ZAOwXAEhwCcGvGWquZum04Q7XWLPEgxBZAUOzl+bAZwYC9AFIWWukhiCFgwK4VwExSIbGMBsS4pENTGA1LPHwPhKAgEULAA69AEA8AAMwakQF4NgHAQBMLwL0OAAgaD0EYMwHgbB3wgBWGgWk2jUAmK4HgLApJCB6HIFQE6eBWHsMQNnCwshaSLDoFgQsXi4S+IAAI9h7AANhid43xGlLHEA0D3PAcBqB6FkKIdgnAcB4AQhY1RASeBBI4YWMJES+HRIqXARJ+AACs+ANiFhaZk1R2Tck8HyYU4pBJWBAA)?

**Comment by AlexPetrov7311** [comment]
not. It works with an extra slash.

**Comment by AlexPetrov7311** [comment]
double slash disappears after http

**Comment by isiahmeadows** [comment]
Now that I'm taking a second look at this, this is operating by design. I'll clarify in the docs that this is specifically for *local* paths, used for routing. If you need general-purpose URL parsing, use [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) - it's made for that very thing.
