### ISSUE TITLE
Re-using hyperscript nodes leads to wrong updates on m.redraw()

### ISSUE THREAD

**Issue by dvdkhlng** [MithrilJS/mithril.js#2441]
## Expected Behavior

Looking at the docs, I think it should be ok to keep around copies of nodes returned by m() and re-arrange them (unmodified) into a new parent when view() is called.  Note that I never try to have the same node referenced more than once within one node tree.

## Current Behavior

However, in practice this leads to strange updating bugs, where the DOM rendered by Mithril diverges from the nodes returned by view().

## Steps to Reproduce

Minimal example of the observed unexpected behaviour is here:

  https://jsfiddle.net/97qthkp1/1/

Pressing "update" adds new <a> nodes, and at more than 3 nodes we throw away the oldest node when appending a new node.

However, running this in the latest Firefox, this fails to properly re-order the node list after the 4th press of "update", only updating the first <a> node and still showing the old nodes that are already gone.

## Context

This issue happens in some experimental code that generates and updates potentially large SVG charts. I'm new to javascript and mithril, so maybe I didn't get some obvious fact that explains this all.

## Workaround

Always re-creating the m() nodes with the same parameters (instead of keeping around the object reference) works around the issue, but looks pretty suboptimal to me (suspecting possible interference with the tree diff'ing).

## Your Environment

* Browser Name and version: Firefox 67.0.4 (64-bit)
* Operating System: Destop / Ubuntu

**Comment by osban** [comment]
@dvdkhlng did you try adding a `key` attribute, like `this.queue.push(m("p", {key: Date.now()}, this.count.toString()))`?

**Comment by dvdkhlng** [comment]
@osban: you are right, adding a key attribute fixes (or works around) the issue:
https://jsfiddle.net/q0Layhw8/1/

Does this have any effect on the validity of the bug report?  I'm a little lost, the Mithril manual does not have any example code that keeps around references to nodes to be returned in view().

**Comment by isiahmeadows** [comment]
@dvdkhlng Not a bug, but undefined behavior. When you're mutating `this.queue`, that's being returned as a literal fragment vnode, roughly equivalent to `m.fragment({}, this.queue)`. Mithril uses `this.queue` directly as the children of interest, and mutating that counts as [mutating a mutable vnode](https://mithril.js.org/vnodes.html#avoid-memoizing-mutable-vnodes). To clarify how the docs apply here:

> Vnodes are supposed to represent the state of the DOM at a certain point in time. Mithril's rendering engine assumes a reused vnode is unchanged, ***so modifying a vnode that was used in a previous render will result in undefined behavior.***

(Emphasis here, not in docs)

If you *really* want this behavior, add `key`s to all the vnodes in question and then return `this.queue.slice()` instead. That way, Mithril will at least know identities moved around. But in either case, don't do this. [Just generate the vnodes as you need them and use `key`s as necessary.](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABFogROOgLw78EMAFdmA1gCMI+AJ4BuADpQPAegBUO+AYA1jD+5IGIOgDuEdoRUIY6mPAB0fg6nBB6iJyWWlDp7BEw0jrx+BEQdnKIYEak+ow6MJZ2eACOlqoeOn7q5IiRABQAlDpgSfAwrDo6AHKIBOmZWogAtGArmIIFEaSWyekrFeqIuphQaRAnWgCEPV4eHpq6AMIQjNjQqiY6wI-5MzGEEsAhQOgAjERuoCOohOmCaABdKEAmZlRBgqD7eAowE6aEzSzYfBbDE6PZQWrkaAjX7-PF48ikHSDTjschTWGdVhIKAAczZOgAfKYAMzDAkMv6ohl4tkc1hcxCsGDs0icEbuGV4sSSuXszmdbnYSyq1kG1iQEGcVgZADKnC05H5I2GWr1gPlUytAgA1L6tbKZoxWCt8FpMEM3ZKJJLJX0BmCKVSaaNpR6Zs8moh4MzTF7A0GM1kcnkdIxBm4QPhyOoq7ig42dDQK1W7JZOBlPMRftAwPByGBAkmQSn8rTgNnc6wiSTBJqdGIJPiQLPSVXhg2m7LW9Xa-WCgqlaxGDhBsnONTx2A0yXcvld9gD8BlzfF8NN8XtzNEV+g9HtUBGMPF1TwoBDRhgQEQZ9EMIgdDeD4vgEACPD4PAkDHag0AAJgAThQAB2cFxEkEAGGYERLRgRR+EEYQ0HEZEQAHKBgloKRKLQRhyDZJ14HkWjcl4NAuE4XAUC8LwQWwQI+Utd4vB4vjKAAARw1gAAYtNWLQwFYAA2JTePYfjBL4TgnGwGQYA2chsDUMRETEIA)

**Comment by osban** [comment]
@dvdkhlng If possible in your case, you could do something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIstACYwokgLyTgAHTSTJdAK4NEkgAwUNWkQCcI8A8gC6G1ho3ipjCcskAKAJTKAfKqm0nIK+LoMHoZBQS6SOgAOshiMHj7+gZpawfJQYbR6xADUhUFaEGBeMjn4FlZw+LBoAObEhJJ+KgCsvlWhtfD4cITlxD6l2X0MlgPxOkOevbnhUoWSaiCSALRrG6toMADukgAiyTA+3kGOmUHmMMQ65prqmVoAblYHBmlKfuNaWE8AHJZBA3kCTK8sgDgYQAIwQnYAFXgxHW3kh0OhgKBACMdMRiPREcB6NQoBBqABrb6+X5xRJnHzsHYAYQAMgBJVkAaXRmKxMKBhAATIiAAYAOR0WFxMHMkloFXJlKpcAMABJgIs8gVWOKMf8sjr+vUsBh4p4AB7pHGg8EUSRW7yXKFaV1aa7XDRYfAyAqeWS0agykT4XFyACejrcxG8lBAcAUMGoxAg9AQPBFABZEIY2BwQJgcHgwnABDR6IxmDw2LYqBS0GqkKgi1w8FgIK1LOQqI9yDwSMR4uqAPSjvTxKlNPJYUed7vQAACcPwq4AbPOu4Qe-h+AniJH4txE9RLPFRKxbKwgA), so instead of working with vnodes, work with data.

**Comment by dvdkhlng** [comment]
@isiahmeadows : modifying queue after I gave it to Mithril was something that I totally overlooked.  Ouch.  Javascript semantics take some time to getting used to...

@osban, yes will move to working on data instead of nodes.

thanks for your helpful comments.

**Comment by isiahmeadows** [comment]
@dvdkhlng 

> modifying queue after I gave it to Mithril was something that I totally overlooked. Ouch. Javascript semantics take some time to getting used to...

Mithril is rather unique among vdom implementations in that it mutates the vnodes it receives. So don't worry, especially if you're coming from a different virtual DOM framework like React. (I didn't make that design choice, BTW.)
