### ISSUE TITLE
m.request defaults to string instead of JSON in IE11

### ISSUE THREAD

**Issue by bit-less** [MithrilJS/mithril.js#2442]
### Mithril Version: 2.0.0-rc.5/6

Since rc.5 and now rc.6 as well, `m.request` does NOT default to JSON for IE(11).  It's a string that has new lines.  NOTE: The extract method is NOT used.

## Expected Behavior
`m.request` should default to return JSON for IE11, and not just the other browsers.

## Current Behavior
This returns JSON in non-IE browsers, but returns a string in IE:
```
m.request({
	method: 'GET',
	url: `./i18n/language-bundle.json`,
})
.then(function(data) {
	i18n = data;
}));
```

## A workaround we've done in the meantime
Our current workaround to be cross-browser supported:
```
m.request({
	method: 'GET',
	url: `./i18n/language-bundle.json`,
	deserialize: str => typeof str === 'string' ? JSON.parse(str) : str,
})
.then(function(data) {
	i18n = data;
}));
```

## Steps to Reproduce
```
m.request({
	method: 'GET',
	url: `./i18n/language-bundle.json`,
})
.then(function(data) {
	i18n = data;
}));
```

## Context
It took a while to narrow down that this was the issue because of the unhelpful errors IE gives, but at least we isolated it.  rc.4 and earlier worked great.

## Your Environment

All desktop OSs, but IE11 is the breaking point.
</details>

**Comment by isiahmeadows** [comment]
What's the value of `xhr.responseType` in `config`? Trying to see how to alter my workaround, as I don't have an IE VM readily available to test.

**Comment by isiahmeadows** [comment]
If it returns `""`, that's convenient since it aligns with what Chrome returns for invalid values, too, and it simplifies my workaround.

**Comment by bit-less** [comment]
Yes, IE returns `""`, whereas Chrome returns `"json"`.  Good catch.
