### ISSUE TITLE
m.request runs code inside `then` and `catch` block both

### ISSUE THREAD

**Issue by rebootcode** [MithrilJS/mithril.js#2467]
### Mithril Version: 2.0.0-rc.7/mithril.min.js

I am doing a simple Post request using `m.request` and when the result is success, it still runs code inside "catch" block

My Code looks like this in short:-

```
return m.request({
    method: "POST",
    url: "/register",
    body: JSON.parse(JSON.stringify({ "email": "test@example.com", "name": "test" })),
}).then(function (res) {
    console.log("doing success");
    if (res.success == "done") {
        console.log("doing done");
        csrf = res.csrf;
        return window.location = "/#!/verify/account";
    } else {
        console.log("doing error");
        swal("Error", res.error, "error");
    }
}).catch(function (err) {
    console.log("not working - yet, here");
    if (typeof err.response != "undefined") {
        swal("Oops", err.response.error, "error");
    } else {
        console.log("why am I here? after then");
        swal("Oops", "Something went wrong! Please try again - If Problem persists, contact support!", "error");
    }
})
```

## Expected Behavior

The expected behavior is when the network returns the correct value, then it should not run code inside the catch block.

## Current Behavior
When I click on register -> If there is an error, then only "catch" block runs", but when there is no error, that is return value is correct with 200 success, it runs the code inside "then" and "catch" block both.

## Steps to Reproduce
1). Please visit the demo URL from browser - http://ec2-18-237-100-56.us-west-2.compute.amazonaws.com/#!/start

2). Please open "console".

3). Now, fill any dummy data and press "Next", you will see console filled with messages :-

```
doing success
doing done
not working
why am I here?
```

but if you see the code, you will notice below log message is part of "then" block

```
doing success
doing done
```

and below log message is part of "catch" block

```
not working
why am I here?
```

But that should not happen, it should never return or run code inside catch block when it is running for "then" block.

**Comment by nickolasgregory** [comment]
It looks like your issue may be related to this code;
`return window.location = "/#!/verify/account";`

You should probably be using the [router](https://mithril.js.org/route.html)

**Comment by rebootcode** [comment]
> It looks like your issue may be related to this code;
> `return window.location = "/#!/verify/account";`
> 
> You should probably be using the [router](https://mithril.js.org/route.html)

I am already using router - if you see demo URL in steps to reproduce and check the source code, you will see the following code -

```
m.route(root, "/start", {
    "/start": Register,
    "/verify/account": AccountVerification,
})
```

**Comment by nickolasgregory** [comment]
`m.route.set('verify/account')` instead of using `window.location`

**Comment by isiahmeadows** [comment]
@rebootcode I dropped a debugger at the entry points of both the `.then` and `.catch` callbacks. You declared `csrf` as `const crsf = ...`, and of course you can't assign to that, so it's throwing a `TypeError` that's finding its way to your subsequent `.catch`. This is why `err.response` is `undefined` and it's running in both. All's good from Mithril's end, just a simple user error here. 😉
