### ISSUE TITLE
Missing implementation of URL templates with m.route.Link

### ISSUE THREAD

**Issue by erikvullings** [MithrilJS/mithril.js#2477]
**Mithril version:** v2.0.0-rc.9

**Browser and OS:**: any

## Code

**Flems:** see [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIIjLJIC8k4AB00k6QBNEkgCwAmVawDcq1VnwAnJhpgWAFKvUba1AK44G+AEa0NATwpHSSw7cwtaV0Z8ABkINABrCiVJQiswbWUQAHoYDRksxAgNTKTaAAdiCHo4bWBJMowLbBrkou0ZGHMiyVZepIByLD9JKDj4-oBKVQmTNEoQOBhYakrqvAAORAAGNg4QTBw8fGo4ARp6RmYeNgBdKlGEhBROQ54sGVToAAEANz18LYAgC0Fmo+AAnPNXBZyDwSMQyjUsllXGgyvEAObHWhYLLvYifKBff6ArYgsHgvEfCzQfDvND4fjzYh+MrcBbUGkVW6sIA)

```javascript
// Code
const item = {
  id: 42
};

m.render(
  document.body,
  m(m.route.Link, { href: "/edit/:id", options: { params: { id: item.id }}}, 'my link')
);
```

## Expected Behavior
As the documentation specifies [here](https://mithril.js.org/route.html#mroutelink), I would expect that the created link contains the supplied parameters, e.g. in the example above, if `item.id: 42`, it should link to `#!/edit/42`.

## Current Behavior
The parameters are ignored, and the URL template is generated as such, i.e. the link becomes `#!/edit/:id`

**Comment by isiahmeadows** [comment]
The fix is two-step:

1. Remove that from the docs altogether for now. It's wrong, and there currently isn't that functionality.
2. Add a `params:` attribute to `m.route.Link` to add that functionality directly. The name here aligns with `m.request` and `m.jsonp` who use it to similar effect.

**Comment by isiahmeadows** [comment]
Do note that adding the `params` bit will wait until a minor update to v2, potentially v2.1.

**Comment by isiahmeadows** [comment]
Okay, that snippet was removed from the site docs. The only thing remaining is part 2.
