### ISSUE TITLE
Re-name vnode.tag so that the name 'tag' can be used in attrs

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#2478]
**Mithril version: 2.x**

**Is this something you're interested in implementing yourself?** Maybe

### Description
Re-name the `vnode.tag` property to something less likely to be used in an application. Eg: `vnode.__TAG`

### Why
Using the property `tag` in an Attrs object will cause Mithril to treat that attrs object as a rendered vnode rather than as parameters to send to the component hooks. This would be surprising behaviour if you're not aware of that reserved property name.

### Possible Implementation
Hopefully can be done mostly with search and replace and tests.

### Open Questions
This would be a breaking feature for applications or libraries that may have used the `vnode.tag` property directly. How should this affect versioning?

It might also be a better name for the `selector` attr used in `m.route.Link`.

**Comment by isiahmeadows** [comment]
I'm considering this for my redesign work, but I don't want to waste 8 bytes per vnode just to have a separate discriminator field.

You *could* put it on the prototype, but then I'm adding complexity to the vnode factory.

**Comment by isiahmeadows** [comment]
So I've been considering it, but I don't want to waste memory doing it.

**Comment by spacejack** [comment]
After discussing it today, I prefer your other ideas of having the Vnode type inferred some other way, like from the prototype. This would not be a breaking change and would make `attrs.tag` available to applications.
