### ISSUE TITLE
Mithril website not responding

### ISSUE THREAD

**Issue by camillo777** [MithrilJS/mithril.js#2480]
**Mithril version:**

**Browser and OS:**
Chrome on Android 8

**Project:**
https://mithril.js.org
https://mithril.js.org/simple-application.html

## Code

```javascript
// Code
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

Chrome browser loads forever the page with a blank page.
Is it normal?

**Comment by osban** [comment]
Seems to work fine on my phone (Chrome on Android 8).

**Comment by camillo777** [comment]
Just leave the page open in background for some time like 30-60 minutes, when you come back to Chrome the page cannot load anymore.

Other Chrome pages load just fine.
I always keep lots of tabs open.

**Comment by osban** [comment]
It has been open since my previous post, but granted, only 3 tabs are open.

**Comment by lhorie** [comment]
IIRC it's hosted on github pages, and Github was having an outage

**Comment by isiahmeadows** [comment]
Yep. Received Twitter alerts about it. Closing since their outage was resolved.

**Comment by camillo777** [comment]
I have now problems as well accessing the web site. Maintenance is still ongoing? 
It is a random behavior...

**Comment by isiahmeadows** [comment]
@camillo777 Next time you run into issues, open the browser console, reload, and see what status code it spits out. It'll usually give some insight as for what's going on. If this persists, ping me either on [Gitter](https://gitter.im/mithriljs/mithril.js) or [Twitter](https://twitter.com/isiahmeadows1) (I have open DMs), and I'll try to work with you to figure out what's going on.

**Comment by isiahmeadows** [comment]
For now, I'm locking this issue.
