### ISSUE TITLE
Move ospec to its' own repo

### ISSUE THREAD

**Issue by thequailman** [MithrilJS/mithril.js#2483]
**Mithril version:**

**Browser and OS:**

**Project:**

**Is this something you're interested in implementing yourself?** Probably can't

### Description

If ospec is going to be a separate package, it should be in its' own repository.

### Why

My npm keeps using the ospec bin installed from mithril instead of from the ospec package, causing problems.
### Possible Implementation

Move ospec to its own GitHub repository.

**Comment by isiahmeadows** [comment]
Not against that, and we could remove the ospec binary short-term. I'd prefer to wait for a semver-minor update to not surprise people, but it's not like we document the fact ospec is shipped with Mithril anyways.

**Comment by isiahmeadows** [comment]
I'd like to give v2 some time to sit first, though.

**Comment by dead-claudia** [comment]
This happened ages ago. Best to close out.
