### ISSUE TITLE
I made a logo, who should i send it to?

### ISSUE THREAD

**Issue by samuelgozi** [MithrilJS/mithril.js#2488]
I made a logo for the project, and I would like to show it to whoever can decide whether to use it or not. Who should I send it to?

**Comment by isiahmeadows** [comment]
Send it to me, and feel free to reach out to me at either contact@isiahmeadows.com or through a Twitter DM at https://twitter.com/isiahmeadows1. 🙂

We've been considering changing things up for a while on the design front, just haven't yet gotten to it. It's been on the back burner for probably over a year at this point.

**Comment by samuelgozi** [comment]
Sent you sn email.
