### ISSUE TITLE
XHR CodePen snippet example doesn't work

### ISSUE THREAD

**Issue by tjkorthal** [MithrilJS/mithril.js#2491]
**Mithril version:**
2.0.1

**Browser and OS:**
Chrome 75.0.3770.142, macOS 10.14.6

## Code

```javascript
m.request({
  method: "PUT",
  url: "//rem-rest-api.herokuapp.com/api/tutorial/1",
  data: {count: count + 1},
  withCredentials: true,
})
```

## Steps to Reproduce

Go to the last CodePen example in the introduction on Mithril.js.org, under XHR (https://Mithril.js.org#xhr), click 'Run Pen', and click on the '0 clicks' button.
## Expected Behavior

'Click' count should update when the button is clicked
## Current Behavior

The REM API responds with a 400 error with a message of "Missing JSON input"
## Context

It looks like the request should be using `body` instead of `data`. [Here](https://codepen.io/TJKorthal/pen/RXoNMR) is a fork of the CodePen with the change made.

**Comment by isiahmeadows** [comment]
Fixed
