### ISSUE TITLE
Key handling in 2.0.3 seems too strict

### ISSUE THREAD

**Issue by ArthurClemens** [MithrilJS/mithril.js#2496]
In updating [Cyano](https://github.com/ArthurClemens/cyano) where shared code is used in a Mithril and React project, I've encountered a problem where code can be made compliant with either Mithril or React but not both.

**Mithril version:**
2.0.3

**Browser and OS:**
any

## Code

It appears that the main problem is that Mithril does not recognise keyed array children as keyed elements. For example:

```javascript
return [
  m("div.wrapper",
    // { key: "controls" } // <= This needs to be uncommented for React 
  ),
  [1,2,3].map(n =>
    m("div",
      { key: n },
      n
    )
  )
]
```

When `{ key: "controls" }` is added to the wrapper, Mithril expects other children of the wrapper div to have keys too. The child elements in the code above in fact do have keys, and React recognises this, but Mithril asks for keys to be added.

And where React shows a warning for missing keys, Mithril code simply won't run.

If this is intended behaviour, it is not clear from the docs how to handle this case. But the current behaviour would be unfortunate because specific "nitpicking" rules need to be memorised when coding for one platform or the other.

I've created 2 flems projects with [both Mithril and React versions](https://gist.github.com/ArthurClemens/d667fcdcc9e46621d287f88bc371d9ef).

**Comment by isiahmeadows** [comment]
It all comes down to a single subtle semantic difference between React and Mithril: React flattens inner arrays, but Mithril doesn't. So `[h("div", {key: 1}), [h("div", {key: 2})]]` ends up processed this way for each:

```js
// React
// Everything's flattened, so everything's keyed as you would expect.
[
	h("div", {key: 1}),
	h("div", {key: 2}),
]

// Mithril
m.fragment([
	h("div", {key: 1}),
	m.fragment([ // Lacks a key, so an error is rightfully thrown here
		h("div", {key: 2}),
	]),
])
```

I used `h` to alias `React.createElement`/`m` to show the difference a little better.

You have two options:

- Spread the mapped array into the parent array so React and Mithril have the same flattened structure. This is probably the easiest, but I'm not sure if React adapts the way Mithril does in this scenario and it's obviously not a generic solution.
- Use an explicit fragment (Cyano can provide the fragment tag: `React.Fragment` for React, `"["` for Mithril, or it can sugar over it like `m.fragment` does) for the second fragment and either add a key to the fragment or remove the key from the upper div.

In both cases, it's about ensuring Mithril and React see the same underlying vnode structure. And in this case, you need to either explicitly flatten for Mithril or explicitly *prevent* flattening for React. And it may be worth mentioning this need in the Cyano docs, maybe even checking for it yourself on the React side so people are less likely to be tripped up.

As it stands, it's everything working as intended on the part of both frameworks, just in a way that isn't the most helpful for you specifically.

**Comment by ArthurClemens** [comment]
Thanks for the elaboration.
