### ISSUE TITLE
Sharing information between modules

### ISSUE THREAD

**Issue by livtanong** [MithrilJS/mithril.js#25]
When I make prototypes for webapps, I like making sample data generators in js (rather than in the database, because why even use databases in prototypes).

My data involves a list of users, and a list of government projects that they request. I generate the list of users first by pulling data from randomuser.me via m.request(), and then I make them generate the list of projects. These are methods within their own controllers (and their own modules), which I instantiate in another controller.

Because routing necessarily requires that I use different modules for each route, I'm at a loss at how to share this data between different modules. The only way I can think of is assigning it to a global variable

```
var data = {}
data.users = new User.controller();
data.projects = new Project.controller();
data.users.genUsers(5).then(function(){data.projects.genProjects(50)})
// genUsers and genProjects create the lists at data.users.list, and data.projects.list
```

And I'm trying to avoid this because global variables are yuck. Maybe my mindset is wrong? I'm too used to angular services.

**Comment by vicvinc** [comment]
Hi~ Im new to Mithril. Is there any docs about parent and children component communications? I meet the same confusion about component communication. for example, my app have some init data(boots data), which only need to load once every time,but I found when the route changes to the different component, when it routes back, this would be reloaded, I think this kinds of data should be put in the root component, and every child component could get them while the data has been loaded. Is this the proper way to solve the problem?

Also, I found that if I dont push every browser history in an array and pop url to redirect, the window.history.back api would go back 2 steps... Its very weired while clicking the browser's back button there seems no problems at all, maybe some thing happened while redraw the view,but I can't debug it, Is there any docs about debug ?

and.. the last, I found that while Im using the default args in components, the view will not be rendered, 
I dont know why..

sorry about my English :)

**Comment by isiahmeadows** [comment]
@vicvinc I'll address these piece by piece:

1. You need to be using a model here to manage your state. The model will even persist through remounts and route changes, which is what you need. All it is is a plain JS object. If you need to observe changes, you can wrap `m.prop` to help in that.

    ```js
    m.prop = (function (old) {
        return function (store, observer) {
            var prop = old(store)
            if (observer == null) return prop
            function call() { observer(prop()) }
            return function () {
                var ret = prop.apply(null, arguments)
                // Let's not chance blowing the stack if the observer changes
                // this property in the tick it's called.
                if (arguments.length) requestAnimationFrame(call)
                return ret
            }
        }
    })(m.prop)
    ```
2. Your history problems might be better addresssed by wrapping Mithril's route change listeners, so you can remember the state as well.
3. If your view isn't rendering, I need more details before I can do anything about it. A very common issue is simply forgetting to return the view (I've done it before).

**Comment by isiahmeadows** [comment]
And in the last case, if you think it's actually Mithril acting up, please file a separate issue.

**Comment by vicvinc** [comment]
@isiahmeadows much thanks. :+1:

**Comment by vicvinc** [comment]
@isiahmeadows  
Hi~ here Iam again. and I reappear the situation that seems view render in trouble. 

It happend on ios mobile safari(iPhone SE/6 tested). here is the user agent: 
```
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) 
AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1
```
_and here is my test code:_ 
the normal code: (views rendered ok)
```
function rdStr(nameBit) {
	var rdcollection = '0123456789AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz';
	var rdid = '';
	for (var i = 0, ii = nameBit; i < ii; i++) {
		var r = Math.floor(Math.random() * (rdcollection.length + 1));
		rdid += rdcollection[r];
	}
	return rdid;
}
var rtest = {};
rtest.controller = function() {
	this.data = rdStr(8);
}
rtest.view = function(ctrl) {
	console.log(ctrl.data);
    return m('div.container',[
            m('div.header'),
            m('div.body', [
                m('a', {href: '/test', config: m.route}, ctrl.data)
            ])
        ]);
}
m.route.mode = 'hash';
m.route(document.getElementById('app'), '/test', {
    '/test': rtest
});
```
while I added a default argument in the rdStr function, the view seem rendered in trouble.
like this:
```
function rdStr(nameBit=8) {
	var rdcollection = '0123456789AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz';
	var rdid = '';
	for (var i = 0, ii = nameBit; i < ii; i++) {
		var r = Math.floor(Math.random() * (rdcollection.length + 1));
		rdid += rdcollection[r];
	}
	return rdid;
}
```
soon I will test some mobile browsers on Android...

I dont know if this is a bug or not..

**Comment by isiahmeadows** [comment]
Does the runtime support default argument syntax? If not, that's your problem. And BTW, feel free to [ask some of these on Gitter](https://gitter.im/lhorie/mithril.js).
