### ISSUE TITLE
Mithril v2 and rendering "on match" components ...

### ISSUE THREAD

**Issue by ChrisGitIt** [MithrilJS/mithril.js#2503]
Hi all,

i just have a quick question to be confirmed. As far as i can understand the source code, as i "normally" mount my routes and my routes are made with "onmatch" functionality like:

```
var com = {
  'onmatch': return new Promise(.....)
}
m.mount(document.body, '/',{
  '/':com
})
```

This will lead to twice calling the render function? I think this will disable all js hydrations client side approaches ... just tried to switch my hydration functionality to the newest version and it seems to be impossible due to this fact. As far as I can see, I'm unable to distinguish between the first and the following render calls. 

Any feedback is greatly appreciate! Discussion around this topic also!

Greets, Chris

**Comment by isiahmeadows** [comment]
@ChrisGitIt Could you come up with a concrete code snippet that demonstrates this?

I will point out the `render` function should never be called *before* the promise returned from `onmatch` resolves. If it is, it's a bug.

**Comment by osban** [comment]
@ChrisGitIt it seems to work fine in this [example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJOAAdNJMn0IaCMUSSAFAEpFAPkkyDAcm26rRimo0A3CDADu+42clZrAEwhnKwpJK1kZezVWNTVxKTosRWUnTTQsDGJqQi8TBXMABQAnWiwIOBh8IvhaKGcYa0YJe3xiQiYDIp9LIqMHVOq0fxgu3J9gSytB4aL7AG5JauIAVyL1PwijGLRttSwq2mXGA39aamWcBnwAI1p-AE9QqwB6EJT1MNf9ROijNUoQBVYNRiBB6AgeABGADMiAADGwOCBMDg8PhqHABDR6IxmDw2ABdKhQbQAawhqGRXDwZTaRWgANW5B4JGIMjgiGez2WaBkpIA5ujSs9aYR6VAAAIAJnwcPw0JFujF0HwZTQ+H4AOI9xk3EB1HpMlErAJrCAA)

**Comment by ChrisGitIt** [comment]
Hi all and thanks for your effort to solve this. I just checked the provided flems example and it looks like its working ... but on closer inspection, something is odd (looks like Mithril is interfering Mithril OR the Promise resolve is to quick ... ?).

I created a minimal "real life" example that is basically how my stuff is working. You can see it on https://www.lorenz-kraft.de/test_m

If you put a breakpoint onto line 1198 in the Mithril code (that's were the rendering starts), you can see the two redraws and also see the DOM text being removed.
 
The vnode passed to the render function does not seem to indicate any state which I could use to determine a hydration start or not.

Bye the way: The rewrite of this part seems complicated and somehow error prone. I like pretty much the 1.1.6 version that was previously handling this. Much smaller with less mental overhead which seem to work all the way.

Thanks for helping!

Greets, Chris

**Comment by ChrisGitIt** [comment]
> I will point out the `render` function should never be called _before_ the promise returned from `onmatch` resolves. If it is, it's a bug.

OK, than it is a bug. The render function will be called immediately.

=> m.route() returns mountRedraw.mount(...) which calls the render function directly:
```
function mount(root, component) {
...
  if (component != null) {
    subscriptions.push(root, component)
    render(root, Vnode(component), redraw)
  }
}
```

**Comment by isiahmeadows** [comment]
@ChrisGitIt 

> => m.route() returns mountRedraw.mount(...) which calls the render function directly:

Not the same thing. Look a little more closely at the `m.route` source. It doesn't directly pass `m.mount` the `routeResolver.render` function, but instead just passes it a component and in the component it passes, it calls `routeResolver.render` once it has such an object. It's a bit more subtle.

If `routeResolver.render` is observably called directly, I'd *love* to see a repro, but you need to find a way to make that happen from userland before I would consider it a bug.

**Comment by ChrisGitIt** [comment]
Hi @isiahmeadows,

I think we are talking about different "render" calls. I think you are referring to the routeResolver rendering call. I'm referring to the mithril render call (which is called twice and in my opinion makes it impossible to integrate any js hydration.). Like in my example code (s. link https://www.lorenz-kraft.de/test_m), i don't use the route resolver "render" at all, so I thought you were referring to the same function than I do. Sorry about the misunderstanding.

Any hints about possible hydration approaches? I have thought about it the whole weekend ... my brain hurts ...

**Comment by isiahmeadows** [comment]
@ChrisGitIt When you specify `onmatch` without `render`, it returns `[m(Comp, m.route.param())]` when it would ordinarily call and return `routeResolver.render(m(Comp, m.route.param()))`, where `Comp` is the resolved value from `onmatch`. It's the same code path. [It's literally the same code path for both](https://github.com/MithrilJS/mithril.js/blob/next/api/router.js#L169-L172), with a single `if` statement to branch based on [whether the component/route resolver has a `render` method or not](https://github.com/MithrilJS/mithril.js/blob/next/api/router.js#L110).

In your case, the resolved component's view [is only called once](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgwAHOdIC804AB0006QHJ6ENBGLbE0sAFc01YhHoAKMWloATGAEpVGrVofOY+OMQYjPiMAco6+obantLsMdpiEDAA7samFlY2aPaOLu7qml5CcLSw+FC0AOa2CUmprjFakjDEZpKaWDVOEGLaFNI+Lv6BwaHErgDcMawaM2gaEjJ0WOEFWrpoWEHUhGnmltZ2+Y3Sza3t0mgp0gAKkrRYEHAwtvuZds0lUGIw-c28MCsx0KXmkz2IABUIDhaGZiK8ModssDQaDPqUfrZ5HJJictOwAIwABhJuJBsQahTiaDmWHw9zhfjkzUgAA9wtptFNNvTYYxbE5aNQzDgGPgAEbOACe-W0AHoxgB9LB9DyFeVKlUmZazSaUEDPWDvNAIHgAVkQACZLWwOCBMDg8PhqHABDR6IxmDw2ABdKhQfQAa1NqHtXDwj2IhEk0AAApb8ET8ABmfVtcg8EjEORwRByuUWOSByrOh5yyPRuMJpPJ8uGStQfCPND4fj64hSuTcA3UGNyUSsH2sIA). If I add an explicit `render` method that does precisely what Mithril does internally, [I get the same result](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgwAHOdIC804AB0006QHJ6ENBGLbE0sAFc01YhHoAKMWloATGAEpVGrVofOY+OMQYjPiMAco6+obantLsMdpiEDAA7samFlY2aPaOLu7qml6SMMRmkppYttpOEGLaFNI+Lv6BwaHErgDcMawavWgaEjJ0WOEFWrpoWEHUhGnmltZ2+TFaxaXl0mgp0gAKkrRYEHAwtguZdsVwtFBiMA3FvDBWK4Ve0ifEACoQOLRmxDOGSW2Ve73eVxud1s8jkXVWXnYAEYAAxo+FvWKuHoUeLFNAuSTzYFZHK+MFeITXWD4KC0ADmVXxhO02Mx6zKmmQTRgAF0cX0NFh8AcAX45MVIAAPcLabTdKYi-6MWxOWjUMw4Bj4ABGzgAng1tAB6doAfSw9Q8hRN5stJhGfS6lBAJ1gFzQCB4SIAnIgkQAmAC0vv9AHY2BwQJgcHh8NQ4AIaPRGMweGxeVQoPoANZe1DRrh4I7EQiSaAAAQD+BR+AAzC6yuQeCRiHI4IhjcaLHIc-T44djSWy5Xq7W60PDCOoPgjmh8PwXcR9XJuK7qOW5KJWLzWEA).

> Any hints about possible hydration approaches? I have thought about it the whole weekend ... my brain hurts ...

If you're talking about DOM hydration, there's an active issue for that: #1838.

-----

Personally, I'm not seeing the issue you've been describing so far, so I'm closing.

**Comment by ChrisGitIt** [comment]
Hi @isiahmeadows,

and thanks for your feedback, but I think we are talking about something different. Its not about my component or component.render called once (or twice or anything). its about the mithril render function [this one]((https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L946)) called twice (if my component is  a route resolver component).

Thats what my initial question was about. About the two time rendering (once with the mithril component and secondly with the resolved component)

If you want to, I can elaborate this in detail, but I think just having a quick debugging session with my provided example is (only look at line 1198) more helpful.

Anyway, I will continue from now on the open thread you linked to.

Greets and thanks again for your feedback!

Chris
