### ISSUE TITLE
Reusing immutable nodes in the same render produces incorrect DOM

### ISSUE THREAD

**Issue by JAForbes** [MithrilJS/mithril.js#2508]
> 💡 Note this is a different issue to #2441 where the list was mutated, this bug occurs when there's no mutation at all.

**Mithril version:**

Version 2.0.3

**Browser and OS:**

Chrome / Windows

**Project:**

[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4wAVzTViEegAIAggAclACgCUwADpo5cnXqFxic+QF45WfMYBOMbKrAYocGOoNyjJgG4QYAdzkLenwsDDUPPQAPIIA+ORiAfktVAHIlVIo5VIAVQhg5KAgAcxI5CDhTNFT1OUQU9MzsvIKi0pMK0zAwGr0Pd119QbticRtdbUG9XwCNSb0FuRGx3WRIxYaAI3FiYnom4CrqIuoAa3qNOKrVAEJ6S-V2bMBeDcBCnZqKdcWZ-w0sgHp-nIACa0eDVEzUQgYNDFGBfBY-S6AkFgypQmFwhEAXXWrA8+LQhJ0ViwtEkxFUoOo4hwDHwm1owIAnlllEp1JQQK5YNJZGgEDwAIwAJkQIoAnGwOCBMDg8PhqHABDR6IxmDw2NiqEU0KdBahZVw8FgIMRCDZoFyxuQeCRiEo4IhAZIlKdioraFh-qbzZaoAABEX4AAM+AAzD6zRboKEIGh8PwucRmUpuNzqJalKJ2Jx5TxfTGoABaWz2LDWmy2kD2x3O-6u92e72F-2l4h2bBB0Oh-5l7CJlUptN4OCZiDZrWsIA)

## Expected Behavior

Reusing a several times node within a render should not cause mithril to use the node from the previous render.

## Current Behavior

Mithril uses the node from the previous render except for the last usage of the vnode.

## Context

The documentation specifies:

>Avoid memoizing mutable vnodes`

But this is not a mutation of a node, just a reuse.  This behaviour means certain rendering patterns with streams become dangerous, that were (prior to v1 at least) previously safe.

**Comment by isiahmeadows** [comment]
It's a docs bug. The heading needs to change to something more specific, like "Avoid reusing vnodes in different positions".

**Comment by JAForbes** [comment]
Breaking referential transparency is unsurprising behaviour, updating the docs to describe the surprising behavior will work.   But would having two caches be a significant amount of work?  

If we update the cache logic, the docs can stay the same and we've got unsurprising behaviour that dovetails with streams to give us performance benefits that other frameworks don't have.

It's unintuitive that vnode's aren't like any other value.

**Comment by isiahmeadows** [comment]
@JAForbes The greater issue is that of `vnode.dom` - you can't have the same underlying node in two different positions in the DOM simultaneously. (It'd be much easier if this *weren't* the case IMHO.)

**Comment by JAForbes** [comment]
Ah I see, that's a shame.  I think that exact justification would be really helpful in the documentation.  Thanks @isiahmeadows for walking me through that.

**Comment by isiahmeadows** [comment]
Reopening because the docs still need fixed.

**Comment by JAForbes** [comment]
I haven't made a docs contribution yet, I'd be happy to give it a go though.

**Comment by 17dec** [comment]
In case anyone's running into a "Node.insertBefore: Child to insert before is not a child of this node" error, you're likely hitting this issue.

Was about to report this as a behavioral bug, but turns out I was just using it wrong. Even made a small test case :)

```js
let a = ['a'];
m.mount(document.body, {
    view: function() {
        const X = m('b', 'X');
        return [
            m('button[type=button]', { onclick: () => a.push('a') }, a, X), X
        ]
    }
})
```
