### ISSUE TITLE
ospec.d.ts

### ISSUE THREAD

**Issue by maranomynet** [MithrilJS/mithril.js#2512]
Hi, I made a quick stab at writing TypeScript definitions for ospec.

https://gist.github.com/maranomynet/1368f8ce0fd344efcd3b9dd5dea637b4

(BTW: Any corrections or improvements would we much appreciated.)

So, what would be the appropriate next step in order to get this published somewhere?
Would you accept a PR to this repo, or would a PR to DefinitelyTyped be more approrpriate?

**Comment by isiahmeadows** [comment]
@maranomynet File that issue [here](https://github.com/MithrilJS/mithril.d.ts/issues). This repo is for Mithril's core, not the TypeScript types.

**Comment by maranomynet** [comment]
Thanks. [Filed](https://github.com/MithrilJS/mithril.d.ts/issues/39)
