### ISSUE TITLE
contentEditable & m.trust failing internally

### ISSUE THREAD

**Issue by bit-less** [MithrilJS/mithril.js#2515]
`const View = { view: () => m('div[contentEditable="true"]', m('div', 'hello')) };`

throws error: `Uncaught Error: Child node of a contenteditable must be trusted` but adding `m.trust` around the child node, produces: `Uncaught TypeError: vnode3.children.match is not a function`

**Mithril version: 2.0.3**

**Browser and OS: Windows 10 Pro, Chrome**

**Comment by bit-less** [comment]
Node should be a string, per the docs.  My bad.

**Comment by isiahmeadows** [comment]
Tip: `m("div", ...)` is not a trusted vnode. `m.trust("hello")` *is* a trusted vnode. So code that works might look like `m("div[contentEditable]", m.trust("hello"))`.
