### ISSUE TITLE
route key parameter

### ISSUE THREAD

**Issue by ericxin1982** [MithrilJS/mithril.js#2518]
Hi All,

I read mithril doc, and I am a little confused how to use key parameter from route.
If use key this keyword, then inside the component code, that is how I should read the key value or how to do?

Please advise!

Thanks
Eric

var Edit = {
    view: function(vnode) {
        return [
            m(Menu),
            m("h1", "Editing " + vnode.attrs.key)
        ]
    }
}
m.route(document.body, "/edit/1", {
    "/edit/:key": Edit,
})

**Comment by isiahmeadows** [comment]
Yes. Or alternatively, you can also read it via `m.route.param("key")`. Either way works, and it's up to you which is better in that given situation.
