### ISSUE TITLE
define component from function like React

### ISSUE THREAD

**Issue by Onesimu** [MithrilJS/mithril.js#2520]
**Mithril version:**
v2.0.4

**Browser and OS:**
Chrome, Windows 10

**Project:**
N/A

**Is this something you're interested in implementing yourself?**
no
### Description

A Mithril component is just an object with a view function. I think it can be more simple by just provide a function, then the framework can test when the argument type is function, it can simple to wrap it to a object. I think it don't need too much code, but convenient to simple component.
### Why

simple component don't need to repeat the boilerplate code of `{view: ...}`, like React can do.

**Comment by Onesimu** [comment]
@spacejack Can you give a simple demo, and can this pattern be used in JSX? Thank you.

**Comment by osban** [comment]
@Onesimu I think @spacejack had something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9GIAEAAX4APSVgA6aFULjFJhGFCi1JAXklw6ABxiGAfJIA8AEwgA3SwAkdeycBO1zrAIQ2Yg7OKmr0GpIYpqaGkgAUAJRWniqSkuqa3uaxNnCmGGiWAOq0AE5QdoF5BZapknWlMMQArqVoKe1pko4QMADuiPFJBtbaurRxWTAJdawqc6poWPhYtM0McXa01M04DPgARrR2AJ4UkdEJlDS0WKbQMKV4BxgHOtdwOjDUxBDheABGAGIAAMbA4IEwODw+GocAEN2EzB4bAAulQoBA0ABrBAoTjQnhYCDEQilaDXVrkHgkYimOCICTrUzYgDmsNuYmJpPJUGkAPwAoAbFySWToPh+NdiCdzHgTOTTKJ2ATuCADvDKeU8LT6YyxMy2RysGINXB+fgAKyC03wyUImVyngKiBKtGsIA) in mind?

**Comment by spacejack** [comment]
I was thinking something simpler - I think the cached vnodes in your example are a bit confusing.
Just a [simple view function like this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9GIAEAAX4APSVgA6aFRMkBxAE4wYxCGgDmkgLSSMkgA5QMByQDcIMAO6SwAVzTV99FR68+aJKGOnoGhgAUmDgAlJLAKpKSOsTuWkEAPAAmEPYAfAASMFBQtBTx0TCsAIQZYjn5KqwqKkJwxOaWlpIAvJIRcT158YmSbR2VvZIA5ADqtFpQWdOjoylpQQlBSQ5Ozoj9g8MhuvpGUVwxo81oNypY+Fi0nsQRWbTU7jgM+ABGtFkAJ7lDBdGKUGi0LCWaAwLR4X4YX7FCFwYowbwQegIHgAFkQACYAAxsDggSp4fDUOACSHCZg8NgAXSoUAMAGscahyVw8FgIMRCFpoBC0uQeCRiJY4IgJJ5LOzDFSoWJ+YLhVBpABGfA6gBsqoFQug+H4EOIgMs3BAcGowssonYnBwCJposWeEl0tlYnliuVWDEvxp2vwAFZdUGaabaRarXhbfbHUzWEA).

**Comment by osban** [comment]
Oh ok, yeah I put that in just to show it would be possible :)

**Comment by dead-claudia** [comment]
Closing due to age. Lighter components are on my radar, but I don't want to commit to a specific shape yet.
