### ISSUE TITLE
null/false are considered a vnode without a key

### ISSUE THREAD

**Issue by mvndaai** [MithrilJS/mithril.js#2527]
**Mithril version:**
2.0.4

**Browser and OS:**
Chrome, Mac OSX

## Code

```javascript
m('', [
    m('', {key: 'foo'}, 'bar'),
    null,
    false && m('', {key: 'baz'})
]),
```

## Expected Behavior

Null and false be ignored.

## Current Behavior

Causes the error:
>Vnodes must either always have keys or never have keys!

## Context

When you try to use a ternary `? :` or `&&` to optionally show a component it causes an error if the component should not be shown.

**Comment by isiahmeadows** [comment]
[In the docs, it explains this](https://mithril.js.org/keys.html#avoid-variable-types):

> Note that `null`s, `undefined`s and booleans are considered unkeyed nodes. If you want the keyed equivalent, use `m.fragment({key: ...}, [])` which is a keyed empty fragment.

**Comment by isiahmeadows** [comment]
This was a design choice. `null`s can't have `key:` attributes, hence why they are considered *unkeyed*.

**Comment by porsager** [comment]
Is there somewhere we can read some more about this design decision?

**Comment by mvndaai** [comment]
@isiahmeadows it seems wrong to have designed `Gotcha`s.

Is there a benefit to having them as unkeyed vnodes as opposed to them just being outright ignored?

**Comment by mvndaai** [comment]
A coworker pointed out that there was already a closed bug for this https://github.com/MithrilJS/mithril.js/issues/2510.

**Comment by isiahmeadows** [comment]
@porsager File an issue about that specifically so I know to file a PR documenting this. (I'll also need to note the correct way to remove vnodes from keyed fragments is to filter them out, like via `Array.prototype.filter`.) The general intuition here is that keyed vnodes have `key:` attributes, and `null` obviously can't have a `key:` atttribute as it can't have attributes at all.

**Comment by isiahmeadows** [comment]
See: https://github.com/MithrilJS/mithril.js/issues/2528
