### ISSUE TITLE
Our error message for the keys check is a little misleading.

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2535]
Currently, it's "Vnodes must either always have keys or never have keys!". This could be more informative, like maybe "Fragment children must either all have keys or none have keys!". The current error message is generating confusion, so it could stand to be improved some.

**Comment by edelventhal** [comment]
Just calling out that I had this exact error and was baffled and irritated and found this issue in Google. Indeed, the more informative error message helped a bunch. I just wrapped my element in another div and it was fine. Weak!

**Comment by pygy** [comment]
@edelventhal  [Our code of conduct](https://github.com/MithrilJS/mithril.js/blob/next/docs/code-of-conduct.md) prohibits derogatory comments. Please refrain from such behavior.

**Comment by edelventhal** [comment]
I mean... I wasn't derogatory? I was stating how I felt, and calling out a solution for others seeing this issue – move the element under another div.

**Comment by dead-claudia** [comment]
@edelventhal The warning was for ending your message in "Weak!", which is very condescending. @pygy edited that bit out, but it's still there in the message's edit history. I hope you understand the warning now, and that you don't make any further such remarks.
