### ISSUE TITLE
Keyed children consisting of both hyperscript and arrays causes "Vnodes must either always have keys or never have keys"

### ISSUE THREAD

**Issue by robinchew** [MithrilJS/mithril.js#2543]
In mithril@2.0.4 below causes `Vnodes must either always have keys or never have keys`.
```javascript
m.render(document.body, m('select',
  m('option', {key: 0}, 'default'),
  [1,2,3].map(i => m('option', {key: i}, i))))
```
[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE5MAJjAkAKabWoBXHA3wAjWtICeFAARZ5AcjgxY1YiYoAdNAaOnaAB2IR6Ng8ADWMXYgGAAzsBiayYBgqUNYAlHYOBsgAjBQATBQAzAC6+FgYLvIQBgC8AHxOJq7unoa+-oEQoRCxrbGUIOaWNWgIPEGIQQC0aYgALABsbBwgmDh4+NRwAjT0jMw8bNlUUBBoPn2os1xiEMSEEtAdKhLkPCTELnCIAPQvKmguPgDmi7RYLywZwu0AAAml8EF8GNAcDLlA8nt8PwOsRdC5uJ1qJc3B0ujArB5engBmkAOyZNIATi2rCAA)
I expect above to be valid as in past versions.

**Comment by isiahmeadows** [comment]
Not a bug - [this is a documented breaking change in v2](https://mithril.js.org/migration-v1x.html#keys).

**Comment by robinchew** [comment]
That documentation suggests either all children are keyed or all children are unkeyed. As you can see in the code presented, all children are keyed. Unless, you are suggesting that the first `option` element is not considered a sibling of the 3 `options` in the array?

**Comment by robinchew** [comment]
Actually, I found a workaround that I find sensible to me, which is to not key the first element which isn't dynamically generated.
```
m.render(document.body, m('select',
  m('option', 'default'),
  [1,2,3].map(i => m('option', {key: i}, i))))
```

**Comment by isiahmeadows** [comment]
> That documentation suggests either all children are keyed or all children are unkeyed. As you can see in the code presented, all children are keyed. Unless, you are suggesting that the first `option` element is not considered a sibling of the 3 `options` in the array?

It's not in the same fragment. Fragments are the arrays themselves. Unlike React, we don't flatten them and instead make them first-class citizens.

Consider this tree in Mithril, the one you gave:

```js
m('select',
  m('option', 'default'),
  [1,2,3].map(i => m('option', {key: i}, i))
)
```

What Mithril sees post-normalization is this:

```
- tag: "select", attrs: {}
	- tag: "option", key: 0, attrs: {}
		- tag: "#", children: "default"
	- tag: "[", attrs: {}
		- tag: "option", key: 1, attrs: {}
			- tag: "#", children: "1"
		- tag: "option", key: 2, attrs: {}
			- tag: "#", children: "2"
		- tag: "option", key: 3, attrs: {}
			- tag: "#", children: "3"
```

Here's the same tree in React using their `React.createElement`:

```jsx
React.createElement('select', null,
  React.createElement('option', null, 'default'),
  [1,2,3].map(i => React.createElement('option', {key: i}, i))
)

// JSX
<select>
  <option>default</option>
  {[1,2,3].map(i => <option key={i}>{i}</option>)}
</select>
```

React sees this instead as it flattens children, one of the biggest differences between Mithril and React:

```
- <select>
	- <option>
		- "default"
	- <option key={1}>
		- "1"
	- <option key={2}>
		- "2"
	- <option key={3}>
		- "3"
```

*(By the way, React would complain here, too, just it'd only log to the console. We differ only in that we enforce it as an invariant.)*

In order to get the tree Mithril uses, you'd have to explicitly wrap the keyed list in a fragment:

```jsx
React.createElement('select', null,
  React.createElement('option', null, 'default'),
  React.createElement(React.Fragment, null,
    [1,2,3].map(i => React.createElement('option', {key: i}, i))
  )
)

// JSX
<select>
  <option>default</option>
  <>{[1,2,3].map(i => <option key={i}>{i}</option>)}</>
</select>
```

This would yield the equivalent tree:

```
- <select>
	- <option>
		- "default"
	- <React.Fragment>
		- <option key={1}>
			- "1"
		- <option key={2}>
			- "2"
		- <option key={3}>
			- "3"
```

Mithril is stricter and less forgiving than React here, if it helps. It also ends up simpler and more statically analyzable.

**Comment by robinchew** [comment]
The confusion is due to past behaviour of keys where all children of the parent element must be keyed (if you need to use keys):
```js
// code block 1
m('select',
  m('option', {key: 0}), // This must be keyed, if options 1, 2 and 3 need to be keyed.
  [1, 2, 3].map(i => m('option', {key: i})))
```
So now the behaviour has changed in 2.0.4, key 0 is not necessary:
```js
// code block 2
m('select',
  m('option'), // no key necessary here
  [1, 2, 3].map(i => m('option', {key: i})))
```
Which is fine by me. I assume the reasoning is due to your above explanation.

My initial dissatisfaction was because I mistakenly thought `key: 0` was still necessary and writing it as in `// code block 1` was giving errors.

**Comment by isiahmeadows** [comment]
The behavior changed in v2.0.0 - before, you could literally mix and match them and now you can't. And in v1, no, you didn't need a key for the first one, either. (You never needed a key for it in the first place.

**Comment by pygy** [comment]
You could mix and match them, but it was undefined behavior IIRC.

**Comment by isiahmeadows** [comment]
@pygy Beat you to it 😉

> The behavior changed in v2.0.0 - before, **you could literally mix and match them and now you can't.**

**Comment by pygy** [comment]
What I meant is that you *could* do it, sure, but having your app working as intended was a matter of luck, and it could have broken at any time on a patch update.

**Comment by isiahmeadows** [comment]
That's true. Basically, just killing undocumented behavior people were relying on, and I'm not exactly a fan of keeping around stuff that's just "here be dragons".

I'll note one thing: it *was* fairly well-defined (mod a few caveats), just nobody bothered writing it down until apparently me just now. What it did was roughly this, a two-layer diff rolled up into a single pass. This path was only triggered if the first element had a key, however, and a pure iterative diff was performed if the first non-hole didn't have a key.

(Warning: lots of abstract math and CS references ahead. 😄)

> Legend:
>
> - `K` = element with key `K`
> - `c` = component of type `c`
> - `a... -> b...` = update from `a...` to `b...`
> - `abc` = sequence of `a`, `b`, and `c`
> - `*` = empty sequence
> - `.` = hole
>
> This is for clarity with how things relate. And yes, it's complicated enough I needed to invent a formal notation for this.

- Unkeyed children are tracked as if all keyed nodes were removed, while keyed children are extracted to a separate collection with their indices tracked.
	- `aBc -> adBc` would be diffed as `a.c -> ad.c` unkeyed, `B -> B` keyed.
	- `aBcDEf -> aDcBf` would be diffed as `a.c..f -> a.c.f` unkeyed, `BDE -> DB` keyed.
	- `abCdeFgh -> aCFgIh` would be diffed as `ab.de.gh -> a..g.h` unkeyed, `CF -> CFI` keyed.
- Unkeyed children were diffed iteratively as usual, but only in consecutive groups.
	- `a.c -> ad.c` would have `d` added and `c` patched.
	- `a.c..f -> a.c.f` would have `a`, `c`, and `f` all patched.
	- `ab.de.gh -> a..g.h` would have `b`, `d`, and `e` removed, `g` patched, and `h` removed and re-created.
- Keyed elements were diffed by key, and spliced into the appropriate positions as necessary.
	- `B -> B` would have `B` simply patched without movement.
	- `BDE -> DB` would have `B` and `D` swapped and patched and `E` removed.
	- `CF -> CFI` would have `C` and `F` patched and `I` added.

And here's how each of those three examples be patched:

- `aBc -> adBc` would have `d` added and `B` and `c` patched.
- `aBcDEf -> aDcBf` would have `a`, `c`, and `f` all patched, `B` and `D` swapped and patched, and `E` removed.
- `abCdeFgh -> aCFgIh` would have `b`, `d`, and `e` removed, `g`, `C`, and `F` patched, `I` added, and `h` removed and re-created in its new location.

In v0.2, this was roughly how *all* fragments were diffed, not just how fragments where the first non-hole had a key, but in v1.x, it's roughly how all fragments whose first non-hole child had a non-nullish key were diffed.

I actually had to [look this up in v1.x](https://github.com/MithrilJS/mithril.js/blob/master-v1_1_x/render/render.js#L185-L246) to remember a few specifics. I might still be off *some*, but this is pretty close to the actual rules involved. (The second loop in that throws a few forks here - suffixes aren't handled *precisely* like the above, but it's similar but in reverse. So technically, the last example would have `h` patched and I think maybe even `g`, but I'd have to double-check.) So don't feel too bad for not knowing it all off-hand.

-----

So although yes, it was fairly well-defined, I think we can both agree this is definitely not the kind of semantics we'd like to maintain, and it's precisely why I pulled it. 🙂

*It's also not like they couldn't just emulate this themselves by splitting them appropriately and generating the resulting fragment programmatically.*
