### ISSUE TITLE
404 workings BUT not multiple slashes

### ISSUE THREAD

**Issue by davidroman0O** [MithrilJS/mithril.js#2548]
**Mithril version:** 2.0.4

**Browser and OS:** OSX && Chrome

**Project:** Mithril

## Code

I've tired what I saw the issues already created!

I found those one :

```javascript
"/:any..."
"/:404..."
```

## Expected Behavior

When going to a random url like `http://localhost:3000/fdskjnfsdkjn` OR `http://localhost:3000/fdskjnf/TEST/AGAIN` it should display my component

## Current Behavior

It's working for that kind of url : `http://localhost:3000/fdskjnfsdkjn`

But with multiples slashes, it only display a blank page! No component is display.

The ressources are loaded correctly and everything is fine on the `Network` tab of Chrome.

I got the same behaviour on both dev server (in local) or hosted (right now on Zeit).

## Steps to Reproduce

1. Currently using this [starter kit of mithril](https://github.com/dhinesh03/mithril-starter-kit)
2. Added a "/:any.." or "/:404..." on the `routes.js` file the component of your choice
3. `yarn start` or `npm start`
4. Go to `http://localhost:3000/randompage`, it's working, and goto `https://localhost:3000/randompage/butnothesame` and it's not working

## Context

I have none and I'm just want to learn more about Mithril! 😄 

Thx everyone for your hard work on this library, it's been a pleasure to use and learn since I started.

Tell me what's I'm missing, I've read the doc and the issues but I'm going nowhere !

**Comment by isiahmeadows** [comment]
These are technically the same route from the view of Mithril. They both match any route that's a single path component. And as a general rule, the first one specified is the first to match, but you can work around this with [`m.route.SKIP`](https://mithril.js.org/route.html#mrouteskip).

BTW, when handling client-side 404s, [you should use a rest parameter (as in, `:404...`), not a simple path parameter (like `:404`)](https://mithril.js.org/route.html#handling-404s).

**Comment by davidroman0O** [comment]
@isiahmeadows  Thx!

Working! 😄
