### ISSUE TITLE
Component anti-patterns and why they are?

### ISSUE THREAD

**Issue by ghtmpn** [MithrilJS/mithril.js#2554]
This is a question about how mithril's DOM optimization works with regard to different types of Components. I created a minimal example to show what the problem is (as far as I see it).

TL;DR: Why [Avoid creating component instances outside views](https://mithril.js.org/components.html#avoid-creating-component-definitions-inside-views) works this way?

**Mithril version:** 2.0.4

**Browser and OS:** Opera 65.0.3467.62 (latest) Windows 10

## Code

I posted this same code on [Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHkJgwBMA+AHTQAEAlnGoAnCAAdiAuGOoBeXiBLFJcRAHpNAVzSSA1gHN8dLJqwRihCVAtWb0fACs4y7i02iJ0vmk-sXH4sAEa0nACefkIsnBAAbtHCmnGJ-J5hkdyUIHAwsNTEEPQIiCAArIgAHCAAvhTo2LhlLghUdAxMxHjxGGICnLRYcAIKAsgCALr8vf0QowIAjPx5xAAqEDi0OsQAFLsAlKPcAsAQANTnANwCWPhiMJxiGADuh-UCAEwADN8H-PwwHpCsVBPRxBxGLtgBhiMQxBpgNQKAI0B9BlhakdgPwhEIOnBaLB8FBaEZdgByCGwmAUlHI1EoikYxB0gZDUwleE6Qq0MT4TA4f6CPEYuDIagAKkW33OaEmCwx-FqgOBRXoAnoOkknBp0Nh8MRDLRKIxWNOuLxBKJMBJZMp2s4bONTLgTXZWFZKN2Yol0tl8tGCjGGIOwpVaBmfQEAGEhpJFgscSKhPEIDA3jC4QjEGdaubk3iiwIHsQdGJBFhKak2UjEIsUWh6yjwQ8aS20I6afVLcXi3cwM8jDgGNDqM3UYhPh3qYwO13GD2U32VwADAAS+VJAgAJHnVxReyu+9biaTyVSMFAoLH44sKWHhUWIxHVWgQRq0BmAPpxrCST5DgtZdS3LQRCxXNMM31bNEQgfNsSPY9QIrW5qwSWtx2nScG01d82znPCFxgJdj2PAchxHPY62wptsNbSEYHnHVu0PZcyLXTdr1oXd9zYjiONPW1z0pagrxvP8AIfMMkLxCNn2VAE0CBd91UEPJLF-eMAGZdgNBFEOXWZTnghZ9LcECYDLVCKIwYcuj02D+JXKtmQwlE620xsJwY9siJYxdnI42z7NHTzvPo-DGOY3VAtkjiNy3Hi93gg94rIoS7QvMTr1vf9tOkmS0SUu4sG2UdBmoHQqPwABHHQYDECIAGV8hgXkxEpTIIgEE5JQfDyjygt5DOQqywPGdKiyrSTcLrXCm2+FEIBRAwYAiVlZrZXzCK1AKSIOIKyKrL8Xi0-9AMO04sO8paBBWgQ1o2ilJM+baor8vbYoOo7jw0iBzskXTwsnO6HqezadPe2cmP876sV+vFpmXF9hRyPICjU0oQCqKdFjqBoQEFZoCGoOA2hoehGGYMo6kmKgoAgNADFKVAiaaPBLGsWwcnLcgylUdQtF0fRjE5cwuccKAAAFPnwb58AAFnsbmnEsNBWhyYgIkkEnvCkbpakmWogA) (html omitted here, since it's trivial)
```javascript
var doms = [ ]
var i = 1
setTimeout(() => {i++; m.redraw()}, 200)

function oncreate({attrs:{c, n}, dom}) {
    console.log('create', c, n, 'dom:', dom.constructor.name)
    doms[c*10+n] = dom
}
function onupdate({attrs:{c, n}, dom}) {
    console.log('upd', c, n, 'same dom:', (doms[c*10+n] === dom))
}

var Comp1 = {
    view({attrs:{i}}) {
        return m('div', {c:1, n:1, oncreate, onupdate},
            m.fragment({c:1, n:2, oncreate, onupdate},
                `Hello ${i}`,
                console.log('call Comp1')))
    }
}

function new_Comp2() {
    return {
        view({attrs:{i}}) {
            return m('div', {c:2, n:1, oncreate, onupdate},
                m.fragment({c:2, n:2, oncreate, onupdate},
                    `Hello ${i}`,
                    console.log('call Comp2')))
        }
    }
}

function semi_Comp3(attrs) {
    var {i} = attrs
    return m.fragment(attrs,
        m('div', {c:3, n:1, oncreate, onupdate},
            m.fragment({c:3, n:2, oncreate, onupdate},
                `Hello ${i}`,
                console.log('call Comp3'))))
}

m.mount(document.querySelector('body > *'), {
    view() {
        return [
            m(Comp1, {c:1, n:0, i, key:'Comp1', oncreate, onupdate}),
            m(new_Comp2(), {c:2, n:0, i, key:'Comp2', oncreate, onupdate}),
            semi_Comp3({c:3, n:0, i, key:'Comp3', oncreate, onupdate}),
        ]
    }
})
```
It just logs what happens in all three components (`oncreate`, `onupdate`). `c` is component number, like `Comp1` -> `c:1`. `n` is just a div level. `Comp1` is static POJO component, `new_Comp2` is a component factory (it's wrong, yes). `semi_Comp3` is not a component, but it works as such, details below.

Output: (extra newlines added by me)
```
call Comp3
call Comp1
call Comp2

create 1 0 dom: HTMLDivElement
create 1 1 dom: HTMLDivElement
create 1 2 dom: Text

create 2 0 dom: HTMLDivElement
create 2 1 dom: HTMLDivElement
create 2 2 dom: Text

create 3 0 dom: HTMLDivElement
create 3 1 dom: HTMLDivElement
create 3 2 dom: Text

call Comp3
call Comp2
call Comp1

upd 3 0 same dom: true
upd 3 1 same dom: true
upd 3 2 same dom: true

create 2 0 dom: HTMLDivElement
create 2 1 dom: HTMLDivElement
create 2 2 dom: Text

upd 1 0 same dom: true
upd 1 1 same dom: true
upd 1 2 same dom: true
```

## Current Behavior

The code above uses three types of Components: 1. POJO component, 2. dynamically created POJO component (which is considered anti-pattern for reasons discussed in the mithril's guide), and 3. semi-component that is a function that creates a "shell" fragment to encapsulate its contents and also passed `attrs` in it to work as, well, semi-component.

Output shows that 1.POJO works as expected. It created three dom nodes and updated it after a timer fired. On the other hand, 2.DynPOJO re-created its dom, because mithril sees that it's not the same component at the redraw.

**My question is: why does mithril compare component raw values at all?**

At first I thought that maybe it is an optimization for not even looking into a component if it's the same, but the second `call Comp1` clearly shows that `m(tag, m(tag, m(tag, ...` is clearly called at every `redraw()`. Thus, vnodes are re-created and compared anyways, so what's the point of `last_comp === this_comp` check somewhere in mithril's code?

With 3.Semi I tried hard to make it behave like 2.DynPOJO, but it never re-created its dom. Basically, with using `m(Comp, ...`-style components I cannot make dynamic components, but with `semi_Comp(...` I can, and there are no observable issues. Both implementations (2,3) differ in few starting boilerplate rows, and 3 also works in the same way as 1, from what I can see. I cannot figure out where this "don't DynPOJO" restriction came from and what goal it serves.

You may point out that 3.Semi doesn't really change, but wrapping it in a factory would not change anything, since it's still just a function, which mithril would never be aware of. So, if I made:

```javascript
function new_semi_Comp3(setup) {
    return function semi_Comp3(attrs) {...}
}
...
    view() {
        return [..., new_semi_Comp3(my_setup)(my_attrs), ...]
```
It would still work as expected. It's full analogy to `m(new_Comp2(my_setup), my_attrs)` except that it doesn't have preformance issues.

Can someone please highlight the details that I'm probably missing?

## Context
I'm trying to build an ui+db library layer based on mithril and am very interested/hunting for user-low-level details. Mithril is the only viable alternative when you look for an ui thing that does its job and doesn't mess with your data management, so I'm here :)

**Comment by cavemansspa** [comment]
hello @ghtmpn, welcome to the mithril community.

in the semi_Comp, you're returning a `vnode` (i.e. not a component). so the diff is a vnode diff as opposed to a component diff.

**Comment by ghtmpn** [comment]
Thanks, @cavemansspa ! Can you please explain the difference between these two diffs?

I can assume that component diff would not re-`view()` when nothing changed at call site, but if I try to remove `i++` from a timer callback, so that a second draw effectively sees the same attrs in:

```javascript
    m(Comp1, {c:1, n:0, i, key:'Comp1', oncreate, onupdate}), // 'i' didn't change
```
But in this case `view()` still get called, because `call Comp1` and `upd 1 ...` get logged too.

**Comment by cavemansspa** [comment]
@ghtmpn -- i created a [flems](https://flems.io/#0=N4IgtglgJlA2CmIBcA2AzAOjSgNCAZhAgM7IDaoAdgIZiJIgYAWALmLCHgMYD2lL8fshAgAvjiq16jAFalufAUIYAdSr0rEWAAgDCYAA4AVAE4BXeNoC824Gu3a+XE-GoCk2gBTAoPMKIBKawA+W3sHbQ1iHgQMWB4Ac08Aci5DABFfMAAleHxrKxss5JxIjKzc-MKivwDwhzSDTL9K620s8PFwvghKCBYPTyCrUKiY+DjElP1jc3gkJB6+lmSAnHCANwh4AHdB4dCwFKgIDZLtZJnTC1W1UTUonRmAMWpYYksbO0oHJxc3eZeHx+QIhMI-CJjWLxJKpcotPIFGpgc6NZo5RHVdq1eplJoVTHYsCddYQpb9fZgqETGHTQyvd7zRZ9ZarUkOLa7SkjbRHZInM6lS70t4fW6Ue6UNQIHRoglVbRmShQPK9eBQaXwHTytpKlWESjqh58LTaABqlB4Kuuny8B3BDhcLDMJh+fIF52+EUc6n+7iBWVBPJ1yPZET4ZgMUABg2B-nt1MmsJDhSJ5xTyLqEPEFwtVvgNvFkse5stKoZHzaQzBXu0TpdbuOp09uL+rn93kD9pDRLDv0okejHbjQdGJvGSeOCKqqeKpQzRKzDhzyTz5dF8CLak1OgARm0WHM1GAMGAeEqWJ5fFwzHR+Bhd1aAJ6lYCcvZ2mvheuu7RkcJ8ruZgsCwfCek4sAQFwADW3KhPuNgAIS7iuXCQTBbLhPuAD8vKeFccxBB4RwvBuazaAA9BRkR+AY1AmL0CQ0YYfBavOfjaPACB3joEDEHW8DOO2RoQjhpb5ja1YeGu8AVvA1ZUcxdEMZQTECtoLDUAkpRcfAPHaHx2gAHIAPJGI6gl+iJAC6dyBJwIC8IYRDwCYwi7tQu5cQ5HwIFwLAQCawhoAAHEgADsaBiBIIA0HQwgYFwxDyI5iiCCwwhiNZeCQZQ0GkEgFCxVIwiQCwTAMRweAuhwDCsCwBjEEgVFKgY0EJIlfgUWVFVEAAAgATBgAAMGAACzdf0vWwKevQYHIDksE+BjSMQzgQAYGWiNZohAA) that may help illustrate the difference.

**Comment by ghtmpn** [comment]
Oh, looks like I had a wrong perspective. When another component silently takes place of the old one, it has to be differentiated and initialized with a new state (`this` / `vnode.state`), even if its child vnodes happen to be the same. If that were not the case, it would inherit the state of the original component, thus breaking its logic. Otoh, if it's the same component instance, then it is safe to re-draw it.

This answers my question, thanks a lot!
