### ISSUE TITLE
Not set vnode.dom after view before next element view until oncreate

### ISSUE THREAD

**Issue by glebfeklistov** [MithrilJS/mithril.js#2562]
Not set vnode.dom after view before next element view until oncreate

**Comment by glebfeklistov** [comment]
![2020-01-02_121358](https://user-images.githubusercontent.com/5002394/71659660-6e0e6d80-2d59-11ea-9f0f-d2da5ef8ddcc.png)
I do flow editor, and i need know dom position to paint wires, but i can get dom only oncreate, and a need call redraw

**Comment by isiahmeadows** [comment]
Could you post example code that reproduces this problem?

**Comment by glebfeklistov** [comment]
node -> port -> hole (onview)
if port view complete and render the hole, port vnode.dom is null, and if i select from document.body port tag, it exists in document, but vnode.dom of port is stil empty when rendering hole.

**Comment by isiahmeadows** [comment]
@glebfeklistov We need actual executable code to test. If you can't provide code that reproduces the problem, I'll have to close this issue.

**Comment by glebfeklistov** [comment]
I found another solution- Not use this framework!
