### ISSUE TITLE
onbeforeupdate - remove component encapsulation requirement

### ISSUE THREAD

**Issue by sorenjakobsen** [MithrilJS/mithril.js#2565]
For the 'onbeforeupdate' hook to work it must be encapsulated within a component. This can lead to some very awkward code, with 'unnatural' components being created only to achieve some necessary optimizations.

**Comment by osban** [comment]
I'm not sure I understand the need of having the hook outside of a component...maybe you can give a simple example/[flems](https://flems.io/mithril)?

**Comment by isiahmeadows** [comment]
@sorenjakobsen This is explained in the introduction of [our docs on the lifecycle methods themselves](https://mithril.js.org/lifecycle-methods.html).

And no, you don't need components for it to work - you can use them inside attributes as well, and many people do this primarily.

**Comment by sorenjakobsen** [comment]
@isiahmeadows - it says in the documentation: 'This hook by itself does not prevent a virtual DOM subtree from being generated unless the subtree is encapsulated within a component.'. I tried putting it on a node in my main document tree and it didn't work.

@osban - am generating an SVG polyline with a lot of points - when the user interacts with the graphic a wrapping viewbox must be updated (to zoom in/out) and there is no need for the inside polyline to be diff'ed. This is a very small piece of code and it doesn't really make sense to encapsulate it in a component.

**Comment by isiahmeadows** [comment]
@sorenjakobsen That's specifically regarding stuff like this:

```js
m("div", {onbeforeupdate: () => false}, someChild())
```

In that case, `someChild` is called even on subsequent renders.

But consider with components:

```js
const Comp = {
	onbeforeupdate: () => false,
	view: () => someChild(),
}
```

In this case, `someChild` is *not* called on subsequent renders.

-----

That part of the docs seriously needs recast and reworded for clarity, though, because while it's *technically* accurate, it's unintuitive even for me. (I didn't write that part. 🙃)

**Comment by sorenjakobsen** [comment]
@isiahmeadows - I guess I at least understood the documentation correctly:) What you are showing is exactly what I consider a problem - I don't think someChild() should be called when using m.render() on your first code snippet.

**Comment by isiahmeadows** [comment]
@sorenjakobsen Note this part of my response

> the distinction should've been explained as due to the language (it's just JS call order) rather than due to the library somehow

Mithril really can't do anything about that - you have to use a child function or view function to work around it. JS doesn't have call-by-name, so we can't really prevent it automatically. (I wish I could, though.)

**Comment by sorenjakobsen** [comment]
@isiahmeadows ok, I understand:) So, m() will always be called, but then wouldn't it be possible maybe to flag the corresponding subtree(s) in the virtual dom, so when m() is called i it will know that the nodes do not need to be diffed/recreated?

**Comment by isiahmeadows** [comment]
You flag it via an `onbeforeupdate: () => false` *attribute*. All lifecycle hooks work as both attributes and component methods.

**Comment by sorenjakobsen** [comment]
@isiahmeadows thanks, yes I see I can use it as an attribute but then it only works for the element itself, not the the whole subtree. So I unfortunately still need to create those 'artificial' components.
