### ISSUE TITLE
How to get vnode element from onmousedown event in view?

### ISSUE THREAD

**Issue by glebfeklistov** [MithrilJS/mithril.js#2566]
How to get vnode element from onmousedown event in view?

**Comment by boazblake** [comment]
@glebfeklistov What exactly are you trying to achieve?

all events contain a link to the dom from which they came from. E.g. 
```
onmousedown: event => event.target //dom
```

**Comment by glebfeklistov** [comment]
> @glebfeklistov What exactly are you trying to achieve?
> 
> all events contain a link to the dom from which they came from. E.g.
> 
> ```
> onmousedown: event => event.target //dom
> ```
> 
> You can use this playground to test your code:
> [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAAQYADtIkBeCcAA6aCRIBuEGAHdEEgBQBKBQD4JWAwHJ80jACcRVislXr1lqwCMArsWL0+NSE0AAmzkr0WLQ+cDChtDpo+jAaImZCcLSw+FC0AObWCVgRqSL4xA75MMRG7BJW1FAQ1ADWFjBWRm4SALrdaKyqqlj40T4MBgnUPjgM+F60oQCeFFKyRpQgcbDUxBD0CDwAbIgATADsbBwgmDh4QXACNPSMzDxsvVTNaK1HqLcuHgsBBiIR7NAtj57OQeCRiNI4IgAPTIibSVr5IK0LDIkFgiFQAACZ3wAAZ8AAWPGg8HQMYQND4fhbYjLaTcbbUCHSUSsXqsIA)

Not  reqular node, but vnode, with attrs, state, and other attributes.

**Comment by osban** [comment]
@glebfeklistov the `vnode` is available like: `view: vnode => m('div')`. [Example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJOAAdNJMkA3CDADuiLWloATGIoB8ytRo3jasfFFoBzABSajpgJTWbAJxhiAFc-dSxXAHJjCE0Iiit1Gw0JAE9YAwjdCGNiQgMARgAGQpkADwBuSUIYCGcSAuKyyoAjDGoAa2c-WiC0YwM4DCgsejjfJPoRoLgYY1pdNANXLwtDExh8CQxGfEYJRUkIsFpaCPHJVh9E1jUbtDUsfCmGVznqIJwGfGaTFPjZGReSggGawajECD0BA8ACciEKbA4IEwODw+GocAENHojGYPDYAF0qFAIGh2tDUMiuHgsBBcn5oMCQuQeCRiDI4IgAPRc3oyTro2hYLm0+nQAACACZ8IV8AAWEV0wgMqBPUn4fjA4gpGTcEHUBkyUSsAmsIA).

**Comment by glebfeklistov** [comment]
Read the question...

**Comment by osban** [comment]
Thanks for the advice! I will also follow your obviously superior approach of answering questions.
