### ISSUE TITLE
[ Documentation ] Chinese documentation collaborate

### ISSUE THREAD

**Issue by ShenQingchuan** [MithrilJS/mithril.js#2568]
I create a repo for mithril.js Chinese documentation [here](https://github.com/ShenQingchuan/mithril-cn)

I would like to publish this here, and if there is anyone else would like to cooperate, please contact with me.

I'm using **VuePress** because it's easy to develop for me and I am familiar with it. 

I don't know if the community would agree to that ... 🤣

**Comment by ShenQingchuan** [comment]
oh I found a chinese doc version...

**Comment by isiahmeadows** [comment]
@ShenQingchuan Could you link it here? I'd like to eventually collect various community translations into a single page on the official English version.
