### ISSUE TITLE
Adding click events to dom that was added via m.trust

### ISSUE THREAD

**Issue by omenking** [MithrilJS/mithril.js#2569]
**Mithril version:**
2.0.0-rc.9

**Browser and OS:**
Electron 8.0.0 (Chrome), macOS Sierra

**Project:**
https://github.com/ExamProCo/fast-author
## Code

```javascript
// Code
```
## Context

I am creating a markdown editor.

![Screen Shot 2020-02-12 at 1 52 28 PM](https://user-images.githubusercontent.com/7776/74366923-efb4da80-4d9e-11ea-88f1-642efdcba29d.png)

I am attempting to make it so that when I click an image in the preview I can process images eg. add a border, crop or etc.

So I render out my markdown and I use `trust` so I its can safely render.

```coffee
m.trust(@md.render(Data.document()))
```
I need to make it so I can fire click events on the images.

I am thinking I can use  `onupdate(vnode)`, however I'm not sure how I would select the elements and bind click events by doing `vnode.dom` to all img elements contained within.

I can use `document.querySelectorAll('.preview img')` and attempt to bind click events through listeners but I imagine this is not a great idea since I would think those event listeners would become invalid on a redraw.

What is the mithril way for binding events that are from dynamic html?

**Comment by danloomer** [comment]
Could you maybe just keep the events at a higher level, like the element that contains the `m.trust` and then react to the event on that single handler based on the `event.target`?

[Something like this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AXvgDmUWgCMMUAAZgwAAjgY0cALRwYAJwhgA3LNoATAJ6rgqrKoCsq1ooA6ad7GJ3zqgLyqbmgAxKoAEjBQMqoA6rT6UObu7gAqhBBwqhmqGKqMcMSI7tqq9DDFeQDutBXEhPow5WiK+MSGWAAUAJTJaF6q1FAQ1ADWMOZhKQCyADL+qgDkC71Y+Fi0AK4MHea01Bs4DPhmVhQ27qqqAG4QMJWIqt3+AHyqyBeXdh0L5hBXC2dOgsCvp6JIAYsAMJDUbjcLTGaIBZdM6DYZjCYIlEfS6dHGfH5-BaqADUqjEil8kkM5mMkmI1FUAEYwPpmazFBR8bjvowAB7EDANDAQ2xXBQbGAPLDmM70CBoAAOG0KqhgL0eMvmMFaQskMGI+HFUElXWc2LQn0+eMtVoJv3+pPJikVzIADJzuZ9bPQ0aMHuq-K8On6MZNZtrdfp9YbNox9OGZmb2F7ca19BsCh0sEKMdnzF0erarUWSx8ALruVhFyg0WhYRXQAx4eSySK1vSwajECD0BA8JlMxAAJjdbA4IEwODw+GocAEdeEzB4bHLVCGaBG-dQk64eCwEDqhnIVA2CTwJGIirgiAA9LetoqRpJZ-Xbwej9AAALD-Bu-AACzvoe9TQGsCr4PwtbEJYircCAcDUIYiqiOwnDTjwYgYGAPaSLWZ7kDwl7XneD5Ks+r5YLeWE4RAkhfv+AAcgG3r8BTUdhuH4PADjgWgkELjBcF4IhyGoROU7wTm+gYnxAn4eeRHEFeN73o+FF0FR0kYgx+DMW6765uMclQVQQnwaJEAoaurBAA).

**Comment by pygy** [comment]
You can use a fragment with an `oncreate` hook (resp. `onupdate` if needed):

```JS
m.render(document.body, m.fragment({
  oncreate({dom}){dom.onclick = () => console.log('clicked')}
}, [
  m.trust('<h1>Hi, click me')
]))
```
[live](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE5MAJjAkAKabWoBXHA3wAjWtICeFAATiwEjAHN1xecAA6aAwfrUpGRtaVZWASmAf8TqAhqAGsDAF4DeS9wgD4DIThaWHwoWjN5AHJqQJCYaQyvVjt2A2Q7B3FiCRU4KwyAHkIARhiACQhDbKDQnAK7AF0vL0oQOBhYamIIegQeAAZEOYBaABZEAGY2DhBMHDx8ajgBGnpGZh42fqpAtGDZ1B2uMQhiQgloEZUJch4SYgAHOCIAD0wJUaH+wTMB1oWGBWBeb2gAAEAEz4Ob4FbwxHvKD4BFofD8EbEXT-bijZwQf6iVj9VhAA)

**Comment by isiahmeadows** [comment]
You might also want to consider just using `innerHTML` + attaching `onclick` listeners to the parent `div` or whatever + using `ev.target.tagName`/etc. to detect what's an image vs what's not.
