### ISSUE TITLE
Contributing page - need fix menu

### ISSUE THREAD

**Issue by WinterSilence** [MithrilJS/mithril.js#2570]
On page https://mithril.js.org/contributing.html left menu is broken.

**Comment by CreaturesInUnitards** [comment]
@WinterSilence I don't repro this. Could you please include some more detail about the browser/device you're using, and what specifically isn't working correctly?

**Comment by WinterSilence** [comment]
@CreaturesInUnitards FF 73 (latest) 
![изображение](https://user-images.githubusercontent.com/3521094/75173639-3fe95080-5740-11ea-9dad-4c9782703dd2.png)

**Comment by CreaturesInUnitards** [comment]
Ah. Yeah I don't think that's so much _broken_ as it is _ugly_. If you visit the `Components` or `Lifecycle methods` page, you'll see that the left nav is just picking up all the `h*` tags and creating links. So the questions on `How to contribute` are longer, and make the nav ugly. Not sure that's gonna get fixed... @isiahmeadows ?

**Comment by isiahmeadows** [comment]
> Not sure that's gonna get fixed... @isiahmeadows ?

It'll get fixed once I have the chance to refactor the docs and rethink much of the design and layout (it isn't cohesive). Of course, with a new job clear across an entire continent (plus the associated move) and the Mithril issues and chat room picking up a little, my free time has dwindled down to approximately zero. This is further compounded by things being on my TODO list that are a bit higher priority.

**Comment by CreaturesInUnitards** [comment]
@isiahmeadows of course I could be wrong, but I _think_ I can speak for everyone when I say “Don’t worry about this one” 😊

**Comment by dead-claudia** [comment]
Closing due to age.
