### ISSUE TITLE
Form validation jsx

### ISSUE THREAD

**Issue by charles269** [MithrilJS/mithril.js#2574]
How to correctly access the value of an input in jsx?

I tried the following code:

    let userName;

    function validateUsername() {
        console.log(userName);
    }

    return {

        view: () => (
            <input type="text" value={userName} />
            <button onclick={validateUsername}>Send</button>
        )
    
    }

But the variable is empty...

**Comment by osban** [comment]
@charles269 you need an `oninput` in the `input`. Unfortunately I don't know how to do it in JSX, but in hyperscript that would be: `m('input', {oninput: e => userName = e.target.value, value: userName})`.

**Comment by osban** [comment]
I've figured it out: [example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoABAAF+ADylYpEsVIA6aMWoCucGFIBCGAEYwoUsLQBOU4tYxo4AB2gQ0AcwCEmzULjEUhjOzlIAvFIAFACU4QB8UsCaUlKwgXow1gByXADcvmgpYDpo1MQQ9FIAbhhQEAAmGIwAqvrWmDgxickpvf60sPhQtB6RGdlc0fmFUqwFPdYwxDrt3TO91RAwAO6IUbFhCZE9GykAPPUQVXEnp+fuzjqBxACezjBh6iCM8sRfUvQHk8wsADIcpOMcjhwlIYPhiBhrB4lvgalAdDBWNVahiQZCuFixDd1ncpGcTE9iJV6NQ6tQANYgtENJowVqZDqYuIAZSY9TOYgpxCpaGJpLJYku11uKWiPTmaAVmiw+CwtBKxEi9Vo1B0OAY+BMtHqLwoQRC0UoNFoWFcsGseBMpnMVv0sDKFSceAATAAGRC+tgcECcvD4ahwATW4TMHhsAC6VDqaHpCBQnBweCwEGIhGs0CtK3IPBIxGccEQ2hKznpHnDNrE2dz+agMm9+F9+AALI2c3noKr3Ph+FbXu88HBqPnnKJWPHWEA).

**Comment by charles269** [comment]
> I've figured it out: [example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoABAAF+ADylYpEsVIA6aMWoCucGFIBCGAEYwoUsLQBOU4tYxo4AB2gQ0AcwCEmzULjEUhjOzlIAvFIAFACU4QB8UsCaUlKwgXow1gByXADcvmgpYDpo1MQQ9FIAbhhQEAAmGIwAqvrWmDgxickpvf60sPhQtB6RGdlc0fmFUqwFPdYwxDrt3TO91RAwAO6IUbFhCZE9GykAPPUQVXEnp+fuzjqBxACezjBh6iCM8sRfUvQHk8wsADIcpOMcjhwlIYPhiBhrB4lvgalAdDBWNVahiQZCuFixDd1ncpGcTE9iJV6NQ6tQANYgtENJowVqZDqYuIAZSY9TOYgpxCpaGJpLJYku11uKWiPTmaAVmiw+CwtBKxEi9Vo1B0OAY+BMtHqLwoQRC0UoNFoWFcsGseBMpnMVv0sDKFSceAATAAGRC+tgcECcvD4ahwATW4TMHhsAC6VDqaHpCBQnBweCwEGIhGs0CtK3IPBIxGccEQ2hKznpHnDNrE2dz+agMm9+F9+AALI2c3noKr3Ph+FbXu88HBqPnnKJWPHWEA).

Thanks. Your example worked very well.
