### ISSUE TITLE
[Documentation] Link to "ospec" points to https://mochajs.org/

### ISSUE THREAD

**Issue by akessner** [MithrilJS/mithril.js#2575]
Link to "ospec" in the documentation on the [Testing page](https://mithril.js.org/testing.html) links to mochajs.org instead of the appropriate ospec documentation.

![image](https://user-images.githubusercontent.com/2528305/76627997-b231a180-6544-11ea-8bb4-cbd148a9b273.png)

**Comment by isiahmeadows** [comment]
If you'd like to file a quick pull request, feel free to do so. It's in `docs/testing.md` in this repo.

**Comment by isiahmeadows** [comment]
Fixed per #2576
