### ISSUE TITLE
Auto redraw doesn't work on array of vnodes

### ISSUE THREAD

**Issue by jhondoeQQUGJehL** [MithrilJS/mithril.js#2586]
Auto redraw doesn't work on array of vnodes

**Mithril version: 2.0.4**

**Browser and OS: Chrome Windows 10**

## Code

```javascript
https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHnxsAbgAI2+ALwAdEDmwGAfHqhKA9KrUnpeJGDFtoXNAEYUtEAF8iPfkEQIQArLhJIWXkxRUiYMQ14NniAKTgoDR0NFIBlAHkAOSFsTHI8AAoAA2pgA20DFAAmAE4iA0i5WQaDAFEkhKhktg1MMDAAVxh+SY0+TABzXj4NCD5BmA18BAhyRA2AR3GIDdX1xMxx-ExZNnHlgBFt3Y0DP1qQetR3AA42mU6xN0QH02AMhiMxpNphs5ot+Cs1q9-HV8A1mgBWP4daJAkFgpHvT4oZoAdix0ABuP6GnWw1GEymfBmsKWCLOW3gOz2GkOxzZyXOl2uzjuGkenOeEFUEC0kzEMqgd0O8KgiDAexgoIJKLRABZyVEuqhetTaRCGdDZgtWacBRyuQcjic1gKsEKbqLxVyVtLZfEFUrxiq1XttR9UahGgBmA2U43A03g+lQpkw63w20be27R18zOCq4eh5PRA+lx++U0wPwsNE5r69oUnHxvE0pOQxnM9PLfPZ7m851nN2FkXFiWl2sRlAANlajcNgJbic15pTXbhPZdWYgk4ajTJ87jKBNoLbK+TMF3qGn9EPzePCdPZovlpZGa3mxLucHrouI9uY7elKbCvIwlQAJQANzmOYcQJEYmSfhMAiyEIhyIOQACeOSII48rkOUBgAMRGAYUEwVASAJAAMskYgAJJyMsWTlOBmQmBotRQOYGi8RouxiOM5AZFxfFiRoahsIgADuKAaOUahQFKiBsToHGieJmkCUJGR8IRIBJAYRAaNQPGaeZvF6QYxjEBJSn4IgQiYGIYhlEI2KyOBbQZBZ5lWSAABG4wudARmcWZvm+dAYBJGAADWcmsex4U+ZFaUaHECCOZy8wKfZjnOa5MBCNo5GpelvlJPEABq+WIVVYi1cpQjsPAcgEXlymMYgfCqRxildUxTkuW52gaAAhFkA0OcNRUlfgUEaJYlj8T1EBqKWmBaExEUVWJPi7elfgvCADlUYgZGHeZjBlRZB3lfdPjQdxlGIAkDVNQ59V0Wk0BCHM2DlOUoI9X1szlLR8TdXwxkg71ZXmHw-0QOMsjlEYxlJWpKVidpwk4+ZkkyYlYMaZFeO6fp4zwGFH35bd5n3ft5g+FB9i4WqziuIoLQoFGvj+CASxBO5MDhP80SKL4zAGWwUBxW4NRC4Eih8KCIjkBw0hCVIaDiGIuAoMtqPYHF8zuaslhq2IGscAAAo0Qi0EIupW+rmvwP9cuhOLYiYdgQRkJr2AxD4jA+EAA
```

## Expected Behavior

I want the list redesigned when an item is removed.

## Current Behavior

The autoredraw doesn't work.

## Context

I have an array of vnodes and I want the list redesigned when an item is removed but the autoredraw doesn't work.

**Comment by porsager** [comment]
Mithril will ignore any vnode object it has seen before (on a true strict equality check).

In your example you are "caching" vnodes by generating the list outside your view. It's also described, albeit a bit more technical, in the docs here: https://mithril.js.org/vnodes.html#avoid-memoizing-mutable-vnodes

**Comment by porsager** [comment]
For your example to work, you could do like this: [flems example](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHnxsAbgAI2+ALwAdEDmwGAfHqhKA9KrUnpeJGDFtoXNAEYUtEAF8iPfkEQIQArLhJIWXkxRSQxDXg2GDEAKTgoDR0NFIBlAHkAOSFsTHI8AAoAA2pgA20DFAAmAE4iA0i5WQaDAFFE+Kgktg1MMDAAVxh+SY0+TABzXj4NCD5BmA18BAhyRA2AR3GIDdX1hMxx-ExZNnHlgBFt3Y0DP1qQetR3AA42mU6xN0QH02AMhiMxpNphs5ot+Cs1q9-HV8A1mgBWP4daJAkFgpHvT4oZoAdix0ABuP6GnWw1GEymfBmsKWCLOW3gOz2GkOxzZSXOl2uzjuGkenOeEFUEC0kzEMqgd0O8KgiDAexgoIJKLRABZyVEuqhetTaRCGdDZgtWacBRyuQcjic1gKsEKbqLxVyVtLZckFUrxiq1XttR9UahGgBmA2U43A03g+lQpkw63w20be27R18zOCq4eh5PRA+lx++U0wPwsNE5r69oUnHxvE0pOQxnM9PLfPZ7m851nN2FkXFiWl2sRlAANlajcNgJbic15pTXbhPZdWYgk4ajTJ87jKBNoLbK+TMF3qGn9EPzePCdPZovlpZGa3mxLucHrouI9uY7elKbCvIwlQAJQANzmOYkTJCM2DYJkn4TAIshCIciDkAAnjkiCOPK5DlAYADERgGFBMFQHEGgADJJGIACScjLFk5TgZkJgaLUUDmBo-EaLsYjjOQGQ8QJEkaGobCIAA7igGjlGoUBSogHE6Fx4mSdpQkiRkfDESAiQGEQGjUHx2mWfxBkGMYxBSSp+CIEImBiGIZRCNisjgW0GRWZZNkgAARuMbnQCZ3EWf5-nQGAiRgAA1gp7GcZFfnRRlGhwQgzmcvMSmOc5rnuTAQjaJR6WZf5iTJGk0DITVqTpEI7DwHIRHlAAHupXGdWV+AaAAhFkymqS5bkeeVkEaJYliCYgfAQGopaYFoLFRVVEk+BtmV+C8IBOXEiAUTtlmMBVVnbZVV0+NBvFQHwQiLeMsjlEYpkpRpaUSbponfZZ0lyclPX-dFv36YZ4zwBFjV1VAT04OU5SggtIMGfRyTMQtpko3w4H43dl0bTdUHSJAfDYBwWGKEFmBBfh9j4WqziuIo7hRig3zeG8IBLEEnkwOE-zRIovjMEZbBQAlbg1LzgSKHwoIiOQHDSCJUhoOIYi4Cgs0vdgCXzJ5qyWIrYjKxwAACjRCLQQi6qbSsq-AT2S6EQtiNh2BBGQKvYDEPiMD4QA)

**Comment by jhondoeQQUGJehL** [comment]
Thanks for your help. I didn't think if i deleted the contents would work.
