### ISSUE TITLE
can use ‘m("script")‘ for project? 

### ISSUE THREAD

**Issue by cnSonkwl** [MithrilJS/mithril.js#2589]
Sometimes,our project can not use AMD,CMD or es6.
So we test use the m("script",{src:"module.js"}) ,that replace require("modele.js").Right now , it's ok! 
Can MithrilJS add this feature？

**Comment by isiahmeadows** [comment]
Does it not already work? Have you tried it yet?

**Comment by cnSonkwl** [comment]
#A new Modular scheme for MithrilJS,by using m("script")
NO NO......It working very well。I mean ,mithril may be use m("scrpit") , to replace the Modular scheme (require or import) of AMD&CMD. It is a way or method,Mithril have a another “Modular scheme".

### I am a chinese web development，so my english is not well.

**Comment by isiahmeadows** [comment]
> I am a chinese web development，so my english is not well.

I get you're not a native speaker. I guessed as much. Don't worry - much of the Mithril community also don't speak English as their first language.

To answer your question:

1. Mithril does *not* have any built-in script loading feature.
2. Rendering an `m("script", {src: "..."})` should still work - it adds a `<script>` to the DOM the same way this does:

```js
var script = document.createElement("script")
script.src = "..."
parentElement.appendChild(script)
```

Does this help?

**Comment by jack0088** [comment]
It actually seems to **replace** the entire **<head>** with this new VNode. Could you explain how I could just _append_ instead, please?

Consider this example: My server returns a barebones html skeleton to the client. <head> references to mithril and a view controller script. This view controller will actually build the entire UI for the client. If that view controller depends on other libraries, then I want to preload them dynamically. I know there are many options to achieve this, but lets go with this very example. So, I use mithril in my view controller to generate and attach a new `<script src="dependency.js">`. (In perfect scenario I want to wait until the remote dependency is fully loaded. So probably mithril returns some kind of a Promise?)

index.html
`<!doctype html><html><head><script src="https://unpkg.com/mithril/mithril.min.js"></script><script src="viewcontroller/main.js"></script></head><body></body></html>`

viewcontroller/main.js
`m.render(document.getElementsByTagName("head")[0], m("script", {src: "whatever/script.js"}));`

When I try the above example, then <head> ends up only containing what m.render gave it - replacing all the previous attached DOM children. Any ideas?

**Comment by osban** [comment]
@jack0088 yes, the first argument of `m.render` is the parent element used for whatever you pass it, thus replacing what's already there. I suppose appending to `<head>` would be possible using vanilla js (as @isiahmeadows showed above):
```js
const head = document.getElementsByTagName('head')[0]
const tag  = document.createElement('script')
tag.src = 'whatever/script.js'
head.appendChild(tag)
```

**Comment by isiahmeadows** [comment]
@jack0088 `parentElement` could be `document.body`, of course. Also, when you add a script and remove it later, the contents are still executed either way - there's no way to "undo" it.

**Comment by jack0088** [comment]
thank you @osban and @isiahmeadows. I decided to not support every possible browser and instead simply fetch the required scripts using the `import("module.js")` function provided by javascript. It's embarrassing that it took me 3 days to finally find out, that this method is now part of javascript and is supported by all major browsers. Bonus: looks and works the same as NodeJS.

**Comment by isiahmeadows** [comment]
Closing as the initial concern has been resolved. If you have further questions, please file a new issue.
