### ISSUE TITLE
webkit engine page load yields InvalidStateError: The object is in an invalid state.

### ISSUE THREAD

**Issue by kriestof** [MithrilJS/mithril.js#2591]
**Mithril version: 2.0.4**

**Browser and OS: epiphany 3.36.1-1 Linux** (heard problem appears on the newest Safari on Mac OSX)

**Project: https://covid19map.icm.edu.pl**  https://github.com/kriestof/COVID-19-MAP

Application crashes under webkit engine when page is loading. I highly use mithril.js and d3.js to produce svg map and chart. Previous version without mithril.js worked fine.

Console yields `InvalidStateError: The object is in an invalid state.   mount-redraw.js:15`.

**Comment by kriestof** [comment]
Seems svg was no trouble but handling of valueAsDate in webkit. Will investigate and eventually reopen.

**Comment by cavemansspa** [comment]
was looking at your app -- nice work @kriestof

**Comment by kriestof** [comment]
Thank you!
