### ISSUE TITLE
Intermittent "Could not resolve default route" error

### ISSUE THREAD

**Issue by elazar** [MithrilJS/mithril.js#2596]
**Mithril version:** 2.0.4

**Browser and OS:** Chrome 81.0.4044, Android 10 (Samsung SM-G970U)

## Code

This is a snippet of bootstrap file for my project.

```javascript
const m = require("mithril");    
    
import "./index.css";      
    
m.route(document.body, "/villagers", {    
    "/villagers": { onmatch: () => import(/* webpackChunkName: "villagers" */ "./views/Villagers") },    
    // <snip>
});
```

## Expected Behavior

The default route should be resolve successfully and consistently.

## Current Behavior

I get intermittent reports (via [Sentry](https://sentry.io)) of this error, which reports the associated mechanism as `onunhandledrejection`:

```
Error: Could not resolve default route /villagers
  at a(/nook-plus-build/js/app.js:1:33580)
```

This is the minified version of the code reported to be causing this issue:

```javascript
.slice(h.prefix.length),o=c(t);function a(){if(t===i)throw new Error("Could not resolve default route "+i);s(i,null,{replace:!0})}d(o.params
```

Which appears to correspond to [this block](https://github.com/MithrilJS/mithril.js/blob/f9c9f6682d70e5d09585c4172a945d3dd145579e/api/router.js#L84-L138) in the Mithril source.

## Steps to Reproduce

Unfortunately, I haven't found a way to intentionally reproduce this. I know that the user can generally access the page after a manual refresh. This doesn't appear to correspond to any deployments of changes to my application source code.

## Context

I'd like to know how I can or should route my users to avoid this intermittent error, whether the issue is with my application or with Mithril.

**Comment by cavemansspa** [comment]
perhaps the dynamic import is intermittently failing? maybe try catching errors and returning an error component to render.

**Comment by elazar** [comment]
I made the change below and haven't seen a report of this error in Sentry since. So, it would unfortunately appear that this is a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug). :cry:  

```js
m.route(document.body, "/villagers", {
    "/villagers": { onmatch: () => {
        try {
            return import(/* webpackChunkName: "villagers" */ "./views/Villagers");
        } catch (error) {
            console.log(error);
            Sentry.captureException(error);
            return <div>
                We are having a small problem. It is probably temporary.
                Care to { m(m.route.Link, { href: "/villagers" }, "try again") }?
            </div>;
        }
    } },
```

**Comment by elazar** [comment]
I received another report of this issue today from Sentry.

Same Mithril version (2.0.4).
Chrome Mobile 88.0.4324 (vs 81.0.4044).
Android 9 (vs 10).
Same device (SM-G970U).

Not sure if it will help, but here's a fragment from the Sentry report.

![Screenshot from 2021-01-25 09-24-06](https://user-images.githubusercontent.com/15487/105725937-24a63880-5eef-11eb-96e7-d80eb612cfc0.png)

**Comment by Alisaien** [comment]
The try/catch block does not solve failing imports, since a dynamic import returns a Promise, but you cannot try/catch unhandled Promise rejections, try for example (in browser console):
1. `try { Promise.reject(1) } catch (err) {console.log("catched") }` this will trigger `Unhandled Promise Rejection: 1`
2. `Promise.reject(1).catch((err) => console.log(err))` this will handle the error properly, simply logging `1`

So if your dynamic import fails, your try/catch will be useless (maybe some browser vendors, handle this slightly differently) the rejected Promise will cause the `onmatch` to fail, which then produces your error.
Using `.catch()`  should solve your issue.

**Comment by Alisaien** [comment]
Maybe the reported error "Could not resolve default route" should be made more specific like "Promise returned by onmatch rejected => cannot resolve default route" to make it clear what causes the error, but I do not know if there are other cases which can trigger the same error.

**Comment by isiahmeadows** [comment]
@elazar You need to `return await` to ensure rejections get caught by your `try`/`catch` block. `return` skips that logic entirely, a long-standing criticism I have of TC39's spec work (they *really* should've known to check for that edge case and not blindly spec it in terms of generators).

**Comment by elazar** [comment]
> @elazar You need to `return await` to ensure rejections get caught by your `try`/`catch` block. `return` skips that logic entirely, a long-standing criticism I have of TC39's spec work on `async`/`await` (they _really_ should've known to check for that edge case and not blindly spec it in terms of generators).

@isiahmeadows Thank you! I've implemented this and haven't seen any recurrences of this issue as of yet. The affected app isn't high-use, though, so it may just be a matter of time. I'll try to remember to update this issue if I run into it again. Thanks again!

**Comment by dead-claudia** [comment]
Closing due to age.
