### ISSUE TITLE
Generate two seperate same-level containers with a global layout component

### ISSUE THREAD

**Issue by VladimirCascarade** [MithrilJS/mithril.js#2598]
Hello guys,

I am trying to update the Layout in the tutorial one page app from the website to return two global components.

**Mithril version:** 2.0.4

```html
// src/views/Layout.js
var m = require("mithril")

module.exports = {
    view: function(vnode) {
        return m("main.layout", [
            m("nav.menu", [
                m(m.route.Link, {href: "/list"}, "Users")
            ]),
            m("section", vnode.children)
        ])
    }
}
```

Ideally I would like the code to output two same-level global components, let's say:

```html
<div class="menu">...</div>
<div class="content">...</div>
```

instead of

```html
<main>
    <nav></nav>
    <section></section>
</main>
```

The issue for me is that I cannot find a way to get rid of the parent container.

**Comment by osban** [comment]
@VladimirCascarade you can achieve that with:
```js
view: () => [
  m("nav"),
  m("section")
]
```

**Comment by VladimirCascarade** [comment]
Thanks for getting back so quick. 

I was doing something along the lines of

```js
view: (vnode) => [
    MenuComponent,
    SiteContentComponent
]
```

but I wasn't able to get SiteContentComponent to display properly (and keep the vnode information). I used your suggestion and it seems to be working now. Thanks!

**Comment by osban** [comment]
@VladimirCascarade you're welcome! If you have more questions you can also post them in the [Gitter chat](https://gitter.im/mithriljs/mithril.js). There are usually people around to help 🙂
