### ISSUE TITLE
Modularization info on gh-pages installation.html out-of-date

### ISSUE THREAD

**Issue by pdfernhout** [MithrilJS/mithril.js#2599]
As mentioned on gitter today, this statement seems out-of-date on the website: at: https://mithril.js.org/installation.html 
"Most browser today do not natively support modularization systems".

See: https://caniuse.com/#search=modules

A larger issue is that the whole page may be increasingly out of date by having only CommonJS examples compared to more examples using ES6 modules.

Example from code I wrote two years ago using Mithril and ES6 modules (with unpackaged modules loaded via SystemJS):
https://github.com/pdfernhout/storyharp-js/blob/master/source/index.html
https://github.com/pdfernhout/storyharp-js/blob/master/source/main.ts
https://github.com/pdfernhout/storyharp-js/blob/master/source/RuleEditorForm.ts

Example from code I wrote about a year ago using Mithril without SystemJS (where Mithril is just loaded via an import statement `import "./vendor/mithril.js"` to defined an `m` global):
https://github.com/pdfernhout/Twirlip7/blob/master/src/ui/chat.html
https://github.com/pdfernhout/Twirlip7/blob/master/src/ui/chat.js

**Comment by isiahmeadows** [comment]
1. Thanks for the link regarding module support.
2. Not going to run through and move everything from CJS to ESM, not *now*, anyways.
