### ISSUE TITLE
Docs incorrect re: "Avoid statements in view methods"

### ISSUE THREAD

**Issue by glenreesor** [MithrilJS/mithril.js#2604]
As per your comment on gitter.im (https://gitter.im/mithriljs/mithril.js?at=5ee99a4630401c1f245f78c5), the anti-pattern "Avoid statements in view methods" (https://mithril.js.org/hyperscript.html#avoid-statements-in-view-methods) has a couple of issues:

- it's incorrect in explaining why it's an anti-pattern
- you figured it belongs here: https://mithril.js.org/vnodes.html#avoid-anti-patterns

**Comment by kevinfiol** [comment]
Made a PR: https://github.com/MithrilJS/mithril.js/pull/2748
