### ISSUE TITLE
Recommendation for handling large (SVG) documents

### ISSUE THREAD

**Issue by sorenjakobsen** [MithrilJS/mithril.js#2606]
Hello, I wonder if there is some recommended technique for working with large virtual DOMs in mithril?

I am using mithril to manage an HTML page with some SVG parts (charts) - there are a lot of data points so the (virtual) DOM gets quite large.

I am using the 'onbeforeupdate' function to avoide that mithril performs a complete diff on every redraw. However, the whole, large js/mithril object that represents the document is still being rebuilt every singe time a redraw is made - causing quite some lag.

I am thinking about caching that large object and tracking which parts of the object needs to be updated (caching those parts separately). But then I am effectively doing the work of mithril - also figuring out which parts of the corresponding DOM that need to be updated...

Anyway, I was also wondering if I could somehow use the component feature of mithril to implement this, but I don't know if mithril automatically caches the result of the components 'view' function, and uses that cached version when 'onbeforeupdate' returns true? (I am actually not mounting my components but calling m.render directly)

**Comment by isiahmeadows** [comment]
You may want to consider two options here:

1. If this is a static (non-interactive and non-animated) SVG, consider putting it in its own file and doing `m("img", {src: "foo.svg"})`.
2. If that isn't possible, definitely consider using a component with a `onbeforeupdate: () => false` as one of its attributes, as that prevents the whole subtree from being reconstructed.

**Comment by dvdkhlng** [comment]
What I did for doing SVG plots with a lot of frequently updating points with Mithril, was to put all points into a single [SVG &lt;path&gt;](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) DOM node joining many "a" (arc) and "M" (moveto) commands in a single attribute.  This improved performance a lot.  Maybe not just for the javascript side, but also for the browser's rendering pipeline.

**Comment by isiahmeadows** [comment]
Just wanted to follow up with this: I would like to see such a large real-world SVG file that I can play with, for benchmarking purposes.

Also, with very large, interactive SVG files, if Mithril's performance becomes a problem, you might want to build and manage the SVG file manually, without using Mithril. Keep in mind that Mithril's overhead is less than 50% of optimal native on most standard DOM trees (which rarely update, BTW), so beating Mithril may be harder than it seems.

**Comment by isiahmeadows** [comment]
@dvdkhlng I'd very highly recommend checking out [the Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API), specifically [`CanvasRenderingContext2D`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D). It's far more efficient for highly dynamic content - one person in the Gitter channel was creating an integrated circuit layout viewer to show the layout of an older CPU, and they went from a few frames per second with fans and everything to fairly low CPU usage and an easy 60 frames per second after they switched from *raw* SVG (they had already abandoned Mithril by that point) to Canvas. And for basic points and shapes, Canvas is *far* easier to use, too - I have my own experiences with it (closed source or I would link to it here). Oh, and actual use of it in practice is more Mithril-like than DOM-like as long as you are careful to separate your render path from your data model (which is best practice for canvas stuff anyways).
