### ISSUE TITLE
it's bad for special character，when you use ‘map’ or redraw. 

### ISSUE THREAD

**Issue by cnSonkwl** [MithrilJS/mithril.js#2616]
###  code1

```
var test=[
    "testVal<br>by used",
    "testVal&#10;by used2"
]

m.render(document.body,test.map(function(item){
    return m("p",item)
}))
```

mithril  do not handle "br" or "#10;"

### code2

```
//use m.request() to back this json
var test={
    val1:"testVal<br>by used",
    val2:"testVal&#10;by used2"
}

var show={
    oninit:function(){
        m.requery().then()
        //response test's json
    },
    view:function(){
        //return m("div",test.val1.replace("<br>","\n"))   
        return m("div",test.val2.toString()) 
    }
}
```

Throw errors!
like 'replace' or 'toString',all JS string-methods not be used in this example;

**Comment by osban** [comment]
@cnSonkwl 
* first code: Mithril does not normally process html, for that you need to use `m.trust`, like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAkZxiAXmQAdNNPXTlIOcQBqGKAB4ARpIB8xgJ7SArnBgATLRVUbN2+HoMAyAMQBGAAYAbitbewcAJi1VAF1VVSx8SSYHGEkACgdaahscBnxjWgdLCh18LAwABwywGzRqYgh6DIhGLABKYFcNFOIbSTUsDK0q52kk4kk7Ylb2jo7VVgXKEHtYRua0BB4AdkQAZjYOEEwcPHxqOAEaekZmHjZYqigINABrHdRTrjwsNsIkmgqwG5B4JGIVTgiAA9DD6lV3gBzS60LAw-7EQHQAACkXwgXwABYMQCgVAKm98PxVsRLFVuGtqECqqJWLFWEA)
* second code: you have a typo: `m.requery` should be `m.request`, but other than that it should work

**Comment by cnSonkwl** [comment]
Oh yes ,  m.trust  works well for code1.
