### ISSUE TITLE
Querystring and pathway routing strategies always serve the default route on page load

### ISSUE THREAD

**Issue by pereriksson** [MithrilJS/mithril.js#2617]
**Mithril version:** 2.0.4
**Browser and OS:** Chrome version 84.0.4147.105 (Official Build) (64-bit). Mac OS X version 10.15.6
**Project:**

## Code
[Example on flems.io](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQiTcEATwAOEAATsoAPgA6dVYIUq1dDRAZJFggPRY9B1eoBG3JBK3qkZAG6yySALzKQDKVK+GjRyd7HSNrWy1jTU5IGAQyXip0AE5UAAYQAF9CeiYWdAwAKypiHj4IAXRZatkYeFkAQV9Zd1kSAFc6eN4ACgBKWWBVGpHZACcIeHaxukHh0YWnMggAd1Q2zu66frnZhf3qiamZ2Wp5g4vZXB7cDDHudsQMABkyOgBrQkGsCZJ1gHIjP9srJ-gAJbjMf59QjnS77a63e6PCAvN6fb6-AFGXDcMbwADmDAJEDAwK+-wAsnjCcTSdDYXt4Qiev8sABGf4UiFQvpw5kAXQA3Pz9plRdVMiKmbIpRYZXVZNT8USSWAWhsuvAEtsBkMZSMjtNZvrmUtVusOlqdTtTcyakaTmcDfbqoi7g8nq8Pl9gD8IH9QUCQeDIRAGRL7e7kV70b7-YHAbiVXSySHlbS1RGXa7rmzORSM6r6XycxdhZGRuKy3KZbW4UjPRAepGxLB2sw+BgSfAAKIwTvwABCEgAkkhWT4pNmDoCuZG7Zc5+smlJGcykzTi2T1kXU5HqyM+tKGx6URgpL8yAAPDX-f5CmLQODaxKsdkAZnSWRyIEYzFYDBYDAEouF4fh4FYLIBWIKB0SSWg-zyVhcDIeAfgoThpgIdAcHgKQwFQIwjE6KR3gJIDIRxNCMKgAABAAmDA0gwAAWaj0LGCgMFQugilA+BpHycBYC4qRIMyAVMiAA)

## Steps to Reproduce
1. Click on Mortgages
2. Reload the page

## Expected Behavior
Mithril serves the Mortgages component.

## Current Behavior
Mithril serves the default route.

## Context
Serving the correct route on page load works well for the default routing strategy. However for the two other routing strategies Mithril always serve the default route. This makes linking to Mithril URL:s from other websites difficult.

**Comment by pereriksson** [comment]
Apache has been configured to always serve index.html for all paths using:
```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
```

**Comment by isiahmeadows** [comment]
Set `m.route.prefix` *before* invoking `m.route`.
