### ISSUE TITLE
Request with 204 no-content response causes syntax error in IE11

### ISSUE THREAD

**Issue by Evoke-PHP** [MithrilJS/mithril.js#2624]
**Mithril version:** 2.0.4

**Browser and OS:**IE11.0.125 on WIndows 7

## Code

```javascript
// Code
m.request('https://httpstat.us/204').then(r => console.log('Success', r));
```
[Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE4wAjgFd4xABQByEsQAOcRAHptazcQzF8suNoBMABgAsygJQAdNAAJn+YoSaKJzgLwA+ZyE4Wlh8AHcMCTQVAGVZamp4OGUKZwk7OwBuShA4GFhqYgh6BB4ARkRrcrYOEEwcPHxqOAEaekZmHjYAXSooCDQAazLUeq4xCA8JaFzZCXIefS1dWTR1IYBzZtosbSwpwhmoAAFzfEt8a33D4-wDtHx+XOIAT3VuPOoZ9VFWHtYQA)

## Expected Behavior

Expected to see Success, null in the console log.
## Current Behavior

Saw Success, null when run in Chrome browser.
Saw Syntax Error in console when run in IE11.

## Context

This appears to be due to: [the JSON parse of an empty string for IE11](https://github.com/MithrilJS/mithril.js/blob/ff3e12e5d398f653b2d0ea182a1fc963473d47f6/request/request.js#L126)

**Comment by isiahmeadows** [comment]
Yeah, we're not matching the XHR spec correctly here: https://xhr.spec.whatwg.org/#json-response

It should be guarded with a `try`/`catch` guard. Thanks for the report!
