### ISSUE TITLE
Can't finish installation with webpack because of webpack-cli 4.1 version

### ISSUE THREAD

**Issue by ThomasK0lasa** [MithrilJS/mithril.js#2634]
**Mithril version:**
2.0.4

## Steps to Reproduce
Do the installation step by step as written here https://mithril.js.org/installation.html#quick-start-with-webpack

## Expected Behavior
Proper npm start

## Current Behavior
Current installation step by step as in documentation ends in Webpack-cli error break. I had to install older version of webpack-cli.

`[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.`

## Solution
I would like some note about using older webpack-cli v3 in documentation (installation) or proper instruction with use of webpack-cli v4.

**Comment by charles1e62** [comment]
I was having the same problem and the following configuration worked for me.

`npm i -D babel-loader @babel/core @babel/preset-env @babel/plugin-transform-react-jsx webpack webpack-cli --save-dev`

**webpack.config.js**

```javascript
const path = require('path')

module.exports = env => {
  return {  
    mode: env.mode,    
    entry: './src/index.js',
    output: {
      filename: 'bundle.js',
      path: path.resolve(__dirname, 'js'),
    },
    module: {
      rules: [
        {
          test: /\.m?js$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env']
            }
          }
        }
      ]
    }
  };
};
```

**package.json**

```json
{
  "scripts": {
    "start": "webpack --watch --env mode=development",
    "build": "webpack --env mode=production"
  }
}
```

**Comment by Smadarl** [comment]
I was able to get it running with the latest webpack and the following start script:
`"start": "webpack ./src/index.js --output-path bin --output-filename app.js --watch --mode development"`

**Comment by msesun** [comment]
how do you view in browser when running locally?

**Comment by ArthurClemens** [comment]
> how do you view in browser when running locally?

When using Webpack, or when just loading a javascript file?

**Comment by msesun** [comment]
When using webpack. I tried copying the path of index.html file to my browser but I get an error `Failed to load resource: net::ERR_FILE_NOT_FOUND` for bin/app.js. I can see the app.js file in my bin folder so I'm thinking I'm just loading the file wrong?

**Comment by ArthurClemens** [comment]
I've created https://github.com/ArthurClemens/mithril-webpack-starter because it is hard to explain in a few words.

**Comment by msesun** [comment]
@ArthurClemens will take a look. Thank you!

**Comment by ArthurClemens** [comment]
I wanted to add: the starter is what I consider the minimal/essential for app development.

It includes:
- dev server with live reload
- loader for CSS (`postcss` because it is handy)

The build is normally viewed using a web server (`npm run preview`) but can be viewed also by opening `dist/index.html` in a browser.
