### ISSUE TITLE
Can't watch videos on Scrimba

### ISSUE THREAD

**Issue by 4skinSkywalker** [MithrilJS/mithril.js#2636]
I don't see any video when navigating to the link you posted on https://mithril.js.org/learning-mithril.html

**Comment by osban** [comment]
@4skinSkywalker You can watch the videos [here](https://vimeo.com/showcase/5584199) (non-interactive).

**Comment by isiahmeadows** [comment]
I did a direct edit to the generated docs to fix that link, so it should be fixed soon. (I haven't yet been able to push all the fixes yet due to work taking too much of my time.)
