### ISSUE TITLE
Mithril redraw doesn't happen when run inside Jest and JSDOM

### ISSUE THREAD

**Issue by sharat87** [MithrilJS/mithril.js#2642]
I'm trying to test a Mithril component using Jest with JSDOM environment. However, I am unable to see the effects of Mithril's redraw being called.

**Mithril version: 2.0.4**
**Mithril-query version: 3.1.0**
**Browser and OS: Firefox on macOS Catalina**

## Code

I have the following test script:

```javascript
// query.test.ts
import m from "mithril"
import mq from "mithril-query"

function RootView(): m.Component {
	let username: string = ""
	let usernameInDisplay: string = ""

	return { view }

	function view(): m.Children {
		return [
			m("label", { for: "username" }, "Username"),
			m("input", {
				id: "username",
				value: username,
				oninput: (event: Event) => {
					console.log("oninput called")
					username = (event.target as HTMLInputElement).value
				}
			}),
			m("button", { type: "button", onclick }, "Print Username"),
			m("p", document.visibilityState),
			m("p.result", usernameInDisplay),
		]
	}

	function onclick() {
		console.log("button clicked")
		usernameInDisplay = username
	}
}

test("mithril query based", async () => {
	console.log(document.visibilityState, window.requestAnimationFrame)
	const root = mq(RootView)
	root.should.contain("Username")
	root.setValue("#username", "Holmes")
	root.click("button")

	// Wait a bit for Mithril to redraw.
	await new Promise(resolve => {
		setTimeout(resolve, 400)
	})

	root.should.contain("Holmes")
})
```

When I run this test script with the following jest command:

```sh
npx jest -c '{"preset": "ts-jest"}' src/tests/query.test.ts
```

I get the following output:

```
  console.log
    visible [Function (anonymous)]

      at Object.<anonymous> (src/tests/query.test.ts:34:10)

  console.log
    oninput called

      at Object.oninput (src/tests/query.test.ts:17:14)

  console.log
    button clicked

      at Object.onclick (src/tests/query.test.ts:28:11)

 FAIL  src/tests/query.test.ts
  ✕ mithril query based (423 ms)

  ● mithril query based

    Expected "Holmes" not found!

      43 |      })
      44 | 
    > 45 |      root.should.contain("Holmes")
         |                  ^
      46 | })
      47 | 

      at Object.shouldContain [as contain] (node_modules/mithril-query/index.js:352:13)
      at Object.<anonymous> (src/tests/query.test.ts:45:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.253 s
Ran all test suites matching /src\/tests\/query.test.ts/i.
npx jest -c '{"preset": "ts-jest"}' src/tests/query.test.ts  5.27s user 1.18s system 132% cpu 4.879 total
```

## Expected Behavior

The test should pass.

## Current Behavior

The test fails because the DOM updates don't happen. Calling `root.redraw` provided by `mithril-query` also doesn't seem to make a difference.

## Steps to Reproduce

Run the test script above with the command given in the same section.

## Context

I'm trying to test my Mithril components with Jest and mithril-query. The testing page on official website recommends mithril-query, JSDOM and ospec, but I'm using mithril-query, JSDOM and Jest since my project already uses Jest for tests on business logic.

**Comment by pygy** [comment]
Hi!, `mithril-query` is out of my perview, but @StephanHoyer will probably be well equipped to help you...

**Comment by barneycarroll** [comment]
@sharat87 Mithril Query does autoredraw (instantly!) but when I tried replicating your issue I found the component closure was reinitialising every draw, wiping the state clean. I raised [an issue on the Mithril Query repo](https://github.com/MithrilJS/mithril-query/issues/109).
