### ISSUE TITLE
Not able to change Content-Type

### ISSUE THREAD

**Issue by PabloBarrachina** [MithrilJS/mithril.js#2647]
https://github.com/MithrilJS/mithril.js/blob/2b5c2f0fc6e16705bddbfe043e90eef5eb31210b/mithril.js#L1398

¿Is this a typo?

**Comment by pygy** [comment]
Great catch @PabloBarrachina this looks like a bundler bug, it is incredibly fickle (it is not using a proper parser, just a RegExp-based approximation of one).

**Comment by pygy** [comment]
I dread these bundler bugs...

I'd be tempted to rename the problematic variables, or to use the RegExp constructor to work around it...
