### ISSUE TITLE
m.render() ignores the key of the vnode returned by comnponents

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2654]
I keep running into this gotcha whereby I have a solitary dynamically-keyed node as the return value of a components view, and changing the vnode key doesn't cause the node to reinitialise. The reason this doesn't work is that AFAICT component instances are the only case in which a user-supplied vnode isn't normalised as a list item. Just as `m(tag, ...vnodes)` is equivalent to `m(tag, [...vnodes])` & `m.render(el, vnode)` to `m.render(el, [vnode])`, I suggest we normalise component view output such that instances are always fragments - which as well as obviating this edge case would have the added benefit of making vnode tree traversal easier to reason about.

[Reproduction here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgCNaATATwAI5i3WAF4AOuHrFEvAIwwsAehn4ArPwxo4AWjgwAThDDiAfKLS9eLAA6nzF3gEleMAB5WY1Yrwy8Abmi4YXghzYkIguGwgq1o4CGIIel42GGIAdxgmXj0mTn04XjT4wm9zAFcrTgwEtABzXgBrGD5iWl5qDDLdXkYMPU5aNPMNTmyYEPiIDCgISIT6CmSyrzDZwugoXnooPlpqajK9YNDw-g96UZCBDWoIkNue08g9AWCCgK9XKxnqeJ3+eJlaowS7DXgzAT4SzyYwACgcaGoORwDHatDKqNavCwXEMfDoWBiaCYXmujAA3MckfISY1mj02tVGISvDkJglprNqok0ABKFgKGFmCwCmzCyycCC+YKcYQYYwCyW+Wwiwh6BQqiVSmXCNgKhRK2wCjg8YyUEC6WCeHkIRAgABMiAAzDIAAwgAC+FHQUTw+AAVggqHQGCS8AoFLwAILYjFVYlojGMI4Eokkswh14AYXRoaOwl4sN5vGExl4wHFsC8dCTJd4rvF4pyxEO5grdgsvggMDS0mlpd44vs2NhAHJkAIhDBdbR+vpEDIrC5+LQZpxyVYMJxJXUF-IALqjihD4cj0dWI+8Uc5pPSS81hi848d08n4dYMdsZatNCX4D0agfgaaQixLMtgETBgAGooN4D0vSvBFqRRatc2IABCUcnzfewcIsD9RzVLDn1PXCX2HXx8GoQhoE4HI0BI09sLsD0zFYtAzAjXhAF4NwBxHd4ABlGIVlOSUwDAfQmAeQA+DcAFF2zDMLB8BxJNYQwRZQIHdsLCrOk+ALBs7CbVJW3LE8ux7EDiwHHCPxvPNFmAJpuC9PCzwvRZRwAaWaO9Fmc5i3IIr9iB-P8AKAqywPLPSYLghDRyQ5FaWczDmNI9K4LY3kFLQJSVIYWE2A06zwMrVI9LrQyLGMls9Dbczu17QtSt4ZBbNhezk0c5zXPI+wCI8q8fO4Py9MC-r8M-b96HCxFIpa6KIOcuL4M8pKaVRVLiJwzKLH3Rj2I9XlzUtDx5k0PAABYVEQe0tHtV1EHdD0DpAGY0AaW1UBATAcDwLBigMcgqEOcg7RIYgrDgRAIwxKwGlqKjaEUQGwmBgABe18FdfAroUNG1WgZSQgDIMQEEdw8DgJEICsYhPX3D0gA).

I'm happy to implement this myself.

**Comment by pygy** [comment]
I'd rather check for the presence of a key at diff-time, it will have the same ultimate result, and will be more efficient.

**Comment by barneycarroll** [comment]
I still think my suggestion is better because along the lines of #2669 it moves us towards monomorphic vnode structures which are more predictable. The counter proposal gets us into the same category of issues as #2669 where we introduce extra code paths for efficiency when IMO having a more consistent structure makes the codebase more maintainable and has the added benefit of making tools integrating with vnode easier to write.

**Comment by barneycarroll** [comment]
Closing this, keeping #1713
