### ISSUE TITLE
Prefix with unicode encoded characters does not work

### ISSUE THREAD

**Issue by charlag** [MithrilJS/mithril.js#2659]
**Mithril version:**
2.8.4

**Browser and OS:**
Electron on Windows

**Project:**
Tutanota

## Code

package.json
```json
{
    "name": "my-electron-app",
    "version": "0.1.0",
    "author": "your name",
    "description": "My Electron app",
    "main": "main.js",
    "scripts": {
        "start": "electron ."
    }
}
```

main.js:
```js
const { app, BrowserWindow } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  win.loadFile('index.html')
}

app.whenReady().then(createWindow)

app.on('activate', () => {
    createWindow()
})
```

index.html
```html
<!doctype html>
<document>
    <body>
    <div id="root"></div>
    <script src="https://unpkg.com/mithril/mithril.js"></script>
    <script>
		m.prefix = window.location.href
		const root = document.getElementById("root")
		history.pushState(null, "", window.location.href + "/ok")

		const Ok = {
			view: () => "ok!"
		}
		const Nok = {
			view: () => "nok!"
		}
		m.route(root, "/ok", {
			"/ok": Ok,
			"/:path...": Nok,
		})
    </script>
    </body>
</document>
```

```sh
npx electron .
```

## Steps to Reproduce

0. Have minimal electron project which just loads the page. Browsers don't allow changing path after .html for file:// URL.
1. Have prefix with non-ascii characters. Must not use #! or query routing modes. Prefix could look something like `file:///home/ivk/dev/t%C3%A4st/index.html` (that folder is täst).
2. Route with such prefix.
2. Observe that routes are not matched correctly

## Expected Behavior

The page renders "ok"

## Current Behavior

The page renders "nok"

## Context

Why?
If we look at this code:
```js
			var prefix = $window.location.hash
			if (route.prefix[0] !== "#") {
				prefix = $window.location.search + prefix
				if (route.prefix[0] !== "?") {
					prefix = $window.location.pathname + prefix
					if (prefix[0] !== "/") prefix = "/" + prefix
				}
			}
			// This seemingly useless `.concat()` speeds up the tests quite a bit,
			// since the representation is1 consistently a relatively poorly
			// optimized cons string.
			var path0 = prefix.concat()
				.replace(/(?:%[a-f89][a-f0-9])+/gim, decodeURIComponent)
				.slice(route.prefix.length)
```

In case of file URLs `prefix` would be `//home/ivk/dev/t%C3%A4st/index.html`. 

The problem is that preix and mithril.prefix would be incosistent because one of decoded and was not. This only happens with "path" routing mode, not hash/query ones.

We stumbled upon this for users with Windows username containing non-ascii characters.

Workaround is simple: when setting mithril prefix do the same transformation:
```js
m.prefix = window.location.href.replace(/(?:%[a-f89][a-f0-9])+/gim, decodeURIComponent)
```

**Comment by StephanHoyer** [comment]
Works for me.

I think the reason for it not working for you is wrong usage.
1. `m.prefix` can [only be ``, `#` or `?`](https://mithril.js.org/route.html#changing-router-prefix) but not any string
2. using `` (or `window.location.href` for that matter) as prefix in this case does not work, no matter what the directory of the app is, because it tries to access a file named `index.html/ok` which of cause does not exist
```
$ npm start

> my-electron-app@0.1.0 start /private/tmp/öö-test
> electron .

(node:90590) electron: Failed to load URL: file:///private/tmp/%C3%B6%C3%B6-test/index.html/ok with error: ERR_FILE_NOT_FOUND
(Use `Electron --trace-warnings ...` to show where the warning was created)
```
3. If you use `#` as prefix prefix, all works as expected
```js
  // m.prefix = window.location.href
  const root = document.getElementById("root")
  // history.pushState(null, "", window.location.href + "/ok")
  history.pushState(null, "", window.location.href + "#!/ok");
```
