### ISSUE TITLE
Mithril + esbuild config for JSX

### ISSUE THREAD

**Issue by shuckster** [MithrilJS/mithril.js#2660]
**Mithril version:** 2.0.4
**Browser and OS:** Chrome, macOS

## Code

```javascript
esbuild.build({
  platform: 'browser',
  jsxFactory: 'm',
  // jsxFragment: 'm.fragment', <- problem line
})
```

## Expected Behavior
JSX works great with the above config for the highly performant [esbuild](https://esbuild.github.io/).

It's just fragments in the following form that don't get transformed quite right:
```jsx
function Component () {
  return (
    <> {/* <- denied! */}
      <One />
      <Two />
    </>
  )
}
```
Despite a bit of Google'ing and trying to write a stub-function that wraps `m.fragment` in various ways, I've not had much luck so far. I feel like there's something obvious I'm missing that screams "it's not possible just write `m.fragment` directly" but I thought I'd try anyway. 😁

**Comment by kevinfiol** [comment]
Having this same issue at the moment. Gonna take a further look into this tonight if I have time.

**Comment by shuckster** [comment]
That worked a treat, thank you very much!

**Comment by shuckster** [comment]
FYI, [here's where](https://github.com/shuckster/OBIS/blob/master/src/main.js#L20) I implemented it in my own project. Thanks again. 🙏
