### ISSUE TITLE
Docs formatting issue in website

### ISSUE THREAD

**Issue by piever** [MithrilJS/mithril.js#2664]
Sorry for not following the issue templates, but I did not find a template for "documentation problems".

It looks like something goes wrong in the rendering of the [Scripts that do not run](https://mithril.js.org/trust.html#scripts-that-do-not-run) section of the `m.trust` API documentation.

This is how it renders for me, both in Chrome and Microsoft Edge:

![mitrhil_docs](https://user-images.githubusercontent.com/6333339/112750328-53608e00-8fc8-11eb-99e8-ac5e2eef9fcc.PNG)

I think the `document.write("</body>")` expression in the markdown file is causing issues with the rendering, but I'm not sure why because it is between backticks.

**Comment by StephanHoyer** [comment]
it's already fixed in #next
