### ISSUE TITLE
Malformed m.request() content-type

### ISSUE THREAD

**Issue by pereriksson** [MithrilJS/mithril.js#2668]
**Mithril version:** 2.0.4
**Browser and OS:** Mac OS X latest Chrome
**Project:**

## Code
```javascript
m.request({
    // Needs to be POST or PUT
    method: "POST",
    url: "https://api.example.com/v1/dummy",
    headers: {
        'Content-Type': 'application/json'
    },
    // Needs to be a body
    body: {}
});
```

## Steps to Reproduce
1. Run the code snippet.
2. Check the content-type of the XHR request in the console (the request that isn't the preflight request).

## Expected Behavior
An XHR request is made with a correct content-type:
`Content-Type: application/json`

## Current Behavior
The content-type header is added twice (once interally, once when requested by the dev) creating a malformed content-type.
`Content-Type: application/json; charset=UTF-8 application/json`

## Context
I need to modify the backend API service so that it accepts malformed content-types.

**Comment by osban** [comment]
Perhaps this is because in `request.js` first this happens:
```js
if (assumeJSON && body != null && !hasHeader(args, /^content-type$/i)) {
  xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8")
}
```
and then:
```js
for (var key in args.headers) {
  if (hasOwn.call(args.headers, key)) {
    xhr.setRequestHeader(key, args.headers[key])
  }
}
```

**Comment by isiahmeadows** [comment]
That sounds like a bug...

That `hasHeader` should be keeping it from overwriting it.

**Comment by pereriksson** [comment]
Is it the regexp `/^content0-type1$/i` that is the issue? With a  0 and 1 my hasHeader returns true and the regexp matches.

For v2.0.0-rc.8
`!hasHeader(args, /^content-type0$/i))`
was changed to:
`!hasHeader(args, /^content0-type1$/i)`

But is `/^content-type0$/i` correct?

**Comment by isiahmeadows** [comment]
That would be a typo.

**Comment by isiahmeadows** [comment]
So an issue with our bundler... 😬

**Comment by pereriksson** [comment]
Is this fixed in commit e9d54b5?

**Comment by barneycarroll** [comment]
It looks like it @pereriksson ... I will run a build later to see.

**Comment by ruizalexandre** [comment]
No more info about this ticket ? ☺️

**Comment by osban** [comment]
@ruizalexandre People are working on things, so hopefully this will be fixed soon.

**Comment by StephanHoyer** [comment]
We will go over all tickets any time soon and hope to get bugfixing up to speed again. ✊

**Comment by StephanHoyer** [comment]
seems to [work](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE4wAjgFd4xABTAAOmgAEm9QHpt6gHIwYAEzjritdQCMY6gAoB5AMoAVdbQn2Aqi7Vb1OMSEtMaI6iogjq4RFH5ashJQYREkxAAOcIi6UtJWEGj4dFjaMNTB2mm0cMTa-PQxcZqEMBjGMBKZ6qoa-loA5ADC9IwMALQuAJ5pMH1hfRhpaVAQ1BjEEPS1cPR9jerse7oGRqbmljbqGNYhE3tWN2HArGqsAJQA3JQgcDCw1Ov0BA8ACsiAATAB2NgcECYHB4QpwAQ0YYiFisAC6VGWaAA1kDULCuGIIEEJNB8PwvglyDxUhkstoJBgAO74ADmpMIsissh+EiEI2IhVoxQAslzyVAAFJObRYSUU-jaNAwAAeNQVZKVyOIU2432o5LSokxrCAA)
