### ISSUE TITLE
Mithril docs not reflecting mithril.js repository

### ISSUE THREAD

**Issue by chronoDave** [MithrilJS/mithril.js#2671]
**Mithril version:**
2.0.4

**Browser and OS:**
Chrome, Windows 10

**Project:**
https://mithril.js.org/testing.html

## Context
Whilst checking out the documentation on [Testing](https://mithril.js.org/testing.html), I noticed the website still says "Add a `"test": "mocha"` to your npm scripts", which has been fixed and merged with #2585. Is there a reason why this isn't reflected on the documentation website?

**Comment by barneycarroll** [comment]
That page has a host of issues we’re tracking in #2665 — #2585 is incomplete on its own terms (the test code sample makes use of the mocha API 😖).
