### ISSUE TITLE
Remove title attribute on Html tag

### ISSUE THREAD

**Issue by ableu** [MithrilJS/mithril.js#2676]
Hello,

I didn't find a way to remove an attribute on a tag after he has been set once. 
In the following example : 
- When the page loads, the title attributes isn't in the DOM. 
- After a click on the link, the title is added
- After a second click, the title is set to 'undefined' and I expect him to be removed from the dom. But it's value is "null" (which appears in the browser tooltip).
https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABO0wwAKuU5IAvJy0BXRAG4AOlEebdAJQgROOszuCOdOurkiADuKDqkVlBgnOTQABQAlL7+AXoGxqaI3joAhPpGJkgOUGk6WoicVlqlNKlljPEA5Pjk6k1EvjqxWSgFmUg6APw69iAAkunq2ZjdRYhjOuFR+IgUUAQ6EvVl6YVZw6MgAMrsEFbw+FPZPUiL4WOn55c6UJ7XOrO3CyCJRDsBRpNTAdXzsCqkFBNADEoOgYHg5DAAGsUJForEEolgOVKtVSqRMPA8LYthIjgBBeCCGqYQQ6Yx3X47AC6ZVSYlGUDEjkcjFYjHOAni+AgYCszAErAARhB8ABPTruTyJXlQPiQRjYSiILQiaWYaWIXgkPBIGJxWAiABsKGtACZxJIQAxmCJWGAYIp+IJhGhxCySIioMjqCg6C7pCJGCZwZQ+NVeGguJxcCgAPTpqLYZEAcw9EEY6ZjnDj8AAAvbWAAGVgAFmLsa0lAF5Cg8m9nHl2BkMDAzewajELLEQA

If I replace { title:hasTitle ? "I have a title" : undefined } by { title:hasTitle ? "I have a title" : '' }, the tooltip disappears but the attribute is still in the DOM (with empty string as a value).

Am I missing something ? Is there a way to remove this attribute ?
Thanks for the help.
Arnaud.

**Comment by cavemansspa** [comment]
yeah, that's odd @ableu .  i was expecting that [using a selector](https://flems.io/#0=N4IgtglgJlA2CmIBcA2ArAOgMwEYA0IAxgPYB2AzsQskVbAIYAO58UIBAZhAucgNqhS9MIiQgMACwAuYWO1qkp8RTRABfPIOGjxAK14ESi5VJoA3egCcABBPrkAKhCkIAvFMsBXeAG4AOqQBFjYASsTEUtau1sAB1tZmEPAA7kjWHJ6khFIQZAAUAJQxcfG29k4u8FHWAIR2js4I-qSl1giRLAjZxDbR9RUI1gD81gDkUBBmfDmVrgCSZWZV9NYzCAC6o9Zp45OjJfGW8FKeli18B6VgeQAGACTAnfDdlmo3eGUNlcPWfiAAyhJiJ5YFBFlU1vA-ttfgCgSCwaQIuDrCtIX8CnhLvFrrszKMPsBVo14Eh+iSfn8FnYlqjiZVoWlMlB4FxSKxrBpsaVyd8Rn9AcDQSj0SAYQL4cKkZEact6QgMViWq1rLj6ASYhIjhwkKMAMQasiEWAQQgAayQGSyOXyBSJRxOZ3S9FgLB8nI0sIAgrAlGd6EprE4FSACpd1q0SmpfqQ1AEAmAMGBgYo8lBiIRPCJFBgAEbEKAATw+YQiYcCpHkJDAjG48EsNFz9Fz8DkBCe2VyFBoaFQABZ1JoQEIRDQMIRyAYFEoVGJ1OsCCbSGbeEgBMPtDRIFItdx5Kc5GJpFJmEgAPRnzKMM0Ac3HxDAZ+3u9gAAEAEwYAAMGD7T+cL5JhApAYPo8hSIWjA6OQhCWBAjCmGo6xqEAA) would be a workaround but getting same the same behavior.  

looks like something specific to the `title` attribute?  experimented with other attrs not named `title` and they will be removed as expected.

**Comment by ableu** [comment]
Hi !
It seems to be the removal of the attribute that doesn't work properly. Calling directly the removeAttribute API from the DOM works : so it's not a limitation of the browsers.
I've tried some attributes and it doesn't seem to be limited to "title". Tried the following : 
KO : name, alt, style, rel, img:src 
OK : class, href, input:type, target, accesskey, charset 
Arnaud.

**Comment by cavemansspa** [comment]
an [alternative approach](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABO0wwAKuU5IAvJy0BXRAG4AOlEebdAJQgROOszuCOdOurkiADuKDqkVlBgnOTQABQAlL7+AXoGxqaI3joAhPpGJkgOUGk6WoicVlqlNKllBZlIOgBkLTqM8QDk+OTqXUS+OrFZKPYgAJLp6tmYw0WI4zoSOuMAyuwQVvD409kjSOOJRPVp+RkLre2dPX0DqyAbWzs6UJ57OnMHiyDHpwEAegBHW6vX6g2A81GjUuAH4HlN9DNPlDDiAdOEovhEBQoARlidSmUdEC0jCsjp4etNttdkj9gsluFqc9dm8vPSUd8joTiSCuph7sB2BVSCgugBie7QMDwchgADWKEi0ViCUSkIqVRqEUw8DwtmWK3GAEF4IIaphBDpjGjEqcALplVJiVZQMSORyMViMLYCeL4CBgKzMASsABGEHwAE9Bu5PPanFA+JBGNhKIgtCJw5hw4heCQ8EgYnFYCIAIzllAATnEkhADGYIlYYBgin4gmEaHEDpIcqgCuoKDoDekIkYJhFlD41V4aC4nFwKCBUWwCoA5i2IIwARPOFP4AABABMrAADKwACy7ydaSg+8hQeTtzjR7AyGBgO-YNRiB1iIA)

that replaces the element on true / false toggle.

**Comment by isiahmeadows** [comment]
So in other words, we have *yet another thing* to if/else in the attributes... 😞

This time, it's not an IE hack, but working around the *spec*.

**Comment by JAForbes** [comment]
I Just came across this as well, [simple repro](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE5MAJjAkAKabWoBXHA3wAjWtICeFAARZ5Ack0rixeicPADxCMViIDJurSgmD7VwBV4xCYAlEEAOmjiUmiyCkqq6sRaOvpGpuaW1rb2js4GaCpQUN6GJv5wgSGUIHAwsNQO9Ag8AIyIAGzNbBwgmDh4+NRwAjT0jMw8bAC6VFAQaADWTag9XGKOhBLQVSoS5DwkxAAOcIgA9KcqaIfzAOYDtFinWOubUAACAEz4AAz4ACxPF7QfDPND4fhVYi6Q7carUTaHUSsSasIA)

I just added a conditional:

```patch
function removeAttr(vnode, key, old, ns) {
	if (key === 'key' || key === 'is' || old == null || isLifecycleMethod(key))
		return
	if (key[0] === 'o' && key[1] === 'n') updateEvent(vnode, key, undefined)
	else if (key === 'style') updateStyle(vnode, old, null)
	else if (
		hasPropertyKey(vnode, key, ns)
		&& key !== 'className'
+		&& !( key === 'title' ) // creates "null" as title
		&& !(
			key === 'value'
			&& (vnode.tag === 'option'
				|| vnode.tag === 'select'
					&& vnode.dom.selectedIndex === -1
					&& vnode.dom === activeElement())
		)
		&& !(vnode.tag === 'input' && key === 'type')
	) {
		vnode.dom[key] = null
	} else {
		let nsLastIndex = key.indexOf(':')
		if (nsLastIndex !== -1) key = key.slice(nsLastIndex + 1)
		if (old !== false)
			vnode.dom.removeAttribute(key === 'className' ? 'class' : key)
	}
}
```

Should I create a PR?
