### ISSUE TITLE
Remove `m.jsonp`

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#2682]
**Mithril version:**

**Platform and OS:**

**Project:**

**Is this something you're interested in implementing yourself?** Yes

### Description

Remove `m.jsonp`

### Why

It's legacy crud to support an API style that's been almost entirely replaced with CORS, and I've not seen a JSON-P endpoint for a public API in years. It only really continued to exist as long as it did because IE 9 didn't support CORS, leaving JSONP as the only realistic way to request data there from other origins. But as even IE 10 supports it now and we're planning on sunsetting IE support entirely relatively soon, it adds nothing to keep it in Mithril.

### Possible Implementation

1. Remove `m.jsonp`
2. Inline all the abstractions into `m.request` as appropriate

### Open Questions

Do we want to continue to support this legacy API? (I strongly say we shouldn't, and I anticipate most of us would agree here.)

**Comment by isiahmeadows** [comment]
@panoply I'll let that be a separate issue: https://github.com/MithrilJS/mithril.js/issues/2683

Would rather not conflate the two, even though it's likely similarly uncontroversial.

**Comment by sonkwl** [comment]
We never use jsonp in our projects.
For us, either m.jsonp or m.request is a request, and we need to request resources. Why not just use m. request.

**Comment by StephanHoyer** [comment]
If anyone still needs it, there a ton of [packages](https://www.npmjs.com/package/jsonp) out there.
