### ISSUE TITLE
 How to verify that the browser supports mithriljs?

### ISSUE THREAD

**Issue by sonkwl** [MithrilJS/mithril.js#2685]
**Browser and OS:**

## Code
```javascript
var init={}
//浏览器兼容性
init.CheckBrower=function(){
    if(typeof m=="undefined" || m==null){
        document.write("brower can not supports your brower");
        return false;
    }
    return true;
}
init.loading=function(callback){
    //浏览器验证
    if(!init.CheckBrower()){
        return;
    }
    //回调函数
    callback();
}
```
IE can not use implement “CheckBrower()”

 How to verify that the browser supports mithriljs?

**Comment by isiahmeadows** [comment]
Mithril supports IE11 still.

Could you explain in a little more detail what your issue is?

**Comment by sonkwl** [comment]
Add browser verification, so as not to open a blank page.
I think we should solve this kind of unfriendly interaction.Don't you think so?

**Comment by isiahmeadows** [comment]
@sonkwl We're not embedding browser support into Mithril. There's better tools for that, like [Modernizr](https://modernizr.com/) and [Bowser](https://github.com/lancedikson/bowser), and in general, browser detection is an anti-pattern anyways. (Also, using IE is generally frowned upon anyways for security reasons if nothing else.)
