### ISSUE TITLE
schedule is not a function

### ISSUE THREAD

**Issue by gilbert** [MithrilJS/mithril.js#2686]
This error gets thrown when calling `m.redraw()`:

```
TypeError: schedule is not a function
    at Function.redraw (node_modules/mithril/api/mount-redraw.js:23:4)
    at ...
    at renderComponent (node_modules/mithril-node-render/index.js:147:27)
```

I was able to get around it by putting `m.redraw = () => {}` in a particular spot. Would it be possible for mithril-node-render to do this itself? Thanks.

**Comment by gilbert** [comment]
The reason I posted this in `mithril-node-render` is because I'm trying to use mithril with `mithril-node-render` for SSR and didn't understand:

- `mithril-node-render` doesn't touch mithril at all
- The ["Make Mithril happy" docs](https://github.com/MithrilJS/mithril-node-render#usage) isn't enough to solve this problem

But now that I had the time to sit down and [study](https://github.com/MithrilJS/mithril.js/blob/v2.0.4/api/mount-redraw.js#L23) the [internals](https://github.com/MithrilJS/mithril.js/blob/773e570b86618be5f9de5b254c8c42e5beabf9d5/mount-redraw.js), I now see that my solution of calling `m.redraw = () => {}` is actually the right solution, as I'm not trying to *emulate* that behavior, but simply ignore calls to it.

I suggest moving this back to `mithril-node-render`, as doing this would not be necessary in normal usage of mithril.

**Comment by isiahmeadows** [comment]
In normal usage, yes, but it still deals with Mithril core APIs as `m.redraw` is part of Mithril, not `mithril-node-render`. That's why I moved it here - it was only tangentially related to `mithril-node-render`.
