### ISSUE TITLE
EventDict can break with uBlockOrigin

### ISSUE THREAD

**Issue by electronicwhisper** [MithrilJS/mithril.js#2687]
**Mithril version:** 2.0.4

**Browser and OS:** Chrome 90.0.4430.212 (Official Build) (x86_64) on Mac

**Project:**

## Code

[Test case](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9GIAEAFUIQ4k+YrS8Y1RgBNJAIwCekgK4AhKLWoBrAPIAnCAHMIaADpoAFGANp1Eeq4CUksAuTsQAbhjWktSSALxR9HC0sBSSULFR+KZ2ANzBYRGSAF7pcDBQYPgAoqEi0hF2MMT4AA7WtMTtus0w+BgaGtUiADLyjGgw1rnOxKXlVTUMddYNTa3tnd29-YMMI3BjE+keXsQ+bhgp2gFB0yFQ+NQYUFCu1CkA5H0DC8R7B9auJwgACkcCBKVBfneKQukgAysRbGg7K4rn4piEQtZGgZrGgir1ms0oLpXMQ5HAYcsDDgGHB0XlWFNWH5-BjnGgJDIKYoFBhJFhHBAsE9JIx9pIAO4QcmSDD4mA-SSEeUaWDWFxCCXSeDEdI3SSSUIQGCS-yBFyGw3Y4i4-FYQEgDQQULgwL0ahQCAWRCSY7eeiSc0Gq2GrVJHpZR2SjAKT3e8wwDRAhn4q2sdiSIFYfTkxx2FNTQ2sFxMlxYfBYWieYiuDRmGkifDaWgaXQpHX7dGUECzNSnBJ4ACMQ8QABYAOxsDggTA4PAPOACGj0MaiHhsAC6VC9aHMCBQnHnPEF5Ns5CouPIPBIxGacEQEk8zXMdgetCwYlPhHPAAEAEz4AADPgY5fjKP7QJWjj4PwPbEF03C9tQtjNKIrCbqwQA)

## Expected Behavior

The above test case to show "my thing" and when you click it, it shows "was clicked" in the console.

## Current Behavior

console shows the error "Cannot convert object to primitive value"

## Steps to Reproduce

1. Go to the test case, see the console output.

## Context

Recently my site https://cuttle.xyz which uses mithril fell under a rule in uBlockOrigin (ad blocker) that injected a script which changed `addEventListener`. Those scripts are [around here](https://github.com/uBlockOrigin/uAssets/blob/1b8ac96f9842d21c995adcbf1f6dd06e49964b10/filters/resources.txt#L1871) and [here](https://github.com/uBlockOrigin/uAssets/blob/1b8ac96f9842d21c995adcbf1f6dd06e49964b10/filters/resources.txt#L1883).

I tracked it down to `EventDict` inheriting from `Object.create(null)`. This means you can't stringify `EventDict` using `String(x)` or `x.toString()`.

Is there a reason you need `EventDict` to inherit from `Object.create(null)`?

I will also file an issue with uBlockOrigin to see what they can do on their end.

**Comment by electronicwhisper** [comment]
uBlockOrigin will fix this on their end: https://github.com/uBlockOrigin/uAssets/issues/9123#issuecomment-848689385

**Comment by isiahmeadows** [comment]
Yeah, I have no interest in fixing a bug just to make a browser extension that mucks with the DOM work.

> They have this object inherit from `Object.create(null)` (I'm not sure why) which is exactly the `x` that would break `String(x)` or `x.toString()`.

Here's why: we don't want to risk accidentally trigger any getters or setters on `Object.prototype`, and if a script decides to freeze `Object.prototype`, we don't want to risk getting in trouble with that, either. And `Object.create(null)` is a lot easier than the alternatives.
