### ISSUE TITLE
Expose compileSelector for external reuse.

### ISSUE THREAD

**Issue by aleph1** [MithrilJS/mithril.js#2699]
I am building an application using Mithril that has complex SVG elements that have to be dynamically updated frequently. I am opting out of Mithril’s auto redraw system for this one component as the SVG DOM updates much faster with direct manipulation via JS. However, it would be useful to use compileSelector when creating these elements outside of Mithril so I can shorthand their creation, versus having to duplicate the code.

For this to happen I think the only really change to mithril would exposing the function on the module that is exported. However, it might be worth adding an option to the compileSelector function as to whether the selector should be cached, which can be useful in some cases — in my case selectors can change fast and frequently and I wouldn’t want to clog the selector cache with objects that don’t need to be kept in memory. This implementation would only require three small changes, and they should gzip without adding just a few bytes:

1. `function compileSelector(selector) {` becomes `function compileSelector(selector, cache) {`
2. the return from compile selector becomes `return cache ? selectorCache[selector] = {tag: tag, attrs: attrs} : {tag: tag, attrs: attrs}`
3. the only internal call to compileSelector in mithril becomes `compileSelector(selector, true)`

I am happy to create a pull request if this is an acceptable feature.

**Comment by isiahmeadows** [comment]
@aleph1 Are you using static strings (as is recommended practice) for tag names and keeping all the dynamicism within the dynamic side? If so, there really isn't much this would offer you, as retrieving from a JS object is really fast compared to everything else.

**Comment by aleph1** [comment]
Yes, static strings. It is more about being able to convert a string to a compiled selector for use outside of mithril. I am building a fairly robust polygon/physics editor for a game pipeline, and have opted out of the redraw system for the component that manages the drawing area — this has allowed me to heavily optimize how updates occur, which is necessary given the nature of the drawing controls and underlying logic. However, it would be **very** useful to be able to convert selectors using the same logic that mithril uses internally. I can always just duplicate the function externally, but wanted to inquire about exposing it.

**Comment by isiahmeadows** [comment]
I could see it, especially with build tooling. Go ahead and file a pull request to expose the utility - shouldn't be that complicated. I just request one thing: move the cache setting out of `compileSelector` when you do, so it can be used for one-time deals without risking memory leaks (I want to leave that trade-off to the end user).

**Comment by aleph1** [comment]
Done #2700.

I assumed you wanted the cache setting moved out of the compileSelector function, but the selector cache kept for internal calls to that same method.

**Comment by aleph1** [comment]
I started into the tests for the compileSelector method, but noticed a couple of small issues. At present the `hyperscript` function currently does the error handling for invalid selectors, which means a direct call to `compileSelector` with an invalid selector doesn't trigger an error, and can return weird values, for example `m.compileSelector(null); // returns { tag: 'null', attrs: {} }`.

I am wondering whether it makes more sense to keep the existing compileSelector function as internal only, and expose a wrapper function that simply does an error check and calls the internal compileSelector. For example:

```
function exposedCompileSelector(selector) {
  if (selector == null || typeof selector !== "string") {
    throw Error("The selector must be a string.");
  }
  return internalCompileSelector(selector);
}
```
