### ISSUE TITLE
Is there a way to use debounce for callback?

### ISSUE THREAD

**Issue by kalxd** [MithrilJS/mithril.js#2714]
**Mithril version:** 2.0.4

**Browser and OS:** Mozilla Firefox

**Project:**

## Code

```javascript
const m = require("mithril");

const debounce = (ms, f) => {
	let lastValue = null;
	let timer = null;

	const callback = () => f(lastValue);

	return event => {
		console.log(timer);  // it said there is no timer all the time
		lastValue = event;
		if (!timer) {
			timer = setTimeout(callback, ms);
		}
	};
}

const App = () => {
	let state = 0;

	const inc = () => ++state;

	return {
		view: () => m("main", [
			m("button", { onclick: inc }, "inc"),
			m("button", { onclick: debounce(1000, inc)}, "inc"),
			m("label", state)
		])
	};
};

m.mount(document.body, App);
```

here is the sample that build a `debounce` for `onclick`, when I clicked second button several times, there is always `null` print out on the console window.
It seems the `debounce` called many times and created indendepnt timers. 

So is there a way to implement the `debounce` method for all callbacks.

thanks a lot.

**Comment by kalxd** [comment]
> Maybe something like this?
> 
> ```js
> const debounce = (ms, f) => {
>   let timer = null;
> 
>   return () => {
>     const later = () => {
>       timer = null;
>       f.call();
>     };
>     clearTimeout(timer);
>     timer = setTimeout(later, ms);
>   };
> };
> ```

Thanks for your reply, but it doesn't work correctly. when clicking the debounced button many times in 1 second, it's nothing happend ever the timer is time out, and the `state` is the value that the times you clicked actually.

I think the `debounce` called again when mitril starts to redraw, so it is hard to clear old timer.

**Comment by osban** [comment]
@kalxd Ah sorry, forgot the `m.redraw()`:

```js
const debounce = (ms, f) => {
  let timer = null;

  return () => {
    const later = () => {
      timer = null;
      f.call();
      m.redraw()
    };
    clearTimeout(timer);
    timer = setTimeout(later, ms);
  };
};
```

**Comment by kalxd** [comment]
> 
thanks again, but it didn't work either.
It seems `debounce` does not debounce the `f`: `m.redraw` redraws the view, the callback for `onclick`  may be "recreated", so the `debounce` called many times. `debounce` would not know whither had called(or clicked) or not.
If try to print `timer` out, its value always be `null`.

**Comment by osban** [comment]
I think I didn't understand what actually should happen. I thought all clicks should go through after the timeout, but I guess it should be that all clicks within the timeout time should become 1 click, right? If that's the case, then maybe something like this would do the trick?

```js
let timer = null;

const debounce = (ms, f) => () => {
  const later = () => {
    f.call();
    m.redraw();
    clearTimeout(timer);
    timer = null;
  };
  if (!timer) {
    timer = setTimeout(later, ms);
  }
};
```
Here's a [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAATEIOAE4SAvBLQBXKFADcAHTQ6hcSQBMYAI1oq01GIokAKLHAoSwASkUA+O24WfgOiRL6klAYjPJKtt6+-gHO+NQY6pHaaLESWPiyMIayGADuyTEB1LAYsgAqMjDmxLbSci4pafUw4cpqmjGsTRIQYHYAhC2ybn6pscM2cDDElTg1tiFhTg6NXTrdOnr0BhIAggAOBzaRHhJjWsTiEgah1koADClbxEG9lidREgDU37eMz10xCyxBUslSF2IlwAbhAYHlEF4zlhbFoQFgMBBdJQJMgXpdLii0SYVMRiPQ0U5gBJ6CUINQANaIrHUCTsCRollolwUfFQ0iokAkskUnHU2lQelMiTGMwWKy2ACMDxVThZLnZnMs3N5QIJArRIRMMCglJuxDuLj5AF0rUDNmgHToMlhzAxbIZaNQVDgGPgzIYAJ5OQ4HRqUEDTWDUaQ7PCKxAPNgcECYHB4eJwAQ0eiMZg8NjWqiStAMhAoTjpnhYCDEQiyaARsHkHgkYgHOCIAD0XYsBwZAHN4rQsF2a3WG1AAAIAJnwD3wABYx7X69B8DW0Ph+BHiIGDtxI9QGwdRKxrawgA).

**Comment by StephanHoyer** [comment]
[this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmiFxiAAgAmMAEa0ArpJgyAvDIAUWOBRlgAlFoB8M4BLHFYsqBmkA1DFBUbtaFVCgBua7YwssQQOABOWjJePv5oAVKy1K5QihjUANaROqaaFlZoMoVGOg7Oru7GEkUyWPhhMHJhGADu2VUyrLEB9cQqYQUwAG4i5pYBNqXELm4eMkMisdXUsBhhACqhMKrEOiHhlXHENnswEdpwQRs42zpJPqkZhvrGi0XzDHUNTc2RYK4XAU6ElY1kk9GkMgAggAHaFZHJ5AJ2GTSDCMSIABi6hwSMggknhowA1ETUYxsYVcQplGpqA0AJIE7TU1TqHQARgxXMM+OoBxsPT6BXyNhsgwgMGaiF0CJqOjEICwGHxCsMyHGR1I8pAihUxGI9FVlhk9GWEAy0t5HUMCt5CuMFA1Niw2t1+sNlGNpqg5vS0pZtIZknYMltkntjsOoq1CocihgUCNZJg-M1AF1U0C0FmJLUsKydnJaNQVDgPso5ABPQww6EvSggC6waghcF4ABMAFZEF22BwQJgcHh8NQ4AIaPRGMweGw01QfWh0ggUJwhzwsBBiIQwtAG31yDwSMRoXBEAB6M9qaHpADmI9oWDPG63O6gAAF2-gMfgACxPzfbtA+Abmg+D8A2xCVtC3CNtQO7QqIrBpqwQA)?

**Comment by kalxd** [comment]
> maybe [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmiFxiAAgAmMAEa0ArpJgyAvDIAUWOBRlgAlFoB8M4BLHFYsqBmkA1DFBUbtaFVCgBua7YwssQQOABOWjJePv5oAVKy1K5QihjUANaROqaaFlZoMoVGOg7Oru7GEkUyWPhhMHJhGADu2VUyrLEB9cQqYQUwAG4i5pYBNqXELm4eMkMisdXUsBhhACqhMKrEOiHhlXHENnswEdpwQRs42zpJPqkZhvrGi0XzDHUNTc2RYK4XAU6ElY1kk9GkMgAggAHaFZHJ5AJ2GTSDCMSIABi6hwSMggknhowA1ETUYxsYVcQplGpqA0AJIE7TU1TqHQARgxXMM+OoBxsPT6BXyNhsgwgMGaiF0CJqOjEICwGHxCsMyHGR1I8pAihUxGI9FVlhk9GWEAy0t5HUMCt5CuMFA1Niw2t1+sNlGNpqg5vS0pZtIZknYMltkntjsOoq1CocihgUCNZJg-M1AF1U0C0FmJLUsKydnJaNQVDgPso5ABPQww6EvSggC6waghcF4ABMAFZEF22BwQJgcHh8NQ4AIaPRGMweGw01QfWh0ggUJwhzwsBBiIQwtAG31yDwSMRoXBEAB6M9qaHpADmI9oWDPG63O6gAAF2-gMfgACxPzfbtA+Abmg+D8A2xCVtC3CNtQO7QqIrBpqwQA)?
> 
> 3 Problems with your solution
> 
>     * you recreated a debounced version of you handler in every redraw, but that's not how debounce can work
> 
>     * you have to set `event.redraw` to false in the debounced case, to avoid a redraw, when you run into the timer
> 
>     * you have to manually trigger a redraw when the timer runs up
> 
> 
> Hope this helps

That's it !
Thank you very much!
