### ISSUE TITLE
`mithril.route.prefix` error

### ISSUE THREAD

**Issue by AlphaBeta1906** [MithrilJS/mithril.js#2716]
So i have a html file with simple routes,but when i add `mithril.route.prefix` ,i got a lot of error like this : 
![Screenshot_20220105_202723](https://user-images.githubusercontent.com/70358251/148226738-709ac924-749d-454f-85a5-41d227a6ed00.png)
so what happen?,did i wrong when use `mithril.route.prefix` ?

**Browser and OS:Firefox  95.0.1  on ubuntu 20.04**

## Code

code inside my script tag : 
```javascript
		m.route.prefix = ""
		var i = 0;
		var Header = {
			view: function(){
				return m("header",
						m(m.route.Link,{href:"/",style:"padding-right:15px"},"Home"),
						m(m.route.Link,{href:"/others",style:"padding-right:15px"},"Halaman lainnya"),
						m(m.route.Link,{href:"/buttontambah",style:"padding-right:15px"},"button tambah")
					)
			}
		}
		var ButtonTambah = {
			view: function(){
						   return m("",
						   m(Header),
						   m("button",{onclick:function(){i++}},"klik ini"),
						   m("span","klik ke-"+i))
				
			}
		}
		var HalamanLain = {
			view: function(){
				return m("",
						m(Header),
						m("p","Halaman yang lain")
						)
			}
		}
		var Home = {
		      view: function(){
		                   	return m("",
		                   	m(Header),
		                    m("h1","hello"),
		                    m("p","ini adalah home"),
		               )
		      }
		}
		
		m.route(document.body,"/",{
			"/":Home,
			"/others":HalamanLain,
			"/buttontambah":ButtonTambah
		})
```

## Steps to Reproduce
I just add `m.route.prefix=""` inside script tag

**Comment by cavemansspa** [comment]
hello @AlphaBeta1906 , code looks fine. i believe this is stemming from using `file://`.

your code [copy / pasted](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxGNWAJwgBXQa2ybEFAB4ACALxmAOiFvWo1zk4BumTWfKWzABgDcDk6u7mYAEoiY+IgeVsCBzgku5IgA7ihmpDpQYJzk0AAUAJRxjglBnEacOppQZoz5tuwRUZq2RPHlndz5Gtp6iKwAMuRQANaS7EakKLYA9G0wnACeSDMg2JH4IwDmALSa5NtcKACMAKzYJrYStqEQzLaF7aVd5fW9uvrDYxNTa7MQThNTQwBbLVa2Db4LZQPYHI6cU4XK7idogUKYLCMTC1LAjKBLTCPZ6vMrdD79IYjcbASbGf4AIz0nGgnCYDMw7DBK0QayhMLhh2O50u1zRTM4LNqbMYHK5IEKHTJTkVLwSYiVGrVbg8ACFmdAACrszneEpdJKpdKZbK5ArFJWkszOyrVWr1ezER3KzjOur5cKRaJPb1dP0ekASqVtYDQMDwchgUYoG05PJQIrAcgAamzYhuIFGCdGnig5GJobJ4YaIBgG0cXsLxbMo0Qu1s2fIhVVpO9WvK-cSIQxWJxg0wIzN3staQyWTT9vNPtdNX9npJPreAeawY3ve6kLat0xTBxZkJsLMeIbPc3CVvA81Sp1YXuiCnar9fpn1vndozDqfl+wEgX6Tgru6NZHkBoGwc6Tj1IGLQhjBcGwRG7AnEeIBNPA8AQBWqFoSBEbYNhIxeJEJ7sGY7BvoR5TEV+D6+sBg5OOxzhqhSgj5PgEBgDozACKwDIQPgSxovMxBLp0IDSSgdzMHuZTyYCwKgqgI6nlA44jCpQTyVGrImvKKD6pKRqmZqhR8HgSALrAIgAMwoAATD4qJSMwIisGAMCKPwgjCGg4gALokAmYzUCgdAgAwPloIw5BAgcvAkNUvBoFwnC4CgsyzFk2CjNsfn3LMyWpZQAACbmsD4rAACwVSlkyUKwyVQPIgXLNgMgwGABzYGoYhhWIQA) to flems sandbox works as expected.

**Comment by AlphaBeta1906** [comment]
@cavemansspa ,yeah i also use mithril  with development server and the error is not appear,the error happen when i just use a file.So `mithril.route.prefix` can't be used from file right? Ok i understand
