### ISSUE TITLE
Broken README Intro

### ISSUE THREAD

**Issue by tbreuss** [MithrilJS/mithril.js#2749]
The Intro of the README.md of the `next` branch is kind of broken...

It looks like this now:

<img width="1224" alt="mithriljs-readme-wrong" src="https://user-images.githubusercontent.com/1334161/155188305-b329f375-6d76-4732-b5a2-37499d81635f.png">

And should look like this (or similar):

<img width="1227" alt="mithriljs-readme-fixed" src="https://user-images.githubusercontent.com/1334161/155188404-df917aaf-4ea5-4fe3-84a2-9992f3853762.png">

Meaning:

- Mithril.js with a capital M
- Icon shields in one row aligned left

I have a branch ready for a pull request.

**Comment by panoply** [comment]
GFM can be painful. Align badges using HTML:


```html
<a href="https://www.npmjs.com/package/mithril" align="left">
  <img src="https://img.shields.io/npm/v/mithril.svg" alt="npm Version" />
</a>&nbsp;
<a href="/LICENSE"  align="left">
  <img src="https://img.shields.io/npm/l/mithril.svg" alt="npm License" />
</a>&nbsp;
<a href="https://www.npmjs.com/package/mithril"  align="left">
  <img src="https://img.shields.io/npm/dm/mithril.svg" alt="npm Downloads">
</a>&nbsp;
<a href="https://www.npmjs.com/package/mithril"  align="left">
  <img src="https://img.shields.io/travis/MithrilJS/mithril.js/next.svg?colorB=brightgreen" alt="Build Status">
</a>&nbsp;
<a href="https://opencollective.com/mithriljs"  align="left">
  <img src="https://img.shields.io/opencollective/all/mithriljs.svg?colorB=brightgreen" alt="Donate at OpenCollective">
</a>&nbsp;
<a href="https://gitter.im/mithriljs/mithril.js"  align="left">
  <img src="https://img.shields.io/gitter/room/mithriljs/mithril.js.svg?logo=gitter" alt="Gitter" />
</a>
```

<a href="https://www.npmjs.com/package/mithril" align="left">
  <img src="https://img.shields.io/npm/v/mithril.svg" alt="npm Version" />
</a>&nbsp;
<a href="/LICENSE"  align="left">
  <img src="https://img.shields.io/npm/l/mithril.svg" alt="npm License" />
</a>&nbsp;
<a href="https://www.npmjs.com/package/mithril"  align="left">
  <img src="https://img.shields.io/npm/dm/mithril.svg" alt="npm Downloads">
</a>&nbsp;
<a href="https://www.npmjs.com/package/mithril"  align="left">
  <img src="https://img.shields.io/travis/MithrilJS/mithril.js/next.svg?colorB=brightgreen" alt="Build Status">
</a>&nbsp;
<a href="https://opencollective.com/mithriljs"  align="left">
  <img src="https://img.shields.io/opencollective/all/mithriljs.svg?colorB=brightgreen" alt="Donate at OpenCollective">
</a>&nbsp;
<a href="https://gitter.im/mithriljs/mithril.js"  align="left">
  <img src="https://img.shields.io/gitter/room/mithriljs/mithril.js.svg?logo=gitter" alt="Gitter" />
</a>

**Comment by tbreuss** [comment]
It is in fact mixed at the moment: some with GFM, others with HTML. 

I took GFM, but will take yours now.

**Comment by tbreuss** [comment]
@StephanHoyer I submitted a proposal as PR.

**Comment by panoply** [comment]
@tbreuss  Though there is not an official naming variant as per https://github.com/MithrilJS/mithril.js/discussions/2709#discussioncomment-1509468 and though this is more so personal preference, the lowercase `mithril.js` variant feels a little more recognizable  opposed to the upcase naming variant (`Mithril.js`).

**Comment by tbreuss** [comment]
@panoply This disussion is too late. I was simply following the rules of another huge PR, that was merged few days ago (cant find it on the mobile right now).

**Comment by panoply** [comment]
No probs.

**Comment by StephanHoyer** [comment]
fixed with https://github.com/MithrilJS/mithril.js/pull/2750
