### ISSUE TITLE
m.route.param() omits trailing slash on three-dots pattern

### ISSUE THREAD

**Issue by FeroxTL** [MithrilJS/mithril.js#2763]
In my project I'm trying to fetch some dynamic path data, so I've decided to store path info as an url parameter. While doing this I've noticed, that `m.route.param(key)` returns value without trailing slash (even if it was provided in the url). 

That is the example:

```
m.route(document.body, "/list/static/index.css", {
  "/list/:path...": {
    view: function(vnode) {
      console.log("route.get():", m.route.get());
      console.log("m.route.param():", m.route.param());
    }
  },
});
```

So if you navigate to `/#!/list/static/index.css` the output would be correct:
```
route.get(): /list/static/index.css
m.route.param(): Object { path: "static/index.css" }
```
But if you navigate to some directory like `/#!/list/static/` the trailing slash in the output would be truncated: 
```
route.get(): /list/static/
m.route.param(): Object { path: "static" }
```

I expect `m.route.param("path")` should return `"static/"` -- one with trailing slash

**Mithril.js version: mithril@2.0.4**

**Browser and OS:**
Same result in latest chrome (v100) and firefox (v91.8)

## Context
I've played around and come to some workarounds:
1. Write custom router and make regex to parse path argument
2. Move some arguments to url query params, but it looks ugly

**Comment by StephanHoyer** [comment]
Can confirm this with a test. Thanks for reporting.

**Comment by StephanHoyer** [comment]
seems like [this line](https://github.com/MithrilJS/mithril.js/blob/next/pathname/parse.js#L16) causes it.

Removing it solves the issue and only results in [one failing test](https://github.com/MithrilJS/mithril.js/blob/next/pathname/tests/test-parsePathname.js#L112-L118) which can be solved easily?

What do you think @dead-claudia?

**Comment by dead-claudia** [comment]
@StephanHoyer Let's hold the fix for v3. The behavior's well-defined as-is: the path has all unnecessary slashes removed, and trailing slashes are considered redundant. Developers may already be relying on the lack of a trailing slash currently, so we should continue to honor it.

We should call this out in the docs if it isn't already.
