### ISSUE TITLE
m.route.Link doesn't proxy event handler prevention

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2767]
`m.route.Link` documentation misleadingly states that 

> [You can also prevent navigation by, in an onclick handler, invoking ev.preventDefault() or returning false. This is the same way you block other events, so it's pretty natural.](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/docs/route.md?plain=1#L174)

Neither of those criteria will actually prevent the default behaviour of a `Link` as they do with a simple `a`. It's a shame because this is IMO the clearest sentence in this APIs documentation, and it's false. [I wrote a little matrix sandbox to try and work out how event handling logic intersected with `Link` behaviour here, it may be useful for anyone else trying to reconcile expectations](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvWGgAgCcYaBXVtAfTAxQ4MEswA6aZlOYAHdgDd6NACIwBnKDVETpzKBjg0ASpU50AJhIlU0h5tXJQI5ANbMAvMxgeAfM2A6zBBgABTsXDz8gsL45pRY+OQAFjCuMOYAlIFS4dySAkIwVpJBoXIwirSq6pqx8YkpaZnZXvjllSpqGBo0IVloAL7FNnY0rBAA5hMwrHAezH2+zMiBWCEJrKZ0+AAyEGguogElUnQAHjQAwtR0tIjMAAYbWzC7+y5iEg8kLUnsYMx7gByAD0QOYAGpmMoMNs0JQAO59H4nexoRzOQ6BAYZFGrEJAjBAo4tc5XG5Ke4PAAK+n2zAAPBgfJ80N9fv9AcxQeCoTC4YjkS0HE5XCipDi8SU1kDzBB5MT-KSYBdrrRKY9aRh6Qy5fIWV9xdIRZijZKJABdYrPMwwEJxcicHC0fAAI0o5gAnqIeZDobDXvCkbilSVQYgZLCkvgY0D7sddNQsLDkn0E7o9AZjC9zPN+YHBf1dAMjVIWuw0OYZvdFu4-C0pDL3V7kIZPbB3GAbogAIz4ACsMCwIIATAPmFhqJQ4JHyDAANwIpIQOgAWhnGDnEfYFuJDakQJ2WbYOeYsOkiv0hhMttzUKBrL3qOk++5R7sFar7Fz58V+fwQaLPej6lror5NqwQK4q+4jPtIMr6K6MBQE+GYZrkkQFMI8wyvsMhmMgNCejIMDuMkqQuO6Zy7tBcG6OCGH5NERQSA+dHMLRaFluxCEYEhKGgWh7RKNU3SaDhBJ4QRREkWRjSUZQ1FQYJGbgsJVRdD0j4wZxaHgQSrqQbpek8QSrZER2cozvonqIBM4zmPO9kQOYq50FgMj6GuVBQE6ti9mArDMD2gW7ipYHsY2BJ6qhXG6E2ipAgAsiufzQKu7qcJWj7GXFsF5dIYyTNMsxCpFHHhS+5UyjFlXxQZiVJRgaCcIIUCehlpjZaxuVxTBiaKKwDl2r1XFFVMMxwGVBU5PANCUOw015aNUijbpQyDP01jUHYvBYDhxRgFl5A0BA1D2INw1pqs8wAPKuoQqQ0PgBhwJMaAhC0IQ0BgEyiLCYxwKIMb4OwhgZEs6a6ME33ETAlAAgDsweO4nhApQD1PeCABk2PMAAhEjcD4PIEAwAiGRQxmIwsFJLCeMAINExtfXsUT8xU2hDjsAGITyJT-XSPdj0nS9cBvRMH3yHUWCiHTRZ5SzXFK8W+77oxzB7d9v3-TQgPAzGYM0ArEpGi0suBP0G0SEd6KnedRsLSN6b7Z4e0SAMIBkMIsAnWdth4P2iAjj2JAABzBwAzCAAwWmQTgHAgKDoNguCICAWCpeMUBeyA3A5+nSR6zIcCICCIJZTILgTIk8QgpnNBpVAAACY4AAz4AALPXWfQPgmdoEQpAgDJacgHA5DjDINAxxaAxAA).

It took me reading the [source](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/api/router.js#L205-L273) & returning to read the docs a few times over to realise they're trying to explain the behaviour of a special-cased magic `disabled` attribute, which is the only way of preventing an `Link` from resolving. On that front, they're extremely unclear. Critically, the published docs have a typo stating that [the `disabled` attribute is forwarded to the `m.route.set` API](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/docs/route.md?plain=1#L212).

**Comment by barneycarroll** [comment]
As a priority, the docs need fixing to remove the misleading line about event handlers & fix the API signature table's description of `disabled`. That can close this bug IMO.

**Comment by pygy** [comment]
The router has been completely rewritten since I left, and I'll have to wrap my head around the new code first if we decide something needs fixing

**Comment by StephanHoyer** [comment]
Do you think it's a release blocker? I was planning to release this weekend 😉

Can anyone fix the docs for now so we can do bugfix release later on?

**Comment by pygy** [comment]
@barneycarroll can you do it? I've yet to wrap my head around the issue, and I have the kids this weekend. I may have a look at it this evening otherwise.
