### ISSUE TITLE
The github PR template is out of date

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2783]
https://github.com/MithrilJS/mithril.js/blob/next/.github/PULL_REQUEST_TEMPLATE.md still instructs users to update the changelog, but pr-release is in charge now.

I'd remove it, but wanted to make sure that we don't need some PR formatting advice to replace it, ensuring a nice looking change log

**Mithril.js version:**

**Browser and OS:**

**Project:**

## Code

```javascript
// Code
```

## Steps to Reproduce

1.
2.
3.
4.

**Comment by JAForbes** [comment]
pr-release tries very hard to not require special formatting, so the contributor can do whatever they like in the feature PR description.  So definitely proceed in removing it.

It will try to extract the first sentence or so of content, ignoring headers, comments and compressing lists into sentences.

**Comment by pygy** [comment]
We could perhaps use the first comment in the template to let users know that what part of the PR text will become the change log item...

**Comment by dead-claudia** [comment]
Forgot to close this when I redid the PR and issue templates, since I fixed this as part of that.
