### ISSUE TITLE
Add an action to ensure PRs have the labels required for pr-release to classify changes

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2787]
https://github.com/jesusvasquez333/verify-pr-label-action seems to do the job.

What do you folks think ?

**Comment by JAForbes** [comment]
Yeah this was raised in the initial PR https://github.com/JAForbes/pr-release/issues/304.

I think it can be a feature of pr-release to fail the pr.yml job if not all merged branches have a semver label.  I would have it off by default though.

**Comment by pygy** [comment]
It would be most useful. I may give it a crack it you want.

What's your philosophy for the pr-release defaults?

In this case, as for the "minimize semver" scenario, I would have picked the other personally.

**Comment by pygy** [comment]
Thanks for the insight. I agree that SemVer diff as a changelog proxy can be useful (even for libs), but the current convention is to have it dense, hence my suggestion.

Let's close this, I'll open a PR on pr-release. Point taken for exit points.
