### ISSUE TITLE
Branch naming scheme

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2788]
As previously discussed in Zulip (and as described by @JAForbes [here](https://github.com/JAForbes/pr-release/blob/next/lib/notes.md)), we should create `next` and `release` branches for v1 and v2 releases once v3 is out.

I suggest we go for `v1-next` => `v1-release`, and `v2-next` => `v2-release`.

We could also rename `master` and go for a `next` => `release` pair. AFAICT since the only PR we have against `master` is `pr-release`'s renaming it should not be too hard. I'll do experiments in a side repo and see how GH and pr-release deal with branch renames. If it proves problematic, we can do it just after v3 is released.

Does this sound fine?

**Comment by JAForbes** [comment]
Sounds good, I think it will be straightforward but always good to test in another repo.

**Comment by dead-claudia** [comment]
I'm subsuming this with #2894.
