### ISSUE TITLE
The test suite uses our Promise polyfill

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2814]
The logic in `./promise/promise.js` picks up the global `window` defined by the `./tests/test-api.js`, doesn't find a Promise implementation, and goes on to use our polyfill instead of native promises.

Adding native promises to `./test-utils/broswerMock.js` would solve this regardless of any future change in test loading order.

**Comment by pygy** [comment]
I fixed this in the v2.x branch, along with perf a regression in the test suite. 

@StephanHoyer @dead-claudia Do you see this going into `next` as well?

**Comment by dead-claudia** [comment]
This has seemingly already been fixed in `next` -> `main`, so I'm closing.
