### ISSUE TITLE
Unsafe assignment to innerHTML

### ISSUE THREAD

**Issue by ramanandapanda** [MithrilJS/mithril.js#2818]
We are working on an add-on for Firefox using mithril.js. During publishing AMO has raised some warning on mithril code.

Here is their response
```
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
mithril.js line 463 column 9
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
mithril.js line 469 column 9
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
mithril.js line 1088 column 47
```

**Mithril.js version:latest (2.2.3)

**Browser and OS: Firefox v109**

**Project:**
https://github.com/zotit/zotit-ui
## Code

```javascript
      var match0 = vnode3.children.match(/^\s*?<(\w+)/im) || [];
      // not using the proper parent makes the child element(s) vanish.
      //     var div = document.createElement("div")
      //     div.innerHTML = "<td>i</td><td>j</td>"
      //     console.log(div.innerHTML)
      // --> "ij", no <td> in sight.
      var temp = $doc.createElement(possibleParents[match0[1]] || 'div');
      if (ns === 'http://www.w3.org/2000/svg') {
        temp.innerHTML =.         //<---HERE
          '<svg xmlns="http://www.w3.org/2000/svg">' +
          vnode3.children +
          '</svg>';
        temp = temp.firstChild;
      } else {
        temp.innerHTML = vnode3.children;       //<---HERE
```
And
```javascript
   var children2 = vnode3.children;
      if (
        children2 != null &&
        children2.length === 1 &&
        children2[0].tag === '<'
      ) {
        var content = children2[0].children;
        if (vnode3.dom.innerHTML !== content) vnode3.dom.innerHTML = content;      //<---Here
      } else if (children2 != null && children2.length !== 0)
        throw new Error('Child node of a contenteditable must be trusted.');
      return true;
    }
    //remove
    function removeNodes(parent, vnodes, start, end) {
      for (var i = start; i < end; i++) {
        var vnode3 = vnodes[i];
        if (vnode3 != null) removeNode(parent, vnode3);
      }
    }

```

## Steps to Reproduce

1.
2.
3.
4.

## Expected Behavior

It should have have this vulnerability
## Current Behavior

It is throughing warning in AMO(addons.mozzilla.org)

**Comment by pygy** [comment]
All these cases are related to rendering the content of `m.trust()` vnodes, whose content should be vouched by the app author (i.e. you :-). You should never let user-controlled values reach a `m.trust()` call.

The first sample you posted is the general case, and the second a special case for DOM nodes with `contenteditable` set.

This is mithril's equvalent to React's `dangerouslySetInnerHTML`, and it couldn't work in another manner, it works as intended.

As long as you pass safe static strings to `m.trust()` you're fine. I hope this will convince folks over at AMO.

**Comment by pygy** [comment]
At worse, given that you've vendoring in Mithril, if you don't plan to use `m.trust()`, you can remove the offending statements from the version of Mithril you ship, it will be of no consequence for your app.

**Comment by ramanandapanda** [comment]
Thanks A lot  @pygy for the quick response. The [extension](https://addons.mozilla.org/en-US/firefox/addon/zotit/) has been approved by AMO. we will remove the innerHTML part for mithril vendor. Happy to support you for this awesome framework.

**Comment by pygy** [comment]
@ramanandapanda thanks for raising this up. This sparked discussion in the team about the topic, and lead me to discover that the WhatWG was working on safer alternatives to `.innerHTML`. We'll incorporate these ASAP (i.e. once they are widely supported).
