### ISSUE TITLE
vnode's className is mixed when an empty object is shared as attrs of vnodes.

### ISSUE THREAD

**Issue by kfule** [MithrilJS/mithril.js#2821]
**Mithril.js version:2.2.3**

**Browser and OS:**

## Code

https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAI4hDACcYAEwCiWAA7EAngEFixOXEkBeScFYAdNJfFSMxyVgAUAcnwZnFabIUr1W3fpwAJTW9BKSAEb2Tq4RHl7ySqoaOnoGIVZoAPRZkW5pcPjUUBhwcAByXF60AK5QipEwkuYgES0A-KFocLSw+FC0AOaOEfmBRSVllTgZlCBwMLDUxBBheACsiADM62wcIJg4eEVlc0KMzDxsALpUUBBoANYIKJxHPFgQxIRy0AACACZ8ECtnManJyDwSMQ1HBEDkamg1I9BkVaFgsp9vr8oIDgfgtpivj9oPhPmh8Pw5lo1Nx5tRfhobqwgA

## Steps to Reproduce

1. define empty object
2. share 1's empty object for attrs of multiple hyperscripts with selector having class name

## Expected Behavior

The vnode class name will be the one defined in the respective selector.

## Current Behavior

The class names defined in the selector of each vnode are mixed.

## Context

I discovered this in the process of creating the following pr.
https://github.com/MithrilJS/mithril.js/pull/2819

**Comment by pygy** [comment]
Great catch! I thought we were doing that safely :-/
