### ISSUE TITLE
I can prevent a mithril component from scrolling to the top on a rerender.

### ISSUE THREAD

**Issue by EverettMcKay** [MithrilJS/mithril.js#2852]
I have a dynamic Mithril component, whose rendering changes as the user makes selections. Works great, but for settings at the bottom, the component scrolls to the top on rerender, which is disorienting and fairly annoying.

Code-wise, it's a simple component, consisting only of an oninit and view functions.

Is there a way to maintain the current scroll position/not scroll to the top when a component rerenders?

**Comment by cavemansspa** [comment]
hello @EverettMcKay, typically that should re-render in place. here's an [example](https://flems.io/?mithril.js#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHnhsoAawAE5RPAC8AHVJiAnpxGJEYo5tPZEhkHIAeYgPRgYMGyJ0tH4mK4KG4e+FBCAFYw+LpsAG7kQlBWblDYfG4sEHyYsmxgALQArmwAAgBMQgCcQhVu+Gww7ni5+WBCfGpCnt4gAHwGUNJ4SGBibNBcaACMKLQgAL5EPPyCIMV45DBRXCSQsvJiikhimpuI25p6mtTAQ5qaRmz4RiiaM0QPTyDs22IAfV4AjePwAsphyBMwJgjF8oI8jFhmkC1qCjGCwABhCAmOHfIyIXIcdEgPh8MCQEy0MpqWL2KCxWQ9CBCYrqfEIn4Ac3ksXIpIAYkTMEhOYiQGxsADMPh8DovKSAMwAVjqStqKrVFRm1SMQ2WmnuXOer1Qmgq8IlfxRwMQpIAclZTOKfsjAXbSQARCAAd1grsJxPgpMZftgMzKMGwEAmLBMLL4gZAvMZl0d0EKACM1JC8cQCZLpbL5YhFeajDMACxKuoVWoAdgb6r1IANRCNhZeoKVVp+No9aIrIAhjPzfaRmFtQ-eRgAQsVyOo1DARJhfcmRSTh3ws4vl7A176KmUWCKhNyIPFk6n+UKRWKCyaizK5Qq+rOQBUq7UZrWZlUDatu2nbPt25pVhOvxsP8qIgsOACCi4QDoybunB9rDgAEpgYhHpg46FluIbDpga54euBFKmUvDxJciY3ny6bDsKuSPlBUqvqW5afrqdTNkqABsQgzLQFT6lAhrGhK4HvCqUEDhhpJzpcKRyGhU6DvBn6YlikKUPAJFQcRpJZhSMLkAZ8BVmUmDFPgmBCCh3JCHZjFpgKw4OpmOa8OQhFgcWb5lh+Pyic2QF1FWwkzKJElSV2ZrvIJCkwdO2k-AA4pc1hPhK6GesOADSxQAF65Juwakty6hlbkKplPETRiDg5BqGIDF5TyTGeZ+rGiphHFBdxoVGFWgEzEIKpVnU03xR20k-LJmgNqlsGFZ+CFQLwhS5G1sJdZO6WYZ+c4QE0MBsMxxlVaRWbnV4V3kIJZSNGwl6dVBt7MX1D6DV2w3vqSf6TTMAAcaozA2tBRcBkkLYloJg2tx2kgASsU9hQhAGmo8OXryFAzXQJVmDbp+5BMkTzTQA2ZRZvAEAuZASaHSmPWkhC7EA1xQPDtUMW0LWgmTYJcMJWBSWaNUKNaSdPxYmu5CcLjcukplZMpJoEAsJoACiUDclgjKk+TPxgNymuIDr8hG3k+Bg1GECY0IkzuXew5c-9gW8yFpIVAH-HqmqDZKvNoEyVLomy0pw5oyIEAOarseflilBeG0pskRTFAQBneTVGUpTFB0BDFO7P0-P13M+yWfO8dFQjNt+wkVIJ4eLaaoKxTHG1V3kyd90YACS8RTiYmwiAeWekuwY8wBPq4HpgZQAUqhQ6MzrLshXvVV39yacXXfvDjqMWAeqVYd4j5oAb3M4-Eh3KbGImyDw-Rg+r6iCQn0N1k9nH4so-Q-22FmV6TRIB0X8p9Qs3094YgGofQGJ9eKxREiqSaAdhJi2vpLbuvZCyKSHiAM65BuTvwykYPW0ZZSXBxmzEyw4sxlmwHQygYAyiqDorA588DOZILZkfYKPEfhVmbABMGIkZiQyrCqPBkdu6QSIWlNWw4ABqMFeSUPlkYAAUpgSAWY4AiCgDPYc8RIiGIgMYiApj8BRhalAbIlMhBl13qSAACggEw-ChEoNEUYCRglW5QyECEhRS0o7yRUetD+IAAAydkdDyB0ejAgjRDbmM-PAHQco1C8jKCIMAQkYYsw8SxA+-jfaBJAFDGG2ChANNoA2SJXdb4pViXjT88dnQHSggVeJnirDkEMWAEQbBsk-HIPYMQozKQTJYBAsgZVkhWAqb9Ni3sZIBNGnUlUDSRINiqONNpkoo6rS6Wo06EBYwWDSfjYoGgcok0YbdT8WZ8BPPUC8w2tJDjwF4RKPxOlBFDRqXspUVQ-wiShRg9ubZ4YRyid3ZGVyU7gkhBMFqDzPwABU2C7javgbRbyAGkj4BMIlLxeQiCjGAK6UAwAEAAQmcpbMQX7y2cgiFpJhINm1EqKRIsznLV1PfKhIA9EQDiNst0mkMVGEyqMuihkplGEiNyFVuhVD03ehZOQgL2VfQ5sOOc71TXguPrUpUM1wZVEhsc0VUsKj0HRSQtGBR1CQjNAMhVJDsrf08v-M2RhyGICDZEGiEaTAoR+UkY1cDTWgprjs3lw5dR2rBr+EJIkKjyMRRLRR5odQSt0SAIqHBVByqOtcn4OEoTwAChKJhn51BKzEE29QZRDWIC1TgEQLI2Qcg5cmzFqalq7L5bWKsk0azSNaYWhG+CS2WndfEnCXR4BiFeX67pWU85-yIu8n4IhLxeHgGURAWYCJDp3qOjyGYoDZlzP5Hl1q9ng1Bg2KRAEcFg2daCCohDnzEPiUVEwrM911qVZQKADCQ2AKMOoLV0AchlDAHwYobivkbK5WCnmH7SRaibrUAOwqr5LuRe09434y2kjxShK6uLwSWDXGYsloanACEQOxqAXCEiICBd1R9lTuXVKIxmnUQh-ziOkQikCndzlAZiaB1RiqQCZRfpgOiLGjCClGVAUq0BnSTM40hlMLBDPGbUhMCAr0TCMlgE5cheHEETueFO4cci6yTWqL+qsAGqNKeWm3ejiFGQ6A3GzQZkqFylTUDWkAragF7gSykbARTihZjYbyHYia+Fjvc0l4RI1gbZrqLQGawGYZg0o4pm+tHLlqbiZKtGEBSqijUHpkAniFS5UQ6SGZ-WACO9NGZGyvN0ArwKisgGriVrzn5BJ2vBnm7UtBxbLuLbRtFLX90jwcqoXgPXK3wCzMSpLKXnjLnO5d8g42mYtXgOoUZjRWQzZEx7TZBHa4iM-YHY5QhAvSLDsFxrFoZbrslXo+ybAKI9a9C8ByfAj3PmuyASIjQ5T8C8Kec8l5rwPu+-hjzL5JOfnndWX92pwaAfNEqN1+2YNSrsdtfphZYvlvUXkEwkJp7mdJJEMeUA+dLnamUK8lxswTeE0YTl+mqlWv+8DWd4Sqg1cvvT94SpPjQ-LXrBLiBxlXTJ1zrxEzDLYGKAN495LhyIGwJb+A1vX5lEiO9Becv2aiZTYt9Ny3-zfgwcE8S4OV067XczjTesdAjugxpuc5AnnquSxdp58QyhO+wGs23hXffjv9xTsK0mAKQxI1DLb1HlMM5A9adTJCvRPJhBxhPJCADK2A1C8GZan-A0Zu+GIjRhlCKRDI4fLsTyuxX30q9PvWEStAsFVhhpm7XmhbXhZ0hweU4E28bv0hdVPfAlZtS8M4MolL4je4V-NpXhG5+fh1JNMGAXQbfnX6qLfPw0aYBYCwHrPSDLK7E9MNFvR3RAEwDDGAPgaAeHFCG-ObL2WfMrYcf8FUKRV1GaOrT-TpaPEhAAeViFUA52fHN2HGGUNirUgNTwgAZG5GoJMFKholwkXCE0+3lzmwWxQPrjCjBmbDBlBl1xEhrE-2a3r1a3LUFEmG2mKCwERxMAPDRxbVAN+HwEUJXFEjKEJ2HTczv3E2V1QN4mqBhgwKEDqzqCrxCyliFW-yME8Vwh6wM2+WUJ+Ax2wCsxcNikl3iEHTUj0OQIk0fzCloEhhmBihVAEgUyRWsJ7Ch3wPiS9DyDM33xh0wB+VcKDHt0-HwCsQyIAizzYPiAQGKAEEQIL0VwMIfyMJ+DMJMKbmbEEgLQawj00BXzsJAEY0shoJi39XiSTzyE7VTzEAu0GPgD-CjBG1KHwFuXKJJxnyCJqKMGmhqFW1rDBmiKLRRQgj1wSMlUVjPwmDyFIPyj6MlUyluXwFODzxUOyPNkvETmuOrFsikX8KnwQX0N+zTWL0rCB1VEqw11oE2O222PeHGg6KSP8lb05zOPLQSXenED71UG5HEBkSjFxyeS3igyTQqM+LJ1K14KMADmaVBmqFrGA3XxrA6PhJO16IO002oN3Tty43gAYMMmtigHCKLiJmZRYBcwoXePvCqL+yWJACaPCVBiq2BzBxaJ2zaOUT2PLQ1jMCS3IJ0nkCelT25AECJkuChm0OtgZQmDLDmOnxHC+MnQDx+FdX-AFlmiwUpNUwkPpIhH8mOyTjpJZ0rTDGhPR1UL4APBmM5MdmwHIBSF9BgF9BgnYJyD0Oyg8imMsGDWqMJLqSVFrGqFp1qFwXDzlOig6K0yNlN1gJ6yTxMH7yZL9LuPlwu3LLgE5MLgsGcCeVNI+MCMMNTNdUhg2KOQkVOVzNBLaPEP7Ab3iVdJMCsRSFO0sEtl9NuK4wDJnLyBmBXjLgZiZh2Gcj0O4MWM7JhWA1-UEn-CbEpL22dJZz0UuCJGbXlXpIXCZREFT0iD3AfJmHATmR1TYDyFbIEXxKW2tM23VFMMwLD1lMHJ-A6OHg9NSPLTxSsBgFFCMmZIs3h3gsQpmE4QgDAAiBSCiGwG3PvxFNTMzLzTzWhVtXXwOQ6IbRuNvJZyT3DDIByBYVTxEAu0YpZhYRmAcV-jkHGR5Mcg4J93mPNL-KtMrB-HMO7LnXqxiIh0wQ6LBAelVNhNJHbwsBgjAFUH-xAOrLJFXEQE0u0rPBmEQEv0MR-M9gtM83EpABVGEmEOrGhTEkoqj3PJj0ZiaBOLosTybTwm60FwdwZhMH8s5KWW-jMnwEsp+zEp+LqWqD7MhmqHIsXTApo00BVDrxHMkNJBxEsmY09MT2gBSDwDnLcNULAHum2jLHkBmG5Aw0ZnshYCwB0GisLx4NQRCMFk1GB1oEooVPcpIUrX+ACpguUnYVT3UBvX5BmDpRgHUBMA4XUDaqMG8mfV8jzA6tqV1H-FhQEL6oHPSq1A6N-xUvpMYw0BXErPnIs2xkutgGgBmHKEgEgAm0KCJhYFMBWt6x8T8Q7M6qMDBlX2ENzXCJmEorwMGrHPemKDiBxUKpIT0hJV0oXJhGRpmCjQeKNhjL4CEAuwIuFO+OCMrFEiOWhWAzzVkq2KOuHKMDA3OMQswBROuhhPpIAHUVTMjktVDuRfROaZhu0WytzBSvIfJX0bybK4rwipEQcErYVgTq9loMCOiipcJcwescIxBxkWaqyuN21cJtbyAZhL0YDihtSzbvqdz-rtqJEgam4Nc25KL4iobJUwQ4b4axqKCdAxAXRArPw+BQznQTAZg+AyhnA1ARBig8grBLbCKibRTdRf04UVspoFbYjzRBImcXby1h5yAidPbPwklDIJbua9KOBELg7+NQE8Jjtlq3iTVcT2yUyAa6lX89rpFQZs118RYOiaF5QpxSyyxaKsiuNr0h6Zh7N4NMBHJCcAjrLydiavxQjzCRDfxZ1u63Lsr6ScITBfQfUesEJRjUdlxWLMAj75q2AZhMtfRaxhaG6RKm6iKW61dMqmkZM06IcjzIKiZLxADRkETDLfVkLSQCh-7maXgZgxsoznBvrH747Uzqw+yJEhJpFQK5LWiVtqS1A34Eb4kaTuQUhkzdaLNDIClCGZgHsz6Og1JXJJ976zS4HLSpaAIRJ6iA47V81u6nSt6WcnQfaUjWaWc3aTcwBU8oABARGZgYAs92orzmhY7CamHF6AIyMgS36-xUr0G5SQkOicRGgzqhH5BGYUaLNMMjGZUZgxAoxVBYhVxIQhN66cSRKrbm7tqjzLDpEGlNHqaa9kpaboIcqItmU1VcHJUvQmCsVU9ZQImoQZhigyhfRihsgPtYyRa-ctqAdMC5NYpf1XVu6zyeGNMlLw0yra1fKf51AkAS6MddwkB0iqmZhM9YgmpBisUFH56CSW6dQkqsExJZpmitHByxZqLIQkBSmQA1SfgfQzbNq-bT0ZiZn-IZhfRXoCBjdUdYGOn-yiSUHwYQK7UIlDrfGVos7CmSEcIkAESesEkCAXEgHiHSQRAkB8A7mZgL8ozlx7BGhHI76nGzSXGn7alg8oZRYGlxF18Gxdjs7vRr0UJEcbcRBqnVC5QEXg6oCYApj7HaFmV2nYrF6gd81gaNchIIXN66bRzJUsII0CqC6fhVbZzWLvVZyZhmDmqvUE1Un6G2ytnbLRJf1-M6gZEZMBmfHlpQ5qKCAmoBTaWjA8VKAWK5mjBxB5XEBXV3dRQ9xcbHH89nG46lHRTgNW5dn+DF80HRWpYGwBqzmxzdBBi1xADfAmgE58LFWyRxkz9nWdQe0dBSHvyhLb8AX4GW7qhJpME80yMoUIXuHyXAmdImMxBSoesDEeS2BIhEAmpRHXW+BJyChU302CgA5TxNIWY2FRdNm8WE61doZwlz5wajmxXIbrXJU9Z4AEKD78ABdBsHdZQDxgNJc+AiZX5Wr-WuC9XJblGmxWHm4YVM6IX-H6apCOAXgDGNNR4pxTFY187gHhw5513RcrxvxzKOgR3cTA39WEG7SRZYZWGDq0rjmf0Oj29IRp7tpSzIRE3XWYAb1yBSp80s8RBsAswsxcWi9lHM6ZNf1IW6gIXnam3ucEg+dxnJmjAip5BfQ2owB49t3Px4gfkoB0OvU25o0+a416IT2RLzU-rXG9k24jkYYjXb3Bn0qgbH25A96oQet2tSqzx4B7mbrSQYB055AeP8AKg6Y4BLxsNyOzS1qX0-IS7Ontq4VLXF8jWRWQTmOoW4OBF9okPVLhxYhNA5w8gflj9Ygb1nkKhHZI7-8Ckd10g84OppOPiz3x3RSVPRIMyZpZ362pYwYyWAn6TlSxmV2O8wAbcTdDYuaMduQVktaJkov6wi5PAor3E0nSdQODXaOnLgdhINj18wYsqY36TFZRn5BQv4l29EskW9LPBquKgV5Y0bdsscaCaeW4rvxoVSbdRmkCurXiuWcqW6QMOsOyD9O+o7IHzWKWBJvxkKhwFRcHIOBHMI18tOW-nuWK2EG7UDkppJpI3fOkZo3AuWcMZywZXEkf5+97PU9lYruaYoAKhOEGC8Jsty3MvOyl95aZNgd1PFa-PG2BuPLVAesHC5kaUTHSRHdcJiVeQKgHExBChoBjshNYg2utuW7wZV9z4I2P7Wj+DFLdA85vKymSFh5GYfbj8OBYwxAKgzK+ckAJ90ePuumw2Qc-xfxaAgs73lpX9qTDK7GesOb2LxmMd4A+aReKgllEBnB+BEsOXsSdX-mx2F6E6hXxom51QZSmPjns0OiEIwyaXBGNMkkfaauuNRRcJTAKh6qb7+S56MfaldvgNoVJ3Yo62eepYTCCycGLvK0gPLAtTlwA-VW5qEuTBmhcIQOMniNV8VjYptRwXDvzQQ2OjYdGgnDLhKB+GnyzxLIae2AKhygxAoyfayP1uleXOVfFO9kQ3WH3850zWNPjnkqOi5Wtw9OSuf5sAxnhjmUcAxmKgo02AzJ3uY-T4VQHVJSpFJ-18yTqTkkCgKu4sEA1AENsO3R7pjsIAKhu0GY1BKnmpo-dzMfA5qx9vz5tfzXQRqh+uTuNN1K8heBO+WckkHyh6db+PhwYBjZtbmhLgKgJtBlEcDYDsAYQAgDDn6wr6zZG67XRet03VAxRSawGKms32WiZldGSsUasbxISYhPEFgVQIry-6fhMMYAJ3HED4AVBQ6DIV2Ov0r5Ck4BlbQVJz0BIe8de6AwHvfxIRnQgOJdZDr1hSTqFU8OWQQSYAqD8Z8AsBUqPb3S6VFGBCDE1pNBU6645+87CluWguZIUxu9JaQrXSvDTcl2GgA9vZmyBiBlwY-E-ttXnRmFRIO3NgdfxT4FMgeJCFtl+XgyjIesWmY0t0Q-ZdtPwfaG3E9B0C-tMs65WLjGCc7QCvsyvRRm50+6r5S8gkaFPl2T7vBqgsHZwf0R-jg9nAPWYeAHR6J+CfgOYAoWILGwmAdUfoXLCaWc4MDHen6bJoBQDi1hGc6+USKc0yGSpUOszC7lS1FB8dyqeldtD-F44VAHsfFUxChDVoWDraeyCwtWDtRy1wY3jRgEMBGC6BjcdmWAIoGhhzAFgywVYAIEUC7BpABwOQAoDQBDADgzQTQO3lziGQz6SAHELICtjkBrgmgAABQABKa4P0GRTe1FwCIRaI8CagRp3gHw4ACbl446BJIPwvQH8OBGPBtAVgQEZoD4AfCAA5I0GvylAhA2I5dlFVUDNAMRC0ZoCqRQAYiNKKJMQO8HaEABSAANxS5yAzVP0IUBMDvA7IO6DEYaChGlgIguQbAB8NQp8BfhaIzEdiNdhyA+AJIzQCKK+EKjvgjwRYN8BVGSQhgVwqYGcEj5yB3hncdUWYnEadBnYsgD4TMXC46kOo90dQiCVBG+hwRcIv4dQCVHiisRCQWUQAAMAAJMAAIJZg024wIQGPHgCw0YAHwnUYgC+FCAxm3IPCIsHOBbAYAmgUYJsIIAeivhfYR4OiLuFWRHhiAZ4S1Hl4dhvgFwbYJ0BwAfDSxYoxEUiNrGaBQg1whAEJgmzhiWocgL4S6LrG1iARYZLMRKISBsg2AogJjDZmezRjmoso50VyC7EzjXRkokUbKPRFuicRQ47Wph3ujOBJxnY2cXWKXFqBXc1AOwA4DXFTUIAzgRgHaD0A+jSxrsfAIsEYCyiaxO4rsdAC0peoHRYoiMdQBvEvBGAmgAAPyaBiCVgRAMmLbGIBvxWwW8X+PeBfifx+AP8TcDmSw1Mxz4mcSeIIDvAAAhFhLglQTfx24tCUiMWAZjCJaEpcVgBYTwAMRHY6cURM0CMAFRqEoiUuPnHSjZR8E0iXRJYn9jr8C4jsDeIXZcT6JSI1iQOP4kJj6IXOWiSJMYlkTaxaox4LRK+GMASJ6wsYFsOmD7IUAByJYCsBAB2hjhvQU4dAHOHHA0A1okwMimZGsjfQ7I94BMjlDyAGRBodSZsJkJaTaAKAKsEsGYATMD+0wO4AZLWCKAugeENqFIBICLgpAaAQIMEFCBPJsAKGRMG4DCmOtL0GuOoKlPhzpTOg3QaINICPGKAyAbUbAMcHvGLAgAA) 

if you can provide an example of your issue, we advise.

**Comment by EverettMcKay** [comment]
Ok, thanks. My component basically boils down to this:

```
export const FhExample = () => ({
  tag: "Example",
  attrs: () => {},
  state: () => {},
  view: () => (
    <>
      <h1>Example</h1>
      <div style="padding:8px 0;width:100%">
        <div key={key} class="card" style="padding:8px 16px;margin:8px 8px">
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
          <SelectOption condition={show based on state} attrs />
        </div>
      </div>
    </>
  ),
});
```

The various options are displayed based on the current state. If the state changes, I increment the key to force a redraw.

Works great until the you scroll. Any redraw undoes the scroll.

**Comment by cavemansspa** [comment]
changing the key will result in a full remove / replace, so that is likely resulting in the scroll reset.  if you can reproduce the issue in a flems, we can have a closer look.

**Comment by osban** [comment]
I agree with @cavemansspa. Using the autoredraw (and diff) of Mithril or m.redraw() (depending on how you deal with the state changes) should keep the scroll position. You might also want to either pass the state and such as attrs if it's external (deconstructing is possible: `view: ({attrs: {tag, state, ...rest}}) =>`), or use the outer function of the closure you're using in case of internal state.

**Comment by EverettMcKay** [comment]
Using a key is in fact the problem. It looks like I do need a key, but not for the part that scrolls. Removing the key from that fixed the problem.

Thanks, @cavemansspa and @osban!
