### ISSUE TITLE
Confused about component redraws (and keys)

### ISSUE THREAD

**Issue by EverettMcKay** [MithrilJS/mithril.js#2853]
I have a component that displays an array of buttons, which looks like this:

## Code
```
const MyComponent = () => ({
  tag: "MyComponent",
  oninit: (v: Vnode<myAttrs, myState>) => {
    initState(v);
  },
  attrs: () => {},
  state: () => {},
  view: (v: Vnode<myAttrs, myState>) => (
    <div style="margin:8px 0;display:inline-block;">
      {v.state.range.map((info, i) => (
        <button
          style={myStyle}
          onclick={() => {
            handleClick(); }}
        >
          {getButtonLabel(v.attrs, v.state)}
        </button>
      ))}
    </div>
  ),
});
```

When the user choose an option, this component might need to be redrawn. As it happens, the button labels are redrawn (so, view is called, getButtonLabel returns the right string.

## Current Behavior
My problem is that initState (which is also called correctly) might change v.state.range. For example, the range might change from 3 buttons to 5.

The view call will not change the number to buttons, however. Only the buttons on the original render remain.

## Expected Behavior
I would expect using a key to fix this, but no matter what key scheme I use (setting the key to i, to the current label), only the original buttons are drawn (but with updated labels). So, even though the array my now have 5 buttons, only the original 3 are redrawn.

What should I do here to force all the buttons to redraw?

PS: Note that this same component is used elsewhere and it's parent has a key. Changing the key in that case gets the correct behavior.

**Comment by EverettMcKay** [comment]
Sorry, the problem is worse than I thought. I removed a bit of complexity from the snippet above. The code is really more like:

```
  view: (v: Vnode<myAttrs, myState>) => (
  <>
      <Title {...v.attrs} />
      <div style="margin:8px 0;display:inline-block;">
        {v.state.range.map((info, i) => (
          <button
            style={myStyle}
            onclick={() => {
              handleClick(); }}
          >
            {getButtonLabel(v.attrs, v.state)}
          </button>
        ))}
      </div>
  </>
  ),
```
Just discovered that even though v.state is updating as expected, <Title ...>, which is based on v.state, doesn't redraw either. But for whatever reason, but button labels do redraw. 

So, it's not a key problem.

I guess my real question is: how do I force a component to redraw itself when the state changes? Most of the time everything works as expected, but sometimes there appears to be nothing you can do to convince a component to redraw on state change.

**Comment by cavemansspa** [comment]
are you using `m.render()` i.e. (`m.render()` does not autoredraw)? see [autoredraw](https://mithril.js.org/autoredraw.html), which is applied when using a`m.mount()` or `m.route()`.

**Comment by EverettMcKay** [comment]
I'm using m.route(). As mentioned, in all other places autoredraw is working as expected.

**Comment by osban** [comment]
It looks like in Title you're only deconstructing `v.attrs`, not `v.state`?

**Comment by EverettMcKay** [comment]
Correct. v.state is updated to reflect the current v.attrs, which happens in oninit.

**Comment by osban** [comment]
Ok, not sure I understand completely how things are done, but `oninit` only runs once when the component is created, not when redraws happen. If you'd want it to happen before every (re)draw of the `view`, use `onbeforeupdate`.

**Comment by EverettMcKay** [comment]
Ok, that fixed it! Thank you!

Might seem like a dumb thing to not have tried onbeforeupdate, but I used the debugger to check if the state was correct on redraw. oninit was getting called and the state was getting updated correctly so I assumed the problem must be elsewhere.

**Comment by EverettMcKay** [comment]
Closing. Thanks again!
