### ISSUE TITLE
Why are v.attrs passed to oninit() for a child component an empty object?

### ISSUE THREAD

**Issue by EverettMcKay** [MithrilJS/mithril.js#2854]
Hi,

I've been using Mithril for awhile and have the vnode attr/state thing figured out.. Or so I thought...

I've split components into subcomponents many time without problem. However, in this case, I have a rather thick component that maps options, and need to split out an Option component. As it happens, the options need to have full access to the parent's attrs and state because that is what they are for. The parent attrs and state don't change during the mapping.

## Code
So, I have a component that looks like this:
```
const Parent = () => ({
  tag: "Parent",
  oninit: (v: Vnode<parentAttrs, parentState>) => {initParentState(v);}
  attrs: () => {},
  state: () => {},
  view: (v: Vnode<parentAttrs, parentState>) => (
    <>
      {v.state.range.map((i) => (
        <Option
          key={`${build unique key}`}
          attrs={v.attrs}
          state={v.state}
          i={i}
        />
      ))}
    </>
  ),
});

```
However, this doesn't work. In an abundance of caution (worried about some object reference problem), I tried cloning the parent attrs and state in oninit(), because using a map that passes the parent attrs and state is different from my other (working) components. So, Option looks like this:

```
const Option = () => ({
  tag: "Option",
  optionAttrs: {},
  oninit: (v: Vnode<childAttrs, childAttrs>) => {
    v.state.optionAttrs = { ...v.attrs };
  },
  attrs: () => {},
  state: () => {},
  view: (v: Vnode<childAttrs, childAttrs>) => (
    <>
      <button {based on v.state} />
    </>
  ),
});
```

## Current Behavior
After doing this, I discovered that v.attrs passed to oninit is an empty object. Never seen that before. 

Reviewing the attrs in <Option /> call above, I don't see anything out of the ordinary.

## Question
So, what would case v.attrs passed to oninit to be empty? (And how do I fix that?)

**Comment by osban** [comment]
As far as I can tell, the attrs and state that you're passing from Parent to Option might be the unaltered vnode ones that have been passed to the Parent, and I'm assuming `initParentState` is changing the Parent state, and not the vnode.state. I'm guessing you want to achieve something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIAChgBOIyQF5JACmAZixOXFYBKZQD5JwADppJkzdrj45GNAHMYyycgCMFAEwUAzAF1zc0sFYgBXOQszC0tJADcIGAB3RDUNLR19IysM23snGHwsDAAHVQhsrFUAeRLiCHoKE3wW6x0miH09YMlWcz60c3EpWvr6V2jLBOTU9Ta4VOBGAA9iDtYspWMqgHIAIzCteh2mleIAaghutAGh+gkrEpKJnumUtQMtySrZBQYmpYwVapUwgRgSUH6fpBNBYIq0MIMVQAE1o1DCOAY+D2tGRAE8mqUSnpKCA4DBYNQxmgEDx3ABWRAABjYHBAmBweHw1DgAho9EYzB4bH8VCgEDQAGtaah2Vw8FgIMRCHJoKSIuQeCRiCUFgB6PWIkqSxzc2hYPWK5WqqAAAS8+CZ+AALJalSroEUJfh+KTiHiStwydRVXURawgA) (sorry, it's in hyperscript, not JSX)?

**Comment by EverettMcKay** [comment]
Thanks, Oscar!

I have a clue: the problem is the spread operator. Could be spreading multiple objects or perhaps doing that in jsx. (Note that spreading a single object works just fine.) Either way, I tried every combination of spread I could think of without success. I figured out a reasonable way that doesn't involve spreading and that is now working.

**Comment by EverettMcKay** [comment]
I don't know how embarrassed I should feel, but I think I just discovered that "tag" is a reserved attribute name in mithril. I was passing a tag attribute. Doh!

Is there a way to flag that?

**Comment by EverettMcKay** [comment]
Will close. Would love to see this flagged during runtime though.

**Comment by dead-claudia** [comment]
> Will close. Would love to see this flagged during runtime though.

Unfortunately, it's basically impossible, since in the locations where it could be special, we have no knowledge of whether it's a vnode or attributes object.

If in doubt, [use `m.censor`](https://mithril.js.org/censor.html). It's not yet reflected in the main docs, but that's really just a docs rebuild away.

We do make sure that if you provide us a non-vnode when only a vnode is accepted, you will be able to spot the error. But unfortunately, Mithril doesn't know the context in which it's called, so it can't tell apart attributes from child vnodes.
