### ISSUE TITLE
There is no onsize/onresize lifecycle method

### ISSUE THREAD

**Issue by EverettMcKay** [MithrilJS/mithril.js#2855]
When a component's size changes, I would like to change the size of its elements rather than have them overflow. I see there is no onsize lifecycle method and onupdate, onbeforeupdate aren't called on resize.

How can I handle resizes in mithril?

**Comment by osban** [comment]
You can use the regular event listeners for that, like this: [example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZPFSsEAO4BGAEwAOAAyLJWDMWqEAsjAAmEDMp0hlEzQAWlMIT2JCREkrOxkAD1V-JP1DeglHDFMAdgA2bIMlJxd3Lx8-AKd40PDI6LzshKSQFL0DACcYYgBXdv1dVIN6ak7nGGi1TUkwtE9aU3wMT08AUQA3EQAZCAkmGHaKzrgIAC8YfwpHfE7PdqzVCjaDSXpOrFoNifUFLRm5hbeHxg6y2O0YaH2h3gp3OlCuNzupgeeieBjWEBgpi+mlRzywygA5PgnBA0ATLgNnlTJBIAJ6waIAAwARhhqABrADm7Vo3Vm0QAJMATBYbLZic5XPBJAB+SQEuAYKDvMmSaJOHL5CUlaVygmMJUEtXy7kwWkE1iM3EGVgpG16VgotBYYm8hjKObUbo4Bj4Zm0Ty0y6yGSqSggOAwWDUYgQdJ4cwAFkQtjYHBAmBweHw1DgAho9HBoh4EtJ2ieYQiUUkllstgSAG4noQYBBOSRouYAKz1+JN1Ksjnct2eaIAYmok-7rHDkejsfjPAAzIhLMEV+YAJxsAC6VCgpPZCBQnCzPBMkXa0HDvXIPBIxBkcEQAHoX3yZFyc7QsC+L4QrygAABSx8HFRM-wgS9oGJUl8H4cNiFpGRuAjEYIBkURWB3VggA).

**Comment by EverettMcKay** [comment]
Ok, thanks. Just one problem: I need access to the component's vnode. How do I inject the vnode into the event handler, which seems to only want a function that takes an Event.

I tried accessing using this, but this points to a completely different object.

**Comment by osban** [comment]
The `vnode` can be accessed like usual in the view: `view: vnode => ...`. Since the event handlers redraw, the view will be redrawn, with any changes you'd want to make.

**Comment by EverettMcKay** [comment]
Got it, thanks!
