### ISSUE TITLE
Typescript return type for mithril components

### ISSUE THREAD

**Issue by EverettMcKay** [MithrilJS/mithril.js#2857]
This should be a simple question, but I haven't been able to figure it out. Suppose I have the following component (using typescript):

```
const MyComponent = (): X => ({
  tag: "MyComponent",
  title: "<placeholder>",
  oninit: (v: Vnode<myAttrs, myState>) => {<set title>},
  onbeforeupdate: (v: Vnode<myAttrs, myState>) => {<update title>},
  attrs: () => {},
  state: () => {},
  view: (v: Vnode<myAttrs, myState>) =>
    <p>My component: {v.state.title}</p>
});

```
For this component, what is the return type X? And if the return type is JSX.Element | null, how do I include the JSX.Element? 

Also, any guidance on what goes in attrs and state functions? Haven't found any examples in the docs, so mine are always empty. Been using oninit and onbeforeupdate for all initialization.

Thanks!

**Comment by osban** [comment]
Hello, have you looked here: [https://github.com/MithrilJS/mithril.d.ts](https://github.com/MithrilJS/mithril.d.ts)?

**Comment by EverettMcKay** [comment]
None of those patterns seem to work for my component shape. I tried this:

```
const MyComponent = (): m.Component<myAttrs, myState> => ({
  tag: "MyComponent",
  title: "<placeholder>",
  oninit: ({attrs, state}) => {<set title>},
  onbeforeupdate: ({attrs, state}) => {<update title>},
  attrs: () => {},
  state: () => {},
  view: ({attrs, state}) =>
    <p>My component: {state.title}</p>
});
```

And ts complains about the tag, title, attrs, and state fields:
`Object literal may only specify known properties, and 'attrs' does not exist in type 'Component<myAttrs, myState>
`
But if I remove them, I get 
```
MyComponent ' cannot be used as a JSX component.
  Its return type 'Component<myAttrs, myState>' is not a valid JSX element.
    Type 'Component<myAttrs, myState>' is missing the following properties from type 'Vnode<{}, {}>': tag, attrs, state

```
It's been awhile since I chose that particular component shape, so I don't know why I chose it...beyond the fact that ts seems to insist on it.

**Comment by osban** [comment]
I'm not familiar with Typescript, so I can't help you, sorry. Hopefully someone else can.

**Comment by sonkwl** [comment]
Typescript does not mix with mithril.
mithril is a front-end component that follows ecmascript. typescript is a superset of ecmascript.

**Comment by EverettMcKay** [comment]
OK, thanks. Will close.

If anyone knows how to make this work, please share. Also, would love to know **the recommended way to include JSX.Element**, that would really help. I'm asking because the way(s) I tried didn't appear to work (or seemed overly convoluted to be right.)

**Comment by dead-claudia** [comment]
@EverettMcKay Feel free to ignore that prior comment. It's wrong and they got kicked out for similarly low quality comments in other issues.

Our current recommendation (due to a number of TS type checker-related issues) is to use TSX with `m` as the pragma and `m.Fragment` as the fragment component type.

And TS in general currently requires you to specify a return value of `JSX.Element` for function components (there's an open issue about this, but I'm on mobile), which is incompatible with Mithril's closure components, so our current recommendation is instead to use class components universally.

**Comment by EverettMcKay** [comment]
Thank you. Could you provide a typescript declaration I could use for JSX.Element? That will take me to the next level (so I don't have to return "any").

**Comment by dead-claudia** [comment]
> Thank you. Could you provide a typescript declaration I could use for JSX.Element? That will take me to the next level (so I don't have to return "any"). 

[That namespace definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/18ad628cb2ff906460761773a89d5c7a5626cdee/types/mithril/index.d.ts#L326) *should* exist by simply importing Mithril, assuming you're using `@types/mithril`.

**Comment by EverettMcKay** [comment]
I have confirmed that I have @types/mithril, but when I refer to JSX, I get "'JSX' is not defined". If I import explicitly, I get "Module '"mithril"' has no exported member 'JSX'.".

**Comment by EverettMcKay** [comment]
Never mind. It was installed, but I installed again (to be sure), and it's working now. Thanks!

**Comment by dead-claudia** [comment]
> Never mind. It was installed, but I installed again (to be sure), and it's working now. Thanks!

If you were just checking in your editor @EverettMcKay, I've had success just restarting the TS server and/or editor in picking up global augments. The language server can be a bit finicky sometimes with that.

**Comment by EverettMcKay** [comment]
Awesome. Thanks again for your help!

**Comment by EverettMcKay** [comment]
Weird...the definition of JSX.Element somehow disappeared again. Restarting the TS server _did not_ fix it.

The exact error: 'JSX' is not defined.

**Comment by dead-claudia** [comment]
@EverettMcKay In any case, you'll get better luck asking around in TS-specific communities instead.

They can help you figure out your setup issue and resolve it for good.
