### ISSUE TITLE
onbeforeremove not being triggered when list element is removed

### ISSUE THREAD

**Issue by frenautvh** [MithrilJS/mithril.js#2881]
**Mithril 2.2.3**

**Firefox 117 on MacOS**

## Code

https://jsfiddle.net/v6qgoczx/

```js
const items = [1, 2, 3]

const TodoItem = {
    view: (v) => m('span', v.attrs.value),
    oncreate: (v) => console.log('create', v.attrs.value),
    onupdate: (v) => console.log('update', v.attrs.value),
    onbeforeupdate: (v) => console.log('beforeupdate', v.attrs.value),
    onremove: (v) => console.log('remove', v.attrs.value),
    onbeforeremove: (v) => console.log('beforeremove', v.attrs.value),
}

const TodoList = {
    view: (v) =>
        m('ul', v.attrs.items.map(item =>
            m('li',
                m(TodoItem, {
                    value: item,
                }))
        ))
}

m.mount(document.body, {
    view: () => m(TodoList, { items })
})

setTimeout(() => {
    items.pop()
    m.redraw();
}, 1000)
```

## Steps to Reproduce

https://jsfiddle.net/v6qgoczx/

## Expected Behavior

Outputs :

create 1
create 2
create 3
beforeupdate 1
beforeupdate 2
**beforeremove 3 <-- missing**
remove 3
update 1
update 2

## Current Behavior

Outputs :

create 1
create 2
create 3
beforeupdate 1
beforeupdate 2
remove 3
update 1
update 2

**Comment by frenautvh** [comment]
This hook is only called on the DOM element that loses its parentNode, but it does not get called in its child elements.

Sorry for the noise

**Comment by dead-claudia** [comment]
> This hook is only called on the DOM element that loses its parentNode, but it does not get called in its child elements.
> 
> 
> 
> Sorry for the noise

Yeah, that's intended behavior. Anything else is a bug.
