### ISSUE TITLE
JSFiddle links are broken in CI

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#2898]
Example pull request: https://github.com/MithrilJS/mithril.js/pull/2897

They're returning 403s, so we need to investigate to see how we can auto-confirm their existence. Might be worth getting an API token from them or at least confirming with their support how best to proceed.

**Comment by devshDotTech** [comment]
hello @dead-claudia , i am new to opensource and i want to start my journey with JavaScript project. Can you help me with this issue

**Comment by dead-claudia** [comment]
@devshDotTech This isn't really a good first issue, and there isn't much right now that would *be* easy for newcomers. I recommend looking into another project for now.

**Comment by dead-claudia** [comment]
Got an open inquiry for JSFiddle: https://github.com/jsfiddle/jsfiddle-users/issues/1876

**Comment by dead-claudia** [comment]
Appears to be a false positive based on #2904. I suspect I may have gotten bot-limited by it due to excessive (and highly avoidable) request concurrency.

**Comment by dead-claudia** [comment]
Okay, #2906 should remove what little else could potentially spam websites outside of directly throttling network requests.
