### ISSUE TITLE
Source map doesn't work from CDN

### ISSUE THREAD

**Issue by bsuh** [MithrilJS/mithril.js#296]
http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.22/mithril.min.map points to `"..\..\mithril.js"` which is
http://cdnjs.cloudflare.com/ajax/libs/mithril.js when it should point to `"mithril.js"`

**Comment by renancouto** [comment]
Not sure if this is related but I'm getting a 404 for the http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.29/mithril.min.js.map file.
