### ISSUE TITLE
After settings element text content, it won't redraw

### ISSUE THREAD

**Issue by up9cloud** [MithrilJS/mithril.js#2962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mithril.js Version

2.2.2

### Browser and OS

Chrome latest, Ubuntu 22.04

### Code

```javascript
import m from 'mithril'

const state   = { count: 0 }

const actions = {
  increment: () => state.count += 1,
  decrement: () => state.count -= 1
}

const Counter = {
  oninit() {
    document.getElementById('r1_1').textContent = state.count
  },
  view: () => {
    return (
      <div>
        <button onclick={actions.increment}>+</button>
        <button onclick={actions.decrement}>-</button>
        <h2>Not work:</h2>
        <div>textContent:<span id="r1_1">{state.count}</span></div>
        <h2>Control group:</h2>
        <div>{state.count}</div>
      </div>
    )
  }
}

m.mount(document.getElementById("app"), {
  view: () => <Counter></Counter>
})
```

- See the complete repo: https://github.com/up9cloud/mithril.js-issues-2962

### Steps to Reproduce

See the code

### Expected Behavior

It should redraw

### Observed Behavior

It didn't redraw

**Comment by dead-claudia** [comment]
Mithril builds and modifies the inner text node directly as it's simpler. It doesn't call `.textContent` [except when initially clearing a node it's about to mount into](https://github.com/MithrilJS/mithril.js/blob/36eedb7b71cac43dbb56f25cc874c5c08606b120/render/render.js#L936).

It's best in general to either only use Mithril to add children to a node or only use another mechanism to add children to a node. Anything else is a recipe for disaster, either with Mithril or with whatever other library or system you're using.
