### ISSUE TITLE
The npm publish workflow sometimes fails, and it fails in a way that results in no publishing occurring

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#2987]
Example failure: https://github.com/MithrilJS/mithril.js/actions/runs/11721294986

What makes this so bizarre is that the previous run worked without issue, and to my knowledge, nobody's made any changes to perms: https://github.com/MithrilJS/mithril.js/actions/runs/11609775531

I've currently enabled force pushes, but I want to re-lock that down. I'm thinking about doing this: give @im-bot (I made that bot account a long time ago) one-off permissions to bypass the force-push prohibition, and set up that workflow to use a token from that bot for the push.

**Comment by dead-claudia** [comment]
Related: https://github.com/JAForbes/pr-release/issues/359

**Comment by JAForbes** [comment]
Hey just looking into this, it seems pr-release successfully exits, its only the next command which fails

https://github.com/MithrilJS/mithril.js/blob/af65b2d430bfdea2f5b1665ad94f695c24e7a0f9/scripts/set-versioned-branch.sh

Do we need this, can we just have `main-$version target `release-$version` in its actions yml and open PRs against the versioned `main` that we are targeting our patch for?

Also noted the comment in the script that we can't force push, we should be able to opt out of that for admins.   Sometimes pr-release will use `--force` as the target branch should always be controlled by the base branch.  If someone mistakenly commits to the target (or they do intentionally for a hotfix), pr-release will perform a force push on the next release to self heal divergent histories.  It only does that if `--force` is specified, but that is the default behaviour.

**Comment by dead-claudia** [comment]
@JAForbes This is less about fixing that bug (I've already resolved the perms issues) and more about eliminating the failure mode of announcing a release that wasn't actually published.

**Comment by JAForbes** [comment]
Yep, if you leave the force push to pr-release it already handles that edge case.  That would require changing the base/target branch though.  So PRs targeting V1 should set main-v1 as the base for the feature PR.  And PRs targeting V2 would set main-v2 as the base branch for their feature PR.

Then there's no need for the subsequent script to force push and GitHub releases won't be created in the case of a failed force push.

I think this is what @pygy suggested before when the original discussion for release channels came up.

But because the force push is happening outside of pr-release it can't really assist with this issue.

It's handling a lot of potential failure cases internally but it can't do it's job if we give it the wrong base/target branch.

**Comment by dead-claudia** [comment]
@JAForbes Woukd it be a better course of action for us to drop pr-release entirely and just stitch it together with a handful of internal actions?

**Comment by JAForbes** [comment]
I don't think so, seems like a minor thing we can figure out.  How about we take a beat, I'll think about how to best implement these lifecycle hooks into pr-release, and in the meantime we'll keep an eye out for failing CI builds together.  Given you've fixed the perms issue releases should work fine for now.

Can you give some thought to what I was saying about the release channel base/target branches?  I think letting pr-release own the force pushing is important as it is conceptually in its remit.  If there's a compelling reason to not use the release channel base/target branches now then I'd like to support the alternative approach in pr-release as it ties in to other features.

I hadn't considered release channels when I made pr-release, and I really liked the elegance of @pygy's solution of `main-$version / next-$version`.  But if there's a reason not to take that approach I'd really like to know about it so I can support alternative flows and document it.

Does that sound okay?

**Comment by dead-claudia** [comment]
> I don't think so, seems like a minor thing we can figure out.  How about we take a beat, I'll think about how to best implement these lifecycle hooks into pr-release, and in the meantime we'll keep an eye out for failing CI builds together.  Given you've fixed the perms issue releases should work fine for now.
> 
> Can you give some thought to what I was saying about the release channel base/target branches?  I think letting pr-release own the force pushing is important as it is conceptually in its remit.  If there's a compelling reason to not use the release channel base/target branches now then I'd like to support the alternative approach in pr-release as it ties in to other features.

I'm okay with that. As long as I can get the desired release flow, I don't care how it's abstracted.

> I hadn't considered release channels when I made pr-release, and I really liked the elegance of @pygy's solution of `main-$version / next-$version`.  But if there's a reason not to take that approach I'd really like to know about it so I can support alternative flows and document it.
>
> Does that sound okay?

I mean, we're already literally migrated to that branch system now, just with `release` instead of `next` and the `$version` being `v1`, `v2`, and so on, with a sole exception of `v0.2` for archival purposes (that I considered deleting more than once). So it's certainly okay by me.

(I killed `next*` as a branch prefix, to avoid migration-related errors. And it's already prevented a few accidental pushes.)

**Comment by dead-claudia** [comment]
@JAForbes It'll be a few days at least before I can circle back myself, anyways, so sounds good to me.
