### ISSUE TITLE
Documentation issue with m#attributes

### ISSUE THREAD

**Issue by Naddiseo** [MithrilJS/mithril.js#315]
The documentation is a bit misleading regarding the attributes of the virtual dom.

``` javascript
m("input", {readonly: true}); //yields <input readonly />
```

Is incorrect, it actually yields: `<input readonly="true" />` and is misleading since:

``` javascript
m("input", {readonly: false}); //yields <input readonly="false" /> which is still readonly
```

Thus, the documentation for the Attributes signature will also need changing, since the following is incorrect:

> Similar, setting the value of attribute `readonly` to `false` is equivalent to removing the attribute in HTML.

For a js fiddle demonstrating:  [using "readonly"](http://jsfiddle.net/9jkzb7ek/1/), and the [working using "readOnly"](http://jsfiddle.net/9jkzb7ek/2/)

**Comment by shadeglare** [comment]
The documentation is still invalid.
