### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by daddybh** [MithrilJS/mithril.js#32]
Hi, I am looking for a light weight MVC framework for my customer embedded page, which use IE as a wrapper. Is mithril only support modern browser? I checkout the website, but i cannot find any related info. Can anybody show me the compatibility of mithril. Thanks in advance.

**Comment by ohenepee** [comment]
Link does not exist @lhorie

**Comment by pygy** [comment]
@ohenepee that resource is now at https://mithril.js.org/archive/v0.2.5/tools.html#internet-explorer-compatibility

But those are older docs... Mithril 0.x was compatible with IE9+ out of the box, and ie7+ with polyfills. Mithril 1.x doesn't support versions prior to IE9 (even with polyfills).
