### ISSUE TITLE
How to route preserving the location hash?

### ISSUE THREAD

**Issue by RafaelFCarneiro** [MithrilJS/mithril.js#322]
Hi,

Im having a problem with “hash” mode on “m.route.mode”. I`m using that because “..is the only mode in which routing changes do not cause page refreshes in any browser. (http://lhorie.github.io/mithril/mithril.route.html#mode)”. However, every time i use the m.route(path) command, the scroll is intentionally set up to top (0,0) ignoring the previous “windown.location.hash”. I know that set up the scroll to top is the most popular and used away to web app, but sometimes would be useful let the scroll on the previous “windown.location.hash” (like in mobile), has any way for to do that? If not with the "hash" mode, any order kind of mode as capable of to do that?

Thnx

**Comment by abdollahpour** [comment]
But how, I did not find any solution for monitoring routing. I can store scrollTop before m.route action but how can I replay it after routing! Use config function does not work for me.

**Comment by lhorie** [comment]
setting scroll position in a config should work as of 0.2.0
