### ISSUE TITLE
Mithril can't be used in strict mode.

### ISSUE THREAD

**Issue by Naddiseo** [MithrilJS/mithril.js#323]
If mithril is wrapped in a `function() { "use strict"; }` as it can be with some bundlers (browserify+es6ify), then an error is thrown due to mithril not being strict mode compatible.
`mithril.js:1 Uncaught ReferenceError: m is not defined`

A minimal example of what's happening:

``` javascript
(function(){"use strict"; Mithril = m = new function app(w) {}(window); })()
```

Issue came up here: https://groups.google.com/forum/#!topic/mithriljs/Weuhh5mKjys

**Comment by avesus** [comment]
:+1:
