### ISSUE TITLE
coming from React, would it be easy to implement Flux style on top of Mithril?

### ISSUE THREAD

**Issue by 0xgeert** [MithrilJS/mithril.js#342]
Coming from React I like Facebook's [Flux](http://facebook.github.io/react/docs/flux-overview.html) approach to creating apps. Would Flux style of layering my app be a natural match for Mithril?

**Comment by MattMcFarland** [comment]
I wrote a mini-guide that I hope may be helpful.  It was added as an issue to get exposure.
#675

**Comment by lhorie** [comment]
@MattMcFarland that looks great, but should probably go in the [wiki](https://github.com/lhorie/mithril.js/wiki), rather than the issue tracker

**Comment by MattMcFarland** [comment]
Thanks lhorie, I believe that is right.  I think my excitement got the best of me, and to muster more attention I made the decision to add it as an issue.  I'm fine with moving this to the wiki.  I just want to make sure it's given attention, could we put this in the readme?

**Comment by MattMcFarland** [comment]
@lhorie I moved this to the wiki Recipes/Snippets Section (also alphabetized it, hope that is ok) https://github.com/lhorie/mithril.js/wiki/Recipes-and-Snippets

**Comment by lhorie** [comment]
Thanks. I tweeted about it: https://twitter.com/LeoHorie/status/611218259153522688
