### ISSUE TITLE
mithril.js Bower package and min.map file

### ISSUE THREAD

**Issue by cachaito** [MithrilJS/mithril.js#346]
Hi!
I don't know if this is a bug in mithril package, but when I run Chrome 38.0.2125.111 with minimalized mithril 0.1.24 version (Enable JavaScript source maps in Dev Tools is checked) there is a error in console: GET http://localhost:3000/bower_components/mithril/mithril.min.js.map 404 (Not Found)
When I manually change name of mithril.min.map this error dissapear.

**Comment by vikbert** [comment]
I use mithril in plunker and have the same problem. 
`http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.30/mithril.min.js.map 404 (Not Found)`

the lib is linked in head
`    <script 
      data-require="mithril@*" 
      data-semver="0.1.30" 
      src="http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.30/mithril.min.js">
    </script>`

Any tips!?
