### ISSUE TITLE
Embed Flems.io code samples in the docs

### ISSUE THREAD

**Issue by lhorie** [MithrilJS/mithril.js#526]
It'd be nice to have runnable samples for the code presented in the docs, especially the longer snippets

**Comment by roundand** [comment]
yes please, as a client-side newbie there's a many areas that I'd like to be able to step through in order to properly understand them.

**Comment by a-s-o** [comment]
Created one for the velocity.js example:  https://jsfiddle.net/8netux0g/

**Comment by glebcha** [comment]
Created fiddle with extended todo app example (used moment.js for pretty timestamps).
http://jsfiddle.net/glebcha/q7tvLxsa/

**Comment by Masquerade-Circus** [comment]
Hi, Leo. 

I made a list of examples from the simplest, like a "hello world" to the resolution of components, in this way, the evolution and understanding of Mitrhil is more progressive and simple.

All examples are in Codepen: [http://codepen.io/MasqueradeCircus/pen/gLwZXZ?editors=0010](http://codepen.io/MasqueradeCircus/pen/gLwZXZ?editors=0010).

**Comment by lhorie** [comment]
@Masquerade-Circus wow this looks pretty awesome

**Comment by Bondifrench** [comment]
@Masquerade-Circus Nice examples, I noticed in `3.2 Components - Lifecycle methods` that the number of `Redraws so far` are incrementing in a weird way: 0,1,3,5,7...bug?

**Comment by Masquerade-Circus** [comment]
@Bondifrench Thanks for noticing this. It was for the onclick function, it performed the natural update for the onclick event and also made a second update by calling the m.redraw method. I just put an empty function and now it's all right.

Thanks.

**Comment by isiahmeadows** [comment]
Closing as the 0.2.x docs are no longer live.

**Comment by tivac** [comment]
IMO this still applies to the 1.0 docs

**Comment by isiahmeadows** [comment]
Reopened and removed the misleading 0.2.x label.

**Comment by porsager** [comment]
I'd love to make all the examples live using flems core. Would a pull request for this be welcomed?

**Comment by tivac** [comment]
I did this already for the guides using codepen, assuming flems has a nice embed I'm 100% in favor of expanding it to the API docs and converting the guide to use flems as well.

**Comment by pygy** [comment]
There!

I'm all for it as well!

**Comment by mike-ward** [comment]
I found embedding flems.io directly in the article a bit jarring and instead list the code statically with a link. See https://mike-ward.net/2018/05/09/mithril-rising/ for examples.

Also, I'm willing to give this a go if it's something we still want for 2.0.

**Comment by isiahmeadows** [comment]
@mike-ward It's a nice-to-have, not a blocker for anything. We're just waiting for someone to just put forth the effort.

I'm okay with us not directly embedding Flems snippets, but I'm personally okay either way.

**Comment by mike-ward** [comment]
@isiahmeadows OK, I'll start with the home page and generate something for comment and feedback.

**Comment by porsager** [comment]
@mike-ward Sorry I hadn't noted inhere that I was working on this, I only mentioned it in gitter I think.. I've got the initial setup ready, I just got sidetracked by work and other stuff, so it was stuck in a local branch with me :-(

If you want to you're very welcome to pick it up from here if you want to. I think now that we have actual live flems running we can remove some of the code boxes as well, but I thought it might be better to make that part of a larger docs overhaul / cleanup.

This is how it looks so far (I've only replaced codemirror by flems): https://porsager.com/mithril-docs/

The branch is here: https://github.com/porsager/mithril.js/tree/flems-in-docs

If you want to get set up quickly I found it quick to use wright like this:
```
npm install wright@next -g
wright -e 'npm run gendocs;docs/**/*' dist/index.html
```

**Comment by mike-ward** [comment]
@porsager Your call. Maybe it would be easier if the core contributors choose another project/issue for me? I'm not fussy, Just want to contribute.

**Comment by porsager** [comment]
I guess I could wrap this up fairly quickly from where it is now, so now that it's current I might as well do that. 

I'm not core, but a quick glance, and maybe 
https://github.com/MithrilJS/mithril.js/issues/2334 would be a good start?

**Comment by mike-ward** [comment]
OK, I own #2334
