### ISSUE TITLE
keys misbehaving

### ISSUE THREAD

**Issue by lhorie** [MithrilJS/mithril.js#639]
http://jsbin.com/litacu/1/edit?js,output

**Comment by andr2** [comment]
Yes, and another one example https://jsfiddle.net/g89znqkr/19/

**Comment by pelonpelon** [comment]
A keyed list must not share its parent with siblings that are not part of the list. You'd never run into this in an HTML list unless done incorrectly (which is possible). But in the above examples we are not using HTML lists, we are just mapping over an array and stacking divs.

mithril.js uses `parentElement.childNodes` for indexing - [L193](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L193)

In Barney/Leo's example, `table` *and* a list of divs are under `.root`
`table` throws off the count.
Here is my solution:
http://jsbin.com/honola/1/edit?js,output

And for Andre:
https://jsfiddle.net/pelonpelon/g89znqkr/20/

This looks like something that should be made clear in the docs.

**Comment by andr2** [comment]
@pelonpelon thank you for response and clarification! 
But can you explain why is it impossible to insert a keyed element at a right place?

**Comment by pelonpelon** [comment]
@andr2 As I look at your example again I realize I gave you a working solution but not the correct solution, which is: you can't do what you're trying to do.

`m("span", { key: 'key' }, "privet")`   **// parent is div#test**
`m("button", { key: "adsf", onclick: function() {} }, "REDRAW")` **//parent is div**

2 keyed list members must have the same parent.

And as indicated above, keyed list members cannot have non-keyed siblings (not applicable to your example).

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
