### ISSUE TITLE
m.request with GET method and objects with m.prop

### ISSUE THREAD

**Issue by cceconi** [MithrilJS/mithril.js#748]
Hi,

I have a problem when I make a m.request with GET method and an object param.
Here an example : 

``` javascript
var TaskRef = function(data) {
     data = data || {};
     this.ref = m.prop(data.ref);
};

var taskref = new TaskRef({ref:"Test"});

m.request({
     method: "GET",
     url: "/task",
     data: taskref,
});
```

the url look like that : 
/task?ref=function%20()%7Breturn%20arguments.length%26%26(a%3Darguments%5B0%5D)%2Ca%7D

after a search in mithril code, it seems that the function buildQueryString don't support m.prop value.

actually, I made little hook reusing your code : 

``` javascript
    // return only m.prop properties
    util.purifyObject = function (object) {
        var pureObject = {};
        var type = {}.toString;

        function isObject(obj) {
            return type.call(obj) === "[object Object]";
        }

        for (var prop in object) {
            var value = object[prop];
            if (_.isFunction(value)) {
                if (value.hasOwnProperty("toJSON")) {
                    pureObject[prop] = isObject(value()) ? util.purifyObject(value()) : value();
                }
            }
        }
        return pureObject;
    };
```

I don't manage the case of an objects array because buildQueryString don't too and in a GET request, this doesn't make sense.

So my new request code : 

``` javascript
m.request({
     method: "GET",
     url: "/task",
     data: purifyObject(taskref),
});
```

the url is now : 
/task?ref=Test

I think this feature must be integrated to mithril.

**Comment by LostKobrakai** [comment]
I think this feature must be integrated to mithril.
There must be something wrong as this [blogpost](http://lhorie.github.io/mithril-blog/json-all-the-things.html) suggest, that this feature already exists.

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
