### ISSUE TITLE
Feature Request: m.prop().subscribe()

### ISSUE THREAD

**Issue by explorigin** [MithrilJS/mithril.js#78]
I've begun playing with Mithril after coming from Knockout.  One thing I really miss that Knockout has is the ability to subscribe to an observable.

Clearly you were not intending to rebuild Knockout, but it seems this functionality could be hacked on top of the current m.prop and m.deferred fairly easily.  I would like to use it like:

```
function controller() {
  var self = this;
  this.selected = m.prop(0);
  this.stuffList = new StuffList();

  this.selected.subscribe(function(value) {
    self.stuffList[value].onselected();
  })
}

```

**Comment by omenking** [comment]
I kind of wish this was baked in already.

**Comment by barneycarroll** [comment]
Worth bearing in mind that Mithril's idiomatic control flow is very simple: an HTTP request (data from server) or a DOM event handler resolves (data from user), Mithril redraws automatically. This means you can easily reason about how data changes and when it is persisted to the view. Most observer-based MVC frameworks use the feature to achieve the same effect with more overhead.

But it wouldn't be hard to write your own function to achieve this feature:

```Javascript
function oprop( store ){
	var observers = []

	function accessor( value ){
		if( arguments.length ){
			if( store != value )
				for( var i = 0; i < observers.length; i++ )
					observers[ i ]( value )
		
			store = value
		}
	
		return store
	}

	accessor.subsbscribe = callbacks.push
	
	return accessor
}
```
