### ISSUE TITLE
Component is not reinitialised correctly when return as only content of the base view

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#823]
If you have a base view that only returns a component that depends on things, the controller of the component is not reinitialized correctly when things change. Even with `key`-Attribute used.

If you wrap a div around it all works fine

see http://jsfiddle.net/br4eLrps/1/

**Comment by StephanHoyer** [comment]
It's enough to wrap the component in an array to make it work: http://jsfiddle.net/br4eLrps/2/

**Comment by Morklympious** [comment]
Is this still an issue now that components can be shorthand referenced via `m(component)`?

**Comment by barneycarroll** [comment]
Yup :/ You can't have more than one component tied to the same unique DOM root node.

**Comment by isiahmeadows** [comment]
I'm seeing the same problem on Chrome even if it's wrapped in a div... O.o

**Comment by StephanHoyer** [comment]
since there is a workaround for this I will close this for now
